### ISSUE TITLE
适配移动设备

### ISSUE THREAD

**Issue by hmsjy2017** [qier222/YesPlayMusic#10]
目前移动设备无法正常显示，希望能适配。
![877B9275-AE9F-4F9F-8478-634CEE90914F](https://user-images.githubusercontent.com/42692274/96357532-a2f48100-112f-11eb-92ec-dc2f48b4be53.png)

**Comment by qier222** [comment]
适配移动端的话，很多页面需要重新设计，而且移动端网页播放音乐的体验并不好，暂时不打算适配。
