### ISSUE TITLE
没有歌词浮窗

### ISSUE THREAD

**Issue by wintsa123** [qier222/YesPlayMusic#1002]
# 尽量每个 issue 只提一个 bug 或新功能
没有歌词浮窗！！！！！

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue]

### 反馈 bug 需要的信息

- 用的是客户端
- windows11

**Comment by wintsa123** [comment]
> 歌词浮窗在0.4.1版本中已移除，可以回退下载0.4.0版本或者在[这里](https://github.com/shih-liang/YesPlayMusicOSD)找到@shih-liang维护的版本

我找了一下，0.4.0版本已经下载不了了

**Comment by shih-liang** [comment]
> 歌词浮窗在0.4.1版本中已移除，可以回退[下载0.4.0版本](https://github.com/qier222/YesPlayMusic/releases/tag/v0.4.0)**或者**在[这里](https://github.com/shih-liang/YesPlayMusicOSD)找到@shih-liang维护的版本, eg, [v0.4.2](https://github.com/shih-liang/YesPlayMusicOSD/releases/tag/v0.4.2)
