### ISSUE TITLE
显示/隐藏自定义全局快捷键会失效

### ISSUE THREAD

**Issue by domeniczz** [qier222/YesPlayMusic#1004]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

Windows11 Pro 22000.282
客户端
![image](https://user-images.githubusercontent.com/42294390/138117640-708e4f3b-820b-4989-9413-57abdb359e71.png)

自定义 显示/隐藏 的全局快捷键，在重启软件之后会失效

**Comment by memorydream** [comment]
最新版应该已经修复

**Comment by domeniczz** [comment]
嗯，刚刚测试，确实修复了辛苦Sent from Domenic ZhangOne will never give up learning and promoting.-------- Original message --------From: memorydream ***@***.***>Date: Sat, Jan 15, 2022, 8:43 AMTo: qier222/YesPlayMusic ***@***.***>Cc: domeniczhang ***@***.***>, Author ***@***.***>Subject: Re: [qier222/YesPlayMusic] 显示/隐藏自定义全局快捷键会失效 (Issue #1004)

最新版应该已经修复
