### ISSUE TITLE
KDE5桌面环境下 全局菜单栏为英文

### ISSUE THREAD

**Issue by iky1905** [qier222/YesPlayMusic#1012]
系统为ArchLinux，桌面环境为kde5，软件窗口在前端时，全局菜单栏为英文而非软件里的中文。不过该应用确实没什么必要使用菜单栏。

另外还发现在我目前的环境下，双击托盘中的图标并不能呼出应用，必须在图标上点击右键->显示主面板才能呼出，不知这是否也与我的桌面环境或系统有关

**Comment by Hibanaw** [comment]
> 做这个功能之前，我查看了一些linux下electron软件，和我当前采用的方案是一样的

（Linux 下的 qqmusic 可以点击托盘图标唤出窗口

**Comment by memorydream** [comment]
> > 做这个功能之前，我查看了一些linux下electron软件，和我当前采用的方案是一样的
> 
> （Linux 下的 qqmusic 可以点击托盘图标唤出窗口

应该是修改过的electron，electron官方的包真的没有相关的API

**Comment by memorydream** [comment]
相关文档：
![image](https://user-images.githubusercontent.com/34763046/140531320-85c1ed16-c6b5-402d-ae66-d758cba9ebbd.png)
https://github.com/electron/electron/blob/main/docs/api/tray.md
