### ISSUE TITLE
吾爱破解来反馈问题啦！

### ISSUE THREAD

**Issue by pgu955** [qier222/YesPlayMusic#102]
无敌旋转金刚--52j
建议：希望能添加下载功能和选择音质功能，然后发现一个问题，在音乐库里面登录网易云之后，然后进入歌单，往下拉选一首歌播放，然后查看歌词在切回歌单，歌单就跑回第一首歌了，又要往下翻
  Pau250--52pj
建议：希望能够支持一个音频下载
  sunxi--52pj
建议：加入日推
登录账号时候可以回车确定

**Comment by qier222** [comment]
- 暂时不打算添加下载MP3的功能
- 每日推荐功能已经加到todo了
- 歌词页回到歌单页的问题我会尝试修复看看
- 回车登录会尽快加上
