### ISSUE TITLE
所有的歌单列表都是空的

### ISSUE THREAD

**Issue by litdev** [qier222/YesPlayMusic#1022]
### 反馈 bug 需要的信息

- Window 客户端

![微信截图_20211029102234](https://user-images.githubusercontent.com/13465940/139363220-b1ce6110-d130-4304-a78e-f369f0521748.png)

**Comment by litdev** [comment]
reset后重新登录歌单列表显示了，但是又有新的问题，点音乐库后，整个软件卡死，F12没反应，CPU占用飙高，27%左右，（i5-9300H）

**Comment by memorydream** [comment]
> reset后重新登录歌单列表显示了，但是又有新的问题，点音乐库后，整个软件卡死，F12没反应，CPU占用飙高，27%左右，（i5-9300H）

#1019 这里有一个相关的问题，但是目前还没有解决方案
在我这里，只有回复相关问题的那两天出现过这个问题，后来在我的windows和arch linux上都没有类似的情况出现

**Comment by yidasanqian** [comment]
同样的问题
![image](https://user-images.githubusercontent.com/10655188/143338664-af861626-8378-4217-832f-5ee7ea5270f3.png)
