### ISSUE TITLE
韩文字体无法显示

### ISSUE THREAD

**Issue by happi0** [qier222/YesPlayMusic#1025]
# 韩文字体无法显示

### 详细信息

- 客户端:yesplaymusic 0.4.2-1
- arch
- 见下图
![1](https://user-images.githubusercontent.com/86256628/139528602-6cad6d3c-3694-4b96-ad1a-c15ad69123ac.png)

**Comment by Bryan2333** [comment]
这不是无法显示，而是韩语的字符出现重叠。你可以参考一下这个知乎上的回答： https://www.zhihu.com/question/59193641

**Comment by happi0** [comment]
> 这不是无法显示，而是韩语的字符出现重叠。要解决这个问题，你可以参考一下这个知乎上的回答： https://www.zhihu.com/question/59193641

谢谢大哥，学到了
