### ISSUE TITLE
希望加入任务栏(系统托盘)歌名／歌词显示功能（Linux)

### ISSUE THREAD

**Issue by 123xzxc** [qier222/YesPlayMusic#1029]
希望加入任务栏(系统托盘)歌名／歌词显示功能（Linux)
类似MacOS的原生网易云
OS:Kubuntu 21.10 x86_64
DE:Plasma 5.22.5

# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by memorydream** [comment]
歌词显示功能？没用过mac，是指在任务栏里开一块显示歌词？

**Comment by 123xzxc** [comment]
就是在顶栏里可以添加歌词/歌名显示的小程序（不是任务栏） 而且可以切换歌曲啥的
因为我现在莫得苹果 只能引用一下这个了
[https://jingyan.baidu.com/article/92255446897467c41648f49a.html](url)

**Comment by memorydream** [comment]
这个应该不会添加，linux的话，可以单独写一个plasma扩展

**Comment by Hibanaw** [comment]
近期正好有了解到这方面内容
dbus 的 mpris2 （https://specifications.freedesktop.org/mpris-spec/latest/ ）有显示歌词的接口
（但现在的 yesplaymusic 并没有使用
plamsa applet 里好像是有 mpris api 的
但现在 kde store 里面还没有这种 applet
希望有会 qml 的 dalao 可以劳烦做一下
另付一个开源的 dde 任务栏歌词插件
[SeptemberHX/dde-mpris2-plugin](https://github.com/SeptemberHX/dde-mpris2-plugin)

**Comment by memorydream** [comment]
我在尝试实现对mpris协议的完全支持，如果成功，应该可以使用各个DE下基于mpris的显示歌词扩展，所以先关闭这个issue了
