### ISSUE TITLE
歌词滚动优化一下嘛

### ISSUE THREAD

**Issue by valdislau** [qier222/YesPlayMusic#103]
看那个歌词的滚动可太生硬了

**Comment by qier222** [comment]
你用的是客户端还是网页版？
网页版的话用的是什么浏览器？

**Comment by valdislau** [comment]
客户端的

**Comment by qtxzy** [comment]
网页端不能看歌词么，还是我操作方法不对，我用的是chrome，版本应该挺新的
![image](https://user-images.githubusercontent.com/54807390/106115305-9a2e3500-618b-11eb-8de9-b55c053a0b3d.png)

**Comment by qtxzy** [comment]
> 网页端不能看歌词么，还是我操作方法不对，我用的是chrome，版本应该挺新的
> ![image](https://user-images.githubusercontent.com/54807390/106115305-9a2e3500-618b-11eb-8de9-b55c053a0b3d.png)
![image](https://user-images.githubusercontent.com/54807390/106118206-d0b97f00-618e-11eb-9829-9bff64836e15.png)

现在可以看到了，我重新刷新了一下，不过现在的问题是这个歌词的字也太大了，而且好像没有给设置的地方

**Comment by qier222** [comment]
> 你用的是客户端还是网页版？
> 网页版的话用的是什么浏览器？

客户端的话，歌词下一行的时候应该有滚动动画啊

**Comment by FunkyPantsSa** [comment]
> > 你用的是客户端还是网页版？
> > 网页版的话用的是什么浏览器？
> 
> 客户端的话，歌词下一行的时候应该有滚动动画啊

我用的是客户端，也确实有滚动动画，但是这个动画看起来有些生硬。可以把歌词的切换速度设置为线性的，先快后慢的一个效果。希望有帮助。

**Comment by Designdocs** [comment]
您好，客户端字体可以自定义吗？尤其是歌词部分
