### ISSUE TITLE
关于搭建速度的问题

### ISSUE THREAD

**Issue by jiangbeth** [qier222/YesPlayMusic#1030]
利用楼主的网站登陆的，速度超快还能登陆网易云。不知道我用vercel搭建的速度特别慢。![image](https://user-images.githubusercontent.com/8001330/140018911-86c5adc3-09d4-43df-b1d4-866aae245d42.png)

**Comment by qier222** [comment]
music.qier222.com 使用的网易云api是托管在Oracle服务器上的，并不是托管在Vercel
