### ISSUE TITLE
UnblockNeteaseMusic这个功能是坏了吗？

### ISSUE THREAD

**Issue by edr1412** [qier222/YesPlayMusic#1036]
windows10 setup 版本
第一次安装不懂见谅，
看readme照理说集成了UnblockNeteaseMusic是不是就直接可以听灰色的歌曲？
试了下网易无版权的歌曲，没有变灰，但是播放不了。
控制台截图：
![圖片](https://user-images.githubusercontent.com/40953911/140529387-470ca17b-6fb8-4b4d-bd1f-10daa0301b6a.png)

是要怎么操作一下才行吗，请问大家怎么弄的

**Comment by memorydream** [comment]
不用操作，只要登陆了账号这个功能就会启用
由于技术限制，不是所有的音乐都能解锁，有些音乐会匹配到错误的音源，是正常的

**Comment by edr1412** [comment]
原来需要登录，现在可以了
不过Readme好像没有说明需要登录
谢谢 YesPlayMusic，这个功能很赞
