### ISSUE TITLE
在音乐库界面卡住

### ISSUE THREAD

**Issue by ZhouJump** [qier222/YesPlayMusic#1046]
我的电脑是Windows11系统，i7,3060laplop,无论网页还是桌面版打开音乐库能加载出来，然后卡在那个画面
![屏幕截图 2021-11-11 184811](https://user-images.githubusercontent.com/60733973/141285305-99847d03-6c21-47ed-b6f9-6424e6360104.png)

**Comment by memorydream** [comment]
#1019

**Comment by Hibanaw** [comment]
https://github.com/qier222/YesPlayMusic/actions/runs/1437734074

**Comment by liukenny961** [comment]
我也遭遇了这个问题。请问怎样将代码打包成应用呢？

**Comment by SAFEluren** [comment]
> 我也遭遇了这个问题。请问怎样将代码打包成应用呢？

Github Actions里有提供
上面那个链接翻到最下面 Artifacts 选对应平台的就行了
YesPlayMusic-linux
YesPlayMusic-mac
YesPlayMusic-win

**Comment by vonl1** [comment]
archlinux也出现音乐库界面卡死

**Comment by SAFEluren** [comment]
> archlinux也出现音乐库界面卡死 F12查看,有出现400错误,和没有出现错误但是就是界面卡死,软件可以退出

这玩意已经修了

**Comment by vonl1** [comment]
修复是修复,但是我还遇见这样的问题
![yesplaymusic](https://user-images.githubusercontent.com/40910092/141677637-9c60a292-05f6-4322-a26e-c039487d3bff.gif)
