### ISSUE TITLE
客户端版本对部分歌曲的封面适配有一些问题

### ISSUE THREAD

**Issue by LeCiel18** [qier222/YesPlayMusic#105]
![image](https://user-images.githubusercontent.com/38390251/106122300-85559f80-6193-11eb-8dec-d6856038e41b.png)

**Comment by qier222** [comment]
网易云API那边的问题，当param=1024y1024的时候返回的是长方形封面（大概是返回原始图片）。
我用css把长方形裁剪成正方形就OK了。
