### ISSUE TITLE
是否可能更改MPRIS bus name

### ISSUE THREAD

**Issue by c02y** [qier222/YesPlayMusic#1052]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

由于我使用的是i3wm+i3status-rust, i3status-rust通过获取MPRIS bus name来显示正在播放的信息，但是YesPlayMusic的信息是
```org.mpris.MediaPlayer2.chromium.instanceTheNum```， 和很多比如Chrome/Chromium/Vivaldi等浏览器的信息一样,如果我把MPRIS bus name是chromium的隐藏，YesPlayMusic也不能显示，选择显示的话，那些浏览器正在播放的也会被显示，所以可否将YesPlayMusic的MPRIS bus name改一下，比如改成`org.mpris.MediaPlayer2.YesPlayMusic.instanceTheNum`，例如Microsoft-Edge基于chromium的就是```org.mpris.MediaPlayer2.edge.instance```

虽然不知道是否有用，可以参考 https://github.com/electron-userland/electron-builder/issues/5339

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
: 客户端
- 浏览器名称或电脑操作系统
: Manjaro+i3wm+i3staus-rust
![image](https://user-images.githubusercontent.com/2135996/142273785-509e307c-2788-458b-b52a-fc3ca7ad4428.png)

- 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://user-images.githubusercontent.com/2135996/142270275-f291e21d-3d86-4ef3-a403-2ed6f51cd2fd.png)

**Comment by memorydream** [comment]
查看了一下相关的资料，是可以得，不过electron提供的东西应该不行，找到一个dbus的库 https://github.com/dbusjs/node-dbus-next ，可以自行实现

有空了我研究一下这个怎么弄，如果有大佬会搞就更好了

**Comment by Star-caorui** [comment]
如果可以的话请在实现更改MPRIS bus name的时候顺便实现一下歌曲封面，歌曲进度这些子功能。

https://github.com/qier222/YesPlayMusic/issues/588#issuecomment-997356768

祝好
