### ISSUE TITLE
LIBRARY 页面卡死

### ISSUE THREAD

**Issue by RichardBaker3020** [qier222/YesPlayMusic#1059]
Ubuntu 20 系统， chrome 或者 firefox 浏览网页端 music.qier222.com，打开 Library 页面会卡死无反应，Firefox 显示 This page is slowing down Firefox。 直接使用客户端问题也能够复现，清空缓存重装后问题还在。 此问题似乎只出现在 LABRARY 页面。

F12调试页面没有出现有用的信息。

**Comment by duskNNNN** [comment]
系统：archlinux 
内核：5.15.4-arch-1
桌面：kde 5.23.3
同样出现library页面卡死,其他页面正常的情况，退出键可用
