### ISSUE TITLE
自建歌单与收藏歌单做个分栏

### ISSUE THREAD

**Issue by AKAPotato** [qier222/YesPlayMusic#106]
建议把自建歌单与收藏歌单做个分栏，不知道能不能实现orz

**Comment by qier222** [comment]
已加入todo

**Comment by qier222** [comment]
已经支持了哦，等待发布新版本客户端吧
https://github.com/qier222/YesPlayMusic/commit/458f6dd4474edd32d6b4f120df1b4ce3129b1c31

**Comment by qier222** [comment]
0.3.7版本已发布
