### ISSUE TITLE
[小建议] 加一个自定义标题栏(Linux)

### ISSUE THREAD

**Issue by greenhat616** [qier222/YesPlayMusic#1062]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- [x] 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- [x] 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端: 客户端
- 浏览器名称或电脑操作系统: Arch Linux  Gnome with Wayland
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![图片](https://user-images.githubusercontent.com/41122242/143048573-a21ad09b-7dea-4f2e-b0e0-56625e6d705b.png)
![图片](https://user-images.githubusercontent.com/41122242/143049075-7ae0c3ab-f712-47d8-b8b8-2722942ada39.png)

程序非常棒, 可以替代 cef 版本的 Linux 的 网易云了. 而且支持 chromium 的 WayLand API, 得给作者点赞 :+1: !

有个小建议: 能不能做一个 custom window decorator, 虽然这是个上游的 bug; 但还是希望作者如果有时间的话可以整一下, 非常感谢!
上游问题: https://github.com/electron/electron/issues/27522

**Comment by memorydream** [comment]
上游已经准备好相关的实现了，或许我们等上游的修改会比自己实现更好
https://github.com/electron/electron/pull/29618

**Comment by memorydream** [comment]
请你尝试一下 #1250 的修改是否可以使用，在我的arch linux kde环境下没有问题，目前需要自行编译，或等待merge后从Actions下载

启用相关选项后需要重启ypm才能应用修改
