### ISSUE TITLE
0.4.2版本，无法打开音乐库。

### ISSUE THREAD

**Issue by liukenny961** [qier222/YesPlayMusic#1064]
0.4.2版本，无法打开音乐库。
我目前使用的版本是Action中已经修复了#1019问题的0.4.2版本，现在的问题是无法加载出音乐库（加载进度条卡在99%左右），驶入resetApp()后重新登录网易云账号同样会出现这个问题。
（我遇到的问题是音乐库加载不出来，不是打开音乐库之后无响应……）
### 反馈 bug 需要的信息

- 用的是网页版还是客户端
 客户端（0.42.0，Action中的Release 429）
- 浏览器名称或电脑操作系统
Windows11 Dev Build 22504
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://user-images.githubusercontent.com/65520199/143240199-cfbab8e6-57ac-4522-a943-df448c2054a7.png)

**Comment by liukenny961** [comment]
Hello？

**Comment by Reisen-U** [comment]
我的0.4.2安装版和便携版，还有以前下载过的0.4.0版本，也存在这个问题，也是在打开音乐库之后，软件窗口很快就完全不再响应；右键点击任务栏托盘的图标可以弹出菜单，但只有退出键是正常的。


版本	Windows 11 专业版
版本	21H2
安装日期	‎2021/‎10/‎15
操作系统版本	22000.318
体验	Windows 功能体验包 1000.22000.318.0

**Comment by phlinsia** [comment]
问题描述：
打开音乐库后，程序不响应，CPU占用达到15%，只能强制退出。尝试了卸载后重新安装，并且更换便携版，问题无法解决。
- 客户端0.42.0（安装版和便携版都有此问题）
- 版本 Windows 10 20H2 
- 操作系统版本 19042.1348
- Console截图
![image](https://user-images.githubusercontent.com/61466017/143466889-9a394577-92e6-448f-a22b-95126275362d.png)
此时退出程序，即使确保状态栏中已经退出，但进程仍然存在。必须手动在任务管理器里杀掉。
![image](https://user-images.githubusercontent.com/61466017/143467995-11026977-efa8-480e-9eb7-471f5355aa36.png)

**Comment by memorydream** [comment]
打开音乐库后完全未响应可以查看 #1019 ，只是白屏没有卡死可以在控制台输入'resetApp()'解决

**Comment by liukenny961** [comment]
看来这个不是偶然问题了，好像是共性问题。@qier222

**Comment by liukenny961** [comment]
> 打开音乐库后完全未响应可以查看 #1019 ，只是白屏没有卡死可以在控制台输入`resetApp()`解决

我目前使用的版本是Action中已经修复了#1019问题的0.4.2版本，现在的问题是无法加载出音乐库（加载进度条卡在99%左右），驶入resetApp()后重新登录网易云账号同样会出现这个问题。

**Comment by mnixry** [comment]
在 Manjaro Linux 下遇到相同问题

**Comment by madness9126** [comment]
我也是打开音乐库之后程序就无响应了，歌曲还是在放，不过啥也按不了只能强制关掉

**Comment by liukenny961** [comment]
目前我遇到的问题是音乐库加载不出来，不是打开音乐库之后无响应……（因为我现在的版本是Action下已经修复#1019问题的0.4.2版本）

**Comment by TheLastGreenseer** [comment]
登出再重新登录后似乎可用，但不确保再次打开时仍然可行

**Comment by Wzzzx** [comment]
版本	Windows 10 家庭中文版
版本号	21H1
安装日期	‎2021/‎02/‎10
操作系统内部版本	19043.1348

我也遇到了这个问题，但是通过resetApp()解决了。我在俩电脑上同一天出现的，后续就没有再出现了

**Comment by liukenny961** [comment]
[2021.11.29更新]按照Wzzzx的方法成功地解决了该问题！目前可以正常使用音乐库。

> 版本 Windows 10 家庭中文版 版本号 21H1 安装日期 ‎2021/‎02/‎10 操作系统内部版本 19043.1348
> 
> 我也遇到了这个问题，但是通过resetApp()解决了。我在俩电脑上同一天出现的，后续就没有再出现了

**Comment by mnixry** [comment]
我这里`resetApp()`或者清除数据文件夹均不能修复该问题
