### ISSUE TITLE
Windows dark mode 标题栏优化建议

### ISSUE THREAD

**Issue by MoonBegonia** [qier222/YesPlayMusic#107]
![image](https://user-images.githubusercontent.com/26798347/106134186-1ed77e00-61a1-11eb-8a48-4ea22c94a87e.png)

Windows dark mode 下标题栏仍然为白色 ，希望可以优化一下。

**Comment by liuup** [comment]
我也想提问这个问题hhh

**Comment by PurBlu** [comment]
+1 界面全黑时窗体标题栏确实有点影响视觉 望大佬优化一波

**Comment by amronbook** [comment]
我也有这个问题

**Comment by qier222** [comment]
0.3.4版本有了
