### ISSUE TITLE
移动网页端无法自动播放下一首

### ISSUE THREAD

**Issue by qtxzy** [qier222/YesPlayMusic#1074]
- 网页端
- 百分浏览器（chrome）Chromium 86.0.4240.198
- 控制台 Console 页面的截图（按 F12 可打开控制台）

PC网页端可以自动播放下一首，移动端浏览器或者微信内置浏览器均不可以自动播放下一首，不知道是为什么，切换了电脑端UA依旧不行，不了解内部机制

**Comment by qtxzy** [comment]
稍微研究了一下，应该是和onended事件有关吧，然后可能在移动端这个出现了什么bug？我也不太清楚，不过我找到一个简陋的音乐项目，在微信移动端浏览器中可以实现自动播放下一首，因此，应该不是移动端的问题

**Comment by XhnPLayer** [comment]
坐等解决。要么有个APP最好了。

**Comment by WTP016-CN** [comment]
同无法自动播放下一首
使用 iOS Safari

**Comment by Ynng** [comment]
https://github.com/qier222/YesPlayMusic/issues/1090#issuecomment-992897246
