### ISSUE TITLE
音乐库界面卡死

### ISSUE THREAD

**Issue by lcx-0504** [qier222/YesPlayMusic#1075]
操作系统：Windows 11
客户端：Windows 客户端（setup）
复现过程：登录账户，然后点击音乐库，然后卡死，风扇开始转起来了
复现概率：100%。目前我还没遇到过成功加载
其他信息：看别的issue好像跟歌词有关。我的歌单里基本上都是纯音乐，很少是有歌词的歌
已经尝试但失败的方法：控制台界面resetAPP（），重新安装软件
控制台报错信息：
![image](https://user-images.githubusercontent.com/62388710/144712404-88def05f-4c4d-4f98-a553-412893d4d385.png)

**Comment by NuymakStone** [comment]
我也一样...我估计是因为歌单太多的原因

**Comment by GuoJunfu-tech** [comment]
+1

**Comment by Ruikoto** [comment]
同样问题，打开音乐库就会卡死

**Comment by cwrb8888** [comment]
## 同样的问题
操作系统：Windows 10
客户端：Windows 客户端（setup）
复现过程：已登录账户，然后点击音乐库，然后界面无响应（**不使用国外代理时会出现该状况，使用代理后问题解决。**）
其他信息：
![image](https://user-images.githubusercontent.com/34412703/144808189-2113e833-98d5-4576-9577-9686c117fc74.png)

**Comment by zeerdeer** [comment]
我也是 估计的音乐太多了 我1000多首

**Comment by rsun-thoughtworks** [comment]
我也遇到了类似的问题，卡死。我是macOS 系统。

不知道是不是歌单问题。我重启 YesPlayMusic 之后就好了。看啥时候再重现 。

**Comment by ThomasQAQOUO** [comment]
同样问题

**Comment by char1eslu** [comment]
同样的问题+1

**Comment by Ruikoto** [comment]
> 同样的问题+1

可以试一下[这个](https://github.com/Ruikoto/YesPlayMusic/releases/tag/v0.4.2.1
)，我自己手动用最新代码打包了个版本，应该不会再卡死了

**Comment by char1eslu** [comment]
> > 同样的问题+1
> 
> 可以试一下[这个](https://github.com/Ruikoto/YesPlayMusic/releases/tag/v0.4.2.1)，我自己手动用最新代码打包了个版本，应该不会再卡死了

啊啊啊，非常感谢呀，但是，问题是，好像木有mac版本😭️

**Comment by rsun-thoughtworks** [comment]
> > > 同样的问题+1
> > 
> > 
> > 可以试一下[这个](https://github.com/Ruikoto/YesPlayMusic/releases/tag/v0.4.2.1)，我自己手动用最新代码打包了个版本，应该不会再卡死了
> 
> 啊啊啊，非常感谢呀，但是，问题是，好像木有mac版本😭️

可以自己打包一个。

**Comment by memorydream** [comment]
> > > 同样的问题+1
> > 
> > 
> > 可以试一下[这个](https://github.com/Ruikoto/YesPlayMusic/releases/tag/v0.4.2.1)，我自己手动用最新代码打包了个版本，应该不会再卡死了
> 
> 啊啊啊，非常感谢呀，但是，问题是，好像木有mac版本😭️

https://github.com/qier222/YesPlayMusic/actions/runs/1544162728
action会自动构建主分支上的commit

**Comment by lcx-0504** [comment]
> > 同样的问题+1
> 
> 可以试一下[这个](https://github.com/Ruikoto/YesPlayMusic/releases/tag/v0.4.2.1)，我自己手动用最新代码打包了个版本，应该不会再卡死了

已验证，bug已解决
