### ISSUE TITLE
当前播放音乐为纯音乐时歌词栏跳转bug

### ISSUE THREAD

**Issue by JiuXuz** [qier222/YesPlayMusic#1076]
操作系统：Windows 10 专业版 20H2 19042.844
客户端：Windows 客户端（setup.exe）
描述：点击右侧歌词栏“纯音乐，请欣赏”会直接下一曲，点击“作曲”会直接重新开始播放当前音乐，疑跳转函数问题？
补充：因所听基本均为纯音乐，未充分测试人声带歌词；音乐库崩溃bug已有issues不再赘述
![screen_副本](https://user-images.githubusercontent.com/75655986/144733630-8508d8dc-0ec6-4014-927c-13198af42f1a.png)

**Comment by memorydream** [comment]
不是bug，如果没有歌词是不会显示歌词窗口的，有歌词窗口说明这首歌有歌词
根据歌词接口返回的信息，一般有歌词的纯音乐， `纯音乐，请欣赏` 这句的lrc为`[99:00.00]纯音乐，请欣赏`，并且在最后一个
其他的作词作曲信息，一般是从 `[00:00.000]` 开始，如果相关信息有多行，一般是 `[00:00.000]` `[00:01.000]` 这样的排列

**Comment by JiuXuz** [comment]
> 不是bug，如果没有歌词是不会显示右侧歌词部分的，有歌词部分说明这首歌存在lrc歌词 根据歌词接口返回的信息，一般有歌词的纯音乐， `纯音乐，请欣赏` 这句的lrc为`[99:00.00]纯音乐，请欣赏`，并且在最后一个 其他的作词作曲信息，一般是从 `[00:00.000]` 开始，如果相关信息有多行，一般是 `[00:00.000]` `[00:01.000]` 这样的排列

额，我们好像不在一个频道哈哈，我的疑问是点击它会直接跳转下一首，这是不应该的

**Comment by JiuXuz** [comment]
> 不是bug，如果没有歌词是不会显示右侧歌词部分的，有歌词部分说明这首歌存在lrc歌词 根据歌词接口返回的信息，一般有歌词的纯音乐， `纯音乐，请欣赏` 这句的lrc为`[99:00.00]纯音乐，请欣赏`，并且在最后一个 其他的作词作曲信息，一般是从 `[00:00.000]` 开始，如果相关信息有多行，一般是 `[00:00.000]` `[00:01.000]` 这样的排列

我们好像不在一个频道哈，我的疑问是即使是纯音乐的lrc，点击它会直接跳转下一个首，这是不应该的

**Comment by JiuXuz** [comment]
> 不是bug，如果没有歌词是不会显示右侧歌词部分的，有歌词部分说明这首歌存在lrc歌词 根据歌词接口返回的信息，一般有歌词的纯音乐， `纯音乐，请欣赏` 这句的lrc为`[99:00.00]纯音乐，请欣赏`，并且在最后一个 其他的作词作曲信息，一般是从 `[00:00.000]` 开始，如果相关信息有多行，一般是 `[00:00.000]` `[00:01.000]` 这样的排列

我们好像不在一个频道哈，我的疑问是即使是纯音乐的lrc，点击它会直接跳转下一首，这是不应该的

**Comment by memorydream** [comment]
> > 不是bug，如果没有歌词是不会显示右侧歌词部分的，有歌词部分说明这首歌存在lrc歌词 根据歌词接口返回的信息，一般有歌词的纯音乐， `纯音乐，请欣赏` 这句的lrc为`[99:00.00]纯音乐，请欣赏`，并且在最后一个 其他的作词作曲信息，一般是从 `[00:00.000]` 开始，如果相关信息有多行，一般是 `[00:00.000]` `[00:01.000]` 这样的排列
> 
> 我们好像不在一个频道哈，我的疑问是即使是纯音乐的lrc，点击它会直接跳转下一首，这是不应该的

因为 纯音乐，请欣赏 这句的时间戳一般都是99分0秒，已经超过了音乐的时长，跳到下一首在这个逻辑下不是很正常么？

**Comment by JiuXuz** [comment]
> > > 不是bug，如果没有歌词是不会显示右侧歌词部分的，有歌词部分说明这首歌存在lrc歌词 根据歌词接口返回的信息，一般有歌词的纯音乐， `纯音乐，请欣赏` 这句的lrc为`[99:00.00]纯音乐，请欣赏`，并且在最后一个 其他的作词作曲信息，一般是从 `[00:00.000]` 开始，如果相关信息有多行，一般是 `[00:00.000]` `[00:01.000]` 这样的排列
> > 
> > 
> > 我们好像不在一个频道哈，我的疑问是即使是纯音乐的lrc，点击它会直接跳转下一首，这是不应该的
> 
> 因为 纯音乐，请欣赏 这句的时间戳一般都是99分0秒，已经超过了音乐的时长，跳到下一首在这个逻辑下不是很正常么？

点击作曲人员重新开始，请欣赏就是下一曲吗；如果开发的意图就是这么设计的，我倒是也无话可说了。。。

**Comment by memorydream** [comment]
> 点击作曲人员重新开始，请欣赏就是下一曲吗；如果开发的意图就是这么设计的，我倒是也无话可说了。。。

和开发意图无关
点击歌词跳转到特定的时间是基于lrc的时间戳的，作曲人员的时间戳是0分0秒，所以跳到开头没有问题
请欣赏的时间戳是99分0秒，超过了音乐的时长，于是判定这首歌已经播放完了，播放下一曲也没有问题
并不是刻意设计的重新开始和跳到下一曲

**Comment by isNijikawa** [comment]
已修复, 修复 bug 的测试发布版在[这里](https://github.com/isNijikawa/YesPlayMusicBugFix).

pr 的事因为要把代码提交到另一个分支所以稍后再说.
