### ISSUE TITLE
未来版本的electron可以更新到14+吗？

### ISSUE THREAD

**Issue by VariatezzZ** [qier222/YesPlayMusic#1078]
操作系统： Manjaro Linux
KDE Plasma 版本： 5.23.3
KDE 程序框架版本： 5.88.0
Qt 版本： 5.15.2
内核版本： 5.10.79-1-MANJARO (64-位)
图形平台： X11   

使用云盘上传歌曲功能的时候，会调用gtk的Nautilus文件管理器而不是使用kde的Dolphin，（主要Nautilus丑），实际上不是yesplaymusic的问题，是electron的问题，不过问题上游已经解决，见[issues31258](https://github.com/electron/electron/issues/31258)、[issues50386](https://github.com/microsoft/vscode/issues/50386)、[pr19159](https://github.com/electron/electron/pull/19159)
所以只要将electron版本更新到14+即可  
将源码中package.json的electron版本指定为14.2.2之后，重新构建安装，问题已经解决，因此希望下个版本electron能够更新到14+   

![image](https://user-images.githubusercontent.com/54707523/144861319-51677e9a-e9cf-4a99-b801-4ba523393723.png)
![image](https://user-images.githubusercontent.com/54707523/144861473-dba0aaeb-04e3-422e-ae42-95d5796bb01d.png)

**Comment by memorydream** [comment]
根据 #1035 ，下一个版本至少要更新到electron13的最新版本，如果这个修改会被反向移植回electron13的话更好，不然直接升到14应该也是个可选项

**Comment by VariatezzZ** [comment]
> 根据 #1035 ，下一个版本至少要更新到electron13的最新版本，如果这个修改会被反向移植回electron13的话更好，不然直接升到14应该也是个可选项  
上游应该不会移植回electron13了，见[这里](https://github.com/electron/electron/pull/19159#issuecomment-825412730)，PR直接在14版本发布了

**Comment by VariatezzZ** [comment]
> 根据 #1035 ，下一个版本至少要更新到electron13的最新版本，如果这个修改会被反向移植回electron13的话更好，不然直接升到14应该也是个可选项

上游应该不会移植回13了，见[这里](https://github.com/electron/electron/pull/19159#issuecomment-825412730)，PR是随着14发布的
