### ISSUE TITLE
启用 Discord Rich Presence 是干什么用的

### ISSUE THREAD

**Issue by swfeng00** [qier222/YesPlayMusic#1084]
用的是win端的  启用 Discord Rich Presence 有什么用 能展开说说吗

**Comment by memorydream** [comment]
会在discord里显示，就像这样
![image](https://user-images.githubusercontent.com/34763046/145572036-f1e57ee4-fe69-480f-9958-b5fad8ce3a56.png)
![image](https://user-images.githubusercontent.com/34763046/145572062-7dcedb46-1718-4830-afdb-2656c3a63198.png)

**Comment by swfeng00** [comment]
原来如此

> 会在discord里显示，就像这样 ![image](https://user-images.githubusercontent.com/34763046/145572036-f1e57ee4-fe69-480f-9958-b5fad8ce3a56.png) ![image](https://user-images.githubusercontent.com/34763046/145572062-7dcedb46-1718-4830-afdb-2656c3a63198.png)
