### ISSUE TITLE
启动时报错且无法使用 resetApp()与卸载重装后仍无法解决

### ISSUE THREAD

**Issue by PurBlu** [qier222/YesPlayMusic#1086]
昨日开始启动后提示
![屏幕截图 2021-12-12 122149](https://user-images.githubusercontent.com/74239692/145700224-b9596a00-54a9-46cd-ad82-1029ea955213.png)
点击确认后进入程序 无法加载任何内容
![image](https://user-images.githubusercontent.com/74239692/145700244-50ff6c77-581f-44ee-89ab-8d912823fb56.png)

在Console里执行resetApp()
以及卸载重新安装不起作用

**Comment by memorydream** [comment]
10754这个端口被其他程序占用了，yesplaymusic需要使用这个端口启动一些必须的服务
