### ISSUE TITLE
关于歌曲播放界面的建议

### ISSUE THREAD

**Issue by minliny** [qier222/YesPlayMusic#109]
- Windows界面下歌曲播放页面可以添加一个音量调整按钮（或者拖动条）
- 或许可以添加一个下拉栏显示当前的播放列表

**Comment by qier222** [comment]
> Windows界面下歌曲播放页面可以添加一个音量调整按钮（或者拖动条）
这个不打算加

> 或许可以添加一个下拉栏显示当前的播放列表
底栏右边有正在播放列表的按钮
