### ISSUE TITLE
手机使用 谷歌浏览器 无法自动播放下一首

### ISSUE THREAD

**Issue by XhnPLayer** [qier222/YesPlayMusic#1090]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by Ynng** [comment]
我已经解决了这个问题，是howler放完歌后的callback的问题。
我有一个给手机用的fork，但代码有点乱，有些东西还没有做完，所以我还没有pull request。

你可以试试先用着 https://music.ynng.ca
