### ISSUE TITLE
主页、音乐库、搜索、发现均不可用

### ISSUE THREAD

**Issue by Seng-Jik** [qier222/YesPlayMusic#1098]
### 反馈 bug 需要的信息

- 用的是网页版还是客户端 - 客户端 ，安装版
- 浏览器名称或电脑操作系统 - Windows 11
- 控制台 Console 页面的截图（按 F12 可打开控制台）
- 在使用和没有使用VPN的情况下均会出问题

![QQ截图20211215152021](https://user-images.githubusercontent.com/11296891/146141396-82e05787-7276-4006-96a0-e710bdd2cdc9.png)

**Comment by Seng-Jik** [comment]
网页端可正常访问

**Comment by JS-jingshu** [comment]
M1的MacBook也有这个问题

**Comment by Softland99** [comment]
尝试action中发出的修复版本
