### ISSUE TITLE
希望歌词加上模糊效果

### ISSUE THREAD

**Issue by Nevodev** [qier222/YesPlayMusic#110]
如题，filter即可
另外transition可以使用cubic-bezier(0.2,0.2,0,1)，这个比较平滑。

**Comment by qier222** [comment]
模糊的意思是把已播放的歌词模糊掉？
这个动画我试试看效果。

**Comment by Nevodev** [comment]
> 模糊的意思是把已播放的歌词模糊掉？
> 这个动画我试试看效果。

对的

**Comment by qier222** [comment]
> > 模糊的意思是把已播放的歌词模糊掉？
> > 这个动画我试试看效果。
> 
> 对的

网易云歌词时间轴有误差，会出现一行歌词模糊掉了，然后歌手还在唱那行歌词的问题。不过可以搞顶部和底部一两行歌词模糊的效果。

**Comment by Nevodev** [comment]
> > > 模糊的意思是把已播放的歌词模糊掉？
> > > 这个动画我试试看效果。
> > 
> > 
> > 对的
> 
> 网易云歌词时间轴有误差，会出现一行歌词模糊掉了，然后歌手还在唱那行歌词的问题。不过可以搞顶部和底部一两行歌词模糊的效果。

全部的歌都有误差吗，如果是个别几首其实不太用管

**Comment by Nevodev** [comment]
> 网易云歌词时间轴有误差，会出现一行歌词模糊掉了，然后歌手还在唱那行歌词的问题。不过可以搞顶部和底部一两行歌词模糊的效果。

这个可以，如果最顶部的模糊半径大，往下一行模糊半径小，就真成了Apple Music了（

**Comment by qier222** [comment]
@MrWillCom 的 fork仓库有这个功能，但是占用GPU太多了所以没有合并
https://github.com/MrWillCom/YesPlayMusic
