### ISSUE TITLE
随着听歌时间增加 占用内存也随之增大

### ISSUE THREAD

**Issue by NuruiSa** [qier222/YesPlayMusic#1108]
客户端的安装版本与单文件版本都测试过
刚打开的时候记得是100M以内 随着时间占用内存也会随之增大达到1758MB 应该还会增加
系统是Win10LTSC 64位

**Comment by Gabirel** [comment]
疑似Vue.js导致的内存泄漏

**Comment by NuruiSa** [comment]
> 疑似Vue.js导致的内存泄漏

如果单曲循环下好像是没事的 但是随机播放 就会增加了

**Comment by qier222** [comment]
可能是因为读取了缓存的mp3生成了blob链接，用完后没有释放

**Comment by Gabirel** [comment]
> 如果单曲循环下好像是没事的 但是随机播放 就会增加了

经过一晚上的实验，单曲循环，不做任何的事情，内存从86MB增加到了490MB。

所以推测应该不止是读取新的blob没有释放。所以除此之外，的确是有内存泄漏的（可能是逻辑上，可能是Vue组件问题）

**Comment by NuruiSa** [comment]
> > 如果单曲循环下好像是没事的 但是随机播放 就会增加了
> 
> 经过一晚上的实验，单曲循环，不做任何的事情，内存从86MB增加到了490MB。
> 
> 所以推测应该不止是读取新的blob没有释放。所以除此之外，的确是有内存泄漏的（可能是逻辑上，可能是Vue组件问题）

我记得以前的版本好像没有过这个问题？或者是我以前没有注意过。。

**Comment by pan93412** [comment]
> > 如果单曲循环下好像是没事的 但是随机播放 就会增加了
> 
> 经过一晚上的实验，单曲循环，不做任何的事情，内存从86MB增加到了490MB。
> 
> 所以推测应该不止是读取新的blob没有释放。所以除此之外，的确是有内存泄漏的（可能是逻辑上，可能是Vue组件问题）

或許跟早期的 UnblockNeteaseMusic bug 有關係 ( https://github.com/UnblockNeteaseMusic/server/issues/86 )。新組建 (16c36132672efc40af6077fd815e53713ce3cc13 之後) 有包含修正過的版本，試試看下載新版？

https://user-images.githubusercontent.com/28441561/147238855-8113baea-ad1a-424c-9145-35fc026fbb45.mov

**Comment by Gabirel** [comment]
> 或許跟早期的 UnblockNeteaseMusic bug 有關係 ( UnblockNeteaseMusic/server#86 )。新組建 (16c3613 之後) 有包含修正過的版本，試試看下載新版？

问题依旧😨

**Comment by pan93412** [comment]
> > 或許跟早期的 UnblockNeteaseMusic bug 有關係 ( UnblockNeteaseMusic/server#86 )。新組建 (16c3613 之後) 有包含修正過的版本，試試看下載新版？
> 
> 问题依旧😨
> 

那試試看對應到這個 issue 的 PR？下載方式依舊。

**Comment by Gabirel** [comment]
在下载https://github.com/qier222/YesPlayMusic/commit/c73da5c5ad3acccd2e72a98ea700305e094753d1 过，单曲循环，任何UI都没有切过～内存由一开始的99MB上升到276MB（大概测试了30多分钟）

然后，我发现，即使是单曲循环，重新播放一下，内存就上升16MB（与歌曲的大小相关可能）。没开始播放一次就会上升一点点

**Comment by Gabirel** [comment]
@qier222 Any possible updates?

**Comment by qier222** [comment]
> **TL;DR:** 问题依旧
> 
> 在下载[c73da5c](https://github.com/qier222/YesPlayMusic/commit/c73da5c5ad3acccd2e72a98ea700305e094753d1) 过（目前最新的commit），单曲循环，任何UI都没有切过～内存由一开始的99MB上升到276MB（大概测试了30多分钟）
> 
> 然后，我发现，即使是单曲循环，重新播放一下，内存就上升16MB（与歌曲的大小相关可能）。每开始播放一次就会上升一点点

感谢提供信息，因为在写新版本，所以我暂时不会去修复这个bug，我在开发新版本时注意下有没有这个bug

**Comment by Gabirel** [comment]
> 感谢提供信息，因为在写新版本，所以我暂时不会去修复这个bug，我在开发新版本时注意下有没有这个bug

OK，那能否先将这个issue reopen？不然后面就忘了😅

**Comment by memorydream** [comment]
新版已修复

**Comment by Cindaralle** [comment]
拉了最新代码测试 此问题依旧没有修复
随便播放一个歌单 然后一直切下一首 不到一会内存就能吃到1G

**Comment by memorydream** [comment]
> 拉了最新代码测试 此问题依旧没有修复 随便播放一个歌单 然后一直切下一首 不到一会内存就能吃到1G

我这里没有问题，任务管理器显示内存立刻就释放掉了

**Comment by Cindaralle** [comment]
> 我这里没有问题，任务管理器显示内存立刻就释放掉了
我好像发现问题所在了 播放列表里面 有云盘的歌曲 好像一播放云盘的歌曲 内存就回收不了了

**Comment by memorydream** [comment]
> > 我这里没有问题，任务管理器显示内存立刻就释放掉了
> 
> 我好像发现问题所在了 播放列表里面 有云盘的歌曲 好像一播放云盘的歌曲 内存就回收不了了 测试的版本是github上的release版本 不是自己编译的

那这是云盘的bug，还请另开个issue来反馈问题
