### ISSUE TITLE
能不能加一个歌词功能

### ISSUE THREAD

**Issue by 520gcl** [qier222/YesPlayMusic#1115]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by NextAlone** [comment]
![image](https://user-images.githubusercontent.com/12210746/146942841-1fac0c0c-b13d-4358-9a2c-27033433c831.png)

这不是有吗？

**Comment by memorydream** [comment]
![image](https://user-images.githubusercontent.com/34763046/146950121-9f7042f9-5159-471b-81bd-8b013986a16c.png)
按一下这个向上的箭头
