### ISSUE TITLE
0.41版本邮箱登录,使用一段时间后(可能为半个月),音乐库无法加载出来

### ISSUE THREAD

**Issue by hlgf** [qier222/YesPlayMusic#1116]
window10系统  0.41版本邮箱登录,使用一段时间后(可能为半个月),音乐库无法加载出来,注销重新登录,可以成功加载出来页面

**Comment by qier222** [comment]
是扫码登录吗？

**Comment by hlgf** [comment]
> 是扫码登录吗？

不是,是网易邮箱登录

**Comment by ReInvade** [comment]
> 是扫码登录吗？

0.42版本 Mac端 手机号登陆也有同样的问题，重新登陆后加载的出了。

**Comment by Oppinos** [comment]
0.42打开音乐库后UI界面卡死，扫码登录和邮箱登录都不行

**Comment by F1Justin** [comment]
升级到0.43音乐库也无法加载

**Comment by pan93412** [comment]
請重新登入。

**Comment by ceabq** [comment]
在请求playlist/detail时返回400,需要登录
![image](https://user-images.githubusercontent.com/83302491/148603868-c89d3400-06b4-4cbd-9521-1331b44e3ef9.png)
发送的cookie只有NMTID

**Comment by topbardon** [comment]
我也是 **0.41 版本邮箱登录**，到目前为止**无法正常加载音乐库**。而且我**不能添加喜欢的歌曲**，也就是点击**心形的喜欢按钮**后没有任何变化，也无法将歌曲添加到我喜欢。
