### ISSUE TITLE
[68073:1223/215230.754891:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by zozx** [qier222/YesPlayMusic#1122]
[background.js] initializing
[background.js] creating express app
(node:68073) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `yesplaymusic --trace-deprecation ...` to show where the warning was created)
[NetEase API] server running @ http://127.0.0.1:10754
[background.js] app ready event
[background.js] creating app window
[background.js] checkForUpdates
APPIMAGE env is not defined, current application is not an AppImage
(node:68073) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:68073) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setMenu' of undefined
    at App.<anonymous> (/opt/YesPlayMusic/resources/app.asar/background.js:2:2247740)
    at App.emit (events.js:315:20)
(node:68073) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:68073) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:68073) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.a (/opt/YesPlayMusic/resources/app.asar/background.js:2:2106695)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:68073) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[68073:1223/215230.754891:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
[1]    68073 trace trap  /opt/YesPlayMusic/yesplaymusic

### 我这边yesplaymusic下下来会有这样的提示，发行版是Gentoo GNU/Linux，请问是上游的问题吗？

**Comment by memorydream** [comment]
#1035
