### ISSUE TITLE
Touch Bar图标显示问题

### ISSUE THREAD

**Issue by Dormxb** [qier222/YesPlayMusic#113]
我今天安装的macOS端 0.3.1版本(macOS 11.2正式版)，在播放歌曲时，Touch Bar的相应图标显示为统一的问号图标，没有办法直观去区别其功能，但是点击图标有效果，应该为图标显示bug，希望修复一下

**Comment by BestWaveRock** [comment]
同样发现了，猜测开发者应该是用了特殊符号，无法正常展示。希望尽早修复！

- [ ] 播放歌曲时，Touch Bar的相应图标显示为统一的问号图标

**Comment by BestWaveRock** [comment]
@qier222

**Comment by Dormxb** [comment]
0.3.2依然存在此问题，望修复

**Comment by Dormxb** [comment]
![Uploading 触控栏快照2021-01-30 21.42.15.png…]()

**Comment by Dormxb** [comment]
<img width="777" alt="触控栏快照2021-01-30 21 42 15" src="https://user-images.githubusercontent.com/34186779/106357961-4ca8f800-6344-11eb-8781-82e2cb8dc307.png">

**Comment by qier222** [comment]
已经在todo list里了，但是目前有优先级比较高的任务，所以还没修复

**Comment by Mayandev** [comment]
> 我今天安装的macOS端 0.3.1版本(macOS 11.2正式版)，在播放歌曲时，Touch Bar的相应图标显示为统一的问号图标，没有办法直观去区别其功能，但是点击图标有效果，应该为图标显示bug，希望修复一下

需要安装一下 [SF Symbol](https://developer.apple.com/sf-symbols/)，和作者商量过后，还是改成图片 icon，我会提一个 pr 来 fix 这个问题。

**Comment by Mayandev** [comment]
> 我今天安装的macOS端 0.3.1版本(macOS 11.2正式版)，在播放歌曲时，Touch Bar的相应图标显示为统一的问号图标，没有办法直观去区别其功能，但是点击图标有效果，应该为图标显示bug，希望修复一下

fixed in #324

**Comment by qier222** [comment]
0.3.4版本已修复

**Comment by xiyangyang410** [comment]
现在我显示成这样：
![Screenshot-2022-02-21 at 17 43 14](https://user-images.githubusercontent.com/10195904/154931550-c0f43c23-1cc4-4e0b-906a-b8d14b87dadc.png)
点击这个图标不会打开应用

**Comment by pan93412** [comment]
> 现在我显示成这样： <img alt="触控栏快照2022-02-21 17 53 25" width="1004" src="https://user-images.githubusercontent.com/10195904/154931686-e12fce63-ae0e-46b1-9bbc-4531a3b9d48c.png">
> 
> 点击这个图标不会打开应用

幫你轉到新 Issue 了

**Comment by xiyangyang410** [comment]
@pan93412 谢谢
