### ISSUE TITLE
操作频繁,请稍后再试.

### ISSUE THREAD

**Issue by ThomasQAQOUO** [qier222/YesPlayMusic#1144]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端                  网页+客户端
- 浏览器名称或电脑操作系统             edge+windows11
- 控制台 Console 页面的截图（按 F12 可打开控制台）只有登录的时候才会出现![image](https://user-images.githubusercontent.com/89352852/147586820-6bc97b63-5238-4d7c-a57c-36e612aabdfe.png)

**Comment by pan93412** [comment]
似乎與 #1026 重複。
