### ISSUE TITLE
无法播放歌曲时报错 EBADF: bad file descriptor

### ISSUE THREAD

**Issue by memorydream** [qier222/YesPlayMusic#1145]
<div align="center">
  <h1>#1238 有可直接使用的解決版本。</h1>
</div>

---

版本：最新的commit构建
windows10

![image](https://user-images.githubusercontent.com/34763046/147595555-c5b53538-ab57-4f94-a346-8bce59256f18.png)

重现步骤：
弹出 `无法播放 <曲名>` 后稍等一会
弹报错

## 

编辑：
**相关问题的临时解决方案：**
**从终端启动yesplaymusic，并保持终端开启**，这至少对我有用

补充：
需要使用setup版本，如果是单文件版，将exe以压缩文件打开，并解压其中的`$PLUGINSDIR/app-64.7z`
里面是程序的运行文件，运行其中的`YesPlayMusic.exe`即可

## Related

#1161 #1164 #1168 #1172 #1175 #1176 #1178 #1186 #1189 #1192 #1194 #1196 #1208 #1209 #1213 #1222 #1225 #1228 #1230 #1232 #1234 #1247 #1252 #1253 #1262 #1263 #1321

**Comment by pan93412** [comment]
應該是 `pino` 上游的問題。你能幫我收集完整的錯誤訊息，找出重現方法，並幫我把這個問題回報到 [`pino/sonic-boom`](https://github.com/pinojs/sonic-boom) 嗎？謝謝！

**Comment by memorydream** [comment]
> 應該是 `pino` 上游的問題。你能幫我收集完整的錯誤訊息，找出重現方法，並幫我把這個問題回報到 [`pino/sonic-boom`](https://github.com/pinojs/sonic-boom) 嗎？謝謝！

我晚上看看

**Comment by memorydream** [comment]
这个issue我先关了，还没有找到相关的问题

**Comment by pan93412** [comment]
> 版本：最新的commit构建 windows10
> 
> ![image](https://user-images.githubusercontent.com/34763046/147595555-c5b53538-ab57-4f94-a346-8bce59256f18.png)
> 
> 重现步骤： 弹出 `无法播放 <曲名>` 后稍等一会 弹报错
> 
> 编辑： **相关问题的临时解决方案：** **从终端启动yesplaymusic，并保持终端开启**，这至少对我有用
> 
> 补充： 需要使用setup版本，如果是单文件版，将exe以压缩文件打开，并解压其中的`$PLUGINSDIR/app-64.7z` 里面是程序的运行文件，运行其中的`YesPlayMusic.exe`即可
> 
> ## Related
> #1161 #1164 #1168 #1172 #1175 #1176 #1178

用 cmd 開啟 YPM 的範例操作影片：

https://user-images.githubusercontent.com/28441561/148159732-ae750acc-8d7c-4125-a0fb-978aa58825d5.mp4

**Comment by memorydream** [comment]
其实不需要这么麻烦，可以直接在cmd中仅使用exe的路径来启动ypm

如果路径很长，可以直接将exe拖入终端，会自动填上exe的绝对路径

**Comment by cs-xiao** [comment]
> 其实不需要这么麻烦，可以直接在cmd中仅使用exe的路径来启动ypm
> 
> 如果路径很长，可以直接将exe拖入终端，会自动填上exe的绝对路径

还是会报错，win10

**Comment by pan93412** [comment]
> > 其实不需要这么麻烦，可以直接在cmd中仅使用exe的路径来启动ypm
> > 如果路径很长，可以直接将exe拖入终端，会自动填上exe的绝对路径
> 
> 还是会报错，win10

終端器顯示什麼

**Comment by memorydream** [comment]
> > 其实不需要这么麻烦，可以直接在cmd中仅使用exe的路径来启动ypm
> > 
> > 如果路径很长，可以直接将exe拖入终端，会自动填上exe的绝对路径
> 
> 还是会报错，win10

请确认从终端启动后，终端内有输出，而不仅仅是换行而没有后续的，终端也要保持开启不能关闭

不能从终端启动单文件版，单文件版请先将其解压，并使用解压出来的运行文件

**Comment by cs-xiao** [comment]
> > > 其实不需要这么麻烦，可以直接在cmd中仅使用exe的路径来启动ypm
> > > 如果路径很长，可以直接将exe拖入终端，会自动填上exe的绝对路径
> > 
> > 
> > 还是会报错，win10
> 
> cmd 顯示什麼

我操作有误，不会报错了，不能播放的歌曲会一直卡住，控制台显示【WARN: (request) The request timed out, or the requester didn't handle the response】.（开启unblock）

**Comment by memorydream** [comment]
> > > > 其实不需要这么麻烦，可以直接在cmd中仅使用exe的路径来启动ypm
> > > > 如果路径很长，可以直接将exe拖入终端，会自动填上exe的绝对路径
> > > 
> > > 
> > > 还是会报错，win10
> > 
> > 
> > cmd 顯示什麼
> 
> 我操作有误，不会报错了，不能播放的歌曲会一直卡住，控制台显示【WARN: (request) The request timed out, or the requester didn't handle the response】.（开启unblock）

如果经常这样的话，可以尝试手动设定unm源，排除掉bilibili

**Comment by nptiger** [comment]
> 

我也有这问题，0.4.2版本OK，升级到0.4.3就这样了
![image](https://user-images.githubusercontent.com/91775896/148692693-109faa8b-f220-442a-bea5-be4ed852488c.png)

**Comment by memorydream** [comment]
> > 
> 
> 我也有这问题，0.4.2版本OK，升级到0.4.3就这样了 ![image](https://user-images.githubusercontent.com/91775896/148692693-109faa8b-f220-442a-bea5-be4ed852488c.png)

问题要等上游修复，这个issue内已经给出了临时的解决方法，可以尝试使用

**Comment by tominysun** [comment]
弄了个小脚本,可以做成bat.参照了上面的方法临时解决问题+隐藏cmd窗口😉
```
@echo off
if "%1" neq "1" (
>"%temp%\tmp.vbs" echo set WshShell = WScript.CreateObject^(^"WScript.Shell^"^)
>>"%temp%\tmp.vbs" echo WshShell.Run chr^(34^) ^& %0 ^& chr^(34^) ^& ^" 1^",0
start /d "%temp%" tmp.vbs
exit

)
"D:\Program Files\YesPlayMusic\YesPlayMusic.exe"
pause
```
记得修改主程序文件路径哈

**Comment by nptiger** [comment]
谢谢兄弟，我先退回到0.4.2版本了2022年1月10日 16:57，Tominysun ***@***.***>写道：

弄了个小脚本,可以做成bat.参照了上面的方法临时解决问题+隐藏cmd窗口😉

@echo off

if "%1" neq "1" (

>"%temp%\tmp.vbs" echo set WshShell = WScript.CreateObject^(^"WScript.Shell^"^)

>>"%temp%\tmp.vbs" echo WshShell.Run chr^(34^) ^& %0 ^& chr^(34^) ^& ^" 1^",0

start /d "%temp%" tmp.vbs

exit



)

"D:\Program Files\YesPlayMusic\YesPlayMusic.exe"

pause



记得修改主程序文件路径哈

**Comment by hexuann** [comment]
win11 也是

**Comment by memorydream** [comment]
> win11 也是

理论上所有的windows系统都会存在这个bug

**Comment by ForestL18** [comment]
> 弄了个小脚本,可以做成bat.参照了上面的方法临时解决问题+隐藏cmd窗口😉
> 
> ```
> @echo off
> if "%1" neq "1" (
> >"%temp%\tmp.vbs" echo set WshShell = WScript.CreateObject^(^"WScript.Shell^"^)
> >>"%temp%\tmp.vbs" echo WshShell.Run chr^(34^) ^& %0 ^& chr^(34^) ^& ^" 1^",0
> start /d "%temp%" tmp.vbs
> exit
> 
> )
> "D:\Program Files\YesPlayMusic\YesPlayMusic.exe"
> pause
> ```
> 
> 记得修改主程序文件路径哈

建议把最后的pause改为exit，不然退出yesplaymusic后，会有控制台主窗口进程留在后台

**Comment by CYLlinmaian** [comment]
> 弄了个小脚本,可以做成bat.参照了上面的方法临时解决问题+隐藏cmd窗口😉
> 
> ```
> @echo off
> if "%1" neq "1" (
> >"%temp%\tmp.vbs" echo set WshShell = WScript.CreateObject^(^"WScript.Shell^"^)
> >>"%temp%\tmp.vbs" echo WshShell.Run chr^(34^) ^& %0 ^& chr^(34^) ^& ^" 1^",0
> start /d "%temp%" tmp.vbs
> exit
> 
> )
> "D:\Program Files\YesPlayMusic\YesPlayMusic.exe"
> pause
> ```
> 
> 记得修改主程序文件路径哈

楼主你好，当我想把这个bat文件固定在开始菜单的时候，在桌面建立快捷方式时输入路径cmd /c "E:\Music\Music.bat"时以cmd启动会出现Windows Script Host缺少语句的错误：
脚本C: \Users\Cyllinmaianvappdata\Local\Temp\tmp. vbs
行2
字符26
错误缺少语句
代码800A0400
源Microsoft VB Script编译器错吴
这个有办法解决吗，我想固定在开始菜单，启动的时候方便

**Comment by Forest-Cxh** [comment]
> > > 
> > 
> > 
> > 我也有这问题，0.4.2版本OK，升级到0.4.3就这样了 ![image](https://user-images.githubusercontent.com/91775896/148692693-109faa8b-f220-442a-bea5-be4ed852488c.png)
> 
> 问题要等上游修复，这个issue内已经给出了临时的解决方法，可以尝试使用

怎么解决这个问题？

**Comment by Forest-Cxh** [comment]
# 播放非网易云的音乐 会弹出弹窗，怎么解决这个问题？

**Comment by pan93412** [comment]
> # 播放非网易云的音乐 会弹出弹窗，怎么解决这个问题？

到 Telegram 群組敲管理員處理。

**Comment by uangsv** [comment]
我已经使用这个思路重新创建了yesplaymusic的快捷方式以便让他正常工作
1. 将 终端启动YESPLAYMUSIC 简化为 .BAT
2. 通过 .VBS 隐藏运行终端启动的 .BAT
3. 将 .BAT， .VBS打包成一个新的 YPM.EXE文件
4. 修改快捷方式目标修改为 "...\YPM.EXE"

[查看详细](https://uangsv.gitee.io/2022/02/28/YesPlayMusic%E5%90%AF%E5%8A%A8%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88/)

> 以上对github yesplaymusic项目造成知识权利等问题可联系我删除此文章

**Comment by Oeaps** [comment]
研究了一下，报错都源于@unblockneteasemusic，给大家提供一个大聪明解决办法，把`@unblockneteasemusic/src/`下的`spwan.js`和`request.js`里的两句`logger.warn...`都注释掉然后重新编译下就行了。
我才测试了一小会儿，还不能确定这样做的稳定性，也不知道对unblock的功能有没有影响，或许可以作为临时解决方案。

**Comment by pan93412** [comment]
> 研究了一下，报错都源于@unblockneteasemusic，给大家提供一个大聪明解决办法，把`@unblockneteasemusic/src/`下的`spwan.js`和`request.js`里的两句`logger.warn...`都注释掉然后重新编译下就行了。
> 我才测试了一小会儿，还不能确定这样做的稳定性，也不知道对unblock的功能有没有影响，或许可以作为临时解决方案。

那也是一種解決方案，但 UNM 端不可能這麼做。其實你也可以考慮把 pino 升級到 v7，這樣或許也能解決問題。

**Comment by iRuizeWu** [comment]
解决方案：在命令行打开。
具体方法：在桌面（或其他任意地方）**新建一个ypm.bat文件**，填入下面的内容，注意里面的路径是自己的安装路径。
效果：闪一下黑框就会隐藏启动播放器的命令行窗口，只显示最后的播放器。
```
@echo off
if "%1" == "h" goto begin
mshta vbscript:createobject("wscript.shell").run("""%~nx0"" h",0)(window.close)&&exit
:begin
REM
cd C:\Program Files\YesPlayMusic
.\YesPlayMusic.exe 
```

**Comment by rampageX** [comment]
Quick Batch File Compiler 转的启动器,内容只有有一句:

```
cd /d %~dp0
.\YesPlayMusic.exe
```

下载改后缀名为 exe,丢到 YesPlayMusic 目录下运行即可.
[YPM.zip](https://github.com/qier222/YesPlayMusic/files/8406159/YPM.zip)

**Comment by pan93412** [comment]
> > > 研究了一下，报错都源于@UnblockNeteaseMusic，给大家提供一个大聪明解决办法，把`@unblockneteasemusic/src/`下的`spwan.js`和`request.js`里的两句`logger.warn...`都注释掉然后重新编译下就行了。
> > > 我才测试了一小会儿，还不能确定这样做的稳定性，也不知道对unblock的功能有没有影响，或许可以作为临时解决方案。
> > 
> > 
> > 那也是一種解決方案，但 UNM 端不可能這麼做。其實你也可以考慮把 pino 升級到 v7，這樣或許也能解決問題。
> 
> 测试了pino 7.9.2 & sonic-boom 2.7.0 ，至少request.js里那句timeout时的logger.warn还是会弹窗报错，和之前的报错完全一致。 有没有考虑在release里先沉默掉这条报错，因为这个报错发起的issue太多了，复现挺容易的没必要都log下来，而且也不影响功能，没有的音源还是播放不了😢
> 
> ```
> [Window Title]
> Error
> 
> [Main Instruction]
> A JavaScript error occurred in the main process
> 
> [Content]
> Uncaught Exception:
> Error: EBADF: bad file descriptor, write
>     at Object.writeSync (fs.js:711:3)
>     at actualWrite (C:\Users\XX\AppData\Local\Temp\27VTecx8cYaEmDfvHDpDJyD6CBo\resources\app.asar\node_modules\@unblockneteasemusic\server\node_modules\sonic-boom\index.js:376:26)
>     at SonicBoom.write (C:\Users\XX\AppData\Local\Temp\27VTecx8cYaEmDfvHDpDJyD6CBo\resources\app.asar\node_modules\@unblockneteasemusic\server\node_modules\sonic-boom\index.js:242:5)
>     at Object.write (C:\Users\XX\AppData\Local\Temp\27VTecx8cYaEmDfvHDpDJyD6CBo\resources\app.asar\node_modules\@unblockneteasemusic\server\node_modules\pino\lib\tools.js:326:12)
>     at Pino.write (C:\Users\XX\AppData\Local\Temp\27VTecx8cYaEmDfvHDpDJyD6CBo\resources\app.asar\node_modules\@unblockneteasemusic\server\node_modules\pino\lib\proto.js:208:10)
>     at Pino.LOG [as warn] (C:\Users\XX\AppData\Local\Temp\27VTecx8cYaEmDfvHDpDJyD6CBo\resources\app.asar\node_modules\@unblockneteasemusic\server\node_modules\pino\lib\tools.js:58:21)
>     at ClientRequest.<anonymous> (C:\Users\XX\AppData\Local\Temp\27VTecx8cYaEmDfvHDpDJyD6CBo\resources\app.asar\node_modules\@unblockneteasemusic\server\src\request.js:119:12)
>     at Object.onceWrapper (events.js:421:28)
>     at ClientRequest.emit (events.js:315:20)
>     at Socket.emitRequestTimeout (_http_client.js:784:9)
> 
> [确定]
> ```

其實影響到功能了。目前比較好的解法，除了 #1238 就是把 UNM 所有的 logger 語句全數砍掉。然而後者的工作量不小，而且這嚴格來說也不是 UNM 的問題（更像是 Windows 的問題），所以不適合在 UNM 上更改。

**Comment by LINGSJH** [comment]
我使用0.44版本出现了这个问题，用回0.33版本后这个问题解决了。

**Comment by Mini-suger** [comment]
安装yt-dlp之后不报错了

**Comment by Victor9578** [comment]
bat的快捷方式 不能添加到任务栏 

可以使用iexpress 转换出一个exe
