### ISSUE TITLE
Windows 0.4.2最新版本，音乐库无法打开bug仍然存在

### ISSUE THREAD

**Issue by TheLastGreenseer** [qier222/YesPlayMusic#1147]
如题，已下载“修复后续问题”版本，但仍然时不时出现无法打开音乐库的问题。

**Comment by memorydream** [comment]
https://github.com/qier222/YesPlayMusic/actions/runs/1632185867   请使用这个版本

**Comment by pan93412** [comment]
修正這個問題的版本尚未發布 😂 這個問題解決之後我會協助發布一個版本
