### ISSUE TITLE
音乐库刷新不出来，设置打不开是什么情况？

### ISSUE THREAD

**Issue by DMCzero** [qier222/YesPlayMusic#115]

**Comment by DMCzero** [comment]
解决了，把缓存清了就行了。

**Comment by Xiritianming** [comment]
一样的问题 问一下怎么解决

**Comment by Unclesoul** [comment]
我也出现同样的问题，请求大佬帮助

**Comment by HatsuneMona** [comment]
你好，我也遇到了相同的问题，首页、发现、登录功能均无法使用。此外，**我在路由器上使用了** [**UnblockNeteaseMusic**](https://github.com/nondanee/UnblockNeteaseMusic) 。我的官方客户端可正常使用， 原生网页端（ http://music.163.com ）因为证书原因无法访问。不知道我的情况对楼主是否有帮助。

根据 UnblockNeteaseMusic 的ReadMe，我找到了这样的话：
> 目前除 UWP 外其它客户端均优先请求 HTTPS 接口，默认配置下本代理对网易云所有 HTTPS API 连接返回空数据，促使客户端降级使用 HTTP 接口 (新版 Linux 客户端和 macOS 客户端已无法降级)

希望能对楼主有所帮助。
经过测试，将路由器上的UnblockNeteaseMusic服务禁用以后，YesPlayMusic可以正常使用。

**Comment by Unclesoul** [comment]
感谢，禁用以后问题解决了

**Comment by DMCzero** [comment]
> 一样的问题 问一下怎么解决

C:\Users\username\AppData\Roaming\YesPlayMusic 我是把这个文件夹删了，然后重新回去登陆就行了

**Comment by qier222** [comment]
按Ctrl+Alt+i / ⌘+⌥+i打开控制台，选择Application，清空Local Storage和Cookies下的所有数据。
如果还是不行的话，请选择Console，然后截图发送给我。

**Comment by HatsuneMona** [comment]
纠正：Windows环境下是 **Shift+Ctrl+i** 打开控制台。
从控制台来看，访问 `localhost:27232` 出现了错误，返回的是504错误。
备注：我测试时，路由器处于开启UnblockNeteaseMusic服务的状态下。

![image](https://user-images.githubusercontent.com/29496879/106347382-f2367a00-62f8-11eb-8ca8-0bce733b8d82.png)
![image](https://user-images.githubusercontent.com/29496879/106347400-27db6300-62f9-11eb-8b47-995cb1bdba53.png)

**Comment by HatsuneMona** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1006
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1070
根据Binaryify/NeteaseCloudMusicApi中的issues，这个问题有可能是API端的证书校验问题？

**Comment by HatsuneMona** [comment]
继续根据楼上的issues，我找到的解决办法如下：（windows）设置系统用户环境变量，变量名： `NODE_TLS_REJECT_UNAUTHORIZED` ，值： `0` 。

**Comment by Xiritianming** [comment]
> > 一样的问题 问一下怎么解决
> 
> C:\Users\username\AppData\Roaming\YesPlayMusic 我是把这个文件夹删了，然后重新回去登陆就行了

可以了 非常感谢

**Comment by zzinggame** [comment]
> Continuing with the issues upstairs,
> I found the following solution: (windows) set the system user environment variable, variable name: , value: .
> (Linux) is also set global variables, little brother is not talented, not very skilled, here is not to write x.`NODE_TLS_REJECT_UNAUTHORIZED``0`
> 
> ##### Modifying system variables can also affect other software developed .js Mode and may affect the security of other software, as appropriate.
> Once set up, the app can coexist with the UnblockNeteaseMusic service. After testing, grey songs could not be searched through a combination of YesPlayMusic and UNblockNeteaseMusic, but grey songs already on the list could be played (this feature is available in YesPlayMusic itself).

Worked but a bit annoying

**Comment by qier222** [comment]
0.3.3版已修复，如果存在这个问题的话请重新开启issue

**Comment by xiandi957** [comment]
> > 一样的问题 问一下怎么解决
> 
> C:\Users\username\AppData\Roaming\YesPlayMusic 我是把这个文件夹删了，然后重新回去登陆就行了

非常感谢

**Comment by bobz1** [comment]
0.35，win10，旁路由器上开了UnblockNeteaseMusic服务，yes还是不能并存使用，求指点？！

**Comment by bobz1** [comment]
> 继续根据楼上的issues，我找到的解决办法如下：
> （windows）设置系统用户环境变量，变量名： `NODE_TLS_REJECT_UNAUTHORIZED` ，值： `0` 。
> （Linux）也是设置全局变量，小弟不才，不是很熟练，这里就不写了x。
> 
> ##### 修改系统变量也会影响到其他使用Node.js开发的软件，可能会影响到其他软件的安全性，请酌情使用。
> 设置后，该应用可以与 UnblockNeteaseMusic服务 并存。经过测试，不能通过YesPlayMusic + UNblockNeteaseMusic的组合搜索到灰色歌曲；但是可以播放歌单里已有的灰色歌曲（这个功能YesPlayMusic本身就提供了）。


同样的问题，用了这个办法，ok了，谢谢

**Comment by xiandi957** [comment]
太感谢了，大佬

bobz1 ***@***.***> 于2021年4月7日周三 下午4:28写道：
