### ISSUE TITLE
通过docker部署无UnblockNeteaseMusic选项

### ISSUE THREAD

**Issue by sjtuross** [qier222/YesPlayMusic#1156]
我是通过docker部署的，网页版访问，发现第三方选项中没有UnblockNeteaseMusic，请问有何办法启用吗？

![image](https://user-images.githubusercontent.com/940110/147740855-f07dd09e-794d-48ef-841a-afb8b8656dc2.png)

**Comment by memorydream** [comment]
网页版不支持UnblockNeteaseMusic
![image](https://user-images.githubusercontent.com/34763046/147741500-65727d3e-319f-4042-98d0-1016fba71500.png)

**Comment by sjtuross** [comment]
其实我是想了解更多细节，是技术原因还是非技术原因

**Comment by memorydream** [comment]
具体我不太清楚，但是有一个相关的issus: #644

**Comment by pan93412** [comment]
> 其实我是想了解更多细节，是技术原因还是非技术原因

UnblockNeteaseMusic 畢竟最早是一個純針對伺服器端的後端伺服器，其底層用了很多 Node.js 才支援的函數。瀏覽器很難相容寫給 Node.js 的 Library，因此就乾脆不允許使用。

至於 Electron 為何就可以使用 UNM 呢？其實 YPM Electron 版的 UnblockNeteaseMusic 仍然是在 Node.js 執行，而 YPM 的前端部分用了 IPC 技術跟執行在後端 Node.js 的 UNM 通訊。

**Comment by sjtuross** [comment]
对于web版来说是有后端的，UNM是不是可以不运行在前端？而是在后端api之前加一层代理服务？

**Comment by pan93412** [comment]
> 对于web版来说是有后端的，UNM是不是可以不运行在前端？而是在后端api之前加一层代理服务？

vue-cli 的後端目前的用途只有 SSR 和 serve 這個 app 而已吧？這個專案用的不是 Nuxt.js，我不清楚要怎麼讓這個後端支援 UNM（我也沒時間重構 😂 ）。

**Comment by qier222** [comment]
> > 对于web版来说是有后端的，UNM是不是可以不运行在前端？而是在后端api之前加一层代理服务？
> 
> 
> 
> vue-cli 的後端目前的用途只有 SSR 和 serve 這個 app 而已吧？這個專案用的不是 Nuxt.js，我不清楚要怎麼讓這個後端支援 UNM（我也沒時間重構 😂 ）。

是不是可以让UMN提供个http api，跑在服务期上🤔

**Comment by pan93412** [comment]
> > > 对于web版来说是有后端的，UNM是不是可以不运行在前端？而是在后端api之前加一层代理服务？
> > 
> > 
> > vue-cli 的後端目前的用途只有 SSR 和 serve 這個 app 而已吧？這個專案用的不是 Nuxt.js，我不清楚要怎麼讓這個後端支援 UNM（我也沒時間重構 😂 ）。
> 
> 是不是可以让UMN提供个http api，跑在服务期上🤔

之後我有空會重寫 UNM。到時候再說了 😂

**Comment by sjtuross** [comment]
请教一下，如果我在OP网关上运行luci插件做透明代理，是否能解锁web版？暂时还没环境测试

**Comment by sjtuross** [comment]
或者如果docker支持通过环境变量设置代理，指向单独运行的UNM？

**Comment by sjtuross** [comment]
透明代理的方式搞定了，由于我用的YesPlayMusic docker容器并没有信任UNM自签的CA，只能添加这个环境变量NODE_TLS_REJECT_UNAUTHORIZED=0来忽略SSL错误UNABLE_TO_VERIFY_LEAF_SIGNATURE，web版可以正常解锁了

@pan93412 @qier222

**Comment by RealKiro** [comment]
> NODE_TLS_REJECT_UNAUTHORIZED

问一下除了开启`luci-UnblockNeteaseMusic`以及给 YesPlayMusic docker容器 增加环境变量 `NODE_TLS_REJECT_UNAUTHORIZED=0` 外还需要作何设置？

**Comment by RealKiro** [comment]
> 透明代理的方式搞定了，由于我用的YesPlayMusic docker容器并没有信任UNM自签的CA，只能添加这个环境变量NODE_TLS_REJECT_UNAUTHORIZED=0来忽略SSL错误UNABLE_TO_VERIFY_LEAF_SIGNATURE，web版可以正常解锁了
> 
> @pan93412 @qier222

@sjtuross 问一下老哥 除了开启`luci-UnblockNeteaseMusic`以及给 YesPlayMusic docker容器 增加环境变量 `NODE_TLS_REJECT_UNAUTHORIZED=0` 外还需要作何设置？

**Comment by RealKiro** [comment]
> > 透明代理的方式搞定了，由于我用的YesPlayMusic docker容器并没有信任UNM自签的CA，只能添加这个环境变量NODE_TLS_REJECT_UNAUTHORIZED=0来忽略SSL错误UNABLE_TO_VERIFY_LEAF_SIGNATURE，web版可以正常解锁了
> > @pan93412 @qier222
> 
> @sjtuross 问一下老哥 除了开启`luci-UnblockNeteaseMusic`以及给 YesPlayMusic docker容器 增加环境变量 `NODE_TLS_REJECT_UNAUTHORIZED=0` 外还需要作何设置？我使用了ipset劫持歌曲不变灰了但播放不了

已成功解锁，感谢

**Comment by conscloud** [comment]
> > > 透明代理的方式搞定了，由于我用的YesPlayMusic docker容器并没有信任UNM自签的CA，只能添加这个环境变量NODE_TLS_REJECT_UNAUTHORIZED=0来忽略SSL错误UNABLE_TO_VERIFY_LEAF_SIGNATURE，web版可以正常解锁了
> > > @pan93412 @qier222
> > 
> > 
> > @sjtuross 问一下老哥 除了开启以及给 YesPlayMusic docker容器 增加环境变量  外还需要作何设置？我使用了ipset劫持歌曲不变灰了但播放不了`luci-UnblockNeteaseMusic``NODE_TLS_REJECT_UNAUTHORIZED=0`
> 
> 已成功解锁，感谢
> 
> > [群晖Docker构建YPM](http://13145212.xyz/archives/%E7%BE%A4%E6%99%96docker%E6%9E%84%E5%BB%BAypm)

怎么实现的能否详细指导下，谢谢。链接打不开了。

**Comment by RealKiro** [comment]
> 怎么实现的能否详细指导下，谢谢。链接打不开了。

更新0.4.4-1后无法解锁，还在试@conscloud

**Comment by scbizu** [comment]
貌似 UNM JS版本是有提供 API 的，参见: https://github.com/nondanee/UnblockNeteaseMusic/issues/377 。

我有个大胆的想法: 是不是部署在 vercel 或者类似平台的 Web 版本也有接入 UNM 的可能性 ?

**Comment by pan93412** [comment]
> 貌似 UNM JS版本是有提供 API 的，参见: [nondanee/UnblockNeteaseMusic#377](https://github.com/nondanee/UnblockNeteaseMusic/issues/377) 。
> 
> 我有个大胆的想法: 是不是部署在 vercel 或者类似平台的 Web 版本也有接入 UNM 的可能性 ?

UNM 的 JS 版本似乎沒有為 Vercel 優化。事實上 UNM Rust 有另一個可靠的 REST API，不過考慮到快取等等的因素，目前還沒有對此的最佳化。

**Comment by scbizu** [comment]
> > 貌似 UNM JS版本是有提供 API 的，参见: [nondanee/UnblockNeteaseMusic#377](https://github.com/nondanee/UnblockNeteaseMusic/issues/377) 。
> > 我有个大胆的想法: 是不是部署在 vercel 或者类似平台的 Web 版本也有接入 UNM 的可能性 ?
> 
> UNM 的 JS 版本似乎沒有為 Vercel 優化。事實上 UNM Rust 有另一個可靠的 REST API，不過考慮到快取等等的因素，目前還沒有對此的規劃。

啊 ，我看到YPM的UNM已经切换成Rust版本的了 ，期待新的 REST API ~

**Comment by huluohu** [comment]
请问这个问题有新进展吗？
