### ISSUE TITLE
听歌过程中出现JavaScript error

### ISSUE THREAD

**Issue by NuruiSa** [qier222/YesPlayMusic#1161]
目前没有试过在打开软件后不操作的情况下会不会出现error

听歌的过程中会出现 以及 在首页音乐库以及发现 这三个选项切换的时候 会增加error出现的几率

![QQ截图20220101210528](https://user-images.githubusercontent.com/96377681/147851950-52d774ce-58b9-450a-b3f2-acc6e895d7dc.png)

**Comment by memorydream** [comment]
和 #1145 应该是同一个问题

**Comment by pan93412** [comment]
dup #1145

**Comment by 866837** [comment]
> 目前没有试过在打开软件后不操作的情况下会不会出现error
> 
> 听歌的过程中会出现 以及 在首页音乐库以及发现 这三个选项切换的时候 会增加error出现的几率
> 
> ![QQ截图20220101210528](https://user-images.githubusercontent.com/96377681/147851950-52d774ce-58b9-450a-b3f2-acc6e895d7dc.png)

我和你的情况一样 听着就莫名出现这个界面有时候确认一次，有时候要确认五六次 
系统是win10 21h2

**Comment by pan93412** [comment]
> > 目前没有试过在打开软件后不操作的情况下会不会出现error
> > 
> > 听歌的过程中会出现 以及 在首页音乐库以及发现 这三个选项切换的时候 会增加error出现的几率
> > 
> > ![QQ截图20220101210528](https://user-images.githubusercontent.com/96377681/147851950-52d774ce-58b9-450a-b3f2-acc6e895d7dc.png)
> 
> 我和你的情况一样 听着就莫名出现这个界面有时候确认一次，有时候要确认五六次 
> 系统是win10 21h2

看 #1145
