### ISSUE TITLE
【bug】A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by jasonchio-cn** [qier222/YesPlayMusic#1164]
在开启 UnblockNeteaseMusic 的情况下，出现了如下的错误提示（socket emit请求超时）
![image](https://user-images.githubusercontent.com/36125147/147912725-2a8bfc17-170a-409b-a86d-3aa33cf4772a.png)

### 反馈 bug 需要的信息
- 客户端 v0.4.3
- Windows 10
- 控制台 Console 页面的截图
![image](https://user-images.githubusercontent.com/36125147/147912843-041e85bf-468b-45b5-80b9-b0160d0002e2.png)

**Comment by qier222** [comment]
cc @pan93412

**Comment by pan93412** [comment]
dup #1145
