### ISSUE TITLE
ios版

### ISSUE THREAD

**Issue by 2211649442** [qier222/YesPlayMusic#1165]
会开发ios版吗 testflight的也行

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by qier222** [comment]
没有计划和兴趣开发移动端

**Comment by Remonli** [comment]
iOS版本开发的话，真的动了蛋糕了，不可能会像现在一样睁一只眼闭一只眼了。
