### ISSUE TITLE
剛才更新的新版本，打開以後播放點了無法暫停，歌詞無法打開，之後就顯示無響應

### ISSUE THREAD

**Issue by yujiahuahua** [qier222/YesPlayMusic#1167]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）
Windows電腦客服端

**Comment by pan93412** [comment]
很難通靈呢⋯⋯

- 你用的電腦作業系統是什麼？
- 你方便錄製整個操作步驟嗎？我這裡測試沒問題。

**Comment by yujiahuahua** [comment]
Windows7 


Uploading QQ录屏20220103221037.mp4…

**Comment by yujiahuahua** [comment]
![20221354303979](https://user-images.githubusercontent.com/63892790/147940752-bdd24397-3ba0-4ee3-90e3-f1d4e6e975b9.jpg)

**Comment by yujiahuahua** [comment]
抱歉视频没发过去
