### ISSUE TITLE
播放久了 出来的啥不知道

### ISSUE THREAD

**Issue by 2211649442** [qier222/YesPlayMusic#1168]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 [👉](url)

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![微信图片_20220103200532](https://user-images.githubusercontent.com/78134574/147928490-c6b27306-e986-4be8-9a4e-dda693074c69.png)

**Comment by 2211649442** [comment]
win11 客户端

**Comment by pan93412** [comment]
dup #1145 我在查錯了

**Comment by 2211649442** [comment]
可靠

**Comment by 2211649442** [comment]
> 

可靠
