### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by schlesimu** [qier222/YesPlayMusic#117]
横屏模式下dock栏希望略微调整
随时可以帮忙，我是UI设计；会h5及css。
然后是主题色，背景渐变可以用css实现。
想把网页端简易打包移到TV上去，这类app空缺。

**Comment by qier222** [comment]
默认就是横屏模式吧…dock具体哪些地方要优化？

**Comment by schlesimu** [comment]
![横屏模式下调整padding](https://user-images.githubusercontent.com/38551584/106230431-6eae5780-622a-11eb-9323-2e4994bfdc46.png)
在UA是安卓或是iPad的情况下， padding:5vw>6vw
或者是通过分辨率，我拿电视测的是3840*2160的，5vw情况下右下角图标略微有一些重叠。你可以拿chrome pixel 2xl试下。
很抱歉我github用的不熟练
![原版](https://user-images.githubusercontent.com/38551584/106230755-33605880-622b-11eb-8fc3-f0321c35bc42.png)

**Comment by qier222** [comment]
写的时候偷懒直接用fixed定位了（之后有空再改）

**Comment by qier222** [comment]
现在打开歌词的按钮已经移动位置了
