### ISSUE TITLE
客户端0.4.3发布版不定时弹出error提示框

### ISSUE THREAD

**Issue by TCH12** [qier222/YesPlayMusic#1172]
客户端v0.4.3
不定时弹出error提示框
![image](https://user-images.githubusercontent.com/95664205/147996191-271a34f7-0e98-445e-b0fd-d20d92eb3d62.png)

**Comment by pan93412** [comment]
dup #1145

**Comment by cs-xiao** [comment]
临时解决：在设置里把unblock功能先关了；或使用旧版客户端

**Comment by pan93412** [comment]
原則上這個錯誤應該不影響程式剩餘邏輯的運作，而且似乎只在 Windows 上發生。我晚點測試。

**Comment by TCH12** [comment]
> 

有一点影响，出现error提示后会在已缓存的歌曲（近10首？）里循环

**Comment by TCH12** [comment]
> 原則上這個錯誤應該不影響程式剩餘邏輯的運作，而且似乎只在 Windows 上發生。我晚點測試。

有一点影响，出现error提示后会在已缓存的歌曲（近10首？）里循环
