### ISSUE TITLE
遇到无法播放的歌曲直接报错

### ISSUE THREAD

**Issue by Mrbusi** [qier222/YesPlayMusic#1175]
歌曲17岁-刘德华
![image](https://user-images.githubusercontent.com/82917170/148012664-8f7a9f4b-a06d-4f0d-ab81-91c013f8a9c5.png)

**Comment by topping-hao** [comment]
我也遇到这个问题，当选择歌单播放时，异常弹窗关不完

**Comment by pan93412** [comment]
dup of #1145, 相關問題請到這個 Issue 討論
