### ISSUE TITLE
下载0.4.3exe版本播放音乐报错(我点击了一首音乐，提示我不能播放)

### ISSUE THREAD

**Issue by wonktondI** [qier222/YesPlayMusic#1176]
你好，作者。
![image](https://user-images.githubusercontent.com/41692176/148024523-733b49f7-1e9c-4e80-9800-ebe51e085324.png)
然后跳转到下一首歌。

我怎么可以区分我是用UnblockNeteaseMusic 音源还是其他，这个可以区分吗？

**Comment by KwokZev** [comment]
在后台播放音乐时同样出现了错误，触发条件不明。
![image](https://user-images.githubusercontent.com/45304802/148034689-18ed4394-5b3a-4ad5-be24-a01dbcd57c2b.png)

**Comment by memorydream** [comment]
#1145 在修了

**Comment by pan93412** [comment]
你可以先將「啟用 UnblockNeteaseMusic」關閉，這樣應該能暫時解決彈窗的問題。其他問題歡迎到 @memorydream 指出的 Issue 繼續詢問w
