### ISSUE TITLE
0.4.3版本unlockneteasemusic失效

### ISSUE THREAD

**Issue by ForestL18** [qier222/YesPlayMusic#1178]
0.4.3客户端
Windows10 21H2
![image](https://user-images.githubusercontent.com/45709305/148098818-6ccf75c6-9edc-40de-8333-fb320f99f178.png)
![image](https://user-images.githubusercontent.com/45709305/148099092-9145b6f8-1f31-4e9f-b55e-fd84b7bd7cbe.png)

**Comment by ForestL18** [comment]
同一首歌，0.4.2版本win10 客户端播放正常

**Comment by memorydream** [comment]
此报错与 #1145 重复，1145中提供了一个解决此报错方案，并且此方案可以一定程度上解决部分歌曲无法解锁的问题

如果有后续的相关问题，请在1145中回复我
