### ISSUE TITLE
windows7，安装包和单文件都试过，一播放就显示停止工作（内有win7修复版链接）

### ISSUE THREAD

**Issue by yujiahuahua** [qier222/YesPlayMusic#1179]
![147940752-bdd24397-3ba0-4ee3-90e3-f1d4e6e975b9](https://user-images.githubusercontent.com/63892790/148155131-f9073ca1-e9bd-4f47-be30-1549d2170a77.jpg)
如图
是什么原因呢

**Comment by wildabc** [comment]
同为Win7，有同样的问题，可能是已不支持旧系统。

**Comment by yujiahuahua** [comment]
哎，我现在还是用着0.42吧

**Comment by pan93412** [comment]
> 同为Win7，有同样的问题，可能是已不支持旧系统。

不是這個原因吧…… 這一次更新根本沒更新 Electron 版本。Windows 7 的話我晚點開個虛擬機測試。

**Comment by memorydream** [comment]
上游相关issue: https://github.com/electron/electron/issues/32120

**Comment by memorydream** [comment]
适用于win7的修复包：https://1drv.ms/u/s!AiC-9Gl0ltrag9hRe2b6wURLrFttoQ?e=Qd0evT

**Comment by abc4001** [comment]
WIN7  我也是一点播放，就闪退

**Comment by pan93412** [comment]
> WIN7  我也是一点播放，就闪退

試試看修復包

**Comment by abc4001** [comment]
> 

可以了
