### ISSUE TITLE
Arch Linux AUR 打包

### ISSUE THREAD

**Issue by RimuruW** [qier222/YesPlayMusic#118]
简单打包了一下，经测试似乎可以正常使用。

![Screenshot_1](https://user-images.githubusercontent.com/59136309/106186461-477e6880-61df-11eb-82eb-6a1e5306cce9.png)
![Screenshot_2](https://user-images.githubusercontent.com/59136309/106186472-4a795900-61df-11eb-82c3-91c94530f7d2.png)
![Screenshot_3](https://user-images.githubusercontent.com/59136309/106186478-4c431c80-61df-11eb-96ee-e7ca8d1e7e64.png)

AUR 地址：https://aur.archlinux.org/packages/yesplaymusic/

第一次打包，如有问题还请指正。

**Comment by qier222** [comment]
你是用哪种方式打包的？electron builder linux打包可以打包成pacman。

**Comment by qier222** [comment]
https://www.electron.build/configuration/linux

**Comment by RimuruW** [comment]
为了方便直接用 deb 包打包的 :joy: 
刚刚用 electron-builder 试了一下没问题，等我参照 PKGBUILD 改一下，今明两天应该会更新 PKGBUILD

**Comment by RimuruW** [comment]
刚刚看到作者已经打包好了，我重复打包好像没啥意义了... :joy: 
这 issue 就关闭吧
