### ISSUE TITLE
捕获ebadf bad file descriptor异常

### ISSUE THREAD

**Issue by Wzzzx** [qier222/YesPlayMusic#1192]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
   - YesPlayMusic-Setup-0.4.3.exe
- 浏览器名称或电脑操作系统
```
版本	Windows 10 家庭中文版
版本号	21H1
安装日期	‎2021/‎02/‎10
操作系统内部版本	19043.1415
```

- 控制台 Console 页面的截图（按 F12 可打开控制台）
![崩溃堆栈](https://user-images.githubusercontent.com/16540508/148415161-d2e517bf-f182-484e-9ae7-45bb191f8ec9.png)

### 操作步骤
双击播放下一首歌曲的时候触发该异常。此时还正常播放歌曲，点击确定按钮还会继续弹出。所以在任务管理器强行结束任务

**Comment by memorydream** [comment]
#1145 重复
