### ISSUE TITLE
【客户端】【Windows 10】无法播放歌曲，然后弹窗报错

### ISSUE THREAD

**Issue by NCSrapoo** [qier222/YesPlayMusic#1194]
![批注 2022-01-07 105502](https://user-images.githubusercontent.com/81073939/148485776-ab484d5d-fdd1-44d7-8a41-a008fd5c0f37.png)

**Comment by wildabc** [comment]
我也遇到了这个报错，不过软件本身仍在正常运行。

**Comment by pan93412** [comment]
Duplicate of #1145

**Comment by colanik** [comment]
same with me
