### ISSUE TITLE
播放时弹出Error弹窗，但不影响正常播放

### ISSUE THREAD

**Issue by JC6123** [qier222/YesPlayMusic#1196]
Win10系统，使用的是桌面播放器v0.4.3（刚刚从v0.4.2更新至0.4.3）。
在播放过程中时不时会弹出错误提示框，但似乎没有影响到软件的使用。
![错误提示框](https://user-images.githubusercontent.com/43566462/148543222-da056661-5586-4a69-8c2a-e97467106083.png)
![控制台信息1](https://user-images.githubusercontent.com/43566462/148543228-dfae95f8-a18e-4cf2-8404-40c42191d023.png)
![控制台信息2](https://user-images.githubusercontent.com/43566462/148543229-b0c3d8a7-4a80-4c67-9a7b-3b96150a01a6.png)

**Comment by pan93412** [comment]
Duplicate of #1145
