### ISSUE TITLE
刚安装的 音乐库打不开

### ISSUE THREAD

**Issue by 18350505266** [qier222/YesPlayMusic#120]

**Comment by 18350505266** [comment]
win10系统

**Comment by HatsuneMona** [comment]
你好，我也遇到了相同的问题，首页、发现、登录功能均无法使用。此外，**我在路由器上使用了 [UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic) **。我的官方客户端可正常使用， 原生网页端（http://music.163.com）因为证书原因无法访问。不知道我的情况对楼主是否有帮助。以及，开发者是否有适配 UnblockNeteaseMusic 的计划呢？

**Comment by HatsuneMona** [comment]
根据 UnblockNeteaseMusic 的ReadMe，我找到了这样的话：
> 目前除 UWP 外其它客户端均优先请求 HTTPS 接口，默认配置下本代理对网易云所有 HTTPS API 连接返回空数据，促使客户端降级使用 HTTP 接口 (新版 Linux 客户端和 macOS 客户端已无法降级)
希望能对楼主有所帮助。

**Comment by HatsuneMona** [comment]
经过测试，将路由器上的UnblockNeteaseMusic服务禁用以后，YesPlayMusic可以正常使用

**Comment by DMCzero** [comment]
楼主有登陆过吗？

**Comment by zhilings** [comment]
你好，我也出现同样的问题，已经好几天了，该问题一直存在，重装软件后依然存在

**Comment by luckyfatpig** [comment]
最新版也一样，能登陆但音乐库一片空白

**Comment by qier222** [comment]
按Ctrl+Alt+i / ⌘+⌥+i打开控制台，选择Application，清空Local Storage和Cookies下的所有数据。
如果还是不行的话，请选择Console，然后截图发送给我。

**Comment by qier222** [comment]
0.3.3版已修复，如果存在这个问题的话请重新开启issue
