### ISSUE TITLE
上下文菜单被遮挡问题

### ISSUE THREAD

**Issue by ceh-ylhy** [qier222/YesPlayMusic#1204]
修复了，但没完全修复。如图所示
![1](https://user-images.githubusercontent.com/48975898/148629092-61a3b27c-67ec-49a6-8e1f-4c3a509a5f49.png)

**Comment by ceh-ylhy** [comment]
![1](https://user-images.githubusercontent.com/48975898/148629099-92e2fb96-d774-4832-9d3c-dc8913831a0e.png)

**Comment by yujiahuahua** [comment]
确实 得往下滑才行
