### ISSUE TITLE
登陆后UNM播放失败

### ISSUE THREAD

**Issue by handysome6** [qier222/YesPlayMusic#1208]
### 客户端，单文件版，win 10。在墙外。
<hr>

#### 默认UNM开启，直接登录网易云账户，登录成功后，自动daily_signin失败。
Console：
`POST http://localhost:27232/api/daily_signin?type=1&timestamp=1641663356640 400 (Bad Request)     xhr.js:177`
<hr>

#### 点一首歌播放（e.g.给我一首歌的时间），连续弹出message：无法播放xxx。
<img src="https://user-images.githubusercontent.com/47099545/148654181-3bca60b5-32c2-4a1e-bc94-333761375b09.png" alt="drawing" width="200"/>
Console：
<img src="https://user-images.githubusercontent.com/47099545/148654266-e9318f0c-b1d9-4dff-a6aa-12f664082977.png" alt="drawing" width="400"/>
  几秒钟后开始不断弹出Error: 
  <img src="https://user-images.githubusercontent.com/47099545/148654292-a5abd1f7-523d-4f71-ac3b-2cdcd4fcdf6e.png" alt="drawing" width="400"/>

**Comment by memorydream** [comment]
#1145 重复
