### ISSUE TITLE
弹出error错误窗口

### ISSUE THREAD

**Issue by alanyin233** [qier222/YesPlayMusic#1209]
### 

![Capture](https://user-images.githubusercontent.com/77308148/148681644-749810a3-1862-4e5b-8dec-4a5a04f7298b.JPG)

### 反馈 bug 

- 用的是桌面版用
- win10
-弹出后可正常关掉不影响应用使用  但是弹出的频率很高 体验不好

**Comment by memorydream** [comment]
重复 #1145
