### ISSUE TITLE
无法播放下一首，控制台报错

### ISSUE THREAD

**Issue by Gabirel** [qier222/YesPlayMusic#1211]
# 无法下一首，或者无法切回私人FM
**场景：** 长期在私人FM模式下

控制台报错`TypeError: Cannot read property 'id' of undefined`，如下图所示
![image](https://user-images.githubusercontent.com/12933851/148727570-9f57a559-7592-46e7-bb4f-a3018449a60c.png)

PS：另外一个表现是播放完成后无法自动下一首（错误逻辑相同）

### 提新 issue 前请确认 👉

- [x] 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- [x] 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 客户端：`v0.4.3`
- 电脑操作系统：MacOS 10.15.7
- 控制台 Console 页面的截图（按 F12 可打开控制台）：如上图所示

### 其他信息补充
1. 经过小段时间的测试，正常情况下都无法触发这一问题。

但由于，吃饭有锁屏的习惯（时间长了可能会导致设备断网），当吃完饭后再打开，可复现（以前的版本似乎也有该问题，以前没有注意。今天发现这一现象尤其严重）
- [x] ~~下午吃饭再测试一下~~ 上厕所锁屏，回来继续听歌持续了不知道多久，然后突然歌就停了。再次报相同的错

2. 其他报错
![image](https://user-images.githubusercontent.com/12933851/148735581-70ccb4cc-39e6-49c8-a875-0512cc729db6.png)

3. `resetApp()`后无法恢复

**Comment by memorydream** [comment]
这是一个已知很久的问题，但是没有如何修复的头绪

我的解决方法是刷新，然后从首页（不是下面的Player）播放FM（点击播放按钮）
再刷新，重复上述步骤，然后就可以继续切歌了
如果不行，就再来一次

**Comment by memorydream** [comment]
#752

**Comment by memorydream** [comment]
如果你觉得这两个不是同一个问题，请重新打开这个issue

**Comment by pan93412** [comment]
抱歉我看錯 Issue

**Comment by memorydream** [comment]
这个bug应该已经被 #1217 修复了，你可以从 https://github.com/qier222/YesPlayMusic/actions/runs/1683663947 下载修复过后的版本
我需要更多人对这个修复进行测试并进行反馈，因为它可能引入了一些其他的bug（主要在网络条件较差的情况下可能出现）和预期但不符合使用直觉的行为

**Comment by Gabirel** [comment]
@memorydream 测试呢一下午🌚也经历了长时间锁屏断网再恢复，目前是没有遇到什么问题

**Comment by Gabirel** [comment]
@memorydream Update Summary: 问题解决了，但是没有完全解决

1. server 404错误
这个错误之前是没有的，新的报错
![image](https://user-images.githubusercontent.com/12933851/149298286-962a0d05-af3a-42ce-a156-18105d6ee1cf.png)

2. id找不到报错（按了两次，因此有两个相同的报错）
![image](https://user-images.githubusercontent.com/12933851/149298533-5068429a-950e-46da-a320-74e570637106.png)

3. **好消息：** 这次出现问题不再需要刷新，无脑按下一首即可（虽然可能需要按多次，例如上述第二点），但是最起码可以继续播放了。坏消息就是，放歌仍然会出现中途暂停的现象

**Comment by memorydream** [comment]
> @memorydream Update Summary: 问题解决了，但是没有完全解决
> 
> 1. server 404错误
>    这个错误之前是没有的，新的报错
>    ![image](https://user-images.githubusercontent.com/12933851/149298286-962a0d05-af3a-42ce-a156-18105d6ee1cf.png)
> 2. id找不到报错（按了两次，因此有两个相同的报错）
>    ![image](https://user-images.githubusercontent.com/12933851/149298533-5068429a-950e-46da-a320-74e570637106.png)
> 3. **好消息：** 这次出现问题不再需要刷新，无脑按下一首即可（虽然可能需要按多次，例如上述第二点），但是最起码可以继续播放了。坏消息就是，放歌仍然会出现中途暂停的现象

看上去应该是有两次没有取得歌曲信息，这个修改只处理了timeout的情况，没有考虑过没有timeout但是没有实际数据的情况

在没有拿到歌曲信息的情况下，ypm最多只能给出一些提示，提醒用户多次重试

我会添加提示和引导，但是ypm无法保证100%拿到歌曲的信息

**Comment by Gabirel** [comment]
> 在没有拿到歌曲信息的情况下，ypm最多只能给出一些提示，提醒用户多次重试

一定要给用户提示/弹窗吗？能不能静默自动寻找下一首，因为觉得都是私人FM无所谓找不到吧（至少我这么觉得），如果多一个提示，反而会有存在感。

**Comment by memorydream** [comment]
#1231 已经被merge了，可以从 https://github.com/qier222/YesPlayMusic/actions/runs/1708685828 下载
软件不能无限制的重试请求接口，这样很容易出现问题，所以只是加了有限制的重试
所以还是有可能出现找不到下一首的情况，但应该会缓解部分情况，也可能只是增加了等待时间，因为自动重试时，`下一首`按钮处于失效状态
