### ISSUE TITLE
播放时随机弹出弹窗

### ISSUE THREAD

**Issue by xiaozhangup** [qier222/YesPlayMusic#1225]
- 用的是网页版还是客户端 ：客户端 
- 浏览器名称或电脑操作系统 ：Windows 11
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://user-images.githubusercontent.com/68374769/148961970-e02598a5-f41d-48ca-bf16-bfe8fda213e6.png)
![image](https://user-images.githubusercontent.com/68374769/148961989-b7b72340-e131-4c9a-b462-61c70fd17b2d.png)

**Comment by memorydream** [comment]
#1145 重复
