### ISSUE TITLE
播放时提示错误 bad file descriptor

### ISSUE THREAD

**Issue by yidasanqian** [qier222/YesPlayMusic#1228]
### 反馈 bug 需要的信息

- 用的是客户端
 0.4.3
- 电脑操作系统 
win10

![bad file descriptor](https://user-images.githubusercontent.com/10655188/149051605-e8a9116a-9994-4c2f-b604-622d2de3fcd8.png)

**Comment by pan93412** [comment]
Duplicate of #1145...
