### ISSUE TITLE
若干改进建议

### ISSUE THREAD

**Issue by plutonemhikari** [qier222/YesPlayMusic#123]
目前使用的是Linux版

- [x] 1.设置按扭放在更显眼的位置
- [x] ~~2. 在播放的界面增加音质切换的功能~~
- [ ] 3. Linux上提供不使用系统风格的title bar和border的选项，类似于Linux版的vs code和chrome有的那种，否则边框的颜色不会跟着主题变化，导致无论深色主题还是浅色主题边框颜色都一样。
- [ ] 4. 一首歌播放结束正在加载下一首歌的时侯，进度条的位置是尾部，但歌曲信息已经是下一首歌，这样很别扭，希望优化。
- [x] 5. 希望增加最小化到托盘的功能。

**Comment by qier222** [comment]
2不打算做，在设置里设置音质即可

**Comment by stonereese** [comment]
> 2不打算做，在设置里设置音质即可

设置界面从哪儿进入?没找到呀,希望加入最小化到托盘功能.
