### ISSUE TITLE
播放任意歌曲就会停止运行

### ISSUE THREAD

**Issue by xushet** [qier222/YesPlayMusic#1235]
windows版客户端setup包，系统win7 64位
歌曲仍会继续播放，放完后就不会放下一首，
![QQ截图20220114225413](https://user-images.githubusercontent.com/34502902/149541744-fc9ca69e-757f-4546-bcae-b7985e68291d.png)
测试过单文件版也会这样

**Comment by memorydream** [comment]
#1179

**Comment by xushet** [comment]
> #1179

谢谢
