### ISSUE TITLE
云盘无法正常播放（进度条為 0:00）

### ISSUE THREAD

**Issue by neverup7** [qier222/YesPlayMusic#1236]
云盘(**歌曲在网易云上没有**)无法正常播放
例如下面的情况
<img width="960" alt="云盘播放状态" src="https://user-images.githubusercontent.com/89000973/149607365-f523fe9b-075e-437c-bf17-1036cb21d07b.png">

**Comment by neverp** [comment]
望解决,谢谢!

**Comment by chen310** [comment]
> 云盘(**歌曲在网易云上没有**)无法正常播放 例如下面的情况 <img alt="云盘播放状态" width="960" src="https://user-images.githubusercontent.com/89000973/149607365-f523fe9b-075e-437c-bf17-1036cb21d07b.png">

感觉是没法播放过大的文件，我发现云盘中有许多无损的歌曲都不能播放
