### ISSUE TITLE
首页apple music歌单怎们更新

### ISSUE THREAD

**Issue by wonktondI** [qier222/YesPlayMusic#1241]
作者大大，
![image](https://user-images.githubusercontent.com/41692176/149704289-cb32a3a4-9206-424e-91b6-83d729d95219.png)
如图，这些歌单 如何更新
![image](https://user-images.githubusercontent.com/41692176/149704351-d2953edf-566b-4c40-a1bd-95f9663f5d9d.png)

**Comment by qier222** [comment]
更新不了，这个是我手动创建的歌单😂

**Comment by wonktondI** [comment]
> 更新不了，这个是我手动创建的歌单😂

能加一个手动更新按钮或者通过其他方式更新吗，大大？😂

**Comment by qier222** [comment]
这个是我自己的账号创建的歌单，没办法给他人更新
