### ISSUE TITLE
docker 容器有问题

### ISSUE THREAD

**Issue by zjm54321** [qier222/YesPlayMusic#1256]
![image](https://user-images.githubusercontent.com/20168947/150623635-b865299b-2b33-4ba0-bc11-c898ae913a08.png)
![image](https://user-images.githubusercontent.com/20168947/150623645-74bb56fb-2333-4cba-8be0-c4e306619930.png)
#如图，最新版的 docker 出现问题，建议重新上传

**Comment by qier222** [comment]
我还没上传Docker镜像😂

**Comment by zjm54321** [comment]
绷不住了

**Comment by hqzh** [comment]
https://hub.docker.com/r/fogforest/yesplaymusic
