### ISSUE TITLE
Error：ebadf： bad file descriptor

### ISSUE THREAD

**Issue by moji111** [qier222/YesPlayMusic#1262]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息
windows 11 客户端版本 
![image](https://user-images.githubusercontent.com/35190339/150666573-44a68851-55b0-4daa-bbf0-36b195fac9d3.png)

控制台完全正常
基本每切换一首歌都会有这个弹窗，歌还是可以正常播放的

**Comment by moji111** [comment]
哦哦 是最新版 v0.4.3

**Comment by memorydream** [comment]
Duplicate of #1145

**Comment by wineejam** [comment]
![image](https://user-images.githubusercontent.com/8789004/154875572-9d46999b-7c3a-4609-a5cb-0957a5b82718.png)
