### ISSUE TITLE
UnblockNeteaseMusic报错

### ISSUE THREAD

**Issue by domeniczz** [qier222/YesPlayMusic#1263]
打开了UnblockNeteaseMusic的开关

但是使用的时候，点击播放有些音乐（可能是VIP音乐，也可能是网易无版权音乐，不是很清楚）的时候，会跳过并且播放下一首歌，并同时报错
<img width="419" alt="error" src="https://user-images.githubusercontent.com/42294390/150833214-1936d059-1b7d-4b19-99f4-2215e2701f2a.png">

**Comment by pan93412** [comment]
Duplicate of #1145
