### ISSUE TITLE
是否可以考虑增加Win10自带播放控件的支持呢

### ISSUE THREAD

**Issue by bitepen** [qier222/YesPlayMusic#128]
就是按笔记本电脑音量加减键的时候 会弹出来播放控件 UWP版QQ、网易云都支持的那种
感谢作者！

**Comment by FrzMtrsprt** [comment]
呃 现在就是支持的啊
![{B44A4D92-3D8A-4E32-9850-25FABC390F35}](https://user-images.githubusercontent.com/15852717/106244278-a5459b80-6245-11eb-8884-d6dc786056a0.png)

**Comment by bitepen** [comment]
> 呃 现在就是支持的啊
> ![{B44A4D92-3D8A-4E32-9850-25FABC390F35}](https://user-images.githubusercontent.com/15852717/106244278-a5459b80-6245-11eb-8884-d6dc786056a0.png)

我傻了，谢谢大佬！
