### ISSUE TITLE
请求新功能----新增EQ(均衡器)

### ISSUE THREAD

**Issue by minecraftlight** [qier222/YesPlayMusic#1281]
你好，开发者(们)，我想能不能新增个均衡器的功能

因为每人的播放设备不一样，导致有些音乐播放的时候，有些音乐频段是偏多甚至有些模糊

我想在本地客户端新增个均衡器的功能可以让我们调整每个设备的输出频段

/***看到客户端有ffmpeg，索性google下，发现有教程，但我不会添加***/
/***如果可以的话，在这里先感谢开发者了***/

**Comment by minecraftlight** [comment]
这是我在网上看到的帖子

[https://superuser.com/questions/695843/how-to-use-equalizer-on-ffmpeg](url)

**Comment by pan93412** [comment]
我們應該用得是 HTML5 的 `audio` Web API。
