### ISSUE TITLE
aur最新构建版(yesplaymusic-git)底部被KDE Plasma任务栏遮挡

### ISSUE THREAD

**Issue by GrassBlock1** [qier222/YesPlayMusic#1284]
- 用的是网页版还是客户端 客户端
- 浏览器名称或电脑操作系统 Arch Linux (with KDE plasma)
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://user-images.githubusercontent.com/46253950/152119474-985a8999-54b6-4416-a028-3c34df627042.png)

![image](https://user-images.githubusercontent.com/46253950/152119082-aa70d169-796c-42ec-88b7-be215daf0cb0.png)

如上图 播放进度等信息被任务栏遮挡 无法正常显示
（可能是低分屏的原因？）

同屏幕的 Windows 设备则正常：

![remmina_20220202-083958](https://user-images.githubusercontent.com/46253950/152120540-4317f89f-6471-47ca-a164-302e21d0e142.png)

**Comment by memorydream** [comment]
屏幕分辨率太低了，ypm有最小分辨率要求

不过windows下可以刚好装下，那么让kde下的ypm无边框应该也可以装下

最新的pr有针对linux自定义标题栏的支持，但其基于的分支不是最新的主分支，你可以自行拉取，在合并主分支修改后构建

**Comment by pan93412** [comment]
> 屏幕分辨率太低了，ypm有最小分辨率要求
> 
> 不过windows下可以刚好装下，那么让kde下的ypm无边框应该也可以装下
> 
> 最新的pr #1280 有针对linux自定义标题栏的支持，但其基于的分支不是最新的主分支，你可以自行拉取，在合并主分支修改后构建

我認識這朋友；我幫他編譯一下好了。

**Comment by GrassBlock1** [comment]
@memorydream 了解。

**Comment by GrassBlock1** [comment]
> 屏幕分辨率太低了，ypm有最小分辨率要求
> 
> 不过windows下可以刚好装下，那么让kde下的ypm无边框应该也可以装下
> 
> 最新的pr #1280 有针对linux自定义标题栏的支持，但其基于的分支不是最新的主分支，你可以自行拉取，在合并主分支修改后构建

了解。

**Comment by Hibanaw** [comment]
> > 屏幕分辨率太低了，ypm有最小分辨率要求
> > 不过windows下可以刚好装下，那么让kde下的ypm无边框应该也可以装下
> > 最新的pr #1280 有针对linux自定义标题栏的支持，但其基于的分支不是最新的主分支，你可以自行拉取，在合并主分支修改后构建
> 
> 了解。

您好，有编译好的二进制包吗，我不太会操作，，，
您方便的话麻烦发我一份，谢谢

**Comment by pan93412** [comment]
> > > 屏幕分辨率太低了，ypm有最小分辨率要求
> > > 不过windows下可以刚好装下，那么让kde下的ypm无边框应该也可以装下
> > > 最新的pr #1280 有针对linux自定义标题栏的支持，但其基于的分支不是最新的主分支，你可以自行拉取，在合并主分支修改后构建
> > 
> > 
> > 了解。
> 
> 您好，有编译好的二进制包吗，我不太会操作，，， 您方便的话麻烦发我一份，谢谢

好呀，檔案在這：https://1drv.ms/u/s!AiC-9Gl0ltrag9sJPbIboO0jjW5Oew?e=sGX9wI

**Comment by Hibanaw** [comment]
感谢w




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qier222/YesPlayMusic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月3日(星期四) 中午12:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qier222/YesPlayMusic] aur最新构建版(yesplaymusic-git)底部被KDE Plasma任务栏遮挡 (Issue #1284)





    
屏幕分辨率太低了，ypm有最小分辨率要求
 不过windows下可以刚好装下，那么让kde下的ypm无边框应该也可以装下
 最新的pr #1280 有针对linux自定义标题栏的支持，但其基于的分支不是最新的主分支，你可以自行拉取，在合并主分支修改后构建
  
了解。
  
您好，有编译好的二进制包吗，我不太会操作，，， 您方便的话麻烦发我一份，谢谢
  
好呀，檔案在這：https://1drv.ms/u/s!AiC-9Gl0ltrag9sJPbIboO0jjW5Oew?e=sGX9wI
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
