### ISSUE TITLE
建议弄一个全屏模式，类似网易云的全屏纯享，可以隐藏状态栏，沉浸感更好

### ISSUE THREAD

**Issue by morelove112** [qier222/YesPlayMusic#1290]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by Hibanaw** [comment]
f11?

**Comment by morelove112** [comment]
牛批，谢谢





------------------ 原始邮件 ------------------
发件人: 火花✨ ***@***.***&gt;
发送时间: 2022年2月5日 12:04
收件人: qier222/YesPlayMusic ***@***.***&gt;
抄送: morelove112 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [qier222/YesPlayMusic] 建议弄一个全屏模式，类似网易云的全屏纯享，可以隐藏状态栏，沉浸感更好 (Issue #1290)





 
f11?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qier222** [comment]
感觉可以做个按钮

**Comment by morelove112** [comment]
> 感觉可以做个按钮

也不是不行，就放在最小化旁边
