### ISSUE TITLE
A JavaScript error Occurred in the main process

### ISSUE THREAD

**Issue by MPC-SLZQ** [qier222/YesPlayMusic#1291]
![image](https://user-images.githubusercontent.com/63146698/152642184-9d484853-c763-44e0-a746-1c3e45a6f5b8.png)
打开应用后几秒会弹出这个窗口。
软件能够正常使用。

**Comment by docry4** [comment]
我遇到了好几次

**Comment by memorydream** [comment]
Duplicate of #1145
