### ISSUE TITLE
beta版歌词换行问题

### ISSUE THREAD

**Issue by DrZhang1208** [qier222/YesPlayMusic#1293]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

### 歌词太长的时候，歌词会动态的换行
- beta版当前歌词放大的时候会根据显示范围动态换行
- 建议在载入歌词的时候就把所有歌词按照放大后的效果换好行，这样就不会出现这种情况了。

https://user-images.githubusercontent.com/97793620/152668759-fc808652-709f-4fba-886f-34092b401445.mp4

https://user-images.githubusercontent.com/97793620/152668760-0b0d205e-05b4-453f-a7e4-cb7e450a30d1.mp4

**Comment by pan93412** [comment]
已解決
