### ISSUE TITLE
提議做個可以從頂欄圖標點開的mini窗口

### ISSUE THREAD

**Issue by ooooox** [qier222/YesPlayMusic#1294]
打開後就吸附在頂欄,窗口背景是張專輯圖片,按鈕盡可能少,然後在加上咔嗒一聲那種音效,就是像個小ipod播放器一樣,可可愛愛的
然後希望支持qq音樂吧,本來也是先開的網易會員,但它版權真的不夠用

**Comment by pan93412** [comment]
目前已經支援 QQ 音樂了，但需要一些特殊設定才能使用。你可以參考 UnblockNeteaseMusic 音源的設定連結來調整環境變數。
