### ISSUE TITLE
能不能把看评论、写评论和赞评论的功能加上，我想这不会影响软件的简洁度

### ISSUE THREAD

**Issue by TotoWang-hhh** [qier222/YesPlayMusic#1304]

**Comment by qier222** [comment]
不打算加这些功能

**Comment by YuriSizuku** [comment]
> 

还是加上看评论比较好，这是网易云的卖点，要是春听音乐还不如自己下载hifes听。

**Comment by akFace** [comment]
同，希望加上评论列表功能，即使不能评论

**Comment by TotoWang-hhh** [comment]
> 同，希望加上评论列表功能，即使不能评论

这都几年了还有人啊？？我自己现在都没怎么用这个软件了😂

**Comment by akFace** [comment]
> > 同，希望加上评论列表功能，即使不能评论
> 
> 这都几年了还有人啊？？我自己现在都没怎么用这个软件了😂

我觉得挺好用的，你有更好的推荐吗

**Comment by TotoWang-hhh** [comment]
> > > 同，希望加上评论列表功能，即使不能评论
> > 
> > 这都几年了还有人啊？？我自己现在都没怎么用这个软件了😂
> 
> 我觉得挺好用的，你有更好的推荐吗

如果是Windows用户可以试试LyricEase，其他系统就用这个YesPlay挺好的。我自己目前主要用Apple Music，我电脑上用Cider，因为跨平台而且可以Shuffle
