### ISSUE TITLE
PC客户端频繁弹出错误窗口

### ISSUE THREAD

**Issue by Prepanpan** [qier222/YesPlayMusic#1307]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

客户端频繁弹出错误窗口
客户端版本0.4.3 
系统Windows 10 1090 专业工作站版
![image](https://user-images.githubusercontent.com/85682561/153694533-cc7965cb-0b1a-49d2-8867-ee31645f8f75.png)
![image](https://user-images.githubusercontent.com/85682561/153694545-2f303010-ae65-47ef-a3a4-321722f5aa5a.png)

**Comment by smoonlight** [comment]
是的  我也遇到了这个问题  会一直谈 我还意味是0.42没有删完的原因 彻底删除之后还是这样

**Comment by mashutong** [comment]
我的也出现了

**Comment by memorydream** [comment]
Duplicate of #1145
