### ISSUE TITLE
一个小建议 -希望歌词页的字体号能小一些 或者可以添加用户自定义的字号的选项

### ISSUE THREAD

**Issue by jiuchengYuu** [qier222/YesPlayMusic#131]
![image](https://user-images.githubusercontent.com/74756286/106264622-db444900-6260-11eb-95da-be41a6327537.png)
如题 这样来看还是太大 有点不协调

**Comment by jiuchengYuu** [comment]
或者上下也像左边一样留白 这样就左右协调了 字体也可以换一个好看的

**Comment by jiuchengYuu** [comment]
还有 希望点X的时候能够给选项 而不是这样直接关软件  而且软件重新打开后 窗口大小会回到默认 而不是调过之后的

**Comment by jiuchengYuu** [comment]
一些吹毛求疵的小建议  还是感谢作者带来的这个软件

**Comment by qier222** [comment]
调节歌词页的字体号大小功能已加入todo

**Comment by qier222** [comment]
v0.3.5 版本支持调整歌词字体大小了
