### ISSUE TITLE
在最新KDE5.24.1下不能打开系统托盘右键菜单

### ISSUE THREAD

**Issue by FrankYang6921** [qier222/YesPlayMusic#1312]
AUR上的客户端，`yesplaymusic-git`，Console中没有任何错误，但自从更新KDE 5.24.x以后，如图所示的托盘菜单无论右键还是左键均无反应，在KDE 5.23.x下无此问题。其他基于Electron的应用貌似均可正常工作，因此来这里提Issue（不确定是否是KDE本身的问题）

![Screenshot_20220216_082040](https://user-images.githubusercontent.com/47714406/154172349-a084e9dc-31fb-4386-8ee4-62a5c318e780.png)
![Screenshot_20220216_082246](https://user-images.githubusercontent.com/47714406/154172550-f4fbbb67-bb87-4098-951c-2cc5d531e92f.png)
![Screenshot_20220216_082418](https://user-images.githubusercontent.com/47714406/154172701-83e11719-ad2f-4d65-8ac6-b7e8d5328fef.png)

**Comment by memorydream** [comment]
无法复现，我的环境为arch linux，5.16.9-arch1-1 kernel，plasma 5.24.1，但是我使用wayland后端，打包的AppImage格式，使用Xwayland运行

**Comment by memorydream** [comment]
因为长时间没有收到后续跟进的信息，我会关掉这个issue，如果后续有更多信息，可以随时打开
