### ISSUE TITLE
播放非网易云音源歌曲会报错，然后跳过歌曲

### ISSUE THREAD

**Issue by Syozhi-1** [qier222/YesPlayMusic#1313]
![image](https://user-images.githubusercontent.com/58074198/154218664-5eeebc10-a951-41cb-a660-480faeba68bd.png)
如图，这里时播放周董的歌；播放其他网易云没版权的歌曲都会这样，部分能播放，不过音乐质量奇差

操作系统：windows 11 专业版 21H2
客户端版本：v0.4.4 bate.1

**Comment by memorydream** [comment]
Duplicate of #1145 

音质问题可参考[音源清单](https://github.com/UnblockNeteaseMusic/server#%E9%9F%B3%E6%BA%90%E6%B8%85%E5%8D%95)，在ypm的设置页面中可以指定unm使用的源，有些音源（比如咪咕）在填入cookie后可以获取到高音质版本，不然只能获取到低音质版
