### ISSUE TITLE
0.4.3版本音乐库进入后白屏！（已解决）

### ISSUE THREAD

**Issue by hsiayuchih** [qier222/YesPlayMusic#1322]
最近一段时间发现音乐库打不开，点进去后会白屏，什么内容都没有，但是发现和首页是正常的！

**Comment by memorydream** [comment]
F12里有什么报错？

**Comment by pan93412** [comment]
跟 #1326 可能有關。

**Comment by hsiayuchih** [comment]
> F12里有什么报错？`resetApp()`有效吗？

> 跟 #1326 可能有關。

问题已解决，我尝试退出并重新登录后就可以了！
