### ISSUE TITLE
Windows 聚焦在关闭按钮时“x“按钮应为白色

### ISSUE THREAD

**Issue by Hibanaw** [qier222/YesPlayMusic#1333]
![图片](https://user-images.githubusercontent.com/61813396/155102251-0b1541c6-e78c-4d1e-a805-d05f5c630fc7.png)
![图片](https://user-images.githubusercontent.com/61813396/155102281-a0a721be-dd71-4fa2-b8e2-b941ec5d1504.png)
p1为资源管理器，p2为ypm

**Comment by pan93412** [comment]
> ![图片](https://user-images.githubusercontent.com/61813396/155102251-0b1541c6-e78c-4d1e-a805-d05f5c630fc7.png)
> ![图片](https://user-images.githubusercontent.com/61813396/155102281-a0a721be-dd71-4fa2-b8e2-b941ec5d1504.png)
> p1为资源管理器，p2为ypm

<img width="143" alt="截圖 2022-02-24 下午4 03 44" src="https://user-images.githubusercontent.com/28441561/155483148-f1cb8182-e005-4559-8581-aba49b4c37e4.png">

這樣嗎？
