### ISSUE TITLE
请求增加歌单内搜索歌曲功能

### ISSUE THREAD

**Issue by WeNeedChinese** [qier222/YesPlayMusic#1334]
类型：新功能
描述：请求增加歌单内搜索歌曲功能
![image](https://user-images.githubusercontent.com/72389265/155134865-6394810a-a3e2-426f-8a46-5e076e26243b.png)

**Comment by memorydream** [comment]
![image](https://user-images.githubusercontent.com/34763046/155138467-ada08ffa-697c-4c1a-b83c-bbf5fc316484.png)
