### ISSUE TITLE
建议在任务栏预览中添加控制按钮

### ISSUE THREAD

**Issue by NZJ-Jimmy** [qier222/YesPlayMusic#134]
在Windows里，建议在任务栏的预览视图中加入4个控制按钮（包括“收藏”按钮），方便无Fn键的用户控制。像这样：
![image](https://user-images.githubusercontent.com/60278084/106273965-755ebe00-626e-11eb-9d38-94bed18525df.png)
另外，建议最小化时可提供仅最小化到任务栏的选项。

**Comment by qier222** [comment]
已经有人发过这个功能的issue了 #129
最小化时可提供仅最小化到任务栏的选项现在已经有了，可以在设置里启用。
