### ISSUE TITLE
当专辑封面不是正方形时的一些问题

### ISSUE THREAD

**Issue by MSGOOHPA** [qier222/YesPlayMusic#135]
当专辑封面不是正方形时（例如：music.163.com/song?id=434902435），在专辑预览界面里，专辑封面上的本来应该是圆形播放按钮被压成了椭圆形，不过播放按钮中的三角形没有被压；而且当鼠标移动到图中红线范围内时就会显示播放按钮，如图所示，预期应该是鼠标指针移动到专辑封面上时才显示播放按钮。
![屏幕截图 2021-01-29 194821](https://user-images.githubusercontent.com/40914017/106272509-231c9d80-626c-11eb-9084-2c46864c6084.png)
![屏幕截图 2021-01-29 194828](https://user-images.githubusercontent.com/40914017/106272543-2adc4200-626c-11eb-91e9-65af1357a992.png)

**Comment by qier222** [comment]
已修复，我裁剪成正方形了。

**Comment by MSGOOHPA** [comment]
> 已修复，我裁剪成正方形了。

这。。。我其实是希望在保留原图不裁剪的情况下修复的，至于下面空出来的地方就空着吧

**Comment by qier222** [comment]
> > 已修复，我裁剪成正方形了。
> 
> 这。。。我其实是希望在保留原图不裁剪的情况下修复的，因为有一些专辑的封面，比如我上传的截图下面几张专辑的封面两侧还是有一些有效信息的，至于下面空出来的地方就空着吧

只能拉伸或者裁切。发现专辑列表也有这个问题，暂时不知道怎么修复。

**Comment by qier222** [comment]
确定已经修复了
