### ISSUE TITLE
能否增加移除顶栏菜单的选项？

### ISSUE THREAD

**Issue by forliuyifei** [qier222/YesPlayMusic#136]
![image](https://user-images.githubusercontent.com/53306807/106275326-96c0a980-6270-11eb-9264-722b6532991f.png)
去掉黑条可以更漂亮一点，就像Deepin内置的那几个应用一样。

**Comment by qier222** [comment]
移除了的话就没办法关闭/最小化/最大化应用了，而且每个系统的标题栏样式都不一样，没办法全部适配。
之后会考虑出一个通用的标题栏。

**Comment by Mrneet** [comment]
> 移除了的话就没办法关闭/最小化/最大化应用了，而且每个系统的标题栏样式都不一样，没办法全部适配。
> 之后会考虑出一个通用的标题栏。

希望都做成Mac那种，和下面的样式统一起来，win上面默认的真的不好看
![image](https://user-images.githubusercontent.com/30075289/106360143-c8f60800-6351-11eb-8a20-316b5a4ee283.png)

**Comment by coolcat870** [comment]
> > 移除了的话就没办法关闭/最小化/最大化应用了，而且每个系统的标题栏样式都不一样，没办法全部适配。
> > 之后会考虑出一个通用的标题栏。
> 
> 希望都做成Mac那种，和下面的样式统一起来，win上面默认的真的不好看
> ![image](https://user-images.githubusercontent.com/30075289/106360143-c8f60800-6351-11eb-8a20-316b5a4ee283.png)

我也是Windows系统，的确这个顶栏不太美观。可以考虑更换一下Windows主题
![20210221_082313](https://user-images.githubusercontent.com/73749474/108624886-a5226f80-7482-11eb-83e9-4f7bf3b3b498.png)

我用的是仿Mac主题，就和上图一样了…

指路：https://zhutix.com/pc/macos-big-sur-vs/

**Comment by forliuyifei** [comment]
> 移除了的话就没办法关闭/最小化/最大化应用了，而且每个系统的标题栏样式都不一样，没办法全部适配。
> 之后会考虑出一个通用的标题栏。

快捷键可以解决那些操作吧

**Comment by coolcat870** [comment]
> > 移除了的话就没办法关闭/最小化/最大化应用了，而且每个系统的标题栏样式都不一样，没办法全部适配。
> > 之后会考虑出一个通用的标题栏。
> 
> 快捷键可以解决那些操作吧

虽然我也一般用快捷键解决...不过主要还是得照顾大部分用户😂新来的用户找不到关闭和最小化的按钮会发疯的

**Comment by forliuyifei** [comment]
> > > 移除了的话就没办法关闭/最小化/最大化应用了，而且每个系统的标题栏样式都不一样，没办法全部适配。
> > > 之后会考虑出一个通用的标题栏。
> > 
> > 
> > 快捷键可以解决那些操作吧
> 
> 虽然我也一般用快捷键解决...不过主要还是得照顾大部分用户😂新来的用户找不到关闭和最小化的按钮会发疯的

默认不隐藏顶栏，如需隐藏可手动用快捷键隐藏，加个提示就好了
