### ISSUE TITLE
【报错】播放歌曲就会出现 ，歌曲开始。每首歌都是。但不会退出

### ISSUE THREAD

**Issue by Steven-XGK** [qier222/YesPlayMusic#1361]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息![00001](https://user-images.githubusercontent.com/100554296/155931863-754ad4eb-8058-48da-8587-52023a4afeab.png)

**Comment by pan93412** [comment]
Duplicate of #1145
