### ISSUE TITLE
有些音乐不知为什么放不了还弹出错误

### ISSUE THREAD

**Issue by dzoo15** [qier222/YesPlayMusic#1363]
一个 bug

 bug 需要的信息

1.有些音乐不知为什么放不了还弹出错误（如图《坏女孩》放不了）
- 客户端
- edge或电脑操作系统win10
![屏幕截图 2022-03-01 213910](https://user-images.githubusercontent.com/59956201/156179274-778e5da1-ee92-4908-9cf3-f69aa1669f6e.png)

**Comment by pan93412** [comment]
Duplicate of #1145
