### ISSUE TITLE
播放音乐的时候会弹出警告窗口

### ISSUE THREAD

**Issue by kuu-an** [qier222/YesPlayMusic#1364]
是不是我系统装的java出问题了？
![image](https://user-images.githubusercontent.com/62643663/156273097-4ff6676c-bbde-4bd0-8cbf-522f3a0f6574.png)

用的是目前最新的客户端
版本	Windows 10 专业版
版本号	21H1
安装日期	‎2021/‎9/‎8
操作系统内部版本	19043.1526
体验	Windows Feature Experience Pack 120.2212.4170.0
![image](https://user-images.githubusercontent.com/62643663/156273252-67ddcc16-e67a-41b4-9f0f-cd086eec4a06.png)

**Comment by pan93412** [comment]
Duplicate of #1145
