### ISSUE TITLE
希望在歌词界面右上角增加一个最小化/最大化/关闭的按钮。

### ISSUE THREAD

**Issue by Ruikoto** [qier222/YesPlayMusic#1365]
希望在歌词界面右上角增加一个最小化/最大化/关闭的按钮，不然需要先退出这个界面才能最小化/最大化/关闭。

**Comment by pan93412** [comment]
Duplicate of #370

**Comment by AlbertWang2018** [comment]
单击歌词界面的 歌曲名称，会退出歌词界面，我确实也摸索了几分钟，有提示更好。
