### ISSUE TITLE
【疑问】关于使用三方播放后官方统计数据

### ISSUE THREAD

**Issue by Nothunpple** [qier222/YesPlayMusic#1367]
如果使用像此类第三方播放器，个人网易云账户内的“歌曲播放量”和“歌曲播放总数”会增加吗

**Comment by laozhuv** [comment]
看上去好像会 但是不会增加歌单播放量

**Comment by laozhuv** [comment]
> 看上去好像会 但是不会增加歌单播放量

**Comment by Nothunpple** [comment]
> > 看上去好像会 但是不会增加歌单播放量

歌单播放啥的无所谓（）主要是想升级hhhh
