### ISSUE TITLE
bug: 新版本部分按钮无法使用

### ISSUE THREAD

**Issue by memorydream** [qier222/YesPlayMusic#1377]
windows10 最新commit
客户端（node js v16与v14构建，action构建，共计3个版本）

console：
![image](https://user-images.githubusercontent.com/34763046/156823905-99afe6c3-6889-49d5-b18e-0b978fa4b654.png)

# 
在点击Player组件中的 `播放` 与 `上一曲` 按钮时会出现此问题，快捷键不会
对应的代码为
https://github.com/qier222/YesPlayMusic/blob/596204dc5896e0de28a31eefd28c979370e05d5e/src/components/Player.vue#L86
https://github.com/qier222/YesPlayMusic/blob/596204dc5896e0de28a31eefd28c979370e05d5e/src/components/Player.vue#L74

> 其他使用类似方法调用的按钮也会有问题，在Player组件和歌词页中所有类似的调用都发现了这个问题

# 
`下一曲` 按钮不受影响，因为这个按钮的实际调用在 `methods:` 中
https://github.com/qier222/YesPlayMusic/blob/596204dc5896e0de28a31eefd28c979370e05d5e/src/components/Player.vue#L90
https://github.com/qier222/YesPlayMusic/blob/596204dc5896e0de28a31eefd28c979370e05d5e/src/components/Player.vue#L217-L223

# 
当我将 `播放` 放入 `methods:` 后，播放按钮无法使用的问题消失
![image](https://user-images.githubusercontent.com/34763046/156824731-a1e3e7ab-6e9c-4e6d-8ecd-286d415d2a9d.png)
![image](https://user-images.githubusercontent.com/34763046/156824769-a95f7ee5-6e69-466d-90de-1bb449f9e99f.png)

# 
我可以通过上面提到的方法，用一个简单的pr来修复这个问题，但是在修复之前，想知道这个问题是否存在其他的修复方法

# 
### 补充说明
在断点后获得的结果对比：

报错时：
![image](https://user-images.githubusercontent.com/34763046/156826636-37763480-d96c-4c9b-bcc9-b7401d64bd90.png)

可用时：
![image](https://user-images.githubusercontent.com/34763046/156826779-97c8efb9-7517-4679-902f-d90baf754c25.png)

**Comment by pan93412** [comment]
大概是因為新版的 `click.native` 不會把 this 綁定到呼叫函式上了。確實是建議把呼叫移到 methods 裏頭。
