### ISSUE TITLE
YesPlayMusic-0.3.2  这个版本的问题

### ISSUE THREAD

**Issue by huanx9** [qier222/YesPlayMusic#138]
无法登录 网页版搜索登录也不能用

邮箱登录也不行 

于是导致也无法设置了。 

另外 `YesPlayMusic-0.3.2.exe`  这个属于便携版吗？

update 
因为隐私问题，隐去了我的ID。 

我已经自己排查出这个问题了。 当 我喜欢的音乐 = 0 时 ,账号无法登录。

**Comment by qier222** [comment]
试试打开控制台，清空LocalStroage和Cookies试试

**Comment by luckyfatpig** [comment]
> 试试打开控制台，清空LocalStroage和Cookies试试

你说的打开控制台快捷键在windows 10 上按了也没有反应，无法打开控制台

**Comment by qier222** [comment]
> > 试试打开控制台，清空LocalStroage和Cookies试试
> 
> 
> 
> 你说的打开控制台快捷键在windows 10 上按了也没有反应，无法打开控制台

Ctrl+Shift+i 试试

**Comment by huanx9** [comment]
我的意思是，我清理缓存和cookie都没有用，我的号好像是个黑号？ 不知道为什么？
