### ISSUE TITLE
Windows11 22567  客户端  报错

### ISSUE THREAD

**Issue by lanzeweie** [qier222/YesPlayMusic#1382]
### 反馈 bug 需要的信息
Windows11 22567 报错 然后黑屏

![屏幕截图 2022-03-06 173547](https://user-images.githubusercontent.com/53991448/156917506-d951049a-789a-4d45-b1ab-ea1530ab4389.png)
![image](https://user-images.githubusercontent.com/53991448/156917542-ab0d034d-7591-4fb2-adc8-f8b73e27106b.png)

**Comment by lanzeweie** [comment]
关掉报错信息后 黑屏消失

**Comment by inoton** [comment]
同样复现，不过已经有人反馈了。
我使用降级到 0.42 解决，目前的测试版 0.4.4 也有该问题。

**Comment by pan93412** [comment]
Duplicate of #1145
