### ISSUE TITLE
希望增加安装目录选择和缓存目录选择

### ISSUE THREAD

**Issue by ZiHaoIt** [qier222/YesPlayMusic#1384]
希望客户端增加安装目录选择和缓存目录选择，强迫症表示受不了。

**Comment by memorydream** [comment]
当前ypm在windows下有带setup的安装版本与不带setup的单文件版，单文件版本质上是一个压缩包，可以用压缩软件打开，并把里面ypm的实际文件解压到任意路径下使用

缓存目录 #558 重复
