### ISSUE TITLE
javascript error occuured in the main process

### ISSUE THREAD

**Issue by Yumega** [qier222/YesPlayMusic#1387]
### 反馈 bug 需要的信息

- 用的是客户端
- 浏览器:edge 
- 电脑操作系统: windows11

![屏幕截图 2022-03-07 135441](https://user-images.githubusercontent.com/61570667/156976733-269b47a3-29d7-42c6-b535-2ffc33ab6857.png)

**Comment by pan93412** [comment]
Duplicate of #1145
