### ISSUE TITLE
UnblockNeteaseMusic Settings?

### ISSUE THREAD

**Issue by zzinggame** [qier222/YesPlayMusic#139]
Is there anywhere i can put my server ip and port to use my self-hosted unblockneteasemusic ?

**Comment by qier222** [comment]
是自带的UnblockMusic用不了吗？

**Comment by zzinggame** [comment]
Yes, VIP Music isn't playable for me, i'm from overseas

**Comment by qier222** [comment]
我刚刚测试了下，在开启全局代理的情况下，测试了发现可以正常解锁VIP歌曲。
你关掉UnblockMusic服务再试试看？

**Comment by HatsuneMona** [comment]
> Yes, VIP Music isn't playable for me, i'm from overseas

https://github.com/qier222/YesPlayMusic/issues/115#issuecomment-770158353
