### ISSUE TITLE
beta无法使用邮箱账号登录

### ISSUE THREAD

**Issue by YI--** [qier222/YesPlayMusic#1402]
# 客户端无法使用邮箱登录，已在music.163.com验证 登录成功

 - 没在在0.4.3验证过

### 反馈 bug 需要的信息

- 客户端
- mac Intel ，OS版本 12.1
- 客户端版本：版本0.4.4 (0.4.4) beta：https://github.com/qier222/YesPlayMusic/releases/download/v0.4.4-beta.1/YesPlayMusic-mac-0.4.4.dmg
- 控制台 Console 页面的截图
<img width="1126" alt="iShot2022-03-10 15 32 28" src="https://user-images.githubusercontent.com/10511182/157611128-bfcaf8d4-3b18-4b47-80c7-8b8f10f13b5c.png">

**Comment by YI--** [comment]
已在0.4.3验证过，同样的问题。

**Comment by memorydream** [comment]
无法复现，我是QQ邮箱

**Comment by YI--** [comment]
Windows Bug - 
0.4.4 beta 
问题1.
 - 邮箱Input和密码Input在随便输入内容之后，点击登录后，登录失败或者成功，输入框锁定无法操作（有时在退出登录重新登录时也无法再次编辑），在一段时间内是无法编辑操作的。
问题2.
 - 与Mac中的问题唯一不一致的是，第一次登录提示失败（有网络，防火墙已公共网络授权），第二次、第三次等等又可以登录与退出登录了（中途没有退出或者改变过应用）
 - 退出登录之后关闭App，重新打开就开始与mac的问题一致了，始终无法登录，`{"message":"当前登录失败，请稍后再试","code":250} `

**Comment by memorydream** [comment]
> Windows Bug - 0.4.4 beta 问题1.
> 
> * 邮箱Input和密码Input在随便输入内容之后，点击登录后，登录失败或者成功，输入框锁定无法操作（有时在退出登录重新登录时也无法再次编辑），在一段时间内是无法编辑操作的。

这个问题存在了很久，只需要切到其他应用再切回来就可以


> 问题2.
> 
> * 与Mac中的问题唯一不一致的是，第一次登录提示失败（有网络，防火墙已公共网络授权），第二次、第三次等等又可以登录与退出登录了（中途没有退出或者改变过应用）
> * 退出登录之后关闭App，重新打开就开始与mac的问题一致了，始终无法登录，`{"message":"当前登录失败，请稍后再试","code":250} `

需要调查

**Comment by memorydream** [comment]
> 看是否我这边需要提供什么其他日志，或者系统版本信息、录屏等等

你有使用其他邮箱的网易云账号吗？我没有163邮箱，希望先确认这个问题是否和特定邮箱相关

**Comment by YI--** [comment]
> > 看是否我这边需要提供什么其他日志，或者系统版本信息、录屏等等
> 
> 你有使用其他邮箱的网易云账号吗？我没有163邮箱，希望先确认这个问题是否和特定邮箱相关

我刚刚新注册了网易yeah.net，第一次在网易云客户端登录需要绑定手机号，然后我绑定之后，这个新账号一直可以登录、没有失败过，我怀疑是我的老帐号没有绑定手机号的原因（我用手机号绑定了网易邮箱、网易游戏都是用这个手机号和邮箱登录的，只不过网易云音乐一直没有绑定过手机号，也没有提示说要绑定手机号），但话又说回来，新账号没有在登录网易云是绑定手机是无法登录的，老帐号没有这个限制（这可是我的几年前升到10级的号）

- 在mac用绑定了手机号的新账号登录没有相关登录失败的问题了

- 我现在在想办法取消绑定手机号，好像没有这个功能😭😭😭，实在不行就注销新账号了


问题1 依旧存在

**Comment by memorydream** [comment]
> 问题1 依旧存在

问题1 一直存在，在windows/linux下可以通过将ypm置于后台(alt + tab切到其他程序)，再重新放回前台的方式让输入框重新聚焦，我没有mac，但是mac下应该也可以通过这种方式解决无法聚焦的问题

**Comment by YI--** [comment]
😂，出现了新的问题，使用一会弹Error窗口 
![image](https://user-images.githubusercontent.com/10511182/157914254-7c8f6a03-49bb-4704-ba14-209b4508468b.png)
这是弹出内容，之后没法登录时使用倒是没有弹这个

**Comment by memorydream** [comment]
我将关闭这个issue，如果后续有其他相关问题，可以继续在这个issue下提问

**Comment by memorydream** [comment]
> 😂，出现了新的问题，使用一会弹Error窗口 ![image](https://user-images.githubusercontent.com/10511182/157914254-7c8f6a03-49bb-4704-ba14-209b4508468b.png) 这是弹出内容，之后没法登录时使用倒是没有弹这个

#1145
