### ISSUE TITLE
javascript error in main process

### ISSUE THREAD

**Issue by volksvagen** [qier222/YesPlayMusic#1403]
### 问题

如题。非付费用户在播放付费乐曲时，此问题必现。

### 平台

- Windows客户端，版本号0.4.3
- Windows **11** Release Channel

Edition	Windows 11 Pro
Version	21H2
OS build	22000.556
Experience	Windows Feature Experience Pack 1000.22000.556.0

![image](https://user-images.githubusercontent.com/30553808/157794186-cb359443-d745-4161-8a9e-a0f4608bf5e1.png)

**Comment by pan93412** [comment]
Duplicate of #1145
