### ISSUE TITLE
预加载下一首歌

### ISSUE THREAD

**Issue by PoorSstudent** [qier222/YesPlayMusic#1409]
和Apple Music一样，在上一首歌播放要结束之前就加载下一首歌，听整轨专辑的时候就可以俩首之间无缝连接

**Comment by memorydream** [comment]
ypm有提前缓存下一首歌，但是切换到下一首歌要时间

**Comment by PoorSstudent** [comment]
那还是保留俩首歌中间的间隔时间吗？

**Comment by memorydream** [comment]
> 那还是保留俩首歌中间的间隔时间吗？

我认为你想说：两首歌无法无缝切换是当前无法实现的吗？
如果是这样，我认为当前应该没有找到什么可以实现的方法

**Comment by PoorSstudent** [comment]
> > 那还是保留俩首歌中间的间隔时间吗？
> 
> 我认为你想说：两首歌无法无缝切换是当前无法实现的吗？
> 如果是这样，我认为当前应该没有找到什么可以实现的方法

好的👌老哥。
