### ISSUE TITLE
总是听到一半报错，必须点一下窗口的【确定】按钮才会继续播放

### ISSUE THREAD

**Issue by Ice-Hazymoon** [qier222/YesPlayMusic#1410]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
Windows 客户端 YesPlayMusic-0.4.3
- 浏览器名称或电脑操作系统
系统：Windows 11
位置：西班牙
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://user-images.githubusercontent.com/25239977/158430826-40c55fe2-69c2-41f8-9bee-246bd86e883f.png)

**Comment by memorydream** [comment]
Duplicate of #1145
