### ISSUE TITLE
运行应用莫名其妙三连报错BUG

### ISSUE THREAD

**Issue by Q-Tai-mu** [qier222/YesPlayMusic#1417]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端  ：电脑

- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）
- ![1647487977(1)](https://user-images.githubusercontent.com/58099119/158731761-184e1b73-4f6b-472a-8eb7-fdc3f68fa1e6.png)
![1647487986(1)](https://user-images.githubusercontent.com/58099119/158731765-7119a532-2823-4c8c-b5ad-9f01e9859531.png)
![1647488079(1)](https://user-images.githubusercontent.com/58099119/158731771-21f0658c-a0e6-4e7c-a5aa-d6a2326d7655.png)

**Comment by Q-Tai-mu** [comment]
这个，我看到了，我这里就关闭了

**Comment by pan93412** [comment]
Duplicate of #1145
