### ISSUE TITLE
建议增加 UnblockNeteaseMusic 的开关并可以更改音源

### ISSUE THREAD

**Issue by ptdisco** [qier222/YesPlayMusic#142]
建议增加 UnblockNeteaseMusic 的开关并可以更改音源

**Comment by qier222** [comment]
已加入todo

**Comment by qier222** [comment]
已支持开关。等发布新版本客户端吧 https://github.com/qier222/YesPlayMusic/commit/7d580e71135825e2da120ec2a9c450f464c61419
