### ISSUE TITLE
Web版，建议增加“在网易云音乐网页版打开”的按钮

### ISSUE THREAD

**Issue by lwd-temp** [qier222/YesPlayMusic#1426]

**Comment by DrZhang1208** [comment]
![图片](https://user-images.githubusercontent.com/97793620/159205177-0dcb96f1-3d5b-4dfe-8a82-793cbfcd47d9.png)

**Comment by DrZhang1208** [comment]
可以试试这个应用版

**Comment by DrZhang1208** [comment]
我看了一下，网页版也有，都在专辑页

**Comment by lwd-temp** [comment]
> 我看了一下，网页版也有，都在专辑页

感谢
