### ISSUE TITLE
歌曲未知专辑时点击歌曲封面卡加载

### ISSUE THREAD

**Issue by maxelblack** [qier222/YesPlayMusic#1432]
用的客户端目前的最新稳定版 (0.4.3)

Windows 11 Professional (10.0.22000.556)

控制台除了大片 404 错误无其他输出，全部发上来太多了，这是第一个 404 的那段报错：

```
Failed to load resource: the server responded with a status of 404 (Not Found)
createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at t.exports (createError.js:16)
    at t.exports (settle.js:17)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:62)
```

看起来这个Bug是因为没考虑没有专辑的情况导致加载时候 404 了

另：这首未知专辑的歌是鹿乃的《この世界を愛したい》

**Comment by maxelblack** [comment]
尝试一下我上面提到的那首歌曲？

**Comment by memorydream** [comment]
就是用的那首，播放时没有观察到你说的报错，win10 客户端

**Comment by maxelblack** [comment]
不是播放，是在歌曲列表中点击这首歌的封面，正常情况是会进专辑页的，这首歌因为没有专辑卡住了，上面的进度条走到99%不动了。

其实我是想建议遇到没有专辑的情况至少弹个提示，没有提示的情况下我当时是一脸懵，打开控制台才知道加载出错了。
