### ISSUE TITLE
关于双显示器下的适配问题❤️

### ISSUE THREAD

**Issue by GKVStory** [qier222/YesPlayMusic#1436]
Windows系统下客户端内，采用**主辅屏**的连接方式，将界面移至副屏后断开副屏连接，界面会**停留在主屏外**导致无法使用

**Comment by memorydream** [comment]
[此pr对于窗口位置的修复较为粗糙，没有在运行时检查屏幕事件，仅在启动时检查窗口位置](https://github.com/qier222/YesPlayMusic/pull/1474#issuecomment-1087619789)

我当前没有多屏可供测试运行时的屏幕变动，对于运行时屏幕变动的支持需要等待其他人后续贡献，或我有多屏进行测试时
