### ISSUE TITLE
是否有向Mpris提供歌词API的想法

### ISSUE THREAD

**Issue by KairuiLiu** [qier222/YesPlayMusic#1439]
我想要实现一个在polybar显示歌词的功能, 看到yesplaymusic已经支持Mpris, 并且可以通过Mpris查询到歌曲名与作者, 想请问是否可以

- 修正Mpris的`meta.playerName`为`yesplamusic`
- 通过Mpris的`meta.album`提供当前歌词呢? 虽然这不符合语意, 但是似乎`album`没有什么用？

或者是否有其他方式获取当前歌词呢？

**Comment by pan93412** [comment]
或許可以開放使用者自訂 mpris 的欄位。

**Comment by memorydream** [comment]
playerName，或许你想说的是`identity` ?
https://github.com/qier222/YesPlayMusic/blob/b1c5873bd6cf50961e045527758fdf9b538b77d0/src/electron/mpris.js#L7-L10

mpris协议没有定义歌词接口，使用一个已定义的接口提供和其不相同的功能，不如使用ypm当前已经提供的接口
ypm当前已经在自己的API中公开的歌曲进度和id等信息，通过ncm api可以获取歌词信息
相关issue: #616

**Comment by KairuiLiu** [comment]
感谢, 我事实使用ypm接口
