### ISSUE TITLE
MacOS的BigSur状态栏显示问题

### ISSUE THREAD

**Issue by koyangyang** [qier222/YesPlayMusic#144]
MacOS的BigSur状态栏信息显示不出来，![](https://cdn.jsdelivr.net/gh/HandsomeKY/picture@master/uPic/20210130144949.png)
MacOS能不能像网易云一样状态栏加入歌词功能

**Comment by qier222** [comment]
这个需要Electron适配，目前看到Chrome都不支持，所以大概率Electron也还没支持。
