### ISSUE TITLE
0.4.4-Beta1中“纯音乐，请欣赏”隐藏问题

### ISSUE THREAD

**Issue by huichen233** [qier222/YesPlayMusic#1449]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
客户端
- 浏览器名称或电脑操作系统
Windows 11 22581.100
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![7`UCLN5QE4{BQPF_HK_K B](https://user-images.githubusercontent.com/65167412/160285405-6658130d-7e15-4ddd-9a1e-9b716d9033f4.png)

如图，在0.4.4-Beta1更新内容中说明了在只有单行“纯音乐，请欣赏”时会隐藏右侧歌词列表，但如果前面有类似“作曲”，"作词"等内容的时候，则不会隐藏。
请问这是否属于bug？
如果属于bug，那我希望可以尽快修复。
如果不属于bug，那我希望可以在未来版本中看到有关此项的优化。

**Comment by memorydream** [comment]
对于隐藏`纯音乐，请欣赏`的相关行为如下：
如果歌词只有`纯音乐，请欣赏`，隐藏
如果歌词中存在`作词：无` `作曲：无`，这些条目会被过滤，在过滤后如果只有`纯音乐，请欣赏`，隐藏
如果歌词中存在`作词：作者名` `作曲：作者名`，这些条目会被过滤，行为如上

对于有作者名字的条目，如果名字和网易云提供的作者名字完全一致，这些条目会被过滤，这里只会匹配第一个作者
这意味着，以你提供的截图来讲，如果作曲内容为`作曲：Satchel`，那么它会被过滤，但是它在这里的内容为`作曲：Satchel/Xiaro`，无法和第一位作者的信息完全匹配，所以它没有被过滤

如果歌词的长度大于10，即使存在`纯音乐，请欣赏`，也不会进行任何过滤操作，这是考虑到有些作者会在歌词里写一些自己的感想，这样可以避免误过滤一些内容，也可以提升一些性能
