### ISSUE TITLE
右键播放需要点击两次才可以切换

### ISSUE THREAD

**Issue by CKylinMC** [qier222/YesPlayMusic#146]
**问题描述**

当我从歌单中选择歌曲右键点击播放，第一次点击会重置当前歌曲的进度，第二次才会切换到我想要切换的歌曲。

控制台没有输出错误信息。

**屏幕截图**

<details>

<summary>GIF</summary>

![屏幕录制](https://user-images.githubusercontent.com/11648014/106350948-8f5bc900-628d-11eb-97ab-211f314395ed.gif)

</details>

**版本**

YesPlayMusic 0.3.2

**Comment by qier222** [comment]
在Mac和Windows上均没有复现，是不是网络慢的缘故，导致加载下一首歌曲比较慢？

**Comment by CKylinMC** [comment]
> 在Mac和Windows上均没有复现，是不是网络慢的缘故，导致加载下一首歌曲比较慢？

我找了我的朋友也没有复现，但是我哪怕重装一下软件也是这样。。。大概是我哪里弄得有问题吧。。。谢谢回复！
