### ISSUE TITLE
无法显示

### ISSUE THREAD

**Issue by qiangua5210** [qier222/YesPlayMusic#147]
![image](https://user-images.githubusercontent.com/24908791/106351030-6cc0c300-6314-11eb-95aa-16e5c57c80cb.png)
老哥这是什么情况啊，无法登陆，也没有显示

**Comment by yaoqi1124** [comment]
遇到了同样的问题，音乐库界面无法显示，偶尔显示出登陆页面，登陆之后又卡白屏了，希望作者能看一下，非常感谢

**Comment by qiangua5210** [comment]
> 遇到了同样的问题，音乐库界面无法显示，偶尔显示出登陆页面，登陆之后又卡白屏了，希望作者能看一下，非常感谢

你往下翻，下面有教程，我是因为路由器里面开了UnblockNeteaseMusic这个插件，我关掉就行了。如果你也是这个问题，你可以试下或者你看下作者的回复， 你往下看，有同样的问题，作者回答了

**Comment by qier222** [comment]
0.3.3版已修复，如果存在这个问题的话请重新开启issue

**Comment by haohaoget** [comment]
> 0.3.3版已修复，如果存在这个问题的话请重新开启issue

0.4.4还是有这个问题，软路由开启unblockneteasemusic插件，win11打开软件还是白屏网易云登录没有二维码。关闭软路由插件正常

**Comment by haohaoget** [comment]
> 你往下翻，下面有教程，我是因为路由器里面开了UnblockNeteaseMusic这个插件，我关掉就行了。如果你也是这个问题，你可以试下或者你看下作者的回复， 你往下看，有同样的问题，作者回答了

软件无论是否开启UnblockNeteaseMusic 设定或开启代理均白屏无法使用
![image](https://user-images.githubusercontent.com/39007967/153705892-1a1fbddf-6e0a-4498-b2e6-1be2a736cf2e.png)
