### ISSUE TITLE
0.4.4-1提示升级0.4.4

### ISSUE THREAD

**Issue by DrZhang1208** [qier222/YesPlayMusic#1470]
![图片](https://user-images.githubusercontent.com/97793620/161474713-4f451ba4-5025-4c87-8518-6979abfa7c24.png)

**Comment by huichen233** [comment]
一样，这bug就很离谱(

**Comment by lRoccoon** [comment]
一样的bug

**Comment by youyang-617** [comment]
一样

**Comment by memorydream** [comment]
这个bug确实很离谱，0.4.5它自己就会好了

**Comment by hsiayuchih** [comment]
> 

哪有0.4.5？

**Comment by GKVStory** [comment]
> > 哪有0.4.5？
> 
> 还没发，在等一个修改

期待！

**Comment by by-FLY** [comment]
弹窗拦截一下:)我真聪明

**Comment by fjiabinc** [comment]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/38276720/163525438-a3bb2028-1d14-4373-a4a7-258b9f5c61e6.png">
mac 平台也是一样.这bug就离谱

**Comment by guohui-ma** [comment]
> 这个bug确实很离谱，0.4.5它自己就会好了

是不是版本号计算的逻辑有问题，哈哈

**Comment by nanwentianfa** [comment]
确实，太离谱了
