### ISSUE TITLE
无法打开,严重错误

### ISSUE THREAD

**Issue by Yofo-me** [qier222/YesPlayMusic#1473]
Apple macbook pro 2020 m1 上不管是安装arm64.dmg还是brew命令安装，在完成安装后，打开软件时都会报错软件损坏
- 如图：
<img width="260" alt="image" src="https://user-images.githubusercontent.com/55388087/161517085-1983a389-1fc4-4e17-bec8-d6fe0e3ee18f.png">

**Comment by qier222** [comment]
https://github.com/qier222/YesPlayMusic/issues/552
