### ISSUE TITLE
希望添加歌曲封面显示

### ISSUE THREAD

**Issue by KazuhaKun** [qier222/YesPlayMusic#1479]
如图
![image](https://user-images.githubusercontent.com/62269875/161600026-3fca629a-2b4a-486f-97ce-f7612af7e3c5.png)
当网易云音乐网页版/Youtube等其他网站播放媒体内容时会在一些系统/桌面环境中的工具上显示歌曲封面(如在安卓为系统通知栏音乐控制，KDE中则如图)，Yesplaymusic貌似没有这个功能。
（KDE+Arch下使用aur中本地安装不会有封面/在chrome中使用vercel构建也没有封面；Android设备使用chrome打开vercel构建播放有封面）

**Comment by memorydream** [comment]
![image](https://user-images.githubusercontent.com/34763046/161608290-0f6e829c-ade4-4d6d-a5b2-12fed9ef878f.png)

**Comment by memorydream** [comment]
环境是arch linux + kde

**Comment by KazuhaKun** [comment]
> 

立马更新了一下，貌似是没有问题了，添麻烦了
