### ISSUE TITLE
打开一首歌不播放，时间卡在0

### ISSUE THREAD

**Issue by Bennett561** [qier222/YesPlayMusic#1486]
经常打开一首歌不播放，app已经切到这首歌，显示出歌词，但没有声音，进度条也不走，基本上等很久也不会播放。

这时候我先换一首歌，再点这首歌，又可以正常播放了…

**Comment by Bennett561** [comment]
版本为0.4.3，
平台mac m1

**Comment by memorydream** [comment]
是哪一首歌？

**Comment by 0x01x0** [comment]
随便哪一首 只要是付费的

**Comment by memorydream** [comment]
升级到最新的0.4.4-1呢？

**Comment by 0x01x0** [comment]
> > 随便哪一首 只要是付费的
> 
> 升级到最新的0.4.4-1呢？

结果是一样的

**Comment by memorydream** [comment]
cc @pan93412

**Comment by 0x01x0** [comment]
估计是api的问题

**Comment by Bennett561** [comment]
有好几次了，昨天是 不能说的秘密，还有 背叛，其他的记不得了

发自我的iPhone

**Comment by Bennett561** [comment]
升级了，再体验几天看看，如果是歌源的问题那倒没啥

发自我的iPhone

**Comment by Bennett561** [comment]
> 升级了，再体验几天看看，如果是歌源的问题那倒没啥 发自我的iPhone
> […](#)
> 在 2022年4月6日，16:56，0x01x0 ***@***.***> 写道： ﻿ 随便哪一首 只要是付费的 升级到最新的0.4.4-1呢？ 结果是一样的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

升级之后，问题仍然存在诶，点歌A，卡住不播放，这时候切到歌B，再切回来，就可以播放了，没有等待。

**Comment by mdddj** [comment]
0.4.4-1 同样的问题

**Comment by pan93412** [comment]
Duplicate of #1543
