### ISSUE TITLE
已登录网易云音乐账号，无法播放歌曲，报错

### ISSUE THREAD

**Issue by istek** [qier222/YesPlayMusic#1488]
# 尽量每个 issue 只提一个 bug 或新功能

已经登录网易云音乐账号，账号是黑胶会员，无法播放音乐，报错如下截图。

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
客户端，客户端版本 V0.4.4-1
- 浏览器名称或电脑操作系统
Win10 21H2
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://user-images.githubusercontent.com/8424803/161920531-8e5c5d2f-c700-4d10-9b41-829f91a08bb0.png)

**Comment by memorydream** [comment]
Duplicate of #1145
