### ISSUE TITLE
在启动YesPlay Music后启动Discord Discord动态不更新

### ISSUE THREAD

**Issue by XiaoMouz** [qier222/YesPlayMusic#1492]
### 已确认 👉

- [x] 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- [x] 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### Bug信息
 - 使用版本:客户端

- 操作系统
> Windows 10 专业版 20H2

- Console页面截图
![image](https://user-images.githubusercontent.com/54032212/162108534-0aa2dc21-a16c-4e2c-854d-ec5c9056a2e4.png)

- 错误表现
启动播放器后启动Discord，播放音乐，Discord并没有出现自己所希望的实时动态
![image](https://user-images.githubusercontent.com/54032212/162108827-3dedb9ce-42ec-4d6c-8882-efadab47200a.png)

**Comment by pan93412** [comment]
之前我有稍微測試過，發現到需要先啟動 Discord 再啟動 YesPlayMusic。試試看改一下啟動順序？

**Comment by XiaoMouz** [comment]
> 之前我有稍微測試過，發現到需要先啟動 Discord 再啟動 YesPlayMusic。試試看改一下啟動順序？

这样是能够生效的，如果可以的话将该 issue 排列在低优先级的待处理中，希望在未来的某个版本能够修复他（佛系）

**Comment by XiaoMouz** [comment]
discord rpc问题
