### ISSUE TITLE
关于中文支持

### ISSUE THREAD

**Issue by hawtim** [qier222/YesPlayMusic#15]
我在 fork 仓库下建了个分支，https://github.com/hawtim/YesPlayMusic/tree/i18n
用 vue-i18n 简单的实现了一下中文支持
有空可以看看是否符合 TODO 中文支持的实现

**Comment by qier222** [comment]
看起来没问题，message最好再分几层，比如navbar的explore可以是message.nav.explore

**Comment by hawtim** [comment]
嗯是个好建议。我打算把顶部条的中文先实现，然后推个 PR ，你看怎样。

**Comment by qier222** [comment]
@hawtim 可以哦
