### ISSUE TITLE
JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by JarvissKuo** [qier222/YesPlayMusic#1506]
运行时遇到一个错误，见截图 JavaScript error occurred in the main process
![JavaScript error](https://user-images.githubusercontent.com/50903880/162580254-aeded01c-cdcf-4a85-ae15-6c3d9de5e72c.png)
客户端v0.4.4-1
win10
 控制台 Console 页面的截图
![控制台截图](https://user-images.githubusercontent.com/50903880/162580358-fab07b8a-4ecf-4f65-ad5c-4865a2108a91.png)

**Comment by memorydream** [comment]
Dulicate of #1145
