### ISSUE TITLE
打开yesplayer后报错

### ISSUE THREAD

**Issue by Bryan2333** [qier222/YesPlayMusic#1507]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）
电脑系统：Windows 11 21H2

报错截图：
![yesplayer-bug](https://user-images.githubusercontent.com/31512600/162599444-41d56578-a85a-46d5-b623-a2000e984954.png)

**Comment by memorydream** [comment]
Dupllicate of #1145
