### ISSUE TITLE
音乐库打不开

### ISSUE THREAD

**Issue by reputati0n** [qier222/YesPlayMusic#152]
console 截图链接：https://www.hualigs.cn/image/601551b154222.jpg

**Comment by qier222** [comment]
试过清空local storage和cookies吗

**Comment by reputati0n** [comment]
> 试过清空local storage和cookies吗
嗯，看到之前的issue已经试过了，没有效果

**Comment by qier222** [comment]
是用什么方式登录的？
你的账号里的 “我喜欢的音乐” 是空的吗？

**Comment by reputati0n** [comment]
> 是用什么方式登录的？
> 你的账号里的 “我喜欢的音乐” 是空的吗？

使用手机号密码方式登陆的，“我喜欢的音乐”的确是空的，我只收藏了一些专辑和歌单

**Comment by reputati0n** [comment]
> 是用什么方式登录的？
> 你的账号里的 “我喜欢的音乐” 是空的吗？

在“我喜欢的音乐”添加了音乐之后正常登录了

**Comment by qier222** [comment]
了解

**Comment by huanx9** [comment]
感觉这个判断方式还是有问题， 不仅得要有 `我喜欢的音乐` 还要有专辑和歌单乱七八糟的，我也懒得测试了。 好像各种元素都要齐全，才可以登录。

**Comment by qier222** [comment]
0.3.3版已修复，如果存在这个问题的话请重新开启issue
