### ISSUE TITLE
播放部分特定歌曲提示无法播放并报错

### ISSUE THREAD

**Issue by DarkCWK** [qier222/YesPlayMusic#1520]
播放部分特定歌曲提示无法播放
![批注 2022-04-11 204317](https://user-images.githubusercontent.com/20531116/162742672-1b1f02aa-197c-485f-9ec9-731545eff86e.png)
并报错
![批注 2022-04-11 204430](https://user-images.githubusercontent.com/20531116/162742689-2ed3e839-ae95-4d14-8dda-11370e0efbc0.png)
目前发现两首歌
[客官不可以](https://music.163.com/#/song?id=174963)
[圈住你](https://music.163.com/#/song?id=1372552573)

**Comment by DarkCWK** [comment]
疑似都是VIP的歌曲
应该是 UnblockNeteaseMusic 出了问题

**Comment by memorydream** [comment]
Dupllicate of #1145
