### ISSUE TITLE
歌词文字亮起时会重新排版

### ISSUE THREAD

**Issue by PhilosopherSM** [qier222/YesPlayMusic#1523]
![image](https://user-images.githubusercontent.com/35450764/162903925-3d1928d9-2cf0-4869-baee-f6b103248c5a.png)

![image](https://user-images.githubusercontent.com/35450764/162903874-df18ed6f-3a08-4731-a975-51b8c9efbd35.png)

![image](https://user-images.githubusercontent.com/35450764/162903947-d597bf89-713a-4541-8399-3365b98170df.png)

像这样，中间这一行歌词在高亮时会重新排版成两行，之后又变成一行。感觉很怪。
我建议高亮增加尺寸但不改变排版。

**Comment by DrZhang1208** [comment]
这个问题已经被记录了，等修复吧
