### ISSUE TITLE
能否考虑做一个spotify客户端？

### ISSUE THREAD

**Issue by billowssun** [qier222/YesPlayMusic#1528]
目前用spotify感觉有点不适应
一是不支持简中。
二是只能看歌手10首热门歌曲，如果想找其他的，就得去翻各种专辑。
所有想找一个spotify的第三方客户端，不知道作者可虑过吗，或者有没有推荐的。

**Comment by qier222** [comment]
Spotify 官方API不能播放音频，所以没办法接入
