### ISSUE TITLE
可以上架 Microsoft store嗎?

### ISSUE THREAD

**Issue by ThomasQAQOUO** [qier222/YesPlayMusic#1529]
可以上架 Microsoft store嗎? 經常更新很麻煩. Microsoft上的更新舒服多. 也方便介紹親朋戚友用

**Comment by Yang7521** [comment]
> 

> 可以上架 Microsoft store嗎? 經常更新很麻煩. Microsoft上的更新舒服多. 也方便介紹親朋戚友用

这是侵犯著作权的东西你觉得能上架吗？

**Comment by qier222** [comment]
不是UWP，所以上架不了？我是没什么兴趣上架。
