### ISSUE TITLE
关于歌词的一些新想法

### ISSUE THREAD

**Issue by fjiabinc** [qier222/YesPlayMusic#1534]
此时在想如果有桌面歌词,或者菜单歌词.再或者~~touch bar 显示歌词?  当然了,这是在mac本子的便利,其他机型或许只需要桌面歌词?
本次lssue只考虑客户端.希望大佬考虑添加TODO

**Comment by qier222** [comment]
不会有桌面歌词和菜单栏歌词。
Touch Bar苹果要砍掉了，没兴趣做了😂
