### ISSUE TITLE
希望添加“屏蔽错误弹窗”的选项

### ISSUE THREAD

**Issue by FCSDFSDVXDFG** [qier222/YesPlayMusic#1535]
0.4.3的时候遇到播放失败的歌会有错误弹窗出现（之前只是跳过播放失败的歌，无弹窗）多次出现根本就受不了，故曾有一段时间放弃使用，现在看到0.4.4更新，这个特性依旧没改，很烦

**Comment by PoorSstudent** [comment]
在终端里面启动即可 或者关闭ubm
