### ISSUE TITLE
Macbook pro 14英寸 用homebrew安装打开之后提示已经损坏

### ISSUE THREAD

**Issue by MinxunYuan** [qier222/YesPlayMusic#1546]
MacBook Pro（14英寸，2021年）
macOS Monterey 12.0.1

问题描述：
版本：0.4.3-arm64
控制台截图（安装成功）
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/61120433/164314636-07d7cace-e202-4c70-b8d3-d74e7a24fad1.png">
启动应用提示已损坏
<img width="466" alt="image" src="https://user-images.githubusercontent.com/61120433/164314922-77d4e874-8e8b-43f4-a219-1f382a54adb0.png">

**Comment by memorydream** [comment]
#552
