### ISSUE TITLE
windows10 LTSC YesPlayMusic_0.4.4 报错

### ISSUE THREAD

**Issue by zheng-yuzhen** [qier222/YesPlayMusic#1548]
客户端 安装版报错
![Quicker_20220421_105131](https://user-images.githubusercontent.com/40607105/164362370-ff131255-800b-4fa4-996b-66f5439dd71e.png)

**Comment by NEANC** [comment]
# 系统 
Windows 10 LTSC 2019；等效 SAC 版本：Windows 10 1809
# 客户端版本
v0.4.4-1 安装版；包名 YesPlayMusic-Setup-0.4.4-1.exe
# 错误内容
在自动切歌/WIN控制器手动切歌时会有概率弹出该错误窗口
![image](https://user-images.githubusercontent.com/30574631/164416456-a362e2b5-6aab-495f-a4b7-2a856de9ff51.png)

同时可能伴随客户端白屏/客户端不播放歌曲
关闭该错误窗口时，恢复运行
*忘记截图了，等复现时再上传*

**Comment by NEANC** [comment]
转移至#1145 或 #1238

**Comment by pan93412** [comment]
> 转移至#1145 或 #1238
> 请关闭该issues，谢谢

謝謝 ❤️
