### ISSUE TITLE
播放云盘里的其中一首歌曲时,不能拖动进度条,别的歌都没问题

### ISSUE THREAD

**Issue by kanzakiken** [qier222/YesPlayMusic#1559]
客户端版本: 0.4.4
系统版本:macos 12.3
只有这一首有问题,拖动进度条会自动跳回到歌曲刚开始播放的状态.试了试网易云客户端没有问题.
能正常播放完,只是无法拖动进度条.总时间那里显示只有1秒
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/18526398/164951959-187a005d-ac4f-4230-b450-5ce35829d221.png">

**Comment by pan93412** [comment]
Duplicate of #1236
