### ISSUE TITLE
检查更新时版本号的小问题

### ISSUE THREAD

**Issue by maxelblack** [qier222/YesPlayMusic#1561]
内置的检查更新在版本号后有 `-` 时会将这个版本当做旧版本。(如 `0.4.4-1` 会被认为比 `0.4.4` 更旧)

版本 0.4.4-1

macOS Big Sur (amd64)

**Comment by memorydream** [comment]
已知问题，发布`0.4.5`的时候它自己就好了，之后会避免这种情况
Duplicate of #1470

**Comment by memorydream** [comment]
已知问题，发布`0.4.5`的时候它自己就好了，之后会避免这种情况
Duplicate of #1470
