### ISSUE TITLE
你要是能把付费的歌曲免费听，那就厉害了

### ISSUE THREAD

**Issue by Chasen-Zhang** [qier222/YesPlayMusic#1566]
### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

你要是能把付费的歌曲免费听，那就厉害了

**Comment by KiWinger** [comment]
https://github.com/UnblockNeteaseMusic/server

**Comment by pan93412** [comment]
已內建本功能（UnblockNeteaseMusic）。
