### ISSUE TITLE
音质选择有问题

### ISSUE THREAD

**Issue by JingBh** [qier222/YesPlayMusic#1588]
#1585 新增对 Hi-Res 音质的支持后，当设置中选择 FLAC 音质，而所播放歌曲没有此音质时，将无法播放。

根据此段代码：

https://github.com/qier222/YesPlayMusic/blob/cf833070d1f448159b03df0c2ff89755f60301c7/src/api/track.js#L11-L25

若 `quality` 为 `flac`，`sqBr` 为 `undefined`，将返回 `flac`，不是合法参数，导致 `NeteaseCloudMusicApi` 将返回 `400` 错误，如图所示。

![image](https://user-images.githubusercontent.com/26338708/166132392-2ac008e1-d724-40a0-a092-2391732c6efd.png)
![image](https://user-images.githubusercontent.com/26338708/166132395-8489887e-f913-4b75-81ca-a4be515df5a8.png)

**Comment by memorydream** [comment]
我已经重写了音质选择器，正在进行一些测试
#1585 的修改是一个兼容性修改，选用`hi-res`即可回到之前的行为，暂时不要选择`flac`即可，当`hi-res`音源不可用时，会匹配到`flac音源`

**Comment by JingBh** [comment]
Hi-Res 文件太大，且个人没有对这么高音质的需求。
一个小拙见，就目前的代码来说，改成这样是不是能解决问题？
```javascript
const getBr = (quality, sqBr, hiResBr) => {
  if (quality === '999000' && hiResBr) return hiResBr;
  if (quality === 'flac' && sqBr) return sqBr;
  return 320000;
};
```

**Comment by JingBh** [comment]
另外：这样有问题的行为是不是不应该草率地 release 到新版本？

**Comment by memorydream** [comment]
> 另外：这样有问题的行为是不是不应该草率地 release 到新版本？

因为我没有测试出这样的问题，而且上一个版本存在着更多不可接受的bug，修复了这些真正最影响软件使用的bug后吗，我们认为现在已经是时候发布新的版本了

这个音质选择的问题确实是我没有写好，但是考虑到选择`hi-res`会回到之前的行为（即如果没有这个支持hi-res的pr，当在音质里选择无损时，会优先使用hi-res音频），在我们发新版本之前应该不会造成过大的问题
