### ISSUE TITLE
音乐库空页面

### ISSUE THREAD

**Issue by zine-fj** [qier222/YesPlayMusic#1592]
问题：点击音乐库页面为空页面，刷新后自动跳到首页也是空页面。但是点击首页和发现tab是有页面的。
我的网址如下：https://yesplaymusic-zine-fj.vercel.app/library
下面为具体信息：
1. 网页版
2. 谷歌浏览器
3. window 11
5. 截图如下：
![微信图片_20220501181809](https://user-images.githubusercontent.com/19276833/166141739-d29f79a5-d651-4d8f-b957-49ceb6e41915.png)

**Comment by memorydream** [comment]
0.4.5已修复

**Comment by zine-fj** [comment]
我应该怎么做，才能让我fork的可以在我的vercel没问题？

**Comment by memorydream** [comment]
把这个仓库的代码合并到你的fork中
