### ISSUE TITLE
windows点击关闭后没有最小化到托盘的选项,直接关闭应用了

### ISSUE THREAD

**Issue by CYLlinmaian** [qier222/YesPlayMusic#1593]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 客户端
- 版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2022/‎4/‎30
操作系统版本	22610.1
体验	Windows Feature Experience Pack 1000.22632.1000.0

**Comment by NEANC** [comment]
请检查您的 `关闭主面板时...` 设置，是否为 `退出`
- 路径
  - `设置 -> 其他 -> 关闭主面板时...`
 
![image](https://user-images.githubusercontent.com/30574631/166144007-42e81686-b80c-4247-b4da-051d933a40c1.png)

**Comment by CYLlinmaian** [comment]
好的，这个版本默认没有提示，是我搞错了，请作者删除这个issue吧
