### ISSUE TITLE
双显示器位置无法正确被记忆

### ISSUE THREAD

**Issue by PurBlu** [qier222/YesPlayMusic#1601]
0.4.5更新了功能 
_“修复: APP启动时检查窗口位置，避免窗口启动在屏幕外”_ #1474  （最初来自于 #1436 ）
然而我个人的使用需求与 #1436 正相反 我基本不会「断开副屏连接」

因此
0.4.5前的版本 启动YPM时 **是会记住我最后一次的打开位置(i.e 副屏正中央)** 这也是我个人的使用期望
0.4.5更新后 **即便我上次使用时将YPM拖拽至副屏 关闭后重新打开YPM 仍然会显示在主屏正中央**

不是太符合我个人的使用期望 理解 #1436 的需求 但不知是否有兼得的更好的实现方式

**Comment by memorydream** [comment]
需要其他有使用双屏的贡献者来查看这个问题，先帮你标记了

**Comment by pan93412** [comment]
Duplicate of #635
