### ISSUE TITLE
【客户端】【Windows 10】歌词界面目前歌詞無圓角

### ISSUE THREAD

**Issue by Linco-me** [qier222/YesPlayMusic#1603]
当前歌词最右侧没有圆角，但其他的歌词都有，而且歌词到最上侧不会消失，遮挡按钮
![2022-05-03 130741](https://user-images.githubusercontent.com/81073939/166407396-9ad31ddf-cf99-4a4d-af30-482612121068.png)
![2022-05-03 130804](https://user-images.githubusercontent.com/81073939/166407415-0c5bee6f-672b-4f6b-a9bb-48a47aaec293.png)

**Comment by Linco-me** [comment]
![2022-05-03 131757](https://user-images.githubusercontent.com/81073939/166407459-e4f6c0ee-f867-4d14-a274-c038b5a190d0.png)
遮挡按钮截图

**Comment by pan93412** [comment]
已知問題，因為是用 `transform` 變換的。目前暫時沒有比較好的解決方案。

**Comment by DrZhang1208** [comment]
可以把没变大的歌词框缩小一点，这样的话当前歌词就不会超过区域了吧
