### ISSUE TITLE
Docker中的Nginx.conf配置有误

### ISSUE THREAD

**Issue by huangyinhaow** [qier222/YesPlayMusic#1604]
此Nginx.conf没有定义最大标头大小，若不手动更改，则会出现无法登陆的bug，且Nginx会返回Header too big错误。

**Comment by huangyinhaow** [comment]
Gittouch的bug导致多次提交，抱歉

**Comment by pan93412** [comment]
建議 PR

**Comment by huangyinhaow** [comment]
> 建議直接往 dockerfile 發 PR

我不太懂Dockerfile，但你只需要往Nginx.conf的server块中添加
 ```
   proxy_buffer_size 128k;
    proxy_buffers 16 32k;
    proxy_busy_buffers_size 128k;
```
即可

**Comment by pan93412** [comment]
https://github.com/qier222/YesPlayMusic/blob/master/Dockerfile @huangyinhaow 你 review 一下，我剛不小心按下 commit to master⋯⋯ QQ
