### ISSUE TITLE
希望加入 Windows 沉浸式窗口顶栏

### ISSUE THREAD

**Issue by zsqw123** [qier222/YesPlayMusic#161]
希望可以做到沉浸式窗口顶栏, 现有顶栏如下  
![现有](https://user-images.githubusercontent.com/49520432/106380217-a6b0c880-63eb-11eb-89d0-f2dadbee81af.png)  
在 win10 非白色主题的情况下, 显示效果存在撕裂感, 可以尝试VSCode这种重写覆盖掉了原来Windows的顶栏  
![VSCode](https://user-images.githubusercontent.com/49520432/106380312-5f770780-63ec-11eb-900d-28fec53d222e.png)  
观感要好了很多, 而且采用这种方法还可以使 Win/Linux/Mac 观感较为一致  
VSCode 基于 Electron, 相信本项目也应该有可以方法去实现这种效果, 或者干脆做成无顶栏应用, 内部内嵌一层操作按钮(甚至可以操作按钮包含一些其他操作?), 非常感谢!

**Comment by qier222** [comment]
已经在todo里面了

**Comment by zsqw123** [comment]
哈哈哈好, 我看那里写的只是 标题栏 Dark Mode, 我还以为是只做一下反色处理什么的, 我就提出了一点具体的想法, 谢谢

**Comment by qier222** [comment]
v0.3.4 已支持
