### ISSUE TITLE
歌词页面添加音量控制和播放列表按钮

### ISSUE THREAD

**Issue by Heporis** [qier222/YesPlayMusic#1612]
每次在歌词页面想调音量或者看播放列表都要退出歌词，然后再回来，好麻烦啊
还有这样的任务栏缩略图上的控制按钮能做一个吗？
![无标题](https://user-images.githubusercontent.com/51895154/166674995-89085aef-06af-4e64-ba9e-7c98022710c2.jpg)

**Comment by memorydream** [comment]
Duplicate of #273 
Duplicate of #1007
