### ISSUE TITLE
10754 端口被占用，启动后无法加载内容

### ISSUE THREAD

**Issue by Skimige** [qier222/YesPlayMusic#162]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- [x] 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- [x] 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 客户端
- Windows 10 20H2
- 没有 Console 截图，就是网页内容没法载入

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: listen EACCES: permission denied 127.0.0.1:10754
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at doListen (net.js:1498:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

[确定]
```

使用 CurrPorts 工具查看 svchost.exe 建立了一个到新加坡 MS 数据中心的 TCP 连接，关闭该连接即正常。
但是，为什么 xjb 抽奖运气也能这么好……

**Comment by qier222** [comment]
排查一下10754端口被哪个软件用了

**Comment by Skimige** [comment]
> 排查一下10754端口被哪个软件用了

…… 描述里写了是 svchost.exe

我更想问的是，能否规避这种情况，要不就给个 solution 在 README 或者什么文档里

**Comment by qier222** [comment]
改端口的话需要改源代码然后build
