### ISSUE TITLE
？？

### ISSUE THREAD

**Issue by Nicky-tian** [qier222/YesPlayMusic#1623]
![image](https://user-images.githubusercontent.com/35889576/167255345-c791e4ff-f3c1-477d-bcb9-15e3eed53d02.png)

**Comment by pan93412** [comment]
其他 Electron 程式有類似情況嗎？

**Comment by Nicky-tian** [comment]
除了一个我知道的kms office激活应用


On 5/7/2022 ***@***.***> wrote：

其他 Electron 程式有類似情況嗎？

**Comment by memorydream** [comment]
#404 #1049 阻止即可，ypm不会用到你的摄像头

**Comment by pan93412** [comment]
Duplicate of #404
