### ISSUE TITLE
客户端 打开应用报错

### ISSUE THREAD

**Issue by RedPanda31415** [qier222/YesPlayMusic#1624]
报错图片：
![NHLJ$P3K`~E$H2RUY)TKJ_O](https://user-images.githubusercontent.com/102841544/167278668-a98caafd-5109-438e-a24b-a61372a4920f.png)

打开应用后出现上面的报错，应用主页面无法成功打开
版本：0.4.5 (Setup)
系统：win10（刚重装）

0.4.4-1可以正常使用，更新到0.4.5报错
尝试过#1145方法解决，但没成功（可能是我步骤错了，但是问题依然没有解决

（第一次反馈bug，内容可能有瑕疵）

**Comment by RedPanda31415** [comment]
其他讨论的超链接不会挂到内容上，所以直接用“#1145“文本代替了（hhhhhhhhh

**Comment by RedPanda31415** [comment]
> 报错图片： ![NHLJ$P3K`~E$H2RUY)TKJ_O](https://user-images.githubusercontent.com/102841544/167278668-a98caafd-5109-438e-a24b-a61372a4920f.png)
> 
> 打开应用后出现上面的报错，应用主页面无法成功打开 版本：0.4.5 (Setup) 系统：win10（刚重装）
> 
> 0.4.4-1可以正常使用，更新到0.4.5报错 尝试过#1145方法解决，但没成功（可能是我步骤错了，但是问题依然没有解决
> 
> （第一次反馈bug，内容可能有瑕疵）

**Comment by RedPanda31415** [comment]
嗯？怎么close了（

> 报错图片： ![NHLJ$P3K`~E$H2RUY)TKJ_O](https://user-images.githubusercontent.com/102841544/167278668-a98caafd-5109-438e-a24b-a61372a4920f.png)
> 
> 打开应用后出现上面的报错，应用主页面无法成功打开 版本：0.4.5 (Setup) 系统：win10（刚重装）
> 
> 0.4.4-1可以正常使用，更新到0.4.5报错 尝试过#1145方法解决，但没成功（可能是我步骤错了，但是问题依然没有解决
> 
> （第一次反馈bug，内容可能有瑕疵）

**Comment by RedPanda31415** [comment]
坏了，手残关闭了。。

求解。。。

**Comment by RedPanda31415** [comment]
> 报错图片： ![NHLJ$P3K`~E$H2RUY)TKJ_O](https://user-images.githubusercontent.com/102841544/167278668-a98caafd-5109-438e-a24b-a61372a4920f.png)
> 
> 打开应用后出现上面的报错，应用主页面无法成功打开 版本：0.4.5 (Setup) 系统：win10（刚重装）
> 
> 0.4.4-1可以正常使用，更新到0.4.5报错 尝试过#1145方法解决，但没成功（可能是我步骤错了，但是问题依然没有解决
> 
> （第一次反馈bug，内容可能有瑕疵）

**Comment by RedPanda31415** [comment]
return就好了吧。。。。

**Comment by RedPanda31415** [comment]
reopened一下就好了吧

**Comment by RedPanda31415** [comment]
reopened一下就好了吧。。。

**Comment by memorydream** [comment]
尝试使用管理员权限启动，可能是权限不够导致一些临时文件没有被成功创建

**Comment by pan93412** [comment]
[大概是缺 runtime](https://stackoverflow.com/questions/41253450/error-the-specified-module-could-not-be-found)，但我不確定具體是哪些 library。

**Comment by pan93412** [comment]
https://docs.microsoft.com/zh-CN/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022 @RedPanda31415 試裝看看？

**Comment by RedPanda31415** [comment]
已解决！是缺了runtime（装纯净系统の痛。。

是不是可以close了？（第一次不是很懂.jpg
