### ISSUE TITLE
Is it possible to add desktop translation?

### ISSUE THREAD

**Issue by zaprtqa** [qier222/YesPlayMusic#1625]
Is it possible to add desktop translation?

**Comment by pan93412** [comment]
We have already implemented the internalization function in this app partially. Not really sure what the parts you are talking about.

**Comment by zaprtqa** [comment]
桌面歌词

**Comment by zaprtqa** [comment]
> 我们已经在这个应用程序中部分实现了内化功能。不太清楚你在说什么部分。

桌面歌词

**Comment by zaprtqa** [comment]
> 歌词桌面

Lyrics Desktop

**Comment by qier222** [comment]
不会增加桌面歌词功能
