### ISSUE TITLE
0.4.5版本不能在openSUSE Tumbleweed上正常运行

### ISSUE THREAD

**Issue by pyfile** [qier222/YesPlayMusic#1637]
# YesPlayMusic 0.4.5无法登录账户
## 本地环境
OS: openSUSE Tumbleweed
Linux Kernel: Linux promote.ldns.rate.local 5.17.5-1-default #1 SMP PREEMPT Thu May 5 10:06:09 UTC 2022 (e57ab05) x86_64 x86_64 x86_64 GNU/Linux
YesPlayMusic软件版本: YesPlayMusic-0.4.5.AppImage
## 问题描述
release中的rpm包在安装时会报错缺乏nss和libuuid依赖，因此尝试使用AppImage，但发现无法通过邮箱或者手机号登录账户（我的账户邮箱还是网易163邮箱），也无法刷新出网易云的登录二维码
![Screenshot_20220512_201142](https://user-images.githubusercontent.com/37824630/168073088-3af1600c-546d-490d-8792-d0df26cb0413.png)

我看过Issue里有一个被关闭的也是openSUSE系统的，但是他最后是换系统解决的，可能这个问题还没有完全解决

**Comment by memorydream** [comment]
主页上的歌单等信息可以加载出来吗

**Comment by memorydream** [comment]
我没有用过openSUSE，之后有空我开个虚拟机试一下看看

**Comment by memorydream** [comment]
我没有用过openSUSE，之后有空我开个虚拟机试一下看看

**Comment by memorydream** [comment]
![](https://user-images.githubusercontent.com/34763046/168161752-9f29eafa-2685-42e2-ad3f-22a5dd128645.png)

没能在虚拟机内复现这个问题，全新安装的openSUSE，进入DE后只安装了ypm

**Comment by pyfile** [comment]
您好，这样的话，请问如果只看我问题描述中开发者选项展示的报错，我该怀疑哪些东西影响了ypm的运行。（我之前自行用lsof -i:27232查看了，27232端口确实是被yesplaymusic占用了，而没有被别的进程占用，似乎也不是端口被抢占的问题。）

**Comment by memorydream** [comment]
electron的话，我记得api应该是跑在`10754`这个端口上，你看一下？

**Comment by pyfile** [comment]
我测试了一下，10754端口没有服务，ypm确实是使用了27232端口（在问题描述的截图中也可以看到报错在localhost:27232的500 INTERNAL SERVER ERROR）

**Comment by pyfile** [comment]
> electron的话，我记得api应该是跑在`10754`这个端口上，你看一下？

我Terminal使用`./YesPlayMusic-0.4.5.AppImage`运行，报错如图
![Screenshot_20220513_173746](https://user-images.githubusercontent.com/37824630/168256911-d003ac8f-a6f1-4ae0-82f2-83651f3c5890.png)
同时使用`netstat|grep 10754`，无结果
使用`netstat|grep 27232`结果如图
![Screenshot_20220513_174305](https://user-images.githubusercontent.com/37824630/168257374-58f6d97c-ab2b-4d04-b5e6-7a68076bd54c.png)
同时ypm的表现以及开发者选项中的提示依然如我在最初的问题描述中所示。

因为我对electron并不是很了解，请问通过这些信息能看出发生了什么问题吗

**Comment by memorydream** [comment]
> Error: connect ECONNREFUSED 127.0.0.1:10754 at TCPConnnectWrap.afterConnect

不清楚为什么你在10754上没有进程，我这里是有的
![image](https://user-images.githubusercontent.com/34763046/168281657-f2fed078-be48-4fd1-8a98-2fefb8d19604.png)

感觉是你本机配置的问题

**Comment by pyfile** [comment]
1. `ping localhost`可以得知`localhost(::1)`
2. 非常抱歉，我之前只做过cmake编译，下载了这个项目的source code然后修改完后我发现我确实完全不知道怎么“编译”它

**Comment by memorydream** [comment]
> 1. `ping localhost`可以得知`localhost(::1)`
> 2. 非常抱歉，我之前只做过cmake编译，下载了这个项目的source code然后修改完后我发现我确实完全不知道怎么“编译”它

在README里有相关操作的说明
[打包客户端](https://github.com/qier222/YesPlayMusic#%EF%B8%8F-%E6%89%93%E5%8C%85%E5%AE%A2%E6%88%B7%E7%AB%AF)

**Comment by BakerBunker** [comment]
那`cat /etc/hosts`会显示什么呢

**Comment by monstorix** [comment]
openSUSE用户，在此给出一些可能有用的参考信息（第二条不保证适用于所有机器）：
1. 对于openSUSE，libuuid与nss的包名分别为**libuuid1**与**mozilla-nss**。安装rpm时出现二者的依赖问题是因为相应rpm的打包采用了Fedora/RHEL的依赖名，与openSUSE的并不匹配。如果系统中已安装上述两个软件包，则可以放心忽略“找不到依赖”的提示，继续安装rpm。
2. 早前也曾遇到过YesPlayMusic的白屏症状，后来是通过添加主机名解决的（openSUSE默认没有指定别名）。可以尝试通过 **YaST > 网络设置 > “主机名/DNS”选项卡** 或者 **YaST > 主机名** 为系统主机（127.0.0.1）指定一个静态主机名。如下图：
![图片](https://user-images.githubusercontent.com/9211781/169712041-9f2cf9a9-cbe8-4dd2-8c50-49bb9e578aea.png)
![图片](https://user-images.githubusercontent.com/9211781/169712020-cecee8af-e9c2-4923-8c62-ce31ba7ad47b.png)

**Comment by pyfile** [comment]
> 那`cat /etc/hosts`会显示什么呢

我摘了关键的，有这些
`127.0.0.1       localhost`
`# fallback hostname used by NetworkManager`
`127.0.0.1       localhost.localdomain`
`# special IPv6 addresses`
`::1             localhost ipv6-localhost ipv6-loopback`

**Comment by pyfile** [comment]
> 同openSUSE用户，在此给出一些可能有用的参考信息（第二条不保证适用于所有机器）：
> 
> 1. 对于openSUSE，libuuid与nss的包名分别为**libuuid1**与**mozilla-nss**。安装rpm时出现二者的依赖问题是因为相应rpm的打包采用了Fedora/RHEL的依赖名，与openSUSE的并不匹配。如果系统中已安装上述两个软件包，则可以放心忽略“找不到依赖”的提示，继续安装rpm。
> 2. 早前也曾遇到过YesPlayMusic的白屏症状，后来是通过添加主机名解决的（openSUSE默认没有指定别名）。可以尝试通过 **YaST > 网络设置 > “主机名/DNS”选项卡** 或者 **YaST > 主机名** 为系统主机（127.0.0.1）指定一个静态主机名。如下图：
>    ![图片](https://user-images.githubusercontent.com/9211781/169712041-9f2cf9a9-cbe8-4dd2-8c50-49bb9e578aea.png)
>    ![图片](https://user-images.githubusercontent.com/9211781/169712020-cecee8af-e9c2-4923-8c62-ce31ba7ad47b.png)

很不幸，这两条我验证了之后发现对我来说都不行

**Comment by monstorix** [comment]
> 很不幸，这两条我验证了之后发现对我来说都不行

@pyfile 第一条我可能需要补充一下：只要确认**libuuid1**与**mozilla-nss**安装后，就**不需要理会zypper或是YaST的警告**，因为它们只是机械索引安装包中的依赖表，只要打包时的依赖名不对openSUSE优化，这个警告就一直有。而YPM本身只会读取存在的uuid与nss库，包管理器的警告不会造成任何影响。每次安装时选择“断开”即可。

另外从你前面发出的hosts来看，你并没有成功添加主机名。而我在本地测试将主机名删掉后，YPM出现了和你一模一样的错误。如果可以的话，建议再次检查一下操作。第一次添加主机名后，最好重启。

**Comment by pyfile** [comment]
> > 很不幸，这两条我验证了之后发现对我来说都不行
> 
> @pyfile 关于包管理器我可能需要补充一下：只要确认**libuuid1**与**mozilla-nss**安装后，就**不需要理会zypper或是YaST的警告**，因为它们只是机械索引安装包中的依赖表，只要打包时的依赖名不对openSUSE优化，这个警告就一直有。而YPM本身只会读取存在的uuid与nss库，包管理器的警告不会造成任何影响。每次安装时选择“断开”即可。
> 
> 对于主机名，我可能写漏了，要添加的是**主机别名**，就是图上模糊的部分（可以从命令行`sudo yast2 host` 或界面 **YaST > 主机名** 进入）。从你前面发出的hosts来看，你并没有成功添加上。而我在本地测试将主机别名删掉后，YPM出现了和你一模一样的错误。如果可以的话，建议再次检查一下操作。第一次添加主机别名后，最好重启。

非常感谢你的帮助，但事实上：
1. 我确认了本机转了libuuid1和mozilla-nss,并且zypper安装release里提供的rpm包后，是通过忽略某些依赖的方式继续安装直至安装成功的
2. 我在hosts里添加了主机别名了，现在我的hosts是这样的`127.0.0.1       localhost loopback`，我已经为127.0.0.1添加了名为"loopback"的主机别名，但是重启电脑后报错相同

请问是你有采用什么特别的主机别名吗？

如果这个方向没有可能有进展，后续有时间我研究一下上一个人向我提出的修改源码重新打包的方案。

**Comment by monstorix** [comment]
> > > 很不幸，这两条我验证了之后发现对我来说都不行
> > 
> > @pyfile 关于包管理器我可能需要补充一下：只要确认**libuuid1**与**mozilla-nss**安装后，就**不需要理会zypper或是YaST的警告**，因为它们只是机械索引安装包中的依赖表，只要打包时的依赖名不对openSUSE优化，这个警告就一直有。而YPM本身只会读取存在的uuid与nss库，包管理器的警告不会造成任何影响。每次安装时选择“断开”即可。
> > 
> > 对于主机名，我可能写漏了，要添加的是**主机别名**，就是图上模糊的部分（可以从命令行`sudo yast2 host` 或界面 **YaST > 主机名** 进入）。从你前面发出的hosts来看，你并没有成功添加上。而我在本地测试将主机别名删掉后，YPM出现了和你一模一样的错误。如果可以的话，建议再次检查一下操作。第一次添加主机别名后，最好重启。
> 
> 非常感谢你的帮助，但事实上：
> 1. 我确认了本机转了libuuid1和mozilla-nss,并且zypper安装release里提供的rpm包后，是通过忽略某些依赖的方式继续安装直至安装成功的
> 2. 我在hosts里添加了主机别名了，现在我的hosts是这样的`127.0.0.1       localhost loopback`，我已经为127.0.0.1添加了名为"loopback"的主机别名，但是重启电脑后报错相同
> 
> 请问是你有采用什么特别的主机别名吗？
> 
> 如果这个方向没有可能有进展，后续有时间我研究一下上一个人向我提出的修改源码重新打包的方案。

我是将主机别名与计算机名设置为同一个。例如计算机名为xxxxx-openSUSE，则主机名也设置为xxxxx-openSUSE。

**Comment by pyfile** [comment]
> > > > 很不幸，这两条我验证了之后发现对我来说都不行
> > > 
> > > 
> > > @pyfile 关于包管理器我可能需要补充一下：只要确认**libuuid1**与**mozilla-nss**安装后，就**不需要理会zypper或是YaST的警告**，因为它们只是机械索引安装包中的依赖表，只要打包时的依赖名不对openSUSE优化，这个警告就一直有。而YPM本身只会读取存在的uuid与nss库，包管理器的警告不会造成任何影响。每次安装时选择“断开”即可。
> > > 对于主机名，我可能写漏了，要添加的是**主机别名**，就是图上模糊的部分（可以从命令行`sudo yast2 host` 或界面 **YaST > 主机名** 进入）。从你前面发出的hosts来看，你并没有成功添加上。而我在本地测试将主机别名删掉后，YPM出现了和你一模一样的错误。如果可以的话，建议再次检查一下操作。第一次添加主机别名后，最好重启。
> > 
> > 
> > 非常感谢你的帮助，但事实上：
> > 
> > 1. 我确认了本机转了libuuid1和mozilla-nss,并且zypper安装release里提供的rpm包后，是通过忽略某些依赖的方式继续安装直至安装成功的
> > 2. 我在hosts里添加了主机别名了，现在我的hosts是这样的`127.0.0.1       localhost loopback`，我已经为127.0.0.1添加了名为"loopback"的主机别名，但是重启电脑后报错相同
> > 
> > 请问是你有采用什么特别的主机别名吗？
> > 如果这个方向没有可能有进展，后续有时间我研究一下上一个人向我提出的修改源码重新打包的方案。
> 
> 我是将主机别名与静态主机名保持一致。例如hostname为xxxxx-openSUSE，则主机别名也设置为xxxxx-openSUSE。
> 
> 可以分别查看`cat /etc/hostname` 和`cat /etc/hosts`的输出，看二者是否一致。
> 
> 静态主机名设置参见**YaST > 网络设置 > “主机名/DNS”选项卡**。

非常感谢，在我将电脑的localhost的主机别名与静态主机名设置为一致，并且重启后，我前面的bug就消失了

**Comment by pyfile** [comment]
不过我挺好奇是什么造成了能够用这种方法解决的bug

**Comment by memorydream** [comment]
> 不过我挺好奇是什么造成了能够用这种方法解决的bug


nodejs中的相关函数: `listen(port: number, hostname: string, callback?: () => void): http.Server;`

以下摘自[archlinux手册](https://man.archlinux.org/man/hostname.5)：
> •If the kernel commandline parameter systemd.hostname= specifies a valid hostname, [systemd(1)](https://man.archlinux.org/man/systemd.1.en) will use it to set the hostname during early boot, see [kernel-command-line(7)](https://man.archlinux.org/man/kernel-command-line.7.en),
•Otherwise, the "static" hostname specified by /etc/hostname as described above will be used.

> the static hostname has higher priority than a transient hostname, which has higher priority than the fallback hostname

看相关函数的签名，nodejs依赖hostname来解析ip地址，由于设置了静态主机名，所以使用了写入在`/etc/hostname`中的静态主机名

于是在`/etc/hosts`中需要一条解析主机名的记录，一般在`/etc/hosts`中都会有这样一条:
> 127.0.0.1 *myhostname*.localdomain *myhostname*

对应的含义为`ip地址 主机名 主机别名`

结合以上信息，该BUG产生的原因应该只是由于nodejs在解析hostname时找不到对应的ip地址，于是无法启动对应的server
