### ISSUE TITLE
无法真正实现hi-res级输出

### ISSUE THREAD

**Issue by ondineyuga** [qier222/YesPlayMusic#1643]
经测试，mac版，黑胶账号登陆，修改音质为hires，选择播放指定的hires音乐，电脑连接的输出DAC解码器识别为44kHz（此电脑我试过其他支持hires的app，是可以正确输出的，比如Audirvana）
同一首音乐，使用手机网易云音乐app，DAC输出解码，可以识别到48kHz。（网易云音乐目前mac版还未支持hi-res，所以暂时无法测试）
有大侠可以更进一下吗，如有需要我可以配合技术测试

**Comment by memorydream** [comment]
可能是html audio的限制，你能进tg来协助调查一下吗 https://t.me/yesplaymusic

**Comment by pan93412** [comment]
將 **電腦** 的聲卡採樣率提高到 48kHz 以上即可。
