### ISSUE TITLE
插队播放队列只能播放一首

### ISSUE THREAD

**Issue by luoling8192** [qier222/YesPlayMusic#1644]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端：客户端
- 浏览器名称或电脑操作系统：macOS 11.6
- 控制台 Console 页面的截图（按 F12 可打开控制台）

点了好几首插队播放，队列里面是有的，但是播放完以后以后，队列会被清空

**Comment by WhitLor** [comment]
我这边也发现，存在很久了，插队队列里是跳着播放的

**Comment by WhitLor** [comment]
我这边也发现，存在很久了，插队队列里是跳着播放的
