### ISSUE TITLE
Linux下每次最小化都会多一个通知栏图标

### ISSUE THREAD

**Issue by monkey-666** [qier222/YesPlayMusic#165]
Ubuntu 18.04
最小化一次，托盘的图标就多一个 ►►►►►
![2021-01-31 20-36-12屏幕截图](https://user-images.githubusercontent.com/55951742/106384272-e7690b80-6404-11eb-8da6-946d5e905734.png)

**Comment by qier222** [comment]
会尽快修复

**Comment by qier222** [comment]
v0.3.4 版本已经修复了
