### ISSUE TITLE
报错: The specified module could not be found

### ISSUE THREAD

**Issue by PurBlu** [qier222/YesPlayMusic#1651]
![image](https://user-images.githubusercontent.com/74239692/168957878-95b4fcde-3c58-4e9b-9ded-fb353a28bcd3.png)
系统是新安装的 缺环境？
启动程序便提示 无法看到主窗体 便携版安装版均复现

**Comment by memorydream** [comment]
#1624

**Comment by pan93412** [comment]
Duplicate of #1624
