### ISSUE TITLE
#bug#窗口变的特别小 暂时无法复现 重启正常

### ISSUE THREAD

**Issue by Flora-air** [qier222/YesPlayMusic#1669]
macOS 12.3.1 
最新版客户端
窗口非常奇怪的变小 如图 暂时无法复现这个BUG
大小似乎不受显示器缩放比例影响
强制退出后重启可以正常显示

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/62434508/170876455-0bf9f8e6-d7da-426c-8029-919e3fff395a.png">

<img width="160" alt="image" src="https://user-images.githubusercontent.com/62434508/170876543-57078be9-57a5-4946-9030-ea0cc0992852.png">
（看起来很模糊是区域截图出来 显示出来就很模糊 F12啥也看不清）

**Comment by pan93412** [comment]
有問題也歡迎再回報～
