### ISSUE TITLE
想请问网页版的demo页面为什么没有找到安装PWA的开关

### ISSUE THREAD

**Issue by RingingVolcano** [qier222/YesPlayMusic#168]
如题

**Comment by qier222** [comment]
不知道哪版开始就没按钮了，我排查看看问题在哪

**Comment by RingingVolcano** [comment]
> 不知道哪版开始就没按钮了，我排查看看问题在哪

emmmm现在好像还是没有

**Comment by qier222** [comment]
还没修复

**Comment by ennnnny** [comment]
@qier222 发现是没有注册service-worker.js导致没生效，将`src/registerServiceWorker.js`文件的if判断改成`或`就行，如下：
```js
if (
  process.env.NODE_ENV === "production" ||
  process.env.IS_ELECTRON === "undefined"
) {
```
示例网站：https://y.paomian.party/

BTW，网页版也可以灰歌曲换源，再加上PWA，其实不需要Electron了🙊

**Comment by qier222** [comment]
> @qier222 发现是没有注册service-worker.js导致没生效，将`src/registerServiceWorker.js`文件的if判断改成`或`就行，如下：
> 
> ```js
> if (
>   process.env.NODE_ENV === "production" ||
>   process.env.IS_ELECTRON === "undefined"
> ) {
> ```
> 
> 示例网站：https://y.paomian.party/
> 
> BTW，网页版也可以灰歌曲换源，再加上PWA，其实不需要Electron了🙊

谢谢提醒，搞了好👍
