### ISSUE TITLE
播放BUG

### ISSUE THREAD

**Issue by yashua77** [qier222/YesPlayMusic#1680]
客户端播放下一首，仅仅只有封面与歌词改变，音频还是上一首歌的

**Comment by yashua77** [comment]
Windows版本:windows10 64bit

**Comment by yashua77** [comment]
yesplay版本：0.4.5客户端单文件版    网页端没有类似情况

**Comment by yashua77** [comment]
![image](https://user-images.githubusercontent.com/106901281/172045226-11a464af-02a4-4930-9814-e83d54bca4f5.png)

**Comment by yashua77** [comment]
现在很影响体验，只能勉强去用官方的了，希望早日修复

**Comment by yashua77** [comment]
![屏幕截图 2022-06-05 182319](https://user-images.githubusercontent.com/106901281/172046106-f27895f3-4542-4b4e-9600-c3f230a38582.png)

**Comment by memorydream** [comment]
请问你尝试过`resetApp()`吗

**Comment by yashua77** [comment]
> 请你尝试过`resetApp()`吗

尝试resetApp( )后恢复正常，谢谢大大，支持yesplaymusic，希望越做越好！！
