### ISSUE TITLE
背景变成黑色，没有适应封面主色

### ISSUE THREAD

**Issue by laolu862** [qier222/YesPlayMusic#1681]
已经打开歌词显示背景，但没有适应专辑封面主色
客户端版本v0.4.5
操作系统win10专业版 版本号21H2
![屏幕截图 2022-06-05 212413](https://user-images.githubusercontent.com/72482029/172053111-410a2c1c-5bcd-4005-b196-a7a0cb44a45a.png)
![屏幕截图 2022-06-05 212656](https://user-images.githubusercontent.com/72482029/172053122-6c9da11c-aed5-4dbe-8302-209c25053e75.png)

**Comment by Theta405** [comment]
这个模糊封面开了嘛
![image](https://user-images.githubusercontent.com/50106454/172067391-299e79e0-9e22-4e50-9b8c-f56089a54a6b.png)

**Comment by memorydream** [comment]
Duplicate #1620
