### ISSUE TITLE
请问macbook air 2020 M1芯片的下载哪个文件呀，小白进去发现几十个压缩包。。。

### ISSUE THREAD

**Issue by soberest288** [qier222/YesPlayMusic#1684]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by memorydream** [comment]
https://github.com/qier222/YesPlayMusic/releases/download/v0.4.5/YesPlayMusic-mac-0.4.5-arm64.dmg

**Comment by soberest288** [comment]
Thank you very much.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月6日(星期一) 下午5:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qier222/YesPlayMusic] 请问macbook air 2020 M1芯片的下载哪个文件呀，小白进去发现几十个压缩包。。。 (Issue #1684)





 
https://github.com/qier222/YesPlayMusic/releases/download/v0.4.5/YesPlayMusic-mac-0.4.5-arm64.dmg
 
&mdash;
