### ISSUE TITLE
音频输出采样率被锁定为 48KHz，无法较好地播放 hi-res 资源

### ISSUE THREAD

**Issue by h0cheung** [qier222/YesPlayMusic#1690]
pipewire 已经过配置，在使用 Totem 等播放器播放本地 hi-res 资源时可以正常地以高采样率输出至耳放。

但使用 yesplaymusic 播放任何音频，输出采样率均不高于 48KHz。

可以使用该歌曲测试：
[Nicole - Don Ellis](https://music.163.com/song?id=534541039)

# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
客户端
- 浏览器名称或电脑操作系统
Fedora 36
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by memorydream** [comment]
html audio api限制，具体输出取决于操作系统设置
