### ISSUE TITLE
bug：网易云vip歌曲解析获取到的歌曲与原歌曲不一致

### ISSUE THREAD

**Issue by qiqizhel** [qier222/YesPlayMusic#1698]
mac客户端版本：v0.4.5
歌曲链接：https://music.163.com/song?id=406716666
这边实际听到的是周杰伦的本草纲目

**Comment by yashua77** [comment]
可以试一下reset()，我前几周也有类似问题

**Comment by qiqizhel** [comment]
@yashua77 请教下，如何reset有比较详细的介绍或者搜索关键字吗

**Comment by liukenny961** [comment]
> @yashua77 请教下，如何reset有比较详细的介绍或者搜索关键字吗

在主界面按F12，然后找到console（控制台），在console里输入reset()，然后刷新即可。
