### ISSUE TITLE
0.4.5在 win10 21H2版本下无法加载主页

### ISSUE THREAD

**Issue by PLX-Tar** [qier222/YesPlayMusic#1699]
使用0.4.5 客户端，在打开软件时提示
![image](https://user-images.githubusercontent.com/106828969/174106251-e185e5f7-dac0-48d7-95a1-32d076028210.png)
打开主界面后无法显示内容
![image](https://user-images.githubusercontent.com/106828969/174106399-96c95f30-cacd-440d-9aa8-afea9dc31c60.png)
在首页 发现 音乐库都没有内容显示
![image](https://user-images.githubusercontent.com/106828969/174106604-df1483bb-e2fe-43ab-bb58-04ecfac14fae.png)
![image](https://user-images.githubusercontent.com/106828969/174106727-f809dc2a-485e-4b88-94ab-b7bc721f420c.png)
![image](https://user-images.githubusercontent.com/106828969/174106773-656aaa9d-4ce6-4d9d-a217-d9633d159847.png)
![image](https://user-images.githubusercontent.com/106828969/174106829-0b3cf5ca-ff27-4c9d-b31f-5b3991852c97.png)
![image](https://user-images.githubusercontent.com/106828969/174106868-2ba94396-a3ea-4438-9afc-b3c8a5758094.png)
![image](https://user-images.githubusercontent.com/106828969/174106903-52538da4-1774-4fc1-bad7-f75dfcf52878.png)

**Comment by liukenny961** [comment]
YPM又有两周没有新的Action了,有又一些bug还没修……
是不是又懈怠了（手动狗头
@pan93412 @qier222

**Comment by pan93412** [comment]
> YPM又有两周没有新的Action了,有又一些bug还没修……
> 是不是又懈怠了（手动狗头
> @pan93412 @qier222

雖然我們非常重視 YesPlayMusic 使用者、貢獻者的體驗，但我們沒有不間斷貢獻一個無收益開源專案的義務。

你可以發 PR 或者是開個 Discussion 一起討論有意義的功能或問題，但這一句話讓我看得並不是很愉悅——即便有 sponsor，我們也有自己穩定的工作要做，也有自己想休息的時間啊！更何況我們內部也一直在開發 YPM 第二代版本。

**Comment by liukenny961** [comment]
> 雖然我們非常重視 YesPlayMusic 使用者、貢獻者的體驗，但我們沒有不間斷貢獻一個無收益開源專案的義務。
> 
> 你可以發 PR 或者是開個 Discussion 一起討論有意義的功能或問題，但這一句話讓我看得並不是很愉悅——即便有 sponsor，我們也有自己穩定的工作要做，也有自己想休息的時間啊！更何況我們內部也一直在開發 YPM 第二代版本。

十分抱歉，我可能表达上存在些问题，我也认同您的意见！
我想表达的意思只是，今天我也遇到了这个问题，现在YPM已经无法正常使用。
我并不太懂软件开发方面，毕竟我也不是干这行的，只是在我看来，维持一个软件能最基本使用可能是最基本的要求？
还是再次说一句十分抱歉！我也不是有意的……🙁

**Comment by PLX-Tar** [comment]
目前已可正常使用，issuse

**Comment by PLX-Tar** [comment]
目前已可正常使用
