### ISSUE TITLE
发现一个小Bug

### ISSUE THREAD

**Issue by cxwht** [qier222/YesPlayMusic#17]
在歌单播放播放的时候 如果下一首是灰色的歌曲，那么不会自动跳过，然后好像点击下一首的按钮还会记住本个的位置，再按一次上一首，又是这首。可以改改，自动跳过灰色歌曲变成下一首

**Comment by qier222** [comment]
这个之前已经修复了，访问demo还有问题的话，请尝试刷新浏览器缓存。
