### ISSUE TITLE
客户端首页/发现/音乐库 均为白屏（空白页面

### ISSUE THREAD

**Issue by screaminrain** [qier222/YesPlayMusic#1705]
![image](https://user-images.githubusercontent.com/99682059/174623439-907b012a-634e-4463-85db-cff791bbd66b.png)

![image](https://user-images.githubusercontent.com/99682059/174623647-2e2a6bf3-b2b0-4f6f-9e32-0c6857e87379.png)
![image](https://user-images.githubusercontent.com/99682059/174641360-7eabb183-cf30-49ca-a342-4990d942b957.png)

**Comment by liukenny961** [comment]
可尝试resetApp()

**Comment by screaminrain** [comment]
不知道是不是跟我网易云解锁音乐的插件有冲突

**Comment by ImTopz** [comment]
如果开了代理 需要设置一下proxy

**Comment by sexyfeifan** [comment]
> 如果开了代理 需要设置一下proxy

我是在本地nas上搭建遇到了一样的问题，本地ip加端口一切正常，域名加端口号以及反代后空白，您指的设置proxy是宿主这个docker让它不走代理，这个意思吗？
