### ISSUE TITLE
播放歌曲时异常使用了上一首歌的缓存

### ISSUE THREAD

**Issue by Xionghaizi001** [qier222/YesPlayMusic#1711]
1. 这是一个bug
2. 具体表现：如果网络状况不佳（高延迟或在加载歌曲时突然中断），软件有时（40%）会使用上一首歌的缓存进行播放，此时可以观察到歌词与演唱内容不对应，且歌词会在过后的某一时刻卡住不动
3. 临时解决方法：出现此故障时清除缓存，切换上一首再切换下一首即可解决

**Comment by Xionghaizi001** [comment]
不知道[#1710 ](https://github.com/qier222/YesPlayMusic/issues/1710)中提到的bug是不是和我这个一样

**Comment by x13771944402** [comment]
我这儿一卡顿就是唱本草纲目，词却对着。

**Comment by JustZiya** [comment]
本草纲目 +1

**Comment by WhitLor** [comment]
> 1. 这是一个bug
> 2. 具体表现：如果网络状况不佳（高延迟或在加载歌曲时突然中断），软件有时（40%）会使用上一首歌的缓存进行播放，此时可以观察到歌词与演唱内容不对应，且歌词会在过后的某一时刻卡住不动
> 3. 临时解决方法：出现此故障时清除缓存，切换上一首再切换下一首即可解决

我这边只要遇到了，无论怎么切歌，只要切回这一首都是本草纲目，reset之后再找这首歌播放，也还是本草纲目
