### ISSUE TITLE
启用Unblock后因vip和版权下架的歌 如Xenogenesis 播放后显示还是Xenogenesis但是会播放周杰伦的本草纲目，大部分是本草纲目，一小些歌会变成别的但都是固定的

### ISSUE THREAD

**Issue by 2845461830** [qier222/YesPlayMusic#1713]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by ZhanYiHui119** [comment]
同问题+1，而且有很多网易云有版权的歌也会匹配错音源

**Comment by liukenny961** [comment]
可以resetApp()
