### ISSUE TITLE
总匹配成百草纲目，请求修复

### ISSUE THREAD

**Issue by ublock-ghost** [qier222/YesPlayMusic#1720]
很多歌昨天还能听，今天就听不了，或者匹配成百草纲目

**Comment by liukenny961** [comment]
去Action里找，Action里修复了这个问题

**Comment by pan93412** [comment]
[f9e6164](https://github.com/qier222/YesPlayMusic/commit/f9e6164245256bf8639eba046951f1a41d65c1a0) resolved
