### ISSUE TITLE
Windows平台   软件进去几乎占满整个屏幕 

### ISSUE THREAD

**Issue by wuqingsix** [qier222/YesPlayMusic#173]
Windows平台   软件进去几乎占满整个屏幕 希望改进大小或者增加记忆窗口大小 每次进软件都要重新调，不是很方便
谢谢作者

**Comment by qier222** [comment]
记住窗口大小这个功能是有的，但是出bug了，会尽快修复

**Comment by wuqingsix** [comment]
好的 感谢

**Comment by 17305879117** [comment]
> 记住窗口大小这个功能是有的，但是出bug了，会尽快恢复

是还没有修复吗
