### ISSUE TITLE
网页版手机号登陆和邮箱登录无效

### ISSUE THREAD

**Issue by StandGreat** [qier222/YesPlayMusic#1730]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 网页版
- edge浏览器
- 
![image](https://user-images.githubusercontent.com/95478133/178612878-7f6a1c97-d3a7-4e59-a383-6db34967b9a4.png)

**Comment by liukenny961** [comment]
据说网页端的服务器IP被网易给封了)

**Comment by pan93412** [comment]
Duplicate of #1702
