### ISSUE TITLE
自定义安装路径文件夹，缓存路径文件夹

### ISSUE THREAD

**Issue by NEARWN** [qier222/YesPlayMusic#1735]
可否自定义安装路径文件夹，缓存路径文件夹，谢谢

**Comment by RekkimiARG** [comment]
同支持，c盘要炸了

**Comment by SkinAir** [comment]
> 同支持，c盘要炸了

可以找到目录直接ctrl+x移走，然后把桌面的图标换一下位置就行了（或者从新添加快捷方式）...

**Comment by pan93412** [comment]
Duplicate of #558
