### ISSUE TITLE
歌曲<归去来>匹配问题

### ISSUE THREAD

**Issue by wabxn514** [qier222/YesPlayMusic#1736]
使用单文件版本[YesPlayMusic-0.4.5.exe]
播放网易云音乐歌曲 <归去来 1995年TVB版电视剧《神雕侠侣》内地发行版主题曲 > [https://music.163.com/#/song?id=5276250]
匹配出来的是一首很难听的，绝对不是胡兵版本的歌曲，这首歌在网易云音乐是[VIP尊享]，所以是不是从各类音源中匹配出了个有问题的版本，还想请问哪儿能看到他匹配的是什么音源的哪首歌？

**Comment by Lew1s777** [comment]
这是[UnblockNeteaseMusic](https://github.com/UnblockNeteaseMusic/server)的问题

**Comment by pan93412** [comment]
Duplicate of #1720
