### ISSUE TITLE
希望增加外置滚动歌词显示（置顶），这样在用别的软件的时候也能看到歌词了！谢谢！

### ISSUE THREAD

**Issue by shiquda** [qier222/YesPlayMusic#1737]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by liukenny961** [comment]
应该是暂无计划支持外置歌词滚动显示.
可以使用https://github.com/shih-liang/YesPlayMusicOSD版本,这个版本有外置滚动歌词,但是这个版本已经许久没有更新,应该会有许多bug.

**Comment by AuroraRock** [comment]
可以用这个https://github.com/cnbluefire/HotLyric

**Comment by shiquda** [comment]
> 可以用这个https://github.com/cnbluefire/HotLyric

好的，谢谢分享！

**Comment by pan93412** [comment]
> 应该是暂无计划支持外置歌词滚动显示.
> 可以使用https://github.com/shih-liang/YesPlayMusicOSD 版本,这个版本有外置滚动歌词,但是这个版本已经许久没有更新,应该会有许多bug.

沒有許久沒更新吧，看起來有跟到上游的 commit。
