### ISSUE TITLE
增加自定义缓存目录功能

### ISSUE THREAD

**Issue by LabmenNo001** [qier222/YesPlayMusic#175]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by qier222** [comment]
暂时不确定要不要做这个功能，目前的缓存是使用indexedDB实现的，改的话需要改挺多逻辑。

**Comment by LabmenNo001** [comment]
> 临时不确定要不要做这个功能，当前的缓存是使用 indexedDB 实现的，改的话需要改挺多逻辑。

下载功能可以吗？

**Comment by qier222** [comment]
> > 临时不确定要不要做这个功能，当前的缓存是使用 indexedDB 实现的，改的话需要改挺多逻辑。
> 
> 
> 
> 下载功能可以吗？

暂时不打算做下载功能

**Comment by RebirthEgo** [comment]
> > 临时不确定要不要做这个功能，当前的缓存是使用indexedDB实现的，改的话需要改挺多逻辑。
> 
> 下载功能可以吗？

缓存里的文件复制出来改一下后缀名就可以了，等同下载

**Comment by jerryzcl** [comment]
> > > 临时不确定要不要做这个功能，当前的缓存是使用indexedDB实现的，改的话需要改挺多逻辑。
> > 
> > 
> > 下载功能可以吗？
> 
> 缓存里的文件复制出来改一下后缀名就可以了，等同下载

缓存文件在哪里？

**Comment by curiosity654** [comment]
> 暂时不确定要不要做这个功能，目前的缓存是使用indexedDB实现的，改的话需要改挺多逻辑。

我也建议考虑一下，现在缓存占了C盘好几个G QAQ

**Comment by muzhi621** [comment]
建议考虑下，C盘的固态就那么大，没多久缓存文件夹就几个G了，强烈建议更改缓存文件位置，或者修改默认到安装文件夹，或者自动在D盘创建一个目录用作缓存文件夹位置

**Comment by rampageX** [comment]
目录连接点，符号链接，不难

**Comment by lonznt** [comment]
> > > > 临时不确定要不要做这个功能，当前的缓存是使用indexedDB实现的，改的话需要改挺多逻辑。
> > > 
> > > 
> > > 下载功能可以吗？
> > 
> > 
> > 缓存里的文件复制出来改一下后缀名就可以了，等同下载
> 
> 缓存文件在哪里？

同问。😛
