### ISSUE TITLE
音乐库界面空白，播放卡顿

### ISSUE THREAD

**Issue by Asthestarsfalll** [qier222/YesPlayMusic#1757]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://user-images.githubusercontent.com/72954905/181879687-1391b32b-5c7e-4bf0-aafa-2246d65a08bf.png)
播放很卡很卡很卡很卡很卡很卡，经常放不出

**Comment by shenghuang147** [comment]
这不是解决方法，只是提供一个参考

我使用的是 `OpenSuse` 也遇到类类似的问题;
我的原因是因为我修改了 `hostname` 但是没有在中 `hosts` 添加解析记录，导致无法将我的 `hostname` 解析到 `127.0.0.1`

我是参考了这个 [issues](https://github.com/qier222/YesPlayMusic/issues/1637#issuecomment-1139360607)
