### ISSUE TITLE
音量调节不能立即生效

### ISSUE THREAD

**Issue by KomiMoe** [qier222/YesPlayMusic#1765]
问题描述：音量调节后立即生效的效果很小。当音乐暂停并继续播放后完全生效
复现：使用10%音量播放歌曲，将音量调节到100%。发现效果不显著。（暂停音乐后继续播放）或（切换到下一首）音量会猛增到100%。
操作系统：Windows 10 LTSC 2021
控制台（似乎与此问题无关）：![alt text](https://i.imgur.com/66PajzL.png)

**Comment by YunfangHou** [comment]
macOS 同样有这个问题。

**Comment by ZhanYiHui119** [comment]
win10 Pro也有一样的问题

**Comment by KomiMoe** [comment]
#1830 fixed this issue
