### ISSUE TITLE
希望可以适配KDE媒体播放器控件

### ISSUE THREAD

**Issue by abc66099** [qier222/YesPlayMusic#177]
希望可以适配KDE的媒体播放器控件。

如下图所示：
![image](https://user-images.githubusercontent.com/35481897/106426653-f69d9700-64a0-11eb-867b-81c80390b6fc.png)

这个是目前播放时的状态：
![image](https://user-images.githubusercontent.com/35481897/106426872-51cf8980-64a1-11eb-809b-c33414465c7b.png)

**Comment by qier222** [comment]
electron文档没有相关的适配方法，网上也搜不到相关的资料，没办法适配。
