### ISSUE TITLE
海外用户无法播放

### ISSUE THREAD

**Issue by Pythonming2020** [qier222/YesPlayMusic#178]
坐标法国，在法国使用客户端，苹果操作系统。

[https://imgur.com/ZiIMpmb](url)

**Comment by waterhydroxyl** [comment]
网易云海外确实没版权，挂回国梯才行

**Comment by qier222** [comment]
所有歌曲都没办法播放吗

**Comment by waterhydroxyl** [comment]
> 所有歌曲都没办法播放吗
> 

你试试原版网易云呗，海外就用spotify或者yt music吧，体验也不错的。

**Comment by waterhydroxyl** [comment]
版权限制问题用UnblockNeteaseMusic就行了吧

**Comment by Pythonming2020** [comment]
> 版权限制问题用UnblockNeteaseMusic就行了吧

谢谢，用了全局代理脚本就解决了

**Comment by Ahgni** [comment]
> > 版权限制问题用UnblockNeteaseMusic就行了吧
> 
> 谢谢，用了全局代理脚本就解决了

请教您可以分享一下是如何全局代理脚本解决的呢？谢谢
