### ISSUE TITLE
不能用了

### ISSUE THREAD

**Issue by liuxiaoqigui** [qier222/YesPlayMusic#1785]
m1 打不开了 音乐也没法播放了<img width="1357" alt="image" src="https://user-images.githubusercontent.com/30720244/186796194-b80d0875-09da-49f6-a393-eb7ea6ac9900.png">

**Comment by PLXT** [comment]
清除缓存试一下
按 f12 在控制台用`resetApp()`
控制台没反应就手动清除一下，我用 AppCleaner 很方便，勾选除了 app 以外的东西清除就可以
<img width="626" alt="image" src="https://user-images.githubusercontent.com/26758820/187162785-abc7e66a-a62a-422e-a8b2-9acc84f51a4c.png">

**Comment by liuxiaoqigui** [comment]
可以了 谢谢谢谢
