### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by KoyamaCN** [qier222/YesPlayMusic#179]
坐标日本，网络为softbank，系统为Windows20H2 19042.746。使用客户端0.3.3版本，手机号登录失败，密码账号均为正确。
![屏幕截图 2021-02-01 164804](https://user-images.githubusercontent.com/58129779/106431437-96165600-64b0-11eb-889b-0fac0091f09b.jpg)

**Comment by qier222** [comment]
这个错误是请求时间超过了15秒，然后被停止了，我看不出来是什么问题，建议你换个网络环境试试。

**Comment by zeerdeer** [comment]
我也是这样，大陆
