### ISSUE TITLE
本地开发环境下，登录账号会无法跳转到 library 页面

### ISSUE THREAD

**Issue by hawtim** [qier222/YesPlayMusic#18]
输入账号密码后点击登录报错。
![image](https://user-images.githubusercontent.com/11072796/96398509-a0ad2800-11fe-11eb-89de-fc7fc2b7d9db.png)
尝试之后发现是 requireLogin 的问题
登录后 Cookies.get("MUSIC_U") === undefined && Cookies.get("loginMode") === "account" 条件满足，跳回登录页面
 
![image](https://user-images.githubusercontent.com/11072796/96398603-d520e400-11fe-11eb-8425-eee37c9b35f3.png)

![image](https://user-images.githubusercontent.com/11072796/96399380-cb987b80-1200-11eb-94cb-e1be94a73f3e.png)

由于不清楚 MUSIC_U 的作用，故发 issue。

**Comment by hawtim** [comment]
在 afterLogin 里设置了该 cookies 可以正常运行。
![image](https://user-images.githubusercontent.com/11072796/96400122-8d9c5700-1202-11eb-94fb-365362c662b3.png)

**Comment by qier222** [comment]
你可以用nginx反代搭建开发环境，我的开发域名是 http://mac.local，网易云api是 http://mac.local/api，这样就不会有跨域问题。
