### ISSUE TITLE
增加点击关闭窗口按钮后最小化的功能

### ISSUE THREAD

**Issue by GoogleCodes** [qier222/YesPlayMusic#180]
软件关闭后就直接关闭了，没有最小化?

**Comment by abc66099** [comment]
设置里面开这个
![image](https://user-images.githubusercontent.com/35481897/106433582-5bf68580-64ab-11eb-821e-13b6e296932c.png)

**Comment by GoogleCodes** [comment]
> 设置里面开这个
> ![image](https://user-images.githubusercontent.com/35481897/106433582-5bf68580-64ab-11eb-821e-13b6e296932c.png)

没有设置按钮是不是版本太低了?
![1612173223(1)](https://user-images.githubusercontent.com/23470846/106442838-bcd78b00-64b6-11eb-9d5d-f5406a87daf2.jpg)

**Comment by abc66099** [comment]
在这里
![image](https://user-images.githubusercontent.com/35481897/106449020-7e45ce80-64be-11eb-9411-40c00afc9f02.png)
