### ISSUE TITLE
与 archlinux flac 1.4.0-1 包不兼容导致无法启动

### ISSUE THREAD

**Issue by txyyh** [qier222/YesPlayMusic#1810]
## 表现
无法启动客户端，命令行启动显示如下报错
/usr/lib/electron13/electron: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory

## 猜想
archlinux 的 flac 1.4.0 包[换用了libFLAC.so.12](https://archlinux.org/todo/flac-140/)，客户端仍然在依赖原 libFLAC.so.8 导致依赖错误

## 环境
archlinux latest (2022.9.19 10:27)

[yesplaymusic-electron-git](https://aur.archlinux.org/packages/yesplaymusic-electron-git) 0.4.5.r30.g9fcb6da-1
or
[yesplaymusic-electron](https://aur.archlinux.org/packages/yesplaymusic-electron) 0.4.5-1

[flac](https://archlinux.org/packages/extra/x86_64/flac/) 1.4.0-1

[electron13](https://aur.archlinux.org/packages/electron13) 13.6.9-3

**Comment by zhanghua000** [comment]
解决办法应该是这边更新 electron 到 17 及以上的版本，因为现在 Arch 官方支持的 electron 最低版本应该是 17。如果这边不能更新的话，就只有用新的 flac 编译 electron13 了。看这个[重新编译计划](https://archlinux.org/todo/flac-140/)的话所有相关软件包都已经完成基于新版 flac 的二次编译了，所以重新编译 electron13 应该不会有啥大问题

**Comment by pan93412** [comment]
Blocking: #1166。原則上只能請 Arch 的志願打包者幫忙重新編譯 Electron 13 了。

**Comment by txyyh** [comment]
> Blocking: #1166。原則上只能請 Arch 的志願打包者幫忙重新編譯 Electron 13 了。

我去 AUR 问问

**Comment by zhanghua000** [comment]
AUR 只提供构建脚本，重新构建的任务应该是你自己来完成（

**Comment by txyyh** [comment]
aur/yesplaymusic 与 aur/yesplaymusic-git 无错误
Close issue
