### ISSUE TITLE
部署在服务端的网站用ssl打开很慢

### ISSUE THREAD

**Issue by xmengnet** [qier222/YesPlayMusic#182]
### 我在服务端部署成功了，但是我想设置成https的，于是就添加了证书，但是添加后打开网页速度变得很慢，不添加的时候正常。

- 你可以试试打开我的网站看看：http://music.xmengnet.cn 
- 添加ssl的网站：https://music.xmengnet.cn 
- 使用的好几个浏览器，chrome,brave还有手机浏览器，打开都很慢，而且不管是http还是https都不能登陆，邮箱和手机号都不行
- 只能使用搜索帐号登陆，使用的是php7.3
- 希望您能提供一个解决方法！感谢！

**Comment by GoogleCodes** [comment]
请问一下你的 nodejs是什么版本的？我下载的依赖貌似不成功！=。=

**Comment by xmengnet** [comment]
@GoogleCodes node版本v15.7.0 npm版本6.14.11

**Comment by qier222** [comment]
看了下，https慢是因为你的网易云api用的是http，http请求都被chrome block了

**Comment by qier222** [comment]
建议用nginx将api反代到https://music.xmengnet.cn/api ，这样就不会有跨域问题

**Comment by xmengnet** [comment]
@qier222 好的，我试试
