### ISSUE TITLE
所有的播放都无反应

### ISSUE THREAD

**Issue by ayasa520** [qier222/YesPlayMusic#1834]
1. 使用最新的 v0.4.5, 官方仓库和 appimage 均尝试过
2. 系统信息
```
OS: Manjaro Linux x86_64 
Kernel: 6.0.2-zen1-1-zen 
DE: GNOME 42.5 
WM: Mutter
```
3. 截图
![image](https://user-images.githubusercontent.com/55699692/200180876-6371a791-adb0-437b-858b-36bbff505ede.png)
![image](https://user-images.githubusercontent.com/55699692/200180977-294acb65-ea7e-4d46-8337-64685b3675da.png)

之前它在我的电脑上运行良好, 但自从我不知升级了什么之后, 所有的播放均无法工作

**Comment by debug16** [comment]
接口挂了 要验证 自己部署吧
