### ISSUE TITLE
希望把客户端设置按钮换个位置，例如放到右上角什么的

### ISSUE THREAD

**Issue by Captpricelsy** [qier222/YesPlayMusic#185]
如题，这样方便些，不用每次要设置就要跳到音乐库再点一遍

**Comment by bxh201** [comment]
+1，转了一圈没找到设置按钮，原来需要登录。

**Comment by shenzhuoyan** [comment]
原来设置在这里，找了一圈没找到

**Comment by chencao187** [comment]
这是我见过的最隐蔽的设置按钮， 没有之一

**Comment by komichiaya** [comment]
确实，上个版本的设置还是在首页最下面 现在移到用户信息旁边的小箭头我是没想到的，，，

**Comment by KlyingSys** [comment]
好家伙，我终于找到设置了。这个设置实在太隐秘了

**Comment by qier222** [comment]
v0.3.5 版本移动了设置的位置，现在应该很容易找到了。
