### ISSUE TITLE
【Windows10】【客户端】当前歌词圆角错误，右侧没有圆角

### ISSUE THREAD

**Issue by Lincope** [qier222/YesPlayMusic#1850]
当前歌词右侧无圆角
![批注 2022-11-22 223207](https://user-images.githubusercontent.com/81073939/203340918-6721cda5-6e11-4c4d-b058-34ee38194f98.png)
其他歌词圆角显示正常
![批注 2022-11-22 223233](https://user-images.githubusercontent.com/81073939/203340940-7a75c6cc-46eb-40b7-8f06-2b6e3f7ee0fe.png)

**Comment by pan93412** [comment]
已經修正了，只是還沒發版。

@qier222 應該可以發 0.4.6 了。

**Comment by HuanLinMaster** [comment]
我是菜鸡 请问在哪打开歌词(Electron v0.4.5)

**Comment by Linco-me** [comment]
> 已經修正了，只是還沒發版。
> 
> @qier222 應該可以發 0.4.6 了。

话说真的好久没有更新了。
