### ISSUE TITLE
mac 0.4.5 可登录 歌单、播放栏空板

### ISSUE THREAD

**Issue by assguard** [qier222/YesPlayMusic#1853]
<img width="1323" alt="截屏2022-11-26 23 01 38" src="https://user-images.githubusercontent.com/87989363/204095494-ea3d4dd3-6bc8-4ba9-8515-be47a0469ac6.png">
如图，不可播放音乐，大佬求解！！

**Comment by NuruiSa** [comment]
控制台用resetApp()清除缓存 我是这样解决的 你可以试试看

**Comment by assguard** [comment]
谢谢大佬 成了！！
