### ISSUE TITLE
部署至 Vercel，可以听歌，可以扫码登录，不能用网易邮箱登录。

### ISSUE THREAD

**Issue by Maogxer** [qier222/YesPlayMusic#1855]
提示 用户名和密码错误。

**Comment by danboruzhi** [comment]
为啥我连扫码都不能登录，用搜索账号账号登录后library页好像是400还是404的。这个网页版是不是已经不维护了？

**Comment by Maogxer** [comment]
是 [NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi) 的问题，作者已经修复了。
