### ISSUE TITLE
vercel部署后无内容

### ISSUE THREAD

**Issue by lifeafter619** [qier222/YesPlayMusic#1862]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息
vercel完成部署后没有内容
![image](https://user-images.githubusercontent.com/65111206/206831630-3c14d9e2-cd76-4779-b6e4-07f57fba50c5.png)
控制台报错
![VeryCapture_20221210134930](https://user-images.githubusercontent.com/65111206/206831688-33950d33-8bb1-47b4-adf4-be3957a20af3.jpg)

- 用的是网页版还是客户端：vercel部署的网页端
- 浏览器名称或电脑操作系统：edge，win10
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by GrassBlock1** [comment]
api 没部署好，你看看部署的时候 env 文件里面的api地址

**Comment by lifeafter619** [comment]
如您所见，我的api部署没有问题
![Snipaste_2022-12-19_19-03-51](https://user-images.githubusercontent.com/65111206/208412140-8893c249-3640-496b-8907-721ad2ca253b.png)
请问我通过vercel部署的需要配置.env吗？我按照文档配置了vercel.json并添加了环境变量
![image](https://user-images.githubusercontent.com/65111206/208412668-0e40b680-1706-43ee-acf5-960e6c614c22.png)

**Comment by Zikinn** [comment]
您好，请问您解决了吗，看您给 issue 关了

**Comment by lifeafter619** [comment]
> 您好，请问您解决了吗，看您给 issue 关了

是的，可能是您的api地址被网易屏蔽过，可尝试使用其它可用的api地址就正常了，如更换vercel部署地点和域名，使用默认域名好像就可以

**Comment by Zikinn** [comment]
> > 您好，请问您解决了吗，看您给 issue 关了
> 
> 是的，可能是您的api地址被网易屏蔽过，可尝试使用其它可用的api地址就正常了，如更换vercel部署地点和域名，使用默认域名好像就可以

好的，感谢，我去试试
