### ISSUE TITLE
web端缺少2个svg文件

### ISSUE THREAD

**Issue by heycmm** [qier222/YesPlayMusic#187]
文件夹位置：
https://github.com/qier222/YesPlayMusic/tree/master/src/assets/icons
对应代码：
https://github.com/qier222/YesPlayMusic/blob/236075a1f89b9871735c10ec010c00ec8b448183/src/views/lyrics.vue#L139

https://github.com/qier222/YesPlayMusic/blob/236075a1f89b9871735c10ec010c00ec8b448183/src/components/Player.vue#L142

svg来源
https://www.iconfinder.com/icons/186407/arrow_up_icon
https://www.iconfinder.com/icons/186411/arrow_down_icon

**Comment by qier222** [comment]
我本地是有的，不知道为什么仓库里没有

**Comment by heycmm** [comment]
大概是没有提交上来吧
