### ISSUE TITLE
[Bug] Support for secondary directory deployment

### ISSUE THREAD

**Issue by ain-soph** [qier222/YesPlayMusic#1872]
## 问题描述 / Issue Description
The web could be used normally after deploying at 3310 port, and I use nginx to proxy_pass to a secondary directory `https://192.168.1.2/yesplaymusic/`. I could still visit the port `https://192.168.1.2:3310` normally, but will get a blank page if I visit `https://192.168.1.2/yesplaymusic/`.

网页端部署在3310端口后，我通过nginx转发到二级目录`https://192.168.1.2/yesplaymusic/`。访问端口`https://192.168.1.2:3310`可以正常使用，但是访问`https://192.168.1.2/yesplaymusic/`打开的是空白网页。

## 原因分析 / Reason Analysis
原因是html里面的静态文件链接错误（详情看最后的截图）。因为使用了绝对路径，导致二级目录被无视了。

例如，`<link href="/css/chunk-21dfbee4.7c372010.css" rel="prefetch">`
    - **实际：**`https://192.168.1.2/css/chunk-21dfbee4.7c372010.css`。
    - **期望：**`https://192.168.1.2/`**`yesplaymusic/`**`css/chunk-21dfbee4.7c372010.css`。

## 解决方法 / Solution
我希望既能通过端口访问也能通过二级目录访问，所以只需要把最前面的斜杠去掉变成相对路径即可。
- **当前：**`"/css/chunk-21dfbee4.7c372010.css"`
- **修改：**`"css/chunk-21dfbee4.7c372010.css"`
（只是个例子，需要修改html里的所有绝对路径，和用到的JS里面也可能出现的绝对路径）

## 补充材料 / Complemental Material
1. Console Screenshot
    <img width="487" alt="image" src="https://user-images.githubusercontent.com/13214530/209232500-073fa601-b770-4d75-9826-02cc6c42cb15.png">

2. 网易云音乐API可以正常运行，因为用的都是相对路径：
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/13214530/209273090-fc6a89e1-3720-4328-bc35-665d3fea796b.png">

**Comment by ain-soph** [comment]
研究了一下，好像没什么好的解决办法。我之前提的应该也不行。
最后只能使用二级域名而不是二级目录了。

**Comment by jinghuashang** [comment]
> 研究了一下，好像没什么好的解决办法。我之前提的应该也不行。 最后只能使用二级域名而不是二级目录了。

你可以将html文件内的文件路径改成/yesplaymusic/css/chunk-21dfbee4.7c372010.css，或者用nginx内的伪静态修改文件链接

**Comment by jinghuashang** [comment]
> 研究了一下，好像没什么好的解决办法。我之前提的应该也不行。 最后只能使用二级域名而不是二级目录了。

虽然解决了文件加载的问题，但是还是不能代理到二级目录
![](https://download.tooc.xlj0.com/uploads/56/%E5%B1%8F%E5%B9%95%E5%BD%95%E5%88%B6%202023-11-09%20195214.mp4)
