### ISSUE TITLE
客户端和网页端使用密码无法登录

### ISSUE THREAD

**Issue by shiquda** [qier222/YesPlayMusic#1879]
![image](https://user-images.githubusercontent.com/104683621/210029217-59c16d34-ff80-4c58-89e8-d65239a57ebf.png)
点击登陆后无反应

**Comment by Maogxer** [comment]
更新[Binaryify/NeteaseCloudMusicApi](https://neteasecloudmusicapi.vercel.app/#/?id=%e5%ae%89%e8%a3%85)
