### ISSUE TITLE
前进后退的逻辑问题

### ISSUE THREAD

**Issue by Yansongsongsong** [qier222/YesPlayMusic#188]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
  - 新issue
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）
  - 无
### 反馈 bug 需要的信息

- 网页版 & 客户端
- edge & windows
- 控制台 Console 页面的截图（按 F12 可打开控制台）

现在的实现有点像是把page url history 用一个全局的队列进行存储，然后进行前进和后退的控制，实际在使用的过程中，前进后退的跳转会让人迷惑。
比较合理的操作应当是类似于
{最终页：主页} -- {一级页：发现/音乐库}  -- {二级页：歌曲页面/歌单页面/搜索页}
每一级页面应该可以相互替换，而不是纯url history这样，，感觉这样跳转有点乱

**Comment by qier222** [comment]
没理解“跳转有点乱”这个问题

**Comment by Yansongsongsong** [comment]
emmm
我尝试举个例子，来说明记录url history做跳转可能存在的问题是什么
1. 我打开app   queue: [首页]
2. 我点击音乐库 显示登陆 queue: [首页，登录页面]
3. 登陆后音乐库 queue [首页，登陆页面，带token的音乐库]

这个时候点返回 会出现输入账号密码进行登录的登录页面。这样感觉是不合理的，，

除此之外，同级页面的跳转给人的感觉也有点乱。理论上到了首页就应该再后退了，到底了，，但是纯url history base就能从首页跳到其他地方。这就很奇怪来着。我尝试找一个原型来进行说明

**Comment by qier222** [comment]
Mac端的网易云也是跟我这个一样的逻辑。
不过网易云的登录是弹窗登录而不是一个页面，所以不存在返回到登录页面的问题，除此之外逻辑都是一样的。

**Comment by Yansongsongsong** [comment]
我了解了，，我还是拿手机端的操作逻辑来套桌面端的逻辑了。。
赞一下👍 repo做的很棒！

**Comment by qier222** [comment]
> 我了解了，，我还是拿手机端的操作逻辑来套桌面端的逻辑了。。
> 赞一下👍 repo做的很棒！

感谢支持
