### ISSUE TITLE
新特性建议：播放列表增加预读功能

### ISSUE THREAD

**Issue by ZzMark** [qier222/YesPlayMusic#189]
> 不清楚与 Project 中的 [增加歌曲切换的中间状态] 是否为同一个功能，如果是请直接关掉。

播放列表中的音频，增加一个预读的功能，播放这一首的时候，预读一下另外一首，这样能让切换更加快速

这个功能还可以有一个弱化版本，就是换歌的时候，先暂停当前的播放，等待网络响应。
现在的版本是点击了【下一首】还在播放当前的音乐，需要等网络响应才会真的切换，这样感受不到这次按钮是否点击成功

**Comment by qier222** [comment]
很不错的建议，预加载下一首的功能已加入todo

**Comment by qier222** [comment]
已经支持了
