### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by pkwenda** [qier222/YesPlayMusic#19]
![image](https://user-images.githubusercontent.com/14212375/96422959-49717c80-122b-11eb-929d-0fd8dfe8f67e.png)
![image](https://user-images.githubusercontent.com/14212375/96422979-4f675d80-122b-11eb-9e78-ed5e666903a0.png)

楼主是怎么解决这个问题的？

如果我用 nginx 的话，api 没有固定前缀，写起规则也很麻烦

https://github.com/Binaryify/NeteaseCloudMusicApi/issues/45

**Comment by qier222** [comment]
这是我的nginx配置

```
server {
    listen          80;
    server_name     mac.local;

    location / {
        proxy_pass http://127.0.0.1:8080;
    }

    location /api {
        rewrite  ^.+api/?(.*)$ /$1 break;
        proxy_pass  http://127.0.0.1:3000;    #node api server
        proxy_redirect off;
    }
}

```

**Comment by pkwenda** [comment]
@qier222 ok 谢谢 0.0

**Comment by pkwenda** [comment]
![image](https://user-images.githubusercontent.com/14212375/96440574-c1936e80-123a-11eb-86c6-621fd6ca2ae6.png)

```
location /api
```

请教一下 api 从何处来的，代码里面没有看到，也代理不过去呀

**Comment by pkwenda** [comment]
明白楼主什么意思了，给后人解释一下，NeteaseCloudMusicApi 这个 API 设计的有问题，没有前缀
@qier222 作者因该是在 request.js 加了个前缀 ："api"
利用 nginx：rewrite 模式重写了 URL 去掉了 /api ，达到统一前缀的目的。
