### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by Pitter-Patter** [qier222/YesPlayMusic#190]
1.设置位置放的更明显些
2.点左下角正在播放的封面直接弹出歌词页面而不是专辑页
3.快捷键
4.一些字体样式和大小

**Comment by qier222** [comment]
点击左下角正在播放歌曲的封面打开歌词页是网易云的逻辑，我这边准备保持使用自己的逻辑，在歌单内的歌曲列表、歌手页的热门歌曲列表、搜索页的歌曲列表里点击专辑封面都会跳转到专辑页面。
