### ISSUE TITLE
设置模块的位置及若干建议

### ISSUE THREAD

**Issue by wannaAC** [qier222/YesPlayMusic#191]
说真的找了好久才找到设置，那个小箭头太太太不显眼了，建议把设置单独拿出来
我是因为默认不是深色模式，为了切换深色模式找的设置，不过切换完发现导航栏还是白色的，就很突兀。。
![image](https://user-images.githubusercontent.com/37830933/106500516-e4e9dd00-64fc-11eb-938f-27ab63483ace.png)
还有就是切换代理了，不能换代理对于我这种后台一般开着全局代理的挺不方便的
希望作者能改进一下，其他都非常好，谢谢！

**Comment by qier222** [comment]
已经有人发过这个功能的issue了

**Comment by qier222** [comment]
代理功能暂时不打算添加，应用已经支持UnblockMusic了。
