### ISSUE TITLE
窗口歌词模式下，没有切换全屏歌词的功能

### ISSUE THREAD

**Issue by Daviding33** [qier222/YesPlayMusic#1912]
我每次都需要退出来全屏再切到歌词模式，有点麻烦，可以出个快捷键在窗口歌词模式下切换全屏模式
谢谢！

**Comment by GrassBlock1** [comment]
冷知识：你可以在任何一处按下 F11 来切换全屏模式。

~~身虽在贡献者，但咱只是修依赖的bot，大事儿别找咱~~
