### ISSUE TITLE
Windows 客户端 UNM 调用 YtDl 引擎会弹出终端窗口，且窗口有时无法正常关闭

### ISSUE THREAD

**Issue by railzy** [qier222/YesPlayMusic#1916]
### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息
yt-dlp 已经尝试了使用 pip 安装的方法和直接指定可执行文件路径的方法，均出现了该问题。尝试了 youtube-dl 也一样。播放到需要解析其他音源的歌曲时就会弹终端窗口到前台，有点烦人，后面指定了无效路径后才不弹窗。

- 客户端 
Windows 安装包安装的 v0.4.5 客户端 [YesPlayMusic-Setup-0.4.5.exe](https://github.com/qier222/YesPlayMusic/releases/download/v0.4.5/YesPlayMusic-Setup-0.4.5.exe)

- 电脑操作系统信息
版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎7/‎13
操作系统版本	22623.1180
序列号	PF3F6DA1
体验	Windows Feature Experience Pack 1000.22638.1000.0

- 控制台 Console 页面的截图（按 F12 可打开控制台）
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/57893649/213874725-10f61d82-b811-4c81-8106-f2418bf32101.png">

![image](https://user-images.githubusercontent.com/57893649/213874501-6d24c708-d888-4904-ad6b-faa34ebbfe37.png)

**Comment by pan93412** [comment]
Weird, UNM 應該已經解決掉這個問題了。試試看 master 最新組建？<https://github.com/qier222/YesPlayMusic/actions/runs/3996024061>

**Comment by railzy** [comment]
用 Actions 里最新的安装包解决了
