### ISSUE TITLE
音乐库无法打开

### ISSUE THREAD

**Issue by JieXuS0507** [qier222/YesPlayMusic#192]
客户端安装版本，系统win10专业版，版本1909（os 18363.1316），打开音乐库一直卡住，试过便携版也还是一样
![1](https://user-images.githubusercontent.com/62798715/106540830-b17a7300-653b-11eb-9cff-f60f77727770.png)
![2](https://user-images.githubusercontent.com/62798715/106540834-b3dccd00-653b-11eb-90fa-6ecd6561298b.png)
不知道是不是我系统的问题

**Comment by qier222** [comment]
打开软件后登录了吗？

**Comment by w526433357** [comment]
我这儿也是，昨天第一次下载安装使用（便携版也尝试过），登陆后音乐库加载不出，歌单页面也加载不出。歌手页面、听歌没有问题。win10专业版

**Comment by AzberCeryain** [comment]
阿哲……我Windows10 Home  x64 （OS 18363.1316）音乐库、首页、发现 一切正常 歌单歌词正常加载 音乐正常播放 最新安装版

ps. 顺便提一句 这个歌词ui觉得非常好 非常清晰明了 点个赞

**Comment by JieXuS0507** [comment]
> 打开软件后登录了吗？

没有登录的界面，音乐库那个界面一直就没加载出来过，但是我听歌正常，歌词正常，只有音乐库打不开

**Comment by w526433357** [comment]
> > 打开软件后登录了吗？
> 
> 没有登录的界面，音乐库那个界面一直就没加载出来过，但是我听歌正常，歌词正常，只有音乐库打不开

我这儿音乐库的界面第一次加载是登陆，登陆后就再也加载不出来了

**Comment by jerryzcl** [comment]
可尝试添加一首喜欢的歌曲再重新加载音乐库

**Comment by jerryzcl** [comment]
> > > 打开软件后登录了吗？
> > 
> > 
> > 没有登录的界面，音乐库那个界面一直就没加载出来过，但是我听歌正常，歌词正常，只有音乐库打不开
> 
> 我这儿音乐库的界面第一次加载是登陆，登陆后就再也加载不出来了
可尝试添加一首喜欢的歌曲再重新加载音乐库

**Comment by jerryzcl** [comment]
可尝试添加一首喜欢的歌曲再重新加载音乐库

**Comment by jerryzcl** [comment]
> > > 打开软件后登录了吗？
> > 
> > 
> > 没有登录的界面，音乐库那个界面一直就没加载出来过，但是我听歌正常，歌词正常，只有音乐库打不开
> 
> 我这儿音乐库的界面第一次加载是登陆，登陆后就再也加载不出来了

可尝试添加一首喜欢的歌曲再重新加载音乐库

**Comment by w526433357** [comment]
> > > > 打开软件后登录了吗？
> > > 
> > > 
> > > 没有登录的界面，音乐库那个界面一直就没加载出来过，但是我听歌正常，歌词正常，只有音乐库打不开
> > 
> > 
> > 我这儿音乐库的界面第一次加载是登陆，登陆后就再也加载不出来了
> 
> 可尝试添加一首喜欢的歌曲再重新加载音乐库

点击爱心没有反应的，音乐库不能刷新，好像也没有退出登陆的位置

**Comment by JieXuS0507** [comment]
> > > > > 打开软件后登录了吗？
> > > > 
> > > > 
> > > > 没有登录的界面，音乐库那个界面一直就没加载出来过，但是我听歌正常，歌词正常，只有音乐库打不开
> > > 
> > > 
> > > 我这儿音乐库的界面第一次加载是登陆，登陆后就再也加载不出来了
> > 
> > 
> > 可尝试添加一首喜欢的歌曲再重新加载音乐库
> 
> 点击爱心没有反应的，音乐库不能刷新，好像也没有退出登陆的位置

我也是这样

**Comment by shenduldh** [comment]
我也是这样

**Comment by WET-MATCH** [comment]
我也这样

**Comment by yue-qiu** [comment]
我也这样，第一次登陆以后音乐库一直没反应

**Comment by shenduldh** [comment]
解决方法：
1. 进入`C:\Users\liuda\AppData\Roaming\YesPlayMusic`缓存目录
2. 删除名为`Cookies`的文件
3. 重新进入软件
4. 使用手机号登录

**Comment by lihsen** [comment]
![image](https://user-images.githubusercontent.com/25364579/106993706-38d31b00-67b6-11eb-9741-83987dfaeb9e.png)
同音乐库登录后没法进入，macOs big sur 版本11.1

**Comment by qier222** [comment]
> ![image](https://user-images.githubusercontent.com/25364579/106993706-38d31b00-67b6-11eb-9741-83987dfaeb9e.png)
> 
> 同音乐库登录后没法进入，macOs big sur 版本11.1

截图控制台看看错误，按F12可以打开控制台

**Comment by lihsen** [comment]
> > ![image](https://user-images.githubusercontent.com/25364579/106993706-38d31b00-67b6-11eb-9741-83987dfaeb9e.png)
> > 同音乐库登录后没法进入，macOs big sur 版本11.1
> 
> 截图控制台看看错误，按F12可以打开控制台

![image](https://user-images.githubusercontent.com/25364579/107321013-cbd4c380-6adc-11eb-8dc9-6ab47df690ed.png)

**Comment by blog0xf** [comment]
新年快乐哈！子kali linux 下的YesPlayMusic 用邮箱登录，音乐库会显示空白，网页端和客户端一样，用手机号码登录显示正常！望作者过年后加快修复BUG,很好的应用。
