### ISSUE TITLE
0.4.6 版本无法正确响应多媒体键

### ISSUE THREAD

**Issue by theta405** [qier222/YesPlayMusic#1924]
### **[0.4.6] win10 / win11**

windows 的 0.4.6 版本，在用多媒体键控制时出了问题
具体表现：

- 播放时按下 `播放 / 暂停` ：歌曲会暂停；但播放界面的 播放 / 暂停 按钮状态不会更新
- 暂停时按下 `播放 / 暂停` ：歌曲不会继续播放，播放界面的 播放 / 暂停 按钮状态不会更新；但歌曲进度条和歌词会开始滚动
- `上一曲` 和 `下一曲` 完全没有响应了

可以用键盘的多媒体键，也可以用 windows 的控制中心，都能复现

![image](https://user-images.githubusercontent.com/50106454/215248570-1bcf9a0b-cd11-4713-932b-082d95d963df.png)
![image](https://user-images.githubusercontent.com/50106454/215250578-0ee1dcb1-986c-48b1-9d45-03bb1dab03a4.png)

**Comment by theta405** [comment]
btw，0.4.5 没有这些问题

**Comment by timesponge** [comment]
win11 22H2 版本
YesPlayMusic 0.4.6
我没有复现出同样问题，我这边正常

**Comment by theta405** [comment]
重启了几次之后解决了。没搞懂是为啥

**Comment by Glucy-2** [comment]
你好，看到Issue关了，是解决了吗？

**Comment by theta405** [comment]
> 你好，看到Issue关了，是解决了吗？

是的呀，重启了几次，莫名其妙就好了
不知道为啥，反正全都能用了，就关了
