### ISSUE TITLE
本地用 docker 搭建网页端，本地局域网访问网站能登录，添加 https 端口转发出去就没法登录了，三种登录方式的接口都是502

### ISSUE THREAD

**Issue by Theoshen** [qier222/YesPlayMusic#1933]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

Windows11 Chrome浏览器
![image](https://user-images.githubusercontent.com/53144901/215394630-2922238a-78ec-4827-bdb5-7de4a05b880b.png)

**Comment by erdongleon** [comment]
进容器修改后台的nginx配置文件

**Comment by BarryYangi** [comment]
后台的nginx配置文件具体怎么修改能说一下不

**Comment by 18271211** [comment]
原来是这样，怪不得我想怎么突然不能登陆了。坐等nginx配置文件

**Comment by SuXin0526** [comment]
插眼坐等

**Comment by krishukr** [comment]
https://github.com/qier222/YesPlayMusic/issues/1604#issuecomment-1126701593

**Comment by Theoshen** [comment]
> [#1604 (comment)](https://github.com/qier222/YesPlayMusic/issues/1604#issuecomment-1126701593)

我打开容器里面的 nginx 配置文件看了，默认就有这部分设置哒
`server {
  gzip on;
  listen      80;
  listen  [::]:80;
  server_name  localhost;

  location / {
    root      /usr/share/nginx/html;
    index     index.html;
    try_files $uri $uri/ /index.html;
  }

  location @rewrites {
    rewrite ^(.*)$ /index.html last;
  }

  location /api/ {
    proxy_buffers           16 32k;
    proxy_buffer_size       128k;
    proxy_busy_buffers_size 128k;
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $remote_addr;
    proxy_set_header        X-Forwarded-Host $remote_addr;
    proxy_set_header        X-NginX-Proxy true;
    proxy_pass              http://localhost:3000/;
  }
}`

**Comment by krishukr** [comment]
> 我打开容器里面的 nginx 配置文件看了，默认就有这部分设置哒

你转发出去的 nginx 配置文件里也要加。

https://github.com/qier222/YesPlayMusic/blob/1b7e33c222f158dba24952445542d1a89b09e0af/Dockerfile#L10

容器里的 nginx 是 1.20.2 ，你这里报错的是 1.23.2 。

**Comment by Theoshen** [comment]
@krishukr ok，我大概懂了，就是说外层反代的 nginx 吧，我去试试

**Comment by Theoshen** [comment]
@krishukr 谢谢你的指路~ 已经解决了
