### ISSUE TITLE
希望功能完善和增加快捷键

### ISSUE THREAD

**Issue by xiaowenlv** [qier222/YesPlayMusic#194]
希望能后台播放，最小化到通知栏，能快捷键操作换歌和音量，支持私人fm，这样我就可以丢掉官方版了，官方客户端音质真不咋地，同样的歌曲音质比安卓差远了。

**Comment by qier222** [comment]
有最小化到任务栏的选项。
支持快捷键，快捷键和网易云的一样。
私人FM在todo里了。

**Comment by xiaowenlv** [comment]
关闭窗口就退出了，不能设置最小化吗，快捷键能不能更改，私人fm怎样找到
