### ISSUE TITLE
[question] 请问怎么查看正在播放的音乐的音源信息？

### ISSUE THREAD

**Issue by HikariXu** [qier222/YesPlayMusic#1947]
请问怎么查看正在播放的音乐的音源信息？一些音乐播放的版本相比在网易云的版本更好听，但是很难找到其来源

**Comment by Force1ess** [comment]
@lonetrail 嗨，我也有同样的问题，请问你解决这个问题了吗

**Comment by lonetrail** [comment]
没有解决> @lonetrail 嗨，我也有同样的问题，请问你解决这个问题了吗
