### ISSUE TITLE
Windows客户端的窗口拉伸大小好像不能记忆.

### ISSUE THREAD

**Issue by LoveLumia** [qier222/YesPlayMusic#195]
**_https://github.com/qier222/YesPlayMusic/projects/1#card-51115206_**
这个记忆窗口大小好像没用啊，每次打开还是默认的大小QAQ

比如说我的窗口喜欢拉伸成这种大小
![image](https://user-images.githubusercontent.com/49342443/106551375-1049e780-6550-11eb-9d04-eddbabd8278c.png)
但是重新打开应用后变成了这种大小
![image](https://user-images.githubusercontent.com/49342443/106551434-35d6f100-6550-11eb-85c8-14e6bef01a36.png)

难道是我操作不对!?????1

**Comment by qier222** [comment]
下个版本会修复这个bug。已经有人发过这个isuue了，这个issue先关闭了
