### ISSUE TITLE
增加私人FM和音效控制器

### ISSUE THREAD

**Issue by Ricardokevins** [qier222/YesPlayMusic#196]
1. 类似于网易云的私人FM，不断的推荐歌曲，不是很喜欢听别人归纳的歌单，很多口味不同
2. 音效控制器，比如3D环绕，人声之类的
3. 效果很惊艳hhh，很不错的第三方工具 Awsome

**Comment by Ricardokevins** [comment]
当然可能是过度需求了，不过提个建议，能实现就再好不过了

**Comment by hawtim** [comment]
私人FM 是一直在 TODO 里的。
做这个产品本质上还是还原工具的本质，所以音效控制器目前是不会考虑去做的。

**Comment by Ricardokevins** [comment]
> 私人FM 是一直在 TODO 里的。
> 做这个产品本质上还是还原工具的本质，所以音效控制器目前是不会考虑去做的。

好嘞，静等私人FM，冲冲冲！
