### ISSUE TITLE
/netease_api..等electron打包所需的部分代码 不提交嘛？？？

### ISSUE THREAD

**Issue by iT-lijun** [qier222/YesPlayMusic#197]
clone下来 经过一番折腾后 尝试electron本地开发打包.. 
NeteaseCloudMusicApi-master 与 /netease_api(被修改但未提交) 还是有些差异..
Ooops **electron:serve** 没法本地跑起来~~
关于electron分支 最近有什么计划嘛？？？

**Comment by qier222** [comment]
v0.3.1 tag的那个commit有这些文件

**Comment by iT-lijun** [comment]
> v0.3.1 tag的那个commit有这些文件

ths.. 已经跑起来了✨✨~
