### ISSUE TITLE
求播放本地歌曲

### ISSUE THREAD

**Issue by Violexjj** [qier222/YesPlayMusic#1972]
一人血书求大佬出可以播放本地歌曲的功能，如果和网易云合在一起不好做的话可以做一个类似界面的单独用来播放本地音乐，真的这大佬的审美太好了，界面我超级喜欢。但是我本地音乐听的多，网易云大多用来搜搜歌曲，奈何找不到颜值这么高的本地播放器，呜呜呜。

**Comment by Violexjj** [comment]
这个是不可以下载音乐的吗，还有，它的缓存在哪里，我下的是exe直接使用不用安装，没找到缓存的歌曲在哪

**Comment by Asaka-xin** [comment]
**~/AppData/Roaming/yesplaymusic**
但我使用的是含setup的版本

**Comment by Violexjj** [comment]
> **~/AppData/Roaming/yesplaymusic** 但我使用的是含setup的版本

OK我也找到了roaming这个文件夹了里面的yesplaymusic了，在IndexedDB里面有缓存的歌，改一下后缀就能听了哈哈

**Comment by Violexjj** [comment]
> **~/AppData/Roaming/yesplaymusic** 但我使用的是含setup的版本

我还以为是作者回复我愿意出本地播放呢哈哈，小小激动了一下

**Comment by Violexjj** [comment]
兄弟有什么好的本地播放器推荐吗，要UI美观，像这个yesplaymusic一样，然后支持本地歌词，实在太稀有了这样的哈哈

> **~/AppData/Roaming/yesplaymusic** 但我使用的是含setup的版本

**Comment by Asaka-xin** [comment]
自己用的是**Foobar2000**，没有见过**符合你描述的播放器**

**Comment by Violexjj** [comment]
> 自己用的是**Foobar2000**，没有见过**符合你描述的播放器**

嗯，还是谢谢了，准备在GitHub里面大找一番哈哈

**Comment by pan93412** [comment]
Duplicate of #2031

**Comment by liinyun** [comment]
> > 自己用的是**Foobar2000**，没有见过**符合你描述的播放器**
> 
> 嗯，还是谢谢了，准备在GitHub里面大找一番哈哈

找到了没有哥，我现在用的rhythm box

**Comment by Tychristine** [comment]
> > > 自己用的是**Foobar2000**，没有见过**符合你描述的播放器**
> > 
> > 嗯，还是谢谢了，准备在GitHub里面大找一番哈哈
> 
> 找到了没有哥，我现在用的rhythm box

AIMP，播放200MiB 以上大小的歌曲都流畅，而且界面点一下自带的默认主题就很美观
