### ISSUE TITLE
win11更新后，安装和运行都有报错，运行显示异常

### ISSUE THREAD

**Issue by chyuhung** [qier222/YesPlayMusic#1976]
报错信息：

![image](https://user-images.githubusercontent.com/26589831/222373846-e38dd5a5-fafc-4553-b0bb-e594285d9f8b.png)

运行显示异常：
![image](https://user-images.githubusercontent.com/26589831/222373976-dfc4d1dd-1432-4b18-b708-b20da712c09e.png)

**Comment by starknt** [comment]
尝试用管理员允许

**Comment by chyuhung** [comment]
后面没注意，更新系统重启了几次恢复正常了
