### ISSUE TITLE
Windows安装板，海外用户无法使用多项功能

### ISSUE THREAD

**Issue by zhucaidan** [qier222/YesPlayMusic#198]
Windows安装板，海外用户无法显示图片，无法播放，无法自定义UnblockNeteaseMusic服务器和端口

![QQ截图20210201221912](https://user-images.githubusercontent.com/47970938/106560342-bad3f300-64db-11eb-885c-cc70161fc518.png)

**Comment by Ahgni** [comment]
我在法国这边可以看到图片
![image](https://user-images.githubusercontent.com/46089068/106956831-78a6ed80-6737-11eb-9e6a-19ed4d04bf87.png)
很感谢这个软件，没有广告的困扰。
有的歌曲听不了是为什么呢？是因为版权吗
