### ISSUE TITLE
【WIN11】R3Play 全屏功能异常

### ISSUE THREAD

**Issue by XYZliang** [qier222/YesPlayMusic#1982]
测试版R3Play打开时为窗口，此时点全屏键，R3Play正常全屏。
![image](https://user-images.githubusercontent.com/59312540/222966078-25995d62-c33e-432d-9d57-44a3f48bcd3b.png)
全屏后点击取消全屏键则无效，依旧是全屏无法恢复成窗口模式。
![image](https://user-images.githubusercontent.com/59312540/222966130-7ba118b0-85cd-4094-8200-b32dae3ce338.png)
将这个全屏窗口移动位置，再次点击取消全屏键却是直接正常全屏了，应该是这个取消全屏键逻辑有误，实际依旧是全屏键，

系统：Windows11 22H2

**Comment by IM515BT** [comment]
win10 22h2 游戏本。画面很流畅，希望可以保持。

左上角漏光，楼上那位的第二张图很明显。笔记本上四个角也是漏。按键功能正常



![屏幕截图 2023-03-06 184502](https://user-images.githubusercontent.com/59956201/223088653-e7dd7598-c8d3-4597-9a76-565952d2e912.png)

**Comment by GrassBlock1** [comment]
Windows 10 LTSC 无法正常复现。
窗口圆角是写死的。

**Comment by IM515BT** [comment]
> Windows 10 LTSC 无法复现，仍可正常切换至最大化以及返回常规 窗口圆角是写死的，这两天开发不会修

不修感觉也没事，问题不大

**Comment by XYZliang** [comment]
新版已经修复
