### ISSUE TITLE
耻辱柱！！！把这个人挂进耻辱柱！！！变相通过软件获利！！！

### ISSUE THREAD

**Issue by coco-maker** [qier222/YesPlayMusic#199]
公众号：光头院长（长期分享各种东西，内含违法的东西）
小程序：老爷花苑（作为公众号转流用）
挂图为证
![yuanzhang (3)](https://user-images.githubusercontent.com/72242727/106562251-04b4eb80-6565-11eb-80a9-5f6fd4044972.png)
![yuanzhang (1)](https://user-images.githubusercontent.com/72242727/106562268-0a123600-6565-11eb-9ecc-f4d9d14882ef.png)
![yuanzhang (4)](https://user-images.githubusercontent.com/72242727/106562293-11d1da80-6565-11eb-979a-5c3101644b1f.png)
![yuanzhang (2)](https://user-images.githubusercontent.com/72242727/106562295-126a7100-6565-11eb-8cf4-a7a9f548fc23.png)
看不到图的点链接看
https://i0.hdslb.com/bfs/album/9b3b3deeb1b1977bc8aee051478a888869c2e5d5.png
https://i0.hdslb.com/bfs/album/eac0895d2e9f0dca9017b94990bde190fb71c2cc.png
https://i0.hdslb.com/bfs/album/37fefd50303370d3204460821c4e7372608ed122.png
https://i0.hdslb.com/bfs/album/361a97304767c51fb0b501f2f80bb97d79e6c138.png
（链接需要复制浏览器打开）

**Comment by amaterasai** [comment]
你想说什么？
有人帮着扩散，有什么问题吗？

**Comment by annkoxx** [comment]
可能他想说被强制加入广告宣传把

**Comment by qier222** [comment]
谢谢告知，但是我觉得这个没什么大问题
