### ISSUE TITLE
美国 billboard 周榜点击 play 有明显延迟并且报错

### ISSUE THREAD

**Issue by hawtim** [qier222/YesPlayMusic#2]
如题，点击play延迟后选择第一条曲目，但是报错没有播放声音。

![image](https://user-images.githubusercontent.com/11072796/96267386-5196a580-0ffa-11eb-9f00-306f365ee1b9.png)

**Comment by qier222** [comment]
已经修好了，还是有问题的话请尝试刷新浏览器缓存。
