### ISSUE TITLE
关于声音设置的BUG

### ISSUE THREAD

**Issue by KeKe12030** [qier222/YesPlayMusic#20]
在使用过程中，发现了一个声音调节的BUG。
右下角设置好声音之后（假设调为5%），F5刷新网页后重新播放，会造成声音设置失效（重新变成100%），需要重新设置（但是前端UI显示还是5%）
甚至是静音了（声音调为0%），刷新之后，实际播放效果却变成100%。但是前端UI仍为静音状态。
（图片较大请耐心等待。）
![image.png](https://pic.rmb.bdstatic.com/bjh/919acd8d5c05f1b6f926d97d1cb78abe.png)

**Comment by gzlearm** [comment]
同样遇到了这个问题，刷新后音量重置100了

**Comment by qier222** [comment]
@gzlearm @KeKe12030 之前的代码放错目录了，导致没有加载最新的代码。现在已经修复了，建议清除下浏览器缓存。
