### ISSUE TITLE
建议：希望增加搜索歌单内歌曲的功能

### ISSUE THREAD

**Issue by xchangfu** [qier222/YesPlayMusic#201]
![image](https://user-images.githubusercontent.com/70430355/106564196-e3093380-6567-11eb-855a-3243caa9f201.png)
![屏幕截图 2021-02-02 150327](https://user-images.githubusercontent.com/70430355/106564237-ef8d8c00-6567-11eb-9024-22a97f0822b2.png)
就是网易云win客户端的这个功能
感谢！！

**Comment by Captpricelsy** [comment]
+1

**Comment by qier222** [comment]
已加入todo（但是不保证能实现）

**Comment by xchangfu** [comment]
> 已加入todo（但是不保证能实现）

OK，辛苦了
