### ISSUE TITLE
虽然是个白嫖党，但是2.0又丑又难用，建议认真在规划下

### ISSUE THREAD

**Issue by Hooper93** [qier222/YesPlayMusic#2024]
## 所有的音乐列表完全都不知道是干什么的
参见下图，这个列表的设计到底是怎么想的。。。
![infoflow 2023-04-03 14-44-18](https://user-images.githubusercontent.com/48215196/229431955-6e532267-80fa-44f0-824b-b65600146f4e.png)
![infoflow 2023-04-03 14-44-32](https://user-images.githubusercontent.com/48215196/229431989-f9bb2358-6cb5-48de-bd75-2b17a6004e4e.png)

## 大圆角和配色已经属于上个时代的产物了
视觉不太专业，其实dribbble有非常非常非常多的音乐播放器的界面，可以参考下。2.0的界面，实在是上个世纪的设计风格了..

**Comment by Smil8y** [comment]
我觉得视觉没有任何问题

**Comment by nuym** [comment]
各个人的审美不同

**Comment by RudolphLiu** [comment]
其实换个角度，你和我，我们两个人各自去开发一个像作者这样的播放器，我保证我开发的，你不喜欢，你开发的，我不喜欢，但是我们并不是为彼此服务而生的，所以没有必要为对方做出改变

**Comment by chuyao123** [comment]
这个风格不太适合国内软件用惯了的人。

**Comment by linsencc** [comment]
对我来说，我觉得页面给人的视觉感受还是很好的，但是确实存在页面不能好展示提供的功能，不知道页面是用于做什么的

**Comment by halftael** [comment]
我倒是觉得这个页面很有意思

**Comment by allawsl** [comment]
> ## 所有的音乐列表完全都不知道是干什么的
> 参见下图，这个列表的设计到底是怎么想的。。。 ![infoflow 2023-04-03 14-44-18](https://user-images.githubusercontent.com/48215196/229431955-6e532267-80fa-44f0-824b-b65600146f4e.png) ![infoflow 2023-04-03 14-44-32](https://user-images.githubusercontent.com/48215196/229431989-f9bb2358-6cb5-48de-bd75-2b17a6004e4e.png)
> 
> ## 大圆角和配色已经属于上个时代的产物了
> 视觉不太专业，其实 dribbble 有非常非常非常多的音乐播放器的界面，可以参考下。2.0 的界面，实在是上个世纪的设计风格了..

设计的角度来说，圆角给人会带来安全感，锐角会带来不安，圆角设计对于大众是友好的，如果你觉得设计落后那是你根本不懂设计，你有能力自己开发，白嫖还这么理直气壮

**Comment by qfys521** [comment]
你觉得不好看自己开发一个嘛

**Comment by whymesocooll** [comment]
你自己开发呗，白嫖还在这挑三拣四的

**Comment by JeamUmika** [comment]
如果你不喜欢这种风格可以提建议，觉得难用也可以pr，但还请别像个老板一样命令开发者。

**Comment by KH-XXXVillager** [comment]
自己fork改ui，如果觉得不错还能pr

**Comment by thalassosag** [comment]
你搁这建议个der呢...说话麻烦直白点
