### ISSUE TITLE
这难道不是网易云换了皮？

### ISSUE THREAD

**Issue by lyy33441314** [qier222/YesPlayMusic#203]
我自己感受了一下  完全和 网易云一样  该不能听的歌曲还是不能听 ，最好加一个 去灰色歌单   还有播放器尺寸问题 不会根据电脑屏幕的尺寸 修改大小

**Comment by Captpricelsy** [comment]
有些V*P的歌是能听到的，有些灰的也可以，不知道作者用了什么魔法
