### ISSUE TITLE
求求大佬给Discord Rich Presence搞个可以看见专辑图片的

### ISSUE THREAD

**Issue by lyu0131** [qier222/YesPlayMusic#2069]
<img width="259" alt="Screen Shot 2023-06-03 at 5 08 03 PM" src="https://github.com/qier222/YesPlayMusic/assets/86496041/11d92381-f83c-4b58-bb13-5de634bbbe87">
->
<img width="265" alt="Screen Shot 2023-06-03 at 5 08 35 PM" src="https://github.com/qier222/YesPlayMusic/assets/86496041/46547894-d562-450c-87a8-5f0a9d5f4396">

类似spotify可以把专辑图片显示出来。Orz

**Comment by FrzMtrsprt** [comment]
https://github.com/qier222/YesPlayMusic/pull/2294
