### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by M1NGc** [qier222/YesPlayMusic#208]
![image](https://user-images.githubusercontent.com/26264126/106691212-18685c80-660e-11eb-95bd-8fe28ae33be2.png)

**Comment by qier222** [comment]
使用管理员权限试试

**Comment by M1NGc** [comment]
> 使用管理员权限试试

![image](https://user-images.githubusercontent.com/26264126/106702357-342a2d80-6623-11eb-8973-50b688da592d.png)
已经是管理员了
