### ISSUE TITLE
运行过程中导致系统死机

### ISSUE THREAD

**Issue by zayn7lie** [qier222/YesPlayMusic#2081]
# 问题描述

经过多次测试，发现当 `yesplaymusic` 运行一段时间后，无论是否正在播放，都有可能使整个 ubuntu 卡在同一个循环点内进行循环。例如 ubuntu 内的声音重复播放某一片段，鼠标不断来回移动等，无法操作。

# 测试报错

因为系统卡死无法操作， `ctrl + alt + f2~f6` 切换后可观察到 `gpu` 报错：

```sh
[drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed  to initialize parser -125!
[drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed  to initialize parser -125!
[drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed  to initialize parser -125!
[drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed  to initialize parser -125!
[drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed  to initialize parser -125!
[drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed  to initialize parser -125!
[drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed  to initialize parser -125!
......
```

不断重复报错，此时还并未登录。
唯一能做的就是在下一次报错前登录并 `$ reboot`

# 系统配置

- Linux: ubuntu 22.04.2 LTS x86_64
- Kernel: 5.19.0-43-generic
- GPU: AMD集显：REMBRANDT (rembrandt, LLVM 15.0.6, DRM 3.47, 5.19.0-43-generic)
- CPU: AMD® Ryzen 7 6800hs with radeon graphics × 16

**Comment by zylo117** [comment]
害，你不是一个人，我分析了很久才分析出是yes的问题，我不打开yes就绝对不会死机。真的不可思议，一个音乐软件还能搞到死机。其实并不需要重启，重启桌面管理器就行，sudo systemctl restart gdm3，但是桌面没保存的就全没了

**Comment by zayn7lie** [comment]
抱歉，并非软件问题，而是 wayland 和 amdgpu 问题，问题 close
