### ISSUE TITLE
打开软件报错，网络无连接

### ISSUE THREAD

**Issue by ke-xi** [qier222/YesPlayMusic#2090]
<img width="536" alt="Snipaste_2023-07-08_19-00-11" src="https://github.com/qier222/YesPlayMusic/assets/58284266/f093ece0-e773-4852-bc5c-591d7fbc7109">
<img width="1086" alt="Snipaste_2023-07-08_19-02-09" src="https://github.com/qier222/YesPlayMusic/assets/58284266/4bcf71ad-0aef-41fe-9b1e-f08d4b8a003e">

**Comment by zxbforever** [comment]
是不是界面都动不了 我也遇到了 重装又好了一会 然后又寄了

**Comment by ke-xi** [comment]
> 是不是界面都动不了 我也遇到了 重装又好了一会 然后又寄了
解决了
安装一个叫Node.js的软件，好像这个依赖Node.js才能运行
