### ISSUE TITLE
适配移动端

### ISSUE THREAD

**Issue by Mayandev** [qier222/YesPlayMusic#21]
手机端浏览器显示效果不太好，需要适配一下

**Comment by Mayandev** [comment]
另外 Dark Mode 我准备来适配一下，之前项目刚好做过

**Comment by qier222** [comment]
移动端暂时不打算适配。Dark Mode我打算用CSS变量来做。

**Comment by Mayandev** [comment]
嗯嗯，好的，我这两天给你发一个 PR。另外看了你的其他 Repo，非常有设计感，真的很棒！
