### ISSUE TITLE
如果可以直接docker直接一键部署在服务器就更方便了

### ISSUE THREAD

**Issue by db-one** [qier222/YesPlayMusic#210]

**Comment by maple3142** [comment]
https://github.com/maple3142/YesPlayMusic/commit/dab93bfdc3fb98e4a5a225caa78ee1f6c2054c4d
可以試試看這個，隨便弄出來的，勉強能用

**Comment by db-one** [comment]
@maple3142 嗯 谢谢  我看看去

**Comment by db-one** [comment]
https://hub.docker.com/r/seenight/yesplaymusic

今天搜到docker上已经有人上传了镜像了
