### ISSUE TITLE
网页版登录无法跳入音乐库

### ISSUE THREAD

**Issue by skykain** [qier222/YesPlayMusic#212]
### 反馈 bug 需要的信息

- 版本：网页版，版本是 git clone 下来自 build 的
- 系统版本：macOS big sur 11.2
- node版本：v12.19.0
- 浏览器版本：Google Chrome 88.0.4324.96
- 问题描述：账号登录正常，可在 `console` 查看到返回的账号信息，但点击 `音乐库` 仍然是登录页面

**Comment by qier222** [comment]
是跨域导致无法set cookie的问题

**Comment by skykain** [comment]
好的，Get it
