### ISSUE TITLE
flatpak 安装后中文乱码

### ISSUE THREAD

**Issue by alfred-hong** [qier222/YesPlayMusic#2121]
系统是fedora 38

NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation

问题如图所示：

![image](https://github.com/qier222/YesPlayMusic/assets/43607830/ad0622cc-32b8-46d6-afac-44cd38faf314)
![image](https://github.com/qier222/YesPlayMusic/assets/43607830/19ead5f1-5d95-4fae-87b5-563b49ee3bed)

请问各位大佬应该如何处理呢！

**Comment by Guanran928** [comment]
NixOS Unstable 不能复现，请确保已经安装好正确字体。
![image](https://github.com/qier222/YesPlayMusic/assets/68757440/e64676b6-6423-4b5a-9e16-6d22f884a2d5)

**Comment by alfred-hong** [comment]
请问是哪种字体，目前版本如图

![image](https://github.com/qier222/YesPlayMusic/assets/43607830/06f9cfa4-0bb6-4e2b-bde2-746cb5feca13)

**Comment by Guanran928** [comment]
> 请问是哪种字体，目前版本如图
> 
> ![image](https://user-images.githubusercontent.com/43607830/263534371-06f9cfa4-0bb6-4e2b-bde2-746cb5feca13.png)

请尝试安装 Noto Sans/Serif CJK、Source Han Sans/Serif CN、文泉驿全系。

**Comment by alfred-hong** [comment]
谢谢！已经成功。

在安装完字体后并未立即生效，需要重启后生效（本人未尝试注销，直接重启）

**Comment by Guanran928** [comment]
> 谢谢！已经成功。
> 
> 在安装完字体后并未立即生效，需要重启后生效（本人未尝试注销，直接重启）

请关闭 Issue。
