### ISSUE TITLE
手机网易云傻逼玩意在播放页加广告，请问大家有什么手机端的替代品吗

### ISSUE THREAD

**Issue by ogios** [qier222/YesPlayMusic#2122]
如图：

![Screenshot_2023-08-27-23-51-38-74_25d38497d72d75227633ae777c2e0df5.jpg](https://github.com/qier222/YesPlayMusic/assets/96933655/adda1f13-4c65-47fa-be82-5f1026d7e9fd)

**Comment by ogios** [comment]
情绪可能有点过了，之前在播客里就看到过，不过很少听也就没在意，以为只是播客那打点小广告啥的
但是今天听音乐突然看到这个真的把我气的不行，一下子脏话就上来了

**Comment by ssln5014** [comment]
找个修改版的吧，酷安或者tg挺多的
