### ISSUE TITLE
网盘音乐播放问题

### ISSUE THREAD

**Issue by Force1ess** [qier222/YesPlayMusic#2124]
#在播放网盘内的歌曲《以父之名》时，连续出现大量网络请求错误
- 网盘内的其他歌曲暂时没有发现类似现象
### 反馈 bug 需要的信息

- 客户端
- Manjaro
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://github.com/qier222/YesPlayMusic/assets/72636351/606d01b1-9f0c-4e30-ba30-224ebaa5d9ba)

![image](https://github.com/qier222/YesPlayMusic/assets/72636351/6ae7e3c5-293f-4314-a838-0f8b7258fc5a)

**Comment by runnableAir** [comment]
可能是你这个音频文件太大导致加载时内存耗尽？

**Comment by ogios** [comment]
> 可能是你这个音频文件太大导致加载时内存耗尽？

音频文件是一次性全部加载到内存的吗？
