### ISSUE TITLE
增加显示当前播放歌曲的音质

### ISSUE THREAD

**Issue by TUT123456** [qier222/YesPlayMusic#214]
设置页面可以设置音质，不过我想在播放页看到当前播放的歌曲是采用什么音质的，有些歌曲和解锁的灰色歌曲没有高音质，在播放页看不出来(虽然也听不出来)，可以看到音质的话方便下载下来和管理。

**Comment by qier222** [comment]
安心听歌，只要听不出来，音质就是最高的。

**Comment by 1191726235** [comment]
怎么用呀？只有代码没有程序呀
