### ISSUE TITLE
ubuntu 20.04 wayland 下界面显示问题

### ISSUE THREAD

**Issue by chenzaichun** [qier222/YesPlayMusic#216]
ubuntu 20.04 wayland 下界面显示问题，不能正常的缩放窗口，造成控制区域无法正常显示。

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 客户端
- ubuntu 20.04 wayland 字体缩放 150%
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://user-images.githubusercontent.com/127616/106722801-5c288980-6641-11eb-8df0-f995871b9010.png)
![image](https://user-images.githubusercontent.com/127616/106722881-72364a00-6641-11eb-9446-ad8c9c24f64b.png)

**Comment by q234rty** [comment]
Arch Linux GNOME X11 下面也有类似的问题。

**Comment by q234rty** [comment]
这个 issue 0.3.9 下依然存在。。

**Comment by AndPuQing** [comment]
在archlinux KDE 缩放200%下同样出现该问题
