### ISSUE TITLE
linux版白屏

### ISSUE THREAD

**Issue by GreenTeodoro839** [qier222/YesPlayMusic#217]
arm64版，启动就白屏，偶尔还闪现一些封面图（一整页显示一样的），点那些位置还会播放。卸载重装过了，昨天还正常，设备性能足够，内存，cpu才用了一点
![IMG_20210203_170052](https://user-images.githubusercontent.com/77104800/106723066-af9ad780-6641-11eb-860b-46ef63a21173.jpg)

**Comment by Fredoong** [comment]
同样的，我的Deepin也是白屏，鼠标感觉明显能点到东西，但是啥都看不到。
