### ISSUE TITLE
点音乐库没有反应。只有白白的屏幕

### ISSUE THREAD

**Issue by wulifangy** [qier222/YesPlayMusic#218]
![图片1](https://user-images.githubusercontent.com/25682008/106755250-dc161a00-6668-11eb-9732-b3cc884dda08.png)

**Comment by bearpool** [comment]
同样的问题，所有歌单都是空白

**Comment by LearnGenius** [comment]
+1 不过只有音乐库空白

**Comment by yanranxiaoxi** [comment]
Windows 出现缓存异常、音乐库白屏问题可以删除个人目录下 YesPlayMusic（C:\Users<用户名>\AppData\Roaming\YesPlayMusic）文件夹，以重置软件配置。

可以尝试核对一下与以下 issue 是否为同一个问题：
[https://github.com/qier222/YesPlayMusic/issues/224](https://github.com/qier222/YesPlayMusic/issues/224)
