### ISSUE TITLE
0.4.8，release没有提供安装包，我是小白，求求打个包

### ISSUE THREAD

**Issue by NilHenard** [qier222/YesPlayMusic#2184]
如题

**Comment by zaqai** [comment]
v2.0.0-alpha-2不香吗

**Comment by NilHenard** [comment]
> v2.0.0-alpha-2不香吗

请务必狠狠更新R3Player😋

**Comment by rEco1LLLL** [comment]
> v2.0.0-alpha-2不香吗

这个版本一堆bug 感觉还有好多功能没完善 选音质 调音量 等等好多 我自己用着感觉很难受

**Comment by laozhuv** [comment]
同求，虽然0.4.7用着也没啥bug

**Comment by pan93412** [comment]
上了，看 https://github.com/qier222/YesPlayMusic/releases/tag/v0.4.8-1
