### ISSUE TITLE
歌曲题目和内容不匹配

### ISSUE THREAD

**Issue by CoccaGuo** [qier222/YesPlayMusic#219]
辻詩音的Lost in wonderland这首歌，题目歌词以及封面是对的，但放出来的歌曲不对。之前偶尔会有这种问题。

**Comment by ShiinaManatsu** [comment]
![image](https://user-images.githubusercontent.com/20186095/106977098-9b1b2400-6794-11eb-950e-70a59e7f30fd.png)

这两首会拉取同一首伴奏

**Comment by qier222** [comment]
这个是因为播放器加载了下一首歌的信息，但是加载音频失败了，按道理来说应该会自动跳过下一首的，需要你提供控制台的截图才能定位错误。
ps：按F12可以打开控制台

**Comment by CoccaGuo** [comment]
![image](https://user-images.githubusercontent.com/42533763/107012162-9e81d000-67d3-11eb-8605-2092fc7421ce.png)

**Comment by qier222** [comment]
感觉是UnblockMusic的问题，你这两首歌在网易云官方客户端里能播放吗？

**Comment by CoccaGuo** [comment]
在网易云中是VIP歌曲，可以试听

**Comment by qier222** [comment]
那就是UnblockMusic的问题。UnblockMusic的原理是去其他音乐API里搜索相关的歌曲，搜出来的结果不一定是正确的。
