### ISSUE TITLE
新版本YesPlayMusic.0.4.8无法联网

### ISSUE THREAD

**Issue by fatyang799** [qier222/YesPlayMusic#2192]
windows10客户端

控制台 Console 页面的截图（按 F12 可打开控制台）：
![image](https://github.com/qier222/YesPlayMusic/assets/52167840/c40935b2-930f-4a47-b747-0e31ce52eb19)

使用界面：
![image](https://github.com/qier222/YesPlayMusic/assets/52167840/16a18d96-628c-400c-9a3e-b7f0b50d7bd6)

**Comment by akllcom** [comment]
+1 同样的报错

**Comment by rainbowflesh** [comment]
Duplicate & probably fixed in #2190

**Comment by xfbobowu** [comment]
+1 同样的报错
