### ISSUE TITLE
希望能增加本地音乐库浏览添加功能

### ISSUE THREAD

**Issue by EliteOtaku** [qier222/YesPlayMusic#222]
如果PC本地客户端能增加对本地音乐库的管理功能就好了，毕竟硬盘里面已经有不少经常听的歌，另外网易云已经把音乐文件转为NCM了，以后如果用其他播放器就无法直接播放，有点烦人。希望YesPlayMusic能理顺这个痛点，多谢了。

**Comment by qier222** [comment]
重复的issue #126
