### ISSUE TITLE
启动时出现Bug

### ISSUE THREAD

**Issue by Hdawen** [qier222/YesPlayMusic#223]
# 启动时出现以下弹窗，版本0.33
[![ylWP3T.png](https://s3.ax1x.com/2021/02/04/ylWP3T.png)](https://imgchr.com/i/ylWP3T)

**Comment by qier222** [comment]
重启电脑试试？我这边没有复现这个bug

**Comment by yikZero** [comment]
我这边也有这个情况
![image](https://user-images.githubusercontent.com/52102693/107041232-3515b780-67fb-11eb-94ba-1d31d50d0710.png)

**Comment by Hdawen** [comment]
> 重启电脑试试？我这边没有复现这个bug

每次打开软件都会出现这个弹窗，关机重启无法解决问题，我的电脑系统是big sur

**Comment by VidocqH** [comment]
> 重启电脑试试？我这边没有复现这个bug

我这里是每次重启后第一次打开软件才会出现此弹窗
