### ISSUE TITLE
登录一个存在的网易云号，但是没有在网易云号音乐绑定手机，存在音乐库页面卡死

### ISSUE THREAD

**Issue by Q-Tai-mu** [qier222/YesPlayMusic#224]
# 我使用一个网易号（完全可以使用），登录软件，出现页面卡死

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 登录一个注册成功但没有登录过网易云音乐的网易号，会卡死在音乐库页面

- 客户端
- win 10
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![捕获](https://user-images.githubusercontent.com/58099119/106834818-0f8c8f00-66d1-11eb-9238-f48da7b32ad7.PNG)

**Comment by tarzanfan** [comment]
同样问题在 uos桌面专业版上出现了.我再也打不开音乐库了
![image](https://user-images.githubusercontent.com/43024508/107332315-fb8cc700-6aee-11eb-849f-2bac58e02bc1.png)

**Comment by KKennyAss** [comment]
我这里也出现了这个问题，sad

**Comment by yanranxiaoxi** [comment]
Windows 出现缓存异常、音乐库白屏问题可以删除个人目录下 YesPlayMusic（C:\Users\<用户名>\AppData\Roaming\YesPlayMusic）文件夹，以重置软件配置。

实测该问题确实存在，等待修复吧
