### ISSUE TITLE
Feature: Sharing account resource. 共享账号资源

### ISSUE THREAD

**Issue by LeviMarvin** [qier222/YesPlayMusic#2244]
The account has a HeiJiao VIP, and after logging in, everyone who visits the website can play songs that can only be heard on HeiJiao VIP.
账号有黑胶会员，登录后可以让所有访问网站的人播放黑胶才能听的歌。

**Comment by Sudo-Winnie** [comment]
Your needs can be resolved on your own after you fork this project, or you can choose between a DMCA complaint or an attorney's letter from NetEase.

**Comment by LeviMarvin** [comment]
I just need the first plan. thx
我全都要（？）
