### ISSUE TITLE
示例/demo网站打不开

### ISSUE THREAD

**Issue by huajideshutiao** [qier222/YesPlayMusic#2248]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 网页版
- 浏览器名称或电脑操作系统
- via浏览器
- 
![Screenshot_2024-05-23-19-53-19-225_mark via](https://github.com/qier222/YesPlayMusic/assets/38980554/6adcb085-b839-4ce2-aaab-5bf4a0e18050)

- 控制台 Console 页面的截图（按 F12 可打开控制台）
- 
![image](https://github.com/qier222/YesPlayMusic/assets/38980554/fefd92b4-0351-4d50-9dba-7368fb9b9e00)

**Comment by huajideshutiao** [comment]
pc上的edge浏览器也打不开

**Comment by GrassBlock1** [comment]
https://github.com/qier222/YesPlayMusic/wiki/YesPlayMusic-使用中可能遇到的问题-(FAQ)#项目-demo-无法登录无法查看任何歌单信息

**Comment by huajideshutiao** [comment]
> [https://github.com/qier222/YesPlayMusic/wiki/YesPlayMusic-使用中可能遇到的问题-(FAQ)#项目-demo-无法登录无法查看任何歌单信息](https://github.com/qier222/YesPlayMusic/wiki/YesPlayMusic-%E4%BD%BF%E7%94%A8%E4%B8%AD%E5%8F%AF%E8%83%BD%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98-(FAQ)#%E9%A1%B9%E7%9B%AE-demo-%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E6%97%A0%E6%B3%95%E6%9F%A5%E7%9C%8B%E4%BB%BB%E4%BD%95%E6%AD%8C%E5%8D%95%E4%BF%A1%E6%81%AF)

ok
