### ISSUE TITLE
树莓派安装可正常运行，点击反应迟钝，不知是否是硬件不支持还是我没有配置好

### ISSUE THREAD

**Issue by zhangyiming748** [qier222/YesPlayMusic#225]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）
使用的是raspiberry4B，安装armv7deb包，程序运行时响应需要十几秒，不知是哪里出问题了

**Comment by qier222** [comment]
没树莓派没办法测试😅

**Comment by GreenTeodoro839** [comment]
能打开吗？我的白屏

**Comment by zhangyiming748** [comment]
可以打开 正常使用 我安装的是 deb 版的 依赖不全需要dpkg安装后`sudo apt-get -f install`

GreenTeodoro839 <notifications@github.com> 于2021年2月7日周日 上午6:18写道：

**Comment by yanranxiaoxi** [comment]
树莓派 4B 4G 版本，安装 YesPlayMusic_0.3.3_armv7l.deb 包，测试使用没有问题，你是不是尝试检查一下网络故障之类的，白屏可能内置 api 没有返回数据

**Comment by zhangyiming748** [comment]
谢谢 我看看

久治明千树汐 <notifications@github.com> 于2021年2月13日周六 上午2:04写道：
