### ISSUE TITLE
无法自动跟随系统深色模式

### ISSUE THREAD

**Issue by xuan-ish3** [qier222/YesPlayMusic#2279]
客户端版本0.4.8
作業系統： KDE neon 6.0
KDE Plasma 版本： 6.1.3
KDE Frameworks 版本： 6.4.0
![螢幕截圖_20240730_010227](https://github.com/user-attachments/assets/98f9269c-66c9-4ae1-aef6-fa5fb13830a8)

**Comment by GrassBlock1** [comment]
使用 AUR 最新的 Yesplaymusic 未能发现此问题。
操作系统： Arch Linux 
KDE Plasma 版本： 6.1.4
KDE 程序框架版本： 6.4.0

![图片](https://github.com/user-attachments/assets/26b3b3a7-f918-4694-97a4-589d24007647)
