### ISSUE TITLE
为啥成了空白页面了？

### ISSUE THREAD

**Issue by sdlkhfksl** [qier222/YesPlayMusic#2288]
![Uploading 屏幕截图 2024-08-19 163031.jpg…]()

**Comment by Niubility-SunLight** [comment]
+1

**Comment by dajgduyqwgdq** [comment]
+1

**Comment by HyperCherry** [comment]
在今天15:00左右，因基础设施故障，导致网易云音乐各端无法正常使用，现在已陆续恢复。此项目为网易云音乐播放器，故收到了影响。
Ref: [微博正文-网易云音乐](https://m.weibo.cn/detail/5069100965695327)
