### ISSUE TITLE
Linux软件标题栏字体无法显示

### ISSUE THREAD

**Issue by puddinging** [qier222/YesPlayMusic#2290]
![image](https://github.com/user-attachments/assets/57773ba5-ff4f-4c78-8426-fedbbaea503d)
如图标题栏位置字体无法显示
系统以及字体如图
![image](https://github.com/user-attachments/assets/83a9e05e-6781-4620-ad3f-e414138343d5)

**Comment by HyperCherry** [comment]
可以检查一下系统中所含字体
https://github.com/qier222/YesPlayMusic/blob/481ba6bce3a53c1ec0131a62821c3e2279961732/src/components/LinuxTitlebar.vue#L90
我在Gome下显示无异常
![image](https://github.com/user-attachments/assets/9d81a82b-348a-4c7a-862e-fe93d14a508c)

**Comment by puddinging** [comment]
> 可以检查一下系统中所含字体
> 
> https://github.com/qier222/YesPlayMusic/blob/481ba6bce3a53c1ec0131a62821c3e2279961732/src/components/LinuxTitlebar.vue#L90
> 
> 
> 我在Gome下显示无异常（已安装[微软字体](https://wiki.archlinuxcn.org/wiki/%E5%BE%AE%E8%BD%AF%E5%AD%97%E4%BD%93))
> ![image](https://private-user-images.githubusercontent.com/20416586/359833773-9d81a82b-348a-4c7a-862e-fe93d14a508c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODIyNTEsIm5iZiI6MTcyNDk4MTk1MSwicGF0aCI6Ii8yMDQxNjU4Ni8zNTk4MzM3NzMtOWQ4MWE4MmItMzQ4YS00YzdhLTg2MmUtZmU5M2QxNGE1MDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAxMzkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMDZmODJhNDY3MzBhNTA4NGJlZjI3NjliZGRiNTdjYjIwMjc5YzdiYTBkMmQ5MmM3MmU0NDhlOWQ2MzNjODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nwJpEaIsSvtfuby-Yv6RM6J3r-F1MekOL5gf1JaHhwE)



> 可以检查一下系统中所含字体
> 
> https://github.com/qier222/YesPlayMusic/blob/481ba6bce3a53c1ec0131a62821c3e2279961732/src/components/LinuxTitlebar.vue#L90
> 
> 
> 我在Gome下显示无异常（已安装[微软字体](https://wiki.archlinuxcn.org/wiki/%E5%BE%AE%E8%BD%AF%E5%AD%97%E4%BD%93))
> ![image](https://private-user-images.githubusercontent.com/20416586/359833773-9d81a82b-348a-4c7a-862e-fe93d14a508c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODI0OTUsIm5iZiI6MTcyNDk4MjE5NSwicGF0aCI6Ii8yMDQxNjU4Ni8zNTk4MzM3NzMtOWQ4MWE4MmItMzQ4YS00YzdhLTg2MmUtZmU5M2QxNGE1MDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAxNDMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYmE4ZDY2OGNlMGY3OWI3ZGY4MjkwYTE1Mzc1YzZlOWZiNjA1ZWM4M2Y3N2YwMzFmZWVlYTdmNTYwNjYyNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jROeVdHWe7VyaNZcCsiph0MNdWIS4GU37qHL209Tzog)

非常感谢，安装字体后可以正常显示了

**Comment by puddinging** [comment]
安装微软雅黑字体后已解决

**Comment by puddinging** [comment]
安装微软雅黑后已解决

**Comment by pugaizai** [comment]
其实是因为老版本electron无法显示vf字体导致的
