### ISSUE TITLE
“ docker build -t yesplaymusic . ” 失败

### ISSUE THREAD

**Issue by w316525096** [qier222/YesPlayMusic#2293]
SSH 输出如下：

> ~/github_downloads/YesPlayMusic$ docker build -t yesplaymusic .
> [+] Building 106.7s (13/17)                                                                                                                                                    docker:default
>  => [internal] load build definition from Dockerfile                                                                                                                                     0.2s
>  => => transferring dockerfile: 1.11kB                                                                                                                                                   0.1s
>  => [internal] load metadata for docker.io/library/nginx:1.20.2-alpine                                                                                                                   4.4s
>  => [internal] load metadata for docker.io/library/node:16.13.1-alpine                                                                                                                   4.7s
>  => [internal] load .dockerignore                                                                                                                                                        0.1s
>  => => transferring context: 199B                                                                                                                                                        0.0s
>  => [build 1/7] FROM docker.io/library/node:16.13.1-alpine@sha256:0e071f3c5c84cffa6b1035023e1956cf28d48f4b36e229cef328772da81ec0c5                                                       0.0s
>  => [internal] load build context                                                                                                                                                        0.2s
>  => => transferring context: 10.57kB                                                                                                                                                     0.0s
>  => CACHED [app 1/5] FROM docker.io/library/nginx:1.20.2-alpine@sha256:016789c9a2d021b2dcb5e1c724c75ab0a57cc4e8cd7aab7bb28e69fec7c8c4fc                                                  0.0s
>  => CACHED [build 2/7] WORKDIR /app                                                                                                                                                      0.0s
>  => CACHED [build 3/7] RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories && apk add --no-cache python3 make g++ git                             0.0s
>  => CACHED [build 4/7] COPY package.json yarn.lock ./                                                                                                                                    0.0s
>  => CACHED [build 5/7] RUN yarn install                                                                                                                                                  0.0s
>  => CACHED [build 6/7] COPY . .                                                                                                                                                          0.0s
>  => ERROR [build 7/7] RUN yarn config set electron_mirror https://npmmirror.com/mirrors/electron/ &&     yarn build                                                                     95.4s
> ------
>  > [build 7/7] RUN yarn config set electron_mirror https://npmmirror.com/mirrors/electron/ &&     yarn build:
> 3.679 yarn config v1.22.15
> 3.745 success Set "electron_mirror" to "https://npmmirror.com/mirrors/electron/".
> 3.746 Done in 0.10s.
> 4.044 yarn run v1.22.15
> 4.120 $ vue-cli-service build
> 10.92
> 10.92 -  Building for production...
> 91.23  ERROR  Failed to compile with 2 errors7:13:49 AM
> 91.23
> 91.23  error  in ./src/components/TrackListItem.vue
> 91.23
> 91.23 Module Error (from ./node_modules/eslint-loader/index.js):
> 91.23
> 91.23 /app/src/components/TrackListItem.vue
> 91.23   45:16  error    Replace `·v-if="isAlbum·&&·(track.mark·&·1048576)·===·1048576"` with `⏎············v-if="isAlbum·&&·(track.mark·&·1048576)·===·1048576"⏎···········`  prettier/prettier
> 91.23   98:5   warning  Prop 'trackProp' requires default value to be set                                                                                                     vue/require-default-prop
> 91.23   99:5   warning  Prop 'trackNo' requires default value to be set                                                                                                       vue/require-default-prop
> 91.23
> 91.23 ✖ 3 problems (1 error, 2 warnings)
> 91.23   1 error and 0 warnings potentially fixable with the `--fix` option.
> 91.23
> 91.23
> 91.23  @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/TrackList.vue?vue&type=script&lang=js 8:0-59 14:4-17
> 91.23  @ ./src/components/TrackList.vue?vue&type=script&lang=js
> 91.23  @ ./src/components/TrackList.vue
> 91.23  @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/dailyTracks.vue?vue&type=script&lang=js
> 91.23  @ ./src/views/dailyTracks.vue?vue&type=script&lang=js
> 91.23  @ ./src/views/dailyTracks.vue
> 91.23  @ ./src/router/index.js
> 91.23  @ ./src/main.js
> 91.23  @ multi ./src/main.js
> 91.23
> 91.23  error  in ./src/views/album.vue
> 91.23
> 91.23 Module Error (from ./node_modules/eslint-loader/index.js):
> 91.23
> 91.23 /app/src/views/album.vue
> 91.23   31:16  error  Replace `·v-if="(album.mark·&·1048576)·===·1048576"` with `⏎············v-if="(album.mark·&·1048576)·===·1048576"⏎···········`  prettier/prettier
> 91.23
> 91.23 ✖ 1 problem (1 error, 0 warnings)
> 91.23   1 error and 0 warnings potentially fixable with the `--fix` option.
> 91.23
> 91.23
> 91.23  @ ./src/router/index.js 32:19-46
> 91.23  @ ./src/main.js
> 91.23  @ multi ./src/main.js
> 91.23
> 91.34  ERROR  Build failed with errors.
> 92.00 error Command failed with exit code 1.
> 92.00 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ------
> Dockerfile:9
> --------------------
>    8 |     COPY . .
>    9 | >>> RUN yarn config set electron_mirror https://npmmirror.com/mirrors/electron/ && \
>   10 | >>>     yarn build
>   11 |
> --------------------
> ERROR: failed to solve: process "/bin/sh -c yarn config set electron_mirror https://npmmirror.com/mirrors/electron/ &&     yarn build" did not complete successfully: exit code: 1

代码贴的有问题，https://pastebin.ai/raw/al3xpd7t3n

相关问题：https://github.com/qier222/YesPlayMusic/issues/1260

**Comment by FrzMtrsprt** [comment]
现在的主分支就是有问题的，可以看action里也是一样的问题，可以checkout最近成功的commit构建。

**Comment by FrzMtrsprt** [comment]
主分支已经修复了相关问题，现在应该不会再构建失败了
