### ISSUE TITLE
网易云音乐多次要求我修改密码

### ISSUE THREAD

**Issue by CorvinYu** [qier222/YesPlayMusic#2299]
最近网易云音乐总是要求我重新设置密码后登录。重新设置密码后次日再次要求重设密码。目前重复了三次。没有使用其他第三方插件，因此推测可能是YesPlayMusic造成的。也可能是梯子的原因。

目前正在和云音乐客服沟通，确认情况。

客户端 v0.4.8
win 11 23H2

**Comment by Xiue233** [comment]
我也是这种情况，账号为黑胶VIP，不知道普通用户如何，可能是防止共享VIP账号的手段。

这是官方客服的回复：“亲亲，系统检测到您的账号存在安全风险，影响您的账号安全，建议检查当前设备是否存在下列场景：例如越狱/安装插件/外挂等，以及是否使用第三方平台。如有，辛苦删除插件等尝试手机重启，或者尝试更换其他设备再尝试操作，感谢您的理解与支持。”

同时，反馈给客服后无任何作为，账号仍会不时被封禁，在使用一段时间yesplaymusic后。

**Comment by CuSO4Deposit** [comment]
使用 YesPlayMusic 时提交的 ip 为内网 ip（172.16.0.0/12），可能更容易触发风控。

YesPlayMusic log：

```
[ERR] /login?xxxxxx
status: 400
body: {
  code: 702,
  message: '密码有安全风险',
  redirectUrl: 'https://xxx'
}
```

**Comment by Ashenone-62** [comment]
+1，最近老是重登，还以为是网易云改成单点登录了。。

**Comment by Nico0825** [comment]
+1，很多次了

**Comment by StarsEnd33A2D17** [comment]
相同情况。是所有使用neteasecloudmusicapi的项目都遇到了这个问题，还是只有yesplaymusic？尝试更新neteasecloudmusicapi版本至4.22.0？

**Comment by CuSO4Deposit** [comment]
第一个问题不清楚，第二个问题我是使用 NeteaseCloudMusicApi 4.22.0 的，同样遇到了这一情况。

**Comment by StarsEnd33A2D17** [comment]
.env带个VUE_APP_REAL_IP=xxx build一个试试？

有使用`公网NeteaseCloudMusicApi后端+网页版`的遇到这个问题吗

**Comment by Lucas04-nhr** [comment]
插个锚点，我用的mac版本从release下载的安装包也出现了这个问题，可能是官方改了风控逻辑的原因

**Comment by whiletoken** [comment]
+1 每隔两三天要重新登录并且重置密码

**Comment by cshjin** [comment]
+1 
![Screenshot_20240928_093435_NetEase_Music 1](https://github.com/user-attachments/assets/73b9c90e-ad66-44cf-a696-e87f5d2b09a5)

**Comment by zpatronus** [comment]
+1 是最近出现的问题，认同这个分析。看起来是针对非国内ip

> 插个锚点，我用的mac版本从release下载的安装包也出现了这个问题，可能是官方改了风控逻辑的原因

**Comment by wcshen** [comment]
+1 已经改了四五次密码 :(

**Comment by StarsEnd33A2D17** [comment]
real_ip后目前正常了几天，再试几天看看还会不会👀
或者网易云音乐不再有这样的行为了？
如果在9.30以后使用release版本仍然遇到这样的问题，点个👀↓
尝试使用[这个版本](https://github.com/StarsEnd33A2D17/YesPlayMusic/actions/runs/11094001106)**并设置你的real_ip**，如果仍然遇到问题，点个😕↓
如果有新的神秘信息要分享，Add a comment

**Comment by CuSO4Deposit** [comment]
同步信息：我尝试使用 vercel 部署的带 real_ip 环境变量的 webapp build（使用 NeteaseCloudMusicApi 4.22.0）测试。

real_ip 功能工作正常（i.e. 发送的 ip 为设置的环境变量值），在 09.29 被风控，存活时间大约是 3 天。

**Comment by lanthth** [comment]
我这个月已经改了5次密码了(┙>∧<)┙へ┻┻

**Comment by xpe-online** [comment]
+1
以及喜报：我网易云今天被冻结了

**Comment by moetayuko** [comment]
补充一个样本，我从 24/9/17 开始每隔 2~3 天就自动退出登录并强制重置密码，今天喜提封号

**Comment by Ives-Natsume** [comment]
> +1 以及喜报：我网易云今天被冻结了

我也是哈哈哈，本来想转战spotify和youtube music，但是支付地区一直过不去，没办法只能用国区apple music了

**Comment by Lucas04-nhr** [comment]
我自从发现频繁强制更改密码后就卸载了 YesPlayMusic，改用官方经过 Electron 套壳重构的 beta 版，如果最近有遇到强制更改密码的用户建议暂时停止使用 YesPlayMusic 以避免封号风险。

beta 版本的网易云音乐 macOS 端和 Windows 端已经开启公测，可以从官网下载页面获取，个人感觉优化的还算可以，并且功能也更加完善。

---

Since I discovered the frequent mandatory changes to the password, I uninstalled YesplayMusic and switch to the BETA version restructured by the official through the Electron sleeve. If you  encounter to change password mandatorily, it is recommended to temporarily stop using YesplayMusic to avoid the risk of account title.

The BETA versions for both macOS and Windows have started public testing. They can be downloaded from the official website. In my opinion, the optimization is quite good, and the features are also more comprehensive.

**Comment by moetayuko** [comment]
> beta 版本的网易云音乐 macOS 端和 Windows 端已经开启公测，可以从官网下载页面获取

电子化了都不给 linux 打包，属实难绷

**Comment by Lucas04-nhr** [comment]
> > beta 版本的网易云音乐 macOS 端和 Windows 端已经开启公测，可以从官网下载页面获取
> 
> 电子化了都不给 linux 打包，属实难绷

💩 由此看来鹅厂比猪场还是要勤劳一些的（指 QQNT）

**Comment by moetayuko** [comment]
> real_ip后目前正常了几天，再试几天看看还会不会👀 或者网易云音乐不再有这样的行为了？ 如果在9.30以后使用release版本仍然遇到这样的问题，点个👀↓ 尝试使用[这个版本](https://github.com/StarsEnd33A2D17/YesPlayMusic/actions/runs/11094001106)**并设置你的real_ip**，如果仍然遇到问题，点个😕↓ 如果有新的神秘信息要分享，Add a comment

试试这个办法？https://gitlab.com/Binaryify/neteasecloudmusicapi/-/issues/25#note_2139438666

**Comment by Lucas04-nhr** [comment]
> > real_ip后目前正常了几天，再试几天看看还会不会👀 或者网易云音乐不再有这样的行为了？ 如果在9.30以后使用release版本仍然遇到这样的问题，点个👀↓ 尝试使用[这个版本](https://github.com/StarsEnd33A2D17/YesPlayMusic/actions/runs/11094001106)**并设置你的real_ip**，如果仍然遇到问题，点个😕↓ 如果有新的神秘信息要分享，Add a comment
> 
> 试试这个办法？[gitlab.com/Binaryify/neteasecloudmusicapi/-/issues/25#note_2139438666](https://gitlab.com/Binaryify/neteasecloudmusicapi/-/issues/25#note_2139438666)

蹲后续，，不敢自己试了，怕被封号:alien:

**Comment by LemonTreeLT** [comment]
这个是一个时间段之后突然要求退出登陆改密码，还是购买黑胶vip之后才频繁要求改密码？
我之前一直用的畅听会员，印象里是购买黑胶vip后才被骚扰

**Comment by cheanus** [comment]
> 这个是一个时间段之后突然要求退出登陆改密码，还是购买黑胶vip之后才频繁要求改密码？ 我之前一直用的畅听会员，印象里是购买黑胶vip后才被骚扰

本人畅听会员，每隔3天就强制换密码一次，现在不敢用了。

**Comment by Ives-Natsume** [comment]
> 我也是这种情况，账号为黑胶VIP，不知道普通用户如何，可能是防止共享VIP账号的手段。
> 
> 这是官方客服的回复：“亲亲，系统检测到您的账号存在安全风险，影响您的账号安全，建议检查当前设备是否存在下列场景：例如越狱/安装插件/外挂等，以及是否使用第三方平台。如有，辛苦删除插件等尝试手机重启，或者尝试更换其他设备再尝试操作，感谢您的理解与支持。”
> 
> 同时，反馈给客服后无任何作为，账号仍会不时被封禁，在使用一段时间yesplaymusic后。

老哥你是被封禁后成功解封过吗，虽然我以后不用网易云了，但我想登录账号导出歌单

**Comment by LemonTreeLT** [comment]
那应该是网易云政策变了

我目前还没被封禁，跟客服反馈掉登陆的问题要我等五个工作日

现在网易云又给api又禁第三方的，搞不懂他什么意思

**Comment by rango886** [comment]
这两天经常要重新登录，今天封号了，申诉中，用了七八年的老号，很多歌单。如果申诉不回来，那就再也不用网易的东西了，垃圾网易云

**Comment by Boneflame** [comment]
同楼上，也是8年老号了，买了好几年的黑胶vip，听歌10w+，如果申诉不成功只能另谋平台了

**Comment by lanthth** [comment]
我前面改了几次密码后就没有登陆过YesPlayMusic了, 也没封号也没继续要求改密码(´・ω・｀)

**Comment by s12mmm3** [comment]
更新最新API试试
![image](https://github.com/user-attachments/assets/fb124fce-153f-4905-b3b9-3fd499af634e)

**Comment by FallingSakura** [comment]
我也是

**Comment by LMingAn** [comment]
我的也是，补个人工客服记录
![Uploading 3f8178a45d15ce56042d4046450642d9_720.png…]()

**Comment by LMingAn** [comment]
我的也是，补个人工客服记录
![3f8178a45d15ce56042d4046450642d9_720](https://github.com/user-attachments/assets/04323a57-825d-4ed5-8bc0-2a0875d6ac65)

**Comment by lanthth** [comment]
> 我的也是，补个人工客服记录 ![3f8178a45d15ce56042d4046450642d9_720](https://private-user-images.githubusercontent.com/113867200/373512505-04323a57-825d-4ed5-8bc0-2a0875d6ac65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNTM5ODUsIm5iZiI6MTcyODA1MzY4NSwicGF0aCI6Ii8xMTM4NjcyMDAvMzczNTEyNTA1LTA0MzIzYTU3LTgyNWQtNGVkNS04YmMwLTJhMDg3NWQ2YWM2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxNDU0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDdjYTk5NmMzNWM2YzUzNzU2YWUzODMyYjgzYWJhYWRkMzQzNGZmMzM4YjkzMmJlYTdkNjhhY2I4YTk5YmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cfMdxC16Ur4rK52DpJF_LJzyW59jaBmSOQ2rvLYaBdg)

工号0721  Σ(っ°Д °;)っ

**Comment by cheanus** [comment]
我是archlinux用户，畅听会员，目前[netease-cloud-music-gtk](https://github.com/gmg137/netease-cloud-music-gtk)用了快一周，没再被强制要求改密码了。
所以大概是API上的问题，修改后应该就可以继续用了。

**Comment by FallingSakura** [comment]
补个现状：账号已被冻结，申诉不成功。

**Comment by Ives-Natsume** [comment]
> 补个现状：账号已被冻结，申诉不成功。

根据多人的客服反馈，用api只会冻结三天，我也被冻结过，现在已经自动解封了

**Comment by FallingSakura** [comment]
> > 补个现状：账号已被冻结，申诉不成功。
> 
> 根据多人的客服反馈，用api只会冻结三天，我也被冻结过，现在已经自动解封了

是这样的，我刚才去问了，8号解封，还有就是怎么修改API啊

**Comment by CorvinYu** [comment]
搬运一些官方电报群里的讨论
---
9月21日
![image](https://github.com/user-attachments/assets/64744a2c-4cdd-4a26-86c3-109fe8f9ec28)
---
10月4日
![image](https://github.com/user-attachments/assets/d385789d-e410-432b-8208-4fd23a17ae41)
---
10月7日
![image](https://github.com/user-attachments/assets/8c2cab9e-885f-4fcc-8000-cc72ead2065c)
---
总结一下：
1. 有没有可能是梯子造成的，这一点目前只有Mr Sugarcane君提出过，没有其他相关讨论。
2. 目前看来还没有出现有效的解决措施，大家依然在观望网易云的态度。

**Comment by zhouhao** [comment]
我也10年老号+黑椒，被封了。。。无语

**Comment by Lucas04-nhr** [comment]
请问有哪位大佬能提供一下经过修改后的版本打包好的文件吗，我在本地进行打包macOS arm64版本时出现`Building modern bundle for production...Error: error:0308010C:digital envelope routines::unsupported`错误。
<img width="730" alt="Snipaste_2024-11-01_19-45-53@2x" src="https://github.com/user-attachments/assets/c3de166b-0e91-4f72-871b-2e4a86e84af8">

**Comment by StarsEnd33A2D17** [comment]
@Lucas04-nhr 检查[https://github.com/StarsEnd33A2D17/YesPlayMusic/actions/runs/11633095479](https://github.com/StarsEnd33A2D17/YesPlayMusic/actions/runs/11633095479)试试
抱歉，我没有mac，无法测试

**Comment by Lucas04-nhr** [comment]
> @Lucas04-nhr 检查[StarsEnd33A2D17/YesPlayMusic/actions/runs/11633095479](https://github.com/StarsEnd33A2D17/YesPlayMusic/actions/runs/11633095479)试试 抱歉，我没有mac，无法测试

OK!thx)

**Comment by Clarkkkk** [comment]
> 请问有哪位大佬能提供一下经过修改后的版本打包好的文件吗，我在本地进行打包macOS arm64版本时出现`Building modern bundle for production...Error: error:0308010C:digital envelope routines::unsupported`错误。 <img alt="Snipaste_2024-11-01_19-45-53@2x" width="730" src="https://private-user-images.githubusercontent.com/117806313/382270723-c3de166b-0e91-4f72-871b-2e4a86e84af8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTQ1NjQsIm5iZiI6MTczMTU5NDI2NCwicGF0aCI6Ii8xMTc4MDYzMTMvMzgyMjcwNzIzLWMzZGUxNjZiLTBlOTEtNGY3Mi04NzFiLTJlNGE4NmU4NGFmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNDI0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDBlMjhmMjBmMmUzOTg1YzhmYTZiYjQzZGI2ZWY2OTdkOTUwN2M3ODcwZmEwMjdhMTY5YzFhOTM2MjE1YWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5-rYljOASaja-xUFYGRxlQ-bBbTCkNuq3nW-AYVDuWE">

看错误应该和node版本有关系，试试降级node版本

**Comment by Lucas04-nhr** [comment]
> > 请问有哪位大佬能提供一下经过修改后的版本打包好的文件吗，我在本地进行打包macOS arm64版本时出现`Building modern bundle for production...Error: error:0308010C:digital envelope routines::unsupported`错误。 <img alt="Snipaste_2024-11-01_19-45-53@2x" width="730" src="https://private-user-images.githubusercontent.com/117806313/382270723-c3de166b-0e91-4f72-871b-2e4a86e84af8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTQ1NjQsIm5iZiI6MTczMTU5NDI2NCwicGF0aCI6Ii8xMTc4MDYzMTMvMzgyMjcwNzIzLWMzZGUxNjZiLTBlOTEtNGY3Mi04NzFiLTJlNGE4NmU4NGFmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNDI0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDBlMjhmMjBmMmUzOTg1YzhmYTZiYjQzZGI2ZWY2OTdkOTUwN2M3ODcwZmEwMjdhMTY5YzFhOTM2MjE1YWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5-rYljOASaja-xUFYGRxlQ-bBbTCkNuq3nW-AYVDuWE">
> 
> 看错误应该和node版本有关系，试试降级node版本

已经用上面那位大佬的Workflow打包好了，谢谢您指出问题！
