### ISSUE TITLE
10.3 网易云账号被封

### ISSUE THREAD

**Issue by popsans** [qier222/YesPlayMusic#2309]
10.3 12.00起来登录，发现客户端掉登录，手机端上网易云音乐账号被冻结
![QQ20241003-122609](https://github.com/user-attachments/assets/c6b4b46d-3d1d-4991-8053-7787b4ef4c3b)
![image](https://github.com/user-attachments/assets/bc0ad021-6f0d-44ef-bd9e-99dbd64e5792)

浏览器EDGE win10专业版

以及跟这个问题有关的是经常退登录，每次登录还需要去网易云改密码

**Comment by Boneflame** [comment]
同被封，也是每隔3天左右就被退出登录要求改密码。在手机客户端里搜过账号相关问题，其中提到若使用第三方客户端会被网易视作账号有风险。

**Comment by goodbird2** [comment]
+1

**Comment by Noah0115** [comment]
+1 我也被封了

**Comment by bajiuqier** [comment]
+1

**Comment by LAST7** [comment]
+1 我是用隔壁 Electron-Netease-Cloud-Music 的，也被冻结了

**Comment by Shyliuli** [comment]
补充：
申诉失败

**Comment by deerdoomer** [comment]
+1

**Comment by Dong-Zhouhong** [comment]
+1

**Comment by Yanfreak** [comment]
Same here. 同样申诉失败，看来多年账号要废掉了。

**Comment by Young143l** [comment]
> Same here. 同样申诉失败，看来多年账号要废掉了。

问了一下客服,封号三天,还能拿回来
![Uploading Screenshot_2024-10-04-13-13-55-33_25d38497d72d75227633ae777c2e0df5.jpg…]()

**Comment by Ives-Natsume** [comment]
> > Same here. 同样申诉失败，看来多年账号要废掉了。
> 
> 问了一下客服,封号三天,还能拿回来
> ![Uploading Screenshot_2024-10-04-13-13-55-33_25d38497d72d75227633ae777c2e0df5.jpg…]()
> 

为什么github app和网页都看不了你的图片😂

**Comment by zhuozhiyongde** [comment]
![image](https://github.com/user-attachments/assets/22e5db92-cb76-4a1e-bcb7-33905c0a1e29)

唉，卑微...

打算解封之后就着手转战 Apple Music 了...

**Comment by popsans** [comment]
网易也是个傻逼，如果自己账号不是黑胶会员在yesmusic上听不了vip的歌，
所以相当于只使用了个第三方放他的音源，结果就这样还不乐意了

**Comment by Ives-Natsume** [comment]
> 唉，卑微...
> 
> 打算解封之后就着手转战 Apple Music 了...

连续申诉两次都没通过，我还以为给我永久注销了，转头买了apple music和spotify哈哈

恢复后第一件事下载所有已购单曲，第二件事导出所有歌单，第三件事注销卸载一条龙

**Comment by Young143l** [comment]
> > 唉，卑微...
> > 打算解封之后就着手转战 Apple Music 了...
> 
> 连续申诉两次都没通过，我还以为给我永久注销了，转头买了apple music和spotify哈哈
> 
> 恢复后第一件事下载所有已购单曲，第二件事导出所有歌单，第三件事注销卸载一条龙

我也准备转战Apple Music了,但发现没有linux版的😂

**Comment by Shyliuli** [comment]
> > > 唉，卑微...
> > > 打算解封之后就着手转战 Apple Music 了...
> > 
> > 
> > 连续申诉两次都没通过，我还以为给我永久注销了，转头买了apple music和spotify哈哈
> > 恢复后第一件事下载所有已购单曲，第二件事导出所有歌单，第三件事注销卸载一条龙
> 
> 我也准备转战Apple Music了,但发现没有linux版的😂

我转qq音乐了，在网易云上搜索用户名找到歌单，然后复制分享链接
到qq音乐（手机端）新建歌单，选择导入，把链接填进去，就可以同步了
因为部分歌曲的版权问题，可能有些歌没有或者不是原版233

**Comment by popsans** [comment]
学到了，这几天正愁没歌听

**Comment by popsans** [comment]
今天解封了，感觉不敢用了，老老实实网易云得了

**Comment by CorvinYu** [comment]
#2299

**Comment by MakiseKurisu** [comment]
所以申诉是在哪里才能进行的？非要android么？我在网页上登录后提示冻结就没别的选项了。

**Comment by WillaBeast55** [comment]
Knock it off!

**Comment by umoiiz** [comment]
> 所以申诉是在哪里才能进行的？非要android么？我在网页上登录后提示冻结就没别的选项了。

申诉没用的, 一般封个3天或者7天, 我已经是第二个7天了, 只要是第三方现在都会封, 只能说网易云死吗了

**Comment by october-rain** [comment]
+1 被封，真恶心啊
