### ISSUE TITLE
实现像Apple Music这种歌词界面背景根据专辑图的模糊效果

### ISSUE THREAD

**Issue by Ssiswent** [qier222/YesPlayMusic#231]
* 希望实现像Apple Music这种歌词界面背景根据专辑图的模糊效果
![image](https://user-images.githubusercontent.com/37449310/106901899-3380bc80-6733-11eb-9bff-bbb669f92d47.png)

* 希望添加一些全局主题色或者自定义主题色
* 另外请问这里最下面那个设置是什么意思呀- -
![image](https://user-images.githubusercontent.com/37449310/106902380-bc97f380-6733-11eb-9e9c-202a07f759ab.png)

**Comment by montbell** [comment]
播放进度条   你试试不就知道了嘛

**Comment by Ssiswent** [comment]
😂不好意思，没注意到= =

**Comment by qier222** [comment]
apple music那种效果我暂时不知道怎么实现
全局主题色这个可以考虑添加

**Comment by hawtim** [comment]
> apple music那种效果我暂时不知道怎么实现
> 全局主题色这个可以考虑添加

https://developer.mozilla.org/en-US/docs/Web/CSS/filter
应该是 filter: blur(10px) 之类的

**Comment by qier222** [comment]
> > apple music那种效果我暂时不知道怎么实现
> 
> > 全局主题色这个可以考虑添加
> 
> 
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/filter
> 
> 应该是 filter: blur(10px) 之类的

需要从专辑封面中提取颜色，然后生成渐变或色块，然后生成动画

**Comment by Ssiswent** [comment]
> apple music那种效果我暂时不知道怎么实现
> 全局主题色这个可以考虑添加

好滴，谢谢啦~

**Comment by qier222** [comment]
v0.3.5 版本已支持，需要去设置页面开启这个选项

**Comment by Ssiswent** [comment]
> v0.3.5 版本已支持，需要去设置页面开启这个选项

牛逼！！！
