### ISSUE TITLE
使用网易云app扫码登陆会导致yesplay和手机网易云的账号强制退出，今天不仅退出账号，还封禁网易云账号了

### ISSUE THREAD

**Issue by 1500302679** [qier222/YesPlayMusic#2310]
如题，不知道是不是扫码登陆的问题，还是说都有问题，望周知

**Comment by WHNMJr44** [comment]
破案，是都被封号了，真恶心啊

**Comment by Dong-Zhouhong** [comment]
我也是而且申诉不成功

**Comment by FrzMtrsprt** [comment]
似乎是所有用网页端api的登录请求都会被封号，见 https://t.me/hyplayer/112
只能等YesPlayMusic改成pc端或者手机端的登录api（如果有人能够提一个pr且@pan93412大佬还肯维护的话）

**Comment by 1500302679** [comment]
> 似乎是所有用网页端api的登录请求都会被封号，见 https://t.me/hyplayer/112 只能等YesPlayMusic改成pc端或者手机端的登录api（如果有人能够提一个pr且@pan93412大佬还肯维护的话）

现在账号申述都失败了，怕是拿不回来了

**Comment by Young143l** [comment]
> > 似乎是所有用网页端api的登录请求都会被封号，见 https://t.me/hyplayer/112 只能等YesPlayMusic改成pc端或者手机端的登录api（如果有人能够提一个pr且@pan93412大佬还肯维护的话）
> 
> 现在账号申述都失败了，怕是拿不回来了

问客服了,封三天
![Uploading Screenshot_2024-10-04-13-13-55-33_25d38497d72d75227633ae777c2e0df5.jpg…]()

**Comment by pan93412** [comment]
> 似乎是所有用网页端api的登录请求都会被封号，见 [t.me/hyplayer/112](https://t.me/hyplayer/112) 只能等YesPlayMusic改成pc端或者手机端的登录api（如果有人能够提一个pr且@pan93412大佬还肯维护的话）

大概要等 PR，我沒在用 YPM 了

**Comment by BlueSword03** [comment]
> 似乎是所有用网页端api的登录请求都会被封号，见 https://t.me/hyplayer/112 只能等YesPlayMusic改成pc端或者手机端的登录api（如果有人能够提一个pr且@pan93412大佬还肯维护的话）

[https://github.com/HyPlayer/HyPlayer](HyPlayer)已经改成手机端的API了，但是有人依然会登录状态异常，且至少有5人以上被冻结（甚至包括开发组成员）

**Comment by 111inhistory** [comment]
> 似乎是所有用网页端api的登录请求都会被封号，见 https://t.me/hyplayer/112 只能等YesPlayMusic改成pc端或者手机端的登录api（如果有人能够提一个pr且@pan93412大佬还肯维护的话）

这个的话有人给上游提issues了，新版本api默认实现了设备模拟，默认的iPhone。目前我把api依赖版本升到最新了以后还是会有问题（网易云安全助手会发消息，说未知设备，但是到账号风险监测里去看又是iPhone……感觉网易云写了两段代码判断设备类型），我自己抓了下包发现是api设备模拟的参数写错了，如果把api默认模拟的设备改成pc的话，没法通知，但是我没后续测试了。目前我是用默认的，只是改成了正确的设备cookie。改好以后，马上一天了，还没有被封，也没有什么登录环境异常。先试试水吧。

**Comment by David-Zhang-test** [comment]
遇到了相似的问题，yesplaymusic使用手机网易云扫码登录时会使手机帐号退出

**Comment by 111inhistory** [comment]
> 遇到了相似的问题，yesplaymusic使用手机网易云扫码登录时会使手机帐号退出

我目前除了YesPlayMusic定期退登以外，一切都好。原因未知。继续观察。
