### ISSUE TITLE
不要登录！不要登录！不要登录！任何使用开源网易云api的软件 否则会被认定账号异常冻结三天

### ISSUE THREAD

**Issue by Hykerisme** [qier222/YesPlayMusic#2311]
早上起来账号被冻结了
去看了下各个网易云第三方客户端项目issue
都有人提到：
1.每次登陆后都会中途强制下线重置密码
2.重置几次后会冻结账号（据说冻三天）

本项目引用的网易云开源api在一月份就已经停止维护（版权问题被提到台面上 不得不跑路）

最近暂时不要登录任何第三方客户端，否则很可能会被风控

**Comment by delphius81** [comment]
对，我也被冻结了，问客服说是第三方插件的问题。应该是三天没错。明天会解封。。

**Comment by G1oow** [comment]
> 对，我也被冻结了，问客服说是第三方插件的问题。应该是三天没错。明天会解封。。

兄弟 客户在哪里问的

**Comment by GDiPD** [comment]
> 兄弟 客户在哪里问的

小号联系

**Comment by shenmo7192** [comment]
修复了的话是不是得发个新版或者把这个pin撤掉？

**Comment by pan93412** [comment]
沒測過不知道有沒有真的修好，但確實能發個版

**Comment by shenmo7192** [comment]
> 沒測過不知道有沒有真的修好，但確實能發個版

确实，先更新了再说吧

**Comment by IamFurina** [comment]
https://www.landiannews.com/archives/105994.html
相关新闻，因为网易云api使用的是网易云网页模拟登录，确实容易被封杀

**Comment by ZSXB2468** [comment]
刚被封（）

**Comment by trcrsired** [comment]
那现在不登录的话怎么用呀。很多音乐都放不了

**Comment by ZSXB2468** [comment]
> 那现在不登录的话怎么用呀。很多音乐都放不了

参考[大家用最新的v0.4.9版本现在不会封号了？ #2383 ]，最新代码删除了打卡功能后编译大概率不封号可以登录。
