### ISSUE TITLE
10.5被封，刚刚申诉客服还没有回应，大家注意些吧

### ISSUE THREAD

**Issue by GDiPD** [qier222/YesPlayMusic#2312]

**Comment by G1oow** [comment]
我的申诉没给通过 也是今天封的

**Comment by Dannyrojas6** [comment]
我昨天封的，今天重新登录下又可以进了，只不过和之前一样要重设密码

**Comment by Dannyrojas6** [comment]
最近还是别用第三方的了，将就用着官方的

**Comment by G1oow** [comment]
> 最近还是别用第三方的了，将就用着官方的
但凡官方软件简洁一点 谁用第三方啊

**Comment by G1oow** [comment]
> 最近还是别用第三方的了，将就用着官方的

太伟大了 网易云3.0

**Comment by GDiPD** [comment]
> 我的申诉没给通过 也是今天封的

我申诉也没通过，联系客服看意思是封三天

**Comment by G1oow** [comment]
国产软件现状就是 一个软件非要做成hub

**Comment by Dannyrojas6** [comment]
准备导出歌单跑路了，不声不响直接封号真逆天

**Comment by GDiPD** [comment]
> > 最近还是别用第三方的了，将就用着官方的
> > 但凡官方软件简洁一点 谁用第三方啊

官方的真是一坨

**Comment by G1oow** [comment]
> 准备导出歌单跑路了，不声不响直接封号真逆天

对啊 通知都没有一个 不联系客服 你连冻结理由都不知道

**Comment by G1oow** [comment]
> > > 最近还是别用第三方的了，将就用着官方的
> > > 但凡官方软件简洁一点 谁用第三方啊
> 
> 官方的真是一坨

我真不相信网易云官方团结 写不出比个人开发者优秀的软件 只能说丁三石 我传世你的梦

**Comment by GDiPD** [comment]
> 准备导出歌单跑路了，不声不响直接封号真逆天

跑路+1

**Comment by G1oow** [comment]
![04F6BB291C6057C7B557708721441FAB](https://github.com/user-attachments/assets/047140ba-513e-44e5-afd7-7255ecb48a1c)
666

**Comment by G1oow** [comment]
这下只能是屈服了

**Comment by Zefrain** [comment]
好几次了，手机登录都让我改密，还准备提个issue问问看情况，这进来一看全是啊。还是用apple music啊，哎，QQ网易都是翔，没事还推直播的流。

**Comment by JKeita** [comment]
手机客户端找人工客服可以解冻

**Comment by NodaSann** [comment]
我的也是，5号起来一看就被冻结了，真的离谱，问了半天也给了个完全对不上的理由，说是手机越狱或者安装插件、外挂等

**Comment by AppleYang530** [comment]
是的，近一个月隔两天手机端就要求修改密码登录。结果2号就被封了，6号解的封，客服也没给出具体理由，提交了要求具体违反条例又要等五个工作日，我看网易云也是不太想做了😅

**Comment by 2536629322** [comment]
能解吗

**Comment by GDiPD** [comment]
> 能解吗

应该都是封三天

**Comment by 2536629322** [comment]
> > 能解吗
> 
> 应该都是封三天

ok

**Comment by CorvinYu** [comment]
#2299
