### ISSUE TITLE
直接使用网页端cookie登陆会封号吗

### ISSUE THREAD

**Issue by ArisuYuki** [qier222/YesPlayMusic#2315]
前几天网页云大开杀戒，封了一堆号
好像据说是通过登陆接口来判断的
那么直接导入cookie避开登录的话还会封号吗
昨天尝试着用postman直接调网易云的api还能正常返回数据也没有封号，建议加入导入cookie登陆功能吧

**Comment by xiaozhi747** [comment]
我已经很久没用客户端了，近期一直用的网页端，都能误封

**Comment by Demolemon11** [comment]
我的账号已经被封了 wwwww

**Comment by SuDeeParke** [comment]
已经被封了

**Comment by jiangyh91** [comment]
被封了+1

**Comment by Leon-101** [comment]
被封了+1
13号解封了
用的客户端，之前经常被下线，要求改密码

**Comment by chenyuxuan2009** [comment]
被封了，今天重登发现解了

**Comment by dissipator** [comment]
建议在第二个仅需账号名登陆的功能里增加利用账号名拉取个人账户下收藏和歌单的功能。这样就应该不会被封吧
