### ISSUE TITLE
增加设置最大缓存大小的功能

### ISSUE THREAD

**Issue by jerryzcl** [qier222/YesPlayMusic#232]
1、打开歌词页面后再退回歌单界面时不能重新定位于正在播放的歌曲（需要从头浏览，有些影响体验）
2、在播放列表中点击歌曲播放无反应
3、添加歌曲时不能指定歌单添加
4、建议加入缓存动态管理功能

**Comment by qier222** [comment]
1这个问题已知晓
2、3、4这三个问题我没理解，麻烦再说详细点

**Comment by jerryzcl** [comment]
> 1、打开歌词页面后再退回歌单界面时不能重新定位于正在播放的歌曲（需要从头浏览，有些影响体验）
> 2、在播放列表中点击歌曲播放无反应
> 3、添加歌曲时不能指定歌单添加
> 4、建议加入缓存动态管理功能

从界面底部的播放列表中进入，点击即将播放中的歌曲，无法播放；
第3点已解决；
缓存动态管理就是比如说设定一个缓存限定值，达到限定值时自动将最开始播放的歌曲产生的缓存空间释放；或者提供一个接口，由使用者自主指定缓存地址。（不知道这样是否可行）
