### ISSUE TITLE
建议在第二个仅需账号名登陆的功能里增加利用账号名拉取个人账户下收藏和歌单的功能。这样就应该不会被封吧，就像pyncmd的拉取歌单功能。

### ISSUE THREAD

**Issue by dissipator** [qier222/YesPlayMusic#2322]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by Hykerisme** [comment]
以前是有这个功能的 不登陆也可以拉取用户歌单听歌 后来好像没了

**Comment by cxzlw** [comment]
> 以前是有这个功能的 不登陆也可以拉取用户歌单听歌 后来好像没了

是不是不登录看歌单被网易云砍了（网页版是只能看前几个）qaq
