### ISSUE TITLE
windows界面请求添加UnblockNeteaseMusic代理选项

### ISSUE THREAD

**Issue by leonyff** [qier222/YesPlayMusic#233]
windows界面请求添加 自己搭建的 UnblockNeteaseMusic代理选项，类似官方客户端这样的！

![image](https://user-images.githubusercontent.com/38803732/106950858-e696e900-6726-11eb-8e40-a555b746dad1.png)

**Comment by Ahgni** [comment]
请问这个自定义代理工具的功能是什么？谢谢

**Comment by qier222** [comment]
项目集成了UnblockMusic，是因为什么原因需要使用自己搭建的？

**Comment by Ahgni** [comment]
> 项目集成了UnblockMusic，是因为什么原因需要使用自己搭建的？

您好，海外用户还是好多音乐无法收听，可能是上面的版权限制吧。不知道您能否访问这个网站：https://www.mp3juices.cc/ 这上几乎可以听到任何歌曲~

**Comment by toure00** [comment]
> 项目集成了UnblockMusic，是因为什么原因需要使用自己搭建的？

默认启用了吗，我这还是有灰色的歌

**Comment by qier222** [comment]
已支持代理，等待发布新版本客户端吧
https://github.com/qier222/YesPlayMusic/commit/2b22c7e050ec1c3b5d30b5f6a658a58234167a39

**Comment by qier222** [comment]
0.3.7版本已发布
