### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by bingling60** [qier222/YesPlayMusic#2336]
没人提过这个 issue
树莓派上正常安装，运行后闪退
以下为当前系统信息
操作系统： Debian GNU/Linux 12
KDE Plasma 版本： 5.27.5
KDE 程序框架版本： 5.103.0
Qt 版本： 5.15.8
内核版本： 6.6.51+rpt-rpi-2712 (64 位)
图形平台： Wayland
处理器： 4 × ARM Cortex-A76
内存： 7.9 GiB 内存
图形处理器： V3D 7.1
产品名称： Raspberry Pi 5 Model B Rev 1.0

**Comment by StarsEnd33A2D17** [comment]
- 从终端运行，看看有啥输出。
- 尝试--enable-features=UseOzonePlatform --ozone-platform=wayland
- 尝试使用基于更新版本electron的,如[这个构建](https://github.com/StarsEnd33A2D17/YesPlayMusic/actions/runs/11235948731)
wayland可能相关的：#2300

**Comment by bingling60** [comment]
因为系统更新导致plasma wayland无法登入，我改用X11，在X11上同样闪退：
这一行是系统报告：
kf.kio.gui: Failed to register new cgroup: "app-yesplaymusic-8b12b7a84a5c4b4fad056856fb612c53.scope" "org.freedesktop.DBus.Error.UnixProcessIdUnknown" "Process with ID 6046 does not exist."

同时在命令行中允许显示：段错误（核心转储）

更新版本electron是需要自行编译安装吗？并未发现arm架构的安装包（github小白）
谢谢

**Comment by StarsEnd33A2D17** [comment]
查看<https://github.com/StarsEnd33A2D17/YesPlayMusic/actions/runs/11702752700>试试，electron 
22.3.27的，deb里有arm的构建。

不熟悉kde plasma，不太清楚这个问题。可以确定“系统更新”发生了什么更改吗

**Comment by bingling60** [comment]
感谢您的帮助，问题已在最新版本中得到解决，X11环境下软件不闪退，可以正常运行

**Comment by bingling60** [comment]
系统更新内容多，我也不清楚是那个软件引起故障，系统日志也没有报错，只能先用X11环境，后面重做系统，再使用waylan环境吧
