### ISSUE TITLE
控制栏（macOS最顶部的操作栏）播放图标点开来只能看到歌曲名字，看不到进度条

### ISSUE THREAD

**Issue by soberest288** [qier222/YesPlayMusic#236]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉
![291612593706_ pic](https://user-images.githubusercontent.com/78636153/107111245-718ff480-6889-11eb-909f-d338f060d685.jpg)

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by qier222** [comment]
这个需要Electron适配了才能做到，目前暂时无法修复

**Comment by soberest288** [comment]
嗯嗯，谢谢啊
