### ISSUE TITLE
歌曲播放页面的退出图标消失

### ISSUE THREAD

**Issue by GreyFlorence** [qier222/YesPlayMusic#239]
- 本地搭建的网页版
- Google Chrome浏览器
- 控制台 Console 页面的截图（按 F12 可打开控制台）

![image](https://user-images.githubusercontent.com/69356026/107113526-7315e880-689a-11eb-8a4b-4b39b324c103.png)

歌曲播放页面的退出图标消失，但是点击该按钮功能正常

**Comment by yanranxiaoxi** [comment]
@qier222 @GreyFlorence 这个问题之前有 issue 且已被关闭

这个问题是由于svg文件不存在造成的，不知道为什么作者在提交的时候丢失了三个svg文件，分别为 arrow-up.svg arrow-down.svg plus.svg，可以手动下载到这三个文件并放置于 /src/assets/icons 文件夹以解决该问题。

PS：可以去 https://www.iconfinder.com/ 找这三个 svg 图像。

**Comment by GreyFlorence** [comment]
@yanranxiaoxi 感谢，根据你的方法，这个问题已经解决了。@qier222 等作者上传相应的svg文件后再把这个issue close 了吧。

**Comment by GreyFlorence** [comment]
Duplicate of #187

**Comment by yanranxiaoxi** [comment]
已提交 PR
