### ISSUE TITLE
客户端没办法登录国内，最看重的是可以同步网易云，不行了， 网页端打不开

### ISSUE THREAD

**Issue by LEOGML** [qier222/YesPlayMusic#242]
客户端没办法登录国内，最看重的是可以同步网易云，不行了， 网页端打不开

**Comment by qier222** [comment]
哪里没办法登录？

**Comment by LEOGML** [comment]
昨天安装后试了好几次没成功一次，退出再登录也不行，我还试了卸载再安装也不行，登录后就空白，之后连登录页面都看不见了，今天看了你的回复，又重新下载0.3.3安装打开也没要登录账户，账户就是登录状态了，奇怪了。我刚刚看了我可能下载的是youtube中的up主分享的资源是0.3.1版本，他还分享了这个网页端https://music.qier222.com/是打不开的。抱歉

**Comment by LEOGML** [comment]
> 哪里没办法登录？
昨天安装后试了好几次没成功一次，退出再登录也不行，我还试了卸载再安装也不行，登录后就空白，之后连登录页面都看不见了，今天看了你的回复，又重新下载0.3.3安装打开也没要登录账户，账户就是登录状态了，奇怪了。我刚刚看了我可能下载的是youtube中的up主分享的资源是0.3.1版本，他还分享了这个网页端https://music.qier222.com/是打不开的。抱歉

**Comment by HuangYog** [comment]
我也无法登录，软件就是这下载的![20210207203601-JXsun8](http://qiniu.oss.mailangyun.cn//20210207203601-JXsun8.png)

**Comment by LEOGML** [comment]
> 我也无法登录，软件就是这下载的![20210207203601-JXsun8](https://camo.githubusercontent.com/7ae2fad24f666d56ed1e53ea762db58c413281a52c4eb908013a2bfe9af66b2f/687474703a2f2f71696e69752e6f73732e6d61696c616e6779756e2e636e2f2f32303231303230373230333630312d4a5873756e382e706e67)

我刚刚打开0.3.3版本还正常

**Comment by HuangYog** [comment]
@LEOGML 不知是什么情况，我使用的M1 的Mac mini确实无法登录,使用的是手机号登录，提示超时：发生错误，请检查你的账号密码是否正确
Error: timeout of 15000ms exceeded

账号密码是没有问题的，我在网页上都能登录！

**Comment by qier222** [comment]
是否开启了UnblockMusic服务？

**Comment by HuangYog** [comment]
@qier222 你说的UnblockMusic服务是个啥服务哦，不过我有软路由里面好像有个什么东西吧，我去检查一下

**Comment by HuangYog** [comment]
@qier222 果然是这个东西， 我去软路由里面关了之后瞬间就出来了
