### ISSUE TITLE
希望客户端深色模式时上方边框也能变为深色   感觉白色的边框有些难受

### ISSUE THREAD

**Issue by YC20020818** [qier222/YesPlayMusic#259]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by Nyyyb** [comment]
+1

**Comment by Nyyyb** [comment]
![image](https://user-images.githubusercontent.com/50623331/107628247-54995e00-6c9b-11eb-8f1b-9da446693227.png)

**Comment by qier222** [comment]
重复的issue #107 # 161
