### ISSUE TITLE
为什么有些网易云上的歌听不了？

### ISSUE THREAD

**Issue by blackcater** [qier222/YesPlayMusic#26]
我体验了一下，登录了网易云音乐账号，我在网易云音乐上可以听《Lordly (Remix)》这张专辑的歌曲，但在 YesPlayMusic 中，这张专辑是灰色的听不了，想知道这是什么问题？

**Comment by blackcater** [comment]
<img width="1002" alt="iShot2020-10-20 10 24 02" src="https://user-images.githubusercontent.com/9465551/96532398-67d48800-12be-11eb-83db-47af23c0929a.png">
<img width="1150" alt="iShot2020-10-20 10 23 37" src="https://user-images.githubusercontent.com/9465551/96532404-6a36e200-12be-11eb-89f3-e8f03df1e332.png">

**Comment by qier222** [comment]
这首歌是VIP才能听，现在还没支持VIP歌曲播放（我还没开会员
