### ISSUE TITLE
增加任务栏图标？

### ISSUE THREAD

**Issue by AKAPotato** [qier222/YesPlayMusic#261]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**WIndows客户端能否添加任务栏图标实现关闭窗口但不退出软件的功能？**

**Comment by qier222** [comment]
有人发过这样的issue了
