### ISSUE TITLE
release下的exe文件windows defender报毒

### ISSUE THREAD

**Issue by nmtzwh** [qier222/YesPlayMusic#262]
免安装版和安装版都是下载完直接被系统删了。

Trojan:Win32/Wacatac.D9!ml
This program is dangerous and executes commands from an attacker.

---
自己编译的electron版本（用当前master的代码，以及v0.3.1的netease_api），则没有这个问题。

**Comment by LinJinKang** [comment]
windows defender设置排除扫描下载文件夹或者关闭windows defender

**Comment by nmtzwh** [comment]
> windows defender设置排除扫描下载文件夹或者关闭windows defender

**Comment by nmtzwh** [comment]
问题不是怎么关闭杀毒软件放进来这个程序，而是这个程序里的什么内容是可疑的。个人怀疑是unblock的service可能会引起误报？
建议作者把electron的源码作为一个branch。

**Comment by zhangyz1997** [comment]
遇到WD误报还是可以在 https://www.microsoft.com/en-us/wdsi/submission/ 向微软反馈一下，这样比较稳妥

**Comment by SteamFinder** [comment]
> 问题不是怎么关闭杀毒软件放进来这个程序，而是这个程序里的什么内容是可疑的。个人怀疑是unblock的service可能会引起误报？
> 建议作者把electron的源码作为一个branch放出来大家可以一起检查测试。
> 
> Re 楼上：关闭杀毒软件是非常危险的行为。

**WD对于个人开发的软件误报很严重**
如有查杀需求，建议前往[VirusTotal](https://www.virustotal.com/)自行扫描
或者使用更加成熟稳定的杀毒软件
此外，安装程序与主程序是分离的，也就是说，在安装程序安装时一系列操作（注册产品，写入注册表，写入文件，创建快捷方式etc.)都有可能引起报毒

2021-02-01 14:14:11 UTC 微软提交了该文件的扫描请求，并由VirusTotal的Trusted Source Project发布检测报告
结果显示无任何潜在危害性。由此可以推测：WD误杀。建议更新WD的安全智能再扫描，可能会解决报毒问题。

这是YesPlayMusic.Setup.0.3.3.exe的扫描结果
MD5: 86141D7702A12A9DA9067A8E9BF13A09
SHA-1: 9A473E53AA610394E47707AD05CB8DA9FF03DC07
VirusTotalReport: [Click Here](https://www.virustotal.com/gui/file/9c9e81ba8f96b35d8d77f472f115a64f584a34fc885a5b0893c00b036e90bb5a/detection)

**Comment by nmtzwh** [comment]
楼上已经传到virustotal检查了，应该是误报。
因为electron只有打包好的程序，没有开源才有此疑虑。希望能够有electron的分支，不过对于这个issue已经off topic了。

**Comment by qier222** [comment]
> 楼上已经传到virustotal检查了，应该是误报。
> 因为electron只有打包好的程序，没有开源才有此疑虑。希望能够有electron的分支，不过对于这个issue已经off topic了。

Electron版的源码都在Master分支里

**Comment by nmtzwh** [comment]
> Electron版的源码都在Master分支里

不完全在master吧，`electron:build`会报错的，您看Action里的日志。
根据 #197 的方法编译的程序倒是不会被WD误报。

**Comment by qier222** [comment]
> > Electron版的源码都在Master分支里
> 
> 不完全在master吧，`electron:build`会报错的，您看Action里的日志。
> 根据 #197 的方法编译的程序倒是不会被WD误报。

报错是因为缺少文件，缺少的文件可以在 v0.3.1 的tag里找到
