### ISSUE TITLE
希望能加入同步QQ音乐歌单的功能

### ISSUE THREAD

**Issue by XYZliang** [qier222/YesPlayMusic#263]
如题，老QQ音乐用户了，因为您开发的这个客户端挺不错的，决定一直使用您的yesplaymusic
可是网易云的版权太蛋疼了，从QQ音乐导入网易云的歌曲，三分之一没版权，三分之一直接给我匹配错的，三分之一正常匹配。
对于没版权的灰色歌曲，yesplaymusic提供了解锁功能，也就能正常播放。
可剩下那1/3网易云匹配错误的歌曲（其实也是网易云没版权，匹配系统自动给你搞了别的），就没办法了（不是yesplaymusic的锅，是网易云匹配系统的锅）。三四百首歌，没法一个个搜索然后加入歌单，而且网易云根本搜不到😭
所以希望能加入同步QQ音乐的歌单到软件内的功能，甚至是Apple music的歌单（平常和QQ音乐交替使用，毕竟5元一月的会员不用买专辑哈哈哈）

一直无法忍受网易云客户端垃圾的UI设计和版权问题。yesplaymusic基本上已经完美解决！点个赞。

**Comment by qier222** [comment]
没办法接入QQ音乐

**Comment by XYZliang** [comment]
> 没办法接入QQ音乐

不用接入，只需要用户分享出自己的歌单链接，导入yesplaymusic即可

**Comment by qier222** [comment]
> > 没办法接入QQ音乐
> 
> 不用接入，只需要用户分享出自己的歌单链接，导入yesplaymusic即可

这个也没法做，没办法判断QQ音乐的歌曲对应的网易云歌曲版本
