### ISSUE TITLE
海外访问拉取封面图片容易加载失败，比较影响美观，希望加上占位图片

### ISSUE THREAD

**Issue by xzifan** [qier222/YesPlayMusic#269]
如图：
![image](https://user-images.githubusercontent.com/34232484/107495288-9097ca80-6b98-11eb-9775-2b4bebe8d747.png)

**Comment by xzifan** [comment]
如果在重新进入页面的时候能重新尝试请求就更好了

**Comment by qier222** [comment]
刷新一下页面就好了，暂时没有打算优化这个
