### ISSUE TITLE
登录账号后，新收藏的歌曲不同步

### ISSUE THREAD

**Issue by RoyRao2333** [qier222/YesPlayMusic#272]
在登录网易云账号后，手机或其他途径对歌曲“红心”后，YesPlayMusic客户端里未同步，仍旧是“未红心”状态。

客户端：macOS 11.2.1

<img width="555" alt="Screen Shot 2021-02-11 at 00 55 54" src="https://user-images.githubusercontent.com/31413093/107543529-4a785080-6c04-11eb-8a72-0df3f3a39403.png">

**Comment by gangxiaoji** [comment]
按过f12后可以按一下f5刷新看看，或者重启软件，应该是页面没刷新

**Comment by RoyRao2333** [comment]
> 按过f12后可以按一下f5刷新看看，或者重启软件，应该是页面没刷新

好的，感谢！
