### ISSUE TITLE
强烈希望能在播放（歌词）页面增加音量调节条

### ISSUE THREAD

**Issue by PrePan01** [qier222/YesPlayMusic#273]
强烈希望能在播放页面增加音量调节条，调节音量总是要退出播放界面真的很麻烦

**Comment by qier222** [comment]
不知道放哪里好

**Comment by PrePan-R** [comment]
播放控制按钮右边 好不好看问题不是很大 重要的是有这个功能

**Comment by theCoolerFy** [comment]
在封面那里用滚轮调整音量就挺好的

**Comment by logres** [comment]
我尝试在收藏键的左侧添加了一个mini 音量条
![image](https://user-images.githubusercontent.com/33395017/128139657-cb54f19d-3818-411c-bc57-0b3cc8c08d13.png)

**Comment by pan93412** [comment]
已經實作。

**Comment by PrePan01** [comment]
fabulous!
