### ISSUE TITLE
是否可以调整一下这个小细节？

### ISSUE THREAD

**Issue by mark47011** [qier222/YesPlayMusic#276]
我第一次使用时，想打开歌词页面，发现只有点击这里可以打开，

![屏幕截图 2021-02-12 144257](https://user-images.githubusercontent.com/42225189/107738484-bca27f80-6d41-11eb-952a-83170e14038d.png)

如果不是我的个人习惯问题的话，希望点击底栏或者点击图片这里

![屏幕截图 2021-02-12 144235](https://user-images.githubusercontent.com/42225189/107738554-de036b80-6d41-11eb-8684-140e5b63032b.png)

都可以打开歌词页面
（第一次提Issue，紧张🤣）

**Comment by GreyFlorence** [comment]
我也觉得点击封面会比较习惯一点

**Comment by qier222** [comment]
点击左下角正在播放歌曲的封面打开歌词页是网易云的逻辑，我这边准备保持使用自己的逻辑，在歌单内的歌曲列表、歌手页的热门歌曲列表、搜索页的歌曲列表里点击专辑封面都会跳转到专辑页面。

**Comment by qier222** [comment]
最新版本的客户端是可以点击底部空白处调出歌词页的
