### ISSUE TITLE
希望完善播放器的基本功能

### ISSUE THREAD

**Issue by GEATB894** [qier222/YesPlayMusic#278]
设置界面没有，或者我没找到，首页拉下去没有了。点击X可以选择，或者在设置中可以选择关闭or最小化，快捷键，全局快捷键设置，0.33我甚至觉得没0.31版本好用

**Comment by yanranxiaoxi** [comment]
1. 设置界面在 音乐库你的名称右侧箭头点开
2. 最小化也在设置里更改
3. 快捷键最新的PR已经提交，全局快捷键暂时不方便实现
4. 0.33我觉得比0.31好用（主观
