### ISSUE TITLE
部署的问题

### ISSUE THREAD

**Issue by heyiWF** [qier222/YesPlayMusic#28]
![image](https://user-images.githubusercontent.com/45261950/96555874-dfb8a780-12ea-11eb-831a-e43a88941d57.png)
![image](https://user-images.githubusercontent.com/45261950/96556317-69687500-12eb-11eb-8c3c-2e4598155dad.png)

网站部署成功了但是页面加载不出来，只有顶部一栏，请问这是因为API地址没有配置好吗？API也是在同一台服务器，地址要怎么填呢，需要带端口吗？

**Comment by qier222** [comment]
尝试下指定 NeteaseCloudMusicApi 的 HOST

```sh
HOST=127.0.0.1 node app.js  # Mac / Linux
set HOST=127.0.0.1 && node app.js # Windows
```

默认的 YesPlayMusic 地址为 `http://127.0.0.1:8080`

默认的网易云 API 地址为 `http://127.0.0.1:3000`

**Comment by heyiWF** [comment]
`src/config/request.js` 中的 `baseURL` 改为 `http://127.0.0.1:3000` 并以 `HOST=127.0.0.1 node app.js` 启动 NeteaseCloudMusicApi 后，从服务器端访问API和YesPlayMusic页面正常，但从外网无法访问 NeteaseCloudMusicApi，打开YesPlayMusic页面情况同上（只显示出顶栏）。
以 `HOST=0.0.0.0 PORT=3000 node app.js` 启动 NeteaseCloudMusicApi 后，从服务器端访问API和YesPlayMusic页面正常，从外网访问 NeteaseCloudMusicApi 正常，但从外网访问YesPlayMusic页面情况同上。

**Comment by qier222** [comment]
如果是部署到服务器上的话，建议使用域名+nginx反代API。

你也可以试试将HOST改成你的服务器IP。

**Comment by heyiWF** [comment]
解决了，不是改API的HOST，我把 `request.js` 里的地址改成服务器外网IP就可以了。感谢。界面美观实用，点赞！
