### ISSUE TITLE
bug: commit: 51fc577e 构建 Windows 应用，歌词可以点击但无法正确显示

### ISSUE THREAD

**Issue by yanranxiaoxi** [qier222/YesPlayMusic#280]
尝试测试 commit: 51fc577e 进行 Windows 桌面客户端构建的时候出现了这个错误：
1. 歌词无法显示，但点击本应显示歌词的位置进度条会相应改变
2. 使用相同代码构建的 Web 版本没有出现问题

![bug-p1](https://user-images.githubusercontent.com/10684000/107820923-97038d80-6db6-11eb-8e36-e9cc5c5e8ed5.png)

**Comment by qier222** [comment]
最近合并了个歌词页的pr，我还没测试

**Comment by MrWillCom** [comment]
> 尝试测试 commit: 51fc577e 进行 Windows 桌面客户端构建的时候出现了这个错误：
> 
> 1. 歌词无法显示，但点击本应显示歌词的位置进度条会相应改变
> 2. 使用相同代码构建的 Web 版本没有出现问题
> 
> ![bug-p1](https://user-images.githubusercontent.com/10684000/107820923-97038d80-6db6-11eb-8e36-e9cc5c5e8ed5.png)

那么当鼠标浮动在歌词区域的时候会不会有背景颜色变化？用开发者工具选择歌词部分有没有出错或无效的 CSS 值？

当视窗宽度小于 `1000px` 时，歌词会自动隐藏，专辑图片和它下面的控件会居中于视窗。

这些自适应行为是在 #249 中添加的，Windows（win32）平台的沉浸式标题栏是在 #277 中添加的。

布局断点变量在 [src/views/lyrics.vue L366](https://github.com/qier222/YesPlayMusic/blob/0c2098d01f9218dbd74f09645d4f2c221eead9f1/src/views/lyrics.vue#L366) 定义，修改这一行变量会调整歌词隐藏的布局断点。

这个问题可能是我的更改导致的，我过会看看。

**Comment by yanranxiaoxi** [comment]
测试布局断点应该没有问题，歌曲播放时会持续提示一个错误，如下：
![bug-p2](https://user-images.githubusercontent.com/10684000/107846619-15484a00-6e20-11eb-9b0b-0cb74ba5f263.png)

**Comment by MrWillCom** [comment]
我这边测试没有问题，你的截图中显示 `e.target.children.forEach is not a function`，但实际源代码中是：

```js
...
    blurEffect(ev) {
      ev.target.children.forEach((el) => {
...
```

在 [src/views/lyrics.vue L279](https://github.com/qier222/YesPlayMusic/blob/0c2098d01f9218dbd74f09645d4f2c221eead9f1/src/views/lyrics.vue#L279)。可能是你一不小心去掉了 `v` 导致的，改回来应该就行了。

![屏幕截图](https://user-images.githubusercontent.com/47271684/107846884-4164ca80-6e22-11eb-99d6-e537fe5e2782.png)

后来我故意把它改错成：

```js
...
    blurEffect(ev) {
      console.log(ev.target.children());
      ev.target.children.forEach((el) => {
...
```

结果就报了你这样的错：

![屏幕截图](https://user-images.githubusercontent.com/47271684/107847017-234b9a00-6e23-11eb-958b-45906ed8d385.png)

**Comment by yanranxiaoxi** [comment]
奇怪了，但我确实没有改动它，这是我刚刚在Notepad++搜索的结果：
![image](https://user-images.githubusercontent.com/10684000/107847250-ec768380-6e24-11eb-8309-e96c44ab6e29.png)

以及服务器上的代码副本：
![image](https://user-images.githubusercontent.com/10684000/107847279-32cbe280-6e25-11eb-83cd-5cdf482d26bf.png)

我现在去尝试复现这个问题，昨晚太晚扛不住了所以没有去纠结这个问题

**Comment by yanranxiaoxi** [comment]
重新编译依旧复现，以下为编译完成的软件与编译使用的代码副本：
https://cowtransfer.com/s/1872ba4c30514a
密码为：420988

代码副本删除了 .env 文件与 node_module .git 文件夹

**Comment by MrWillCom** [comment]
> 重新编译依旧复现，以下为编译完成的软件与编译使用的代码副本：
> https://cowtransfer.com/s/1872ba4c30514a
> 密码为：420988
> 
> 代码副本删除了 .env 文件与 node_module .git 文件夹

好，我再看看。

**Comment by yanranxiaoxi** [comment]
你核对一下是不是pull的时候有修改没有提交上来，有时会出现这种情况

我是从 GitHub 拉取的全新镜像编译的

**Comment by MrWillCom** [comment]
> 你核对一下是不是pull的时候有修改没有提交上来，有时会出现这种情况
> 
> 我是从 GitHub 拉取的全新镜像编译的

刚刚查了下，不是这个问题。

**Comment by MrWillCom** [comment]
> > 你核对一下是不是pull的时候有修改没有提交上来，有时会出现这种情况
> > 我是从 GitHub 拉取的全新镜像编译的
> 
> 刚刚查了下，不是这个问题。

你试试 `yarn run electron:serve` 会不会复现问题。

**Comment by MrWillCom** [comment]
这个漏洞刚在 #285 中成功修复。

**Comment by yanranxiaoxi** [comment]
感谢！
经测试成功解决了该问题。

**Comment by yanranxiaoxi** [comment]
发现一个新的问题，“播放列表”页面以及“我喜欢的”页面 标题都偏左了，据我所知这不属于正常情况
这个问题仅在最新的四个commit中复现（97f2ce0 之前是正常的）
![bug-p3](https://user-images.githubusercontent.com/10684000/107855567-2d3ebe80-6e5e-11eb-83f2-0bb1b406b363.png)
![bug-p4](https://user-images.githubusercontent.com/10684000/107855634-8f97bf00-6e5e-11eb-9d3b-ab8200db3464.png)

**Comment by MrWillCom** [comment]
> 发现一个新的问题，“播放列表”页面以及“我喜欢的”页面 标题都偏左了，据我所知这不属于正常情况
> 这个问题仅在最新的四个commit中复现（97f2ce0 之前是正常的）
> ![bug-p3](https://user-images.githubusercontent.com/10684000/107855567-2d3ebe80-6e5e-11eb-83f2-0bb1b406b363.png)
> ![bug-p4](https://user-images.githubusercontent.com/10684000/107855634-8f97bf00-6e5e-11eb-9d3b-ab8200db3464.png)

这些问题正在我的 fork 里修复中。这应该我移动端适配时弄小屏幕横向滚动的时候搞出来的。
