### ISSUE TITLE
JS错误导致程序无法启动

### ISSUE THREAD

**Issue by SteamFinder** [qier222/YesPlayMusic#283]
启动时
![QQ截图20210213164504](https://user-images.githubusercontent.com/34237075/107845997-293d7d00-6e1b-11eb-8b25-b0bc938e97a9.png)
进入后
![QQ截图20210213164819](https://user-images.githubusercontent.com/34237075/107846017-512ce080-6e1b-11eb-8f71-9b940d7bd20d.png)
已经遇到多次，随机产生

**Comment by SteamFinder** [comment]
另外，进入后无法加载页面，一直是白屏

**Comment by qier222** [comment]
试试看使用管理员身份运行

**Comment by SteamFinder** [comment]
仍然不行
![SSSSSSSSS0210213171448](https://user-images.githubusercontent.com/34237075/107846473-044b0900-6e1f-11eb-821c-63566bacb2de.png)
