### ISSUE TITLE
bug: after commit: 1d34aa7 “播放列表”页面以及“我喜欢的”页面 标题显示效果左偏

### ISSUE THREAD

**Issue by yanranxiaoxi** [qier222/YesPlayMusic#286]
在所有版本客户端及网页端都可以复现，且仅在最新的四个commit中复现（97f2ce0 之前是正常的）
![bug-p1](https://user-images.githubusercontent.com/10684000/107857413-44cf7480-6e69-11eb-9fe0-5bf0b5f1bcce.png)
![bug-p2](https://user-images.githubusercontent.com/10684000/107857416-4862fb80-6e69-11eb-94ce-f267498d106f.png)

**Comment by MrWillCom** [comment]
这些问题正在我的 fork 里修复中。这应该我移动端适配时弄小屏幕横向滚动的时候搞出来的。

**Comment by MrWillCom** [comment]
MrWillCom@7a4ca61 修复了这个问题，将与“播放列表移至侧边栏”一起请求合并。

**Comment by MrWillCom** [comment]
播放列表和歌词页布局自适应的更新可能来的会比较晚，如果此问题对进一步开发有影响，可以在 https://github.com/qier222/YesPlayMusic/blob/a75c039a400bdefaab8bf988c54fe59365cbac66/src/views/playlist.vue#L727 和 https://github.com/qier222/YesPlayMusic/blob/a75c039a400bdefaab8bf988c54fe59365cbac66/src/views/next.vue#L114 这两行后添加
```css
  padding: var(--main-content-padding);
```
就可解决问题。

**Comment by yanranxiaoxi** [comment]
> 播放列表和歌词页布局自适应的更新可能来的会比较晚，如果此问题对进一步开发有影响，可以在
> 
> https://github.com/qier222/YesPlayMusic/blob/a75c039a400bdefaab8bf988c54fe59365cbac66/src/views/playlist.vue#L727
> 
> 和
> https://github.com/qier222/YesPlayMusic/blob/a75c039a400bdefaab8bf988c54fe59365cbac66/src/views/next.vue#L114
> 
> 这两行后添加
> ```css
>   padding: var(--main-content-padding);
> ```
> 
> 就可解决问题。

感谢回复！我已经去你的fork查看过解决方法了，验证确实解决了该问题

期待你的更新！
