### ISSUE TITLE
无法登陆 错误码：500

### ISSUE THREAD

**Issue by JankingHuang** [qier222/YesPlayMusic#287]
![image](https://user-images.githubusercontent.com/47512530/107867562-bda8ed80-6eb6-11eb-80a4-b2fad8c1c73a.png)

- 客户端
- 电脑操作系统 OpenSUSE Leap Linux
- 号码和密码都正确，提示密码错误。

**Comment by qier222** [comment]
麻烦提供下控制台错误截图

**Comment by JankingHuang** [comment]
![image](https://user-images.githubusercontent.com/47512530/107897359-cb707880-6f73-11eb-9308-0c3011c1dfba.png)

**Comment by tangli159** [comment]
看到其他第三方软件作者说第三方客户端的手机登录貌似挂了 只能试试邮箱。也许是同一个原因？

**Comment by JankingHuang** [comment]
> 看到其他第三方软件作者说第三方客户端的手机登录貌似挂了 只能试试邮箱。也许是同一个原因？

不会吧，我没有网易邮箱。它又不支持判定第3方邮箱

**Comment by tangli159** [comment]
> > 看到其他第三方软件作者说第三方客户端的手机登录貌似挂了 只能试试邮箱。也许是同一个原因？
> 
> 不会吧，我没有网易邮箱。它又不支持判定第3方邮箱

我也是同样的情况，我在Windows系统下和安卓系统下尝试两个作者的第三方都是没办法登录。安卓系统的作者说手机登录最近好像挂了只能邮箱。我看了下网易自己的手机登录是可以用的，所以我就暂时没用第三方客户端了

**Comment by JankingHuang** [comment]
> > > 看到其他第三方软件作者说第三方客户端的手机登录貌似挂了 只能试试邮箱。也许是同一个原因？
> > 
> > 
> > 不会吧，我没有网易邮箱。它又不支持判定第3方邮箱
> 
> 我也是同样的情况，我在Windows系统下和安卓系统下尝试两个作者的第三方都是没办法登录。安卓系统的作者说手机登录最近好像挂了只能邮箱。我看了下网易自己的手机登录是可以用的，所以我就暂时没用第三方客户端了

我现在使用lx-music-desktop 不用的登入的软件了。
