### ISSUE TITLE
希望可以增加类似官方客户端的macOs状态栏

### ISSUE THREAD

**Issue by Squaregentleman** [qier222/YesPlayMusic#289]
能否添加和官方客户端相同的状态栏功能
![2021-02-14_18-04-40](https://user-images.githubusercontent.com/22393739/107873736-9a4e6480-6eef-11eb-9e25-7526596b7e21.png)

**Comment by zy21802** [comment]
同！用惯了跟着状态栏唱歌和切歌，突然没了好不习惯啊

**Comment by Squaregentleman** [comment]
> 同！用惯了跟着状态栏唱歌和切歌，突然没了好不习惯啊

mac版的网易云这个功能真的超棒

**Comment by qier222** [comment]
mac的话，建议用键盘或Touchbar 上面的上一首下一首。
不打算做这个功能。

**Comment by Squaregentleman** [comment]
> mac的话，建议用键盘或Touchbar 上面的上一首下一首。
> 不打算做这个功能。

imac没有tounchbar
主要是习惯了看状态栏歌词
