### ISSUE TITLE
无法打开媒体库

### ISSUE THREAD

**Issue by biliblihuorong** [qier222/YesPlayMusic#291]
今天打开需要重新登录,登陆完媒体库无法打开,尝试卸载在安装无果.
![image](https://user-images.githubusercontent.com/40906916/107877092-36369b00-6f05-11eb-90ed-88ba5df8b9de.png)

**Comment by dingding1024** [comment]
我也遇到这个问题，无法解决

**Comment by biliblihuorong** [comment]
> 我也遇到这个问题，无法解决

不过我用了IObit Uninstaller清理清理完之后重新登陆即可使用

**Comment by dingding1024** [comment]
> > 我也遇到这个问题，无法解决
> 
> 不过我用了IObit Uninstaller清理清理完之后重新登陆即可使用

好的 感谢，我试试
