### ISSUE TITLE
触控栏出现问题

### ISSUE THREAD

**Issue by cocowater** [qier222/YesPlayMusic#295]
Mac OS 11.2.1（20D74）
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)

触控栏出现问号图标
<img width="1085" alt="触控栏快照2021-02-16 上午9 03 08" src="https://user-images.githubusercontent.com/14013619/108006317-1b177880-7036-11eb-8450-e8258d948c08.png">

**Comment by Squaregentleman** [comment]
已经有todo了 #113

**Comment by qier222** [comment]
0.3.4版本已修复
