### ISSUE TITLE
M1芯片Macbook Air 安装完成后运行显示已损坏无法打开

### ISSUE THREAD

**Issue by alasion** [qier222/YesPlayMusic#297]
macos 11.2.1
YesPlayMusic-0.3.3-mac-arm64.dmg

**Comment by reworld** [comment]
终端试试下面的命令：
xattr -r -d com.apple.quarantine /Applications/YesPlayMusic.app

**Comment by Eric-kll** [comment]
为啥YesPlay0.3.3 没办法喜欢音乐和添加到库

**Comment by singularitti** [comment]
如果你是从 [Homebrew](https://brew.sh/) 安装的，更好的方法是使用 [`--no-quarantine` flag](https://github.com/Homebrew/homebrew-cask/blob/HEAD/USAGE.md#options):

```shell
brew install --cask --no-quarantine yesplaymusic
```
