### ISSUE TITLE
自动缓存设定变动后无法显示已有的缓存及清除缓存

### ISSUE THREAD

**Issue by Ayiiiii** [qier222/YesPlayMusic#298]
Windows1909 客户端版本
已有歌曲缓存存在情况下，关掉缓存按钮导致缓存显示清空，再次打开后未恢复，原缓存文件还在（目测）且无法清除

**Comment by Q-Tai-mu** [comment]
这是逻辑问题，你希望是什么效果？是再次打开后恢复吗？

**Comment by Ayiiiii** [comment]
> 这是逻辑问题，你希望是什么效果？是再次打开后恢复吗？

是的，希望开关按钮后可以恢复显示所有已缓存内容并可以正常清理缓存
