### ISSUE TITLE
希望大神添加音乐播放器基本功能

### ISSUE THREAD

**Issue by wulei19991221** [qier222/YesPlayMusic#299]
我本地有缓存的音乐,希望能添加功能: 扫描指定文件夹, 并且将本地音乐当作一个类似歌单的, 可以播放全部本地音乐

**Comment by Q-Tai-mu** [comment]
你是要将本地的音乐扫描处理，并创建一个本地的网易云歌单，还是单纯的将音乐添加到播放列表？

**Comment by wulei19991221** [comment]
本地歌单，谢谢
