### ISSUE TITLE
希望添加将启动页设置为音乐库的可选功能

### ISSUE THREAD

**Issue by 1140811911** [qier222/YesPlayMusic#301]
希望可以将音乐库设置为启动的初始界面

**Comment by Q-Tai-mu** [comment]
您是想，做一个开始个性化设置吗？

**Comment by 1140811911** [comment]
> 您是想，做一个开始个性化设置吗？
对的

**Comment by W4J1e** [comment]
我也想要这个，这样歌单页面就可以使用这个项目了，而不用挨个去aplayer中添加id。

**Comment by canvascat** [comment]
每次退出应用时保存当前路由，初始化时重定向过去，也许这样比较好吧😁
