### ISSUE TITLE
大哥，就整一个windows x86的吧

### ISSUE THREAD

**Issue by Lan-5869** [qier222/YesPlayMusic#302]
大哥，整一个吧
![1613674561366](https://user-images.githubusercontent.com/75728986/108407235-71ff9680-725e-11eb-97d6-f2a9966eba79.jpg)

**Comment by qier222** [comment]
OK

**Comment by qier222** [comment]
增加32位支持的话，会显著增加安装包的大小，建议你根据readme的说明自行编译32位的安装包。
