### ISSUE TITLE
会出现任务栏的歌曲跟软件页面显示的不同步

### ISSUE THREAD

**Issue by MrLemon520** [qier222/YesPlayMusic#304]
win7 安装版
出现过列表页面的正在播放与任务栏上面的歌曲不一直，且任务栏显示的才是当前正在播放的，列表的显示正在播放不正确，同时页面的播放进度条丢失，无法打开歌曲详情页，歌词页。

**Comment by qier222** [comment]
需要提供控制台的日志截图
