### ISSUE TITLE
请教客户端是如何做到破灰的（使用第三方源解决版权问题不能播放）

### ISSUE THREAD

**Issue by zengxiaoliang** [qier222/YesPlayMusic#308]
- 现象： 网页版正常播放有版权歌曲，请教如何使用UnblockNeteaseMusic 进行破灰（或者讲下客户端版本是如何做到的呢）
- 
- 用的是网页版还是客户端 ：网页版
- 

- 浏览器名称或电脑操作系统： macos 、node14.5.0 、Chrome版本 86.0.4240.75（正式版本） (x86_64)
-

**Comment by qier222** [comment]
https://github.com/qier222/YesPlayMusic/pull/69/files
