### ISSUE TITLE
海外(马来西亚)无法播放

### ISSUE THREAD

**Issue by lingerwaaaa** [qier222/YesPlayMusic#317]

**Comment by junwei-wang** [comment]
法国也无法播放

**Comment by junwei-wang** [comment]
Is this fixed?

**Comment by qier222** [comment]
> Is this fixed?

没有定位到问题在哪，需要有人提供播放时出错的控制台错误信息

**Comment by junwei-wang** [comment]
我可以帮忙定位，如何提供？ 可以重新打开这个issue吗？谢谢🙏

**Comment by lingerwaaaa** [comment]
就是能登录，然后在官方app里面有版权限制的歌，在这边就是灰色的，然后也播放不了，点的话下面就弹出提示无法播放"歌曲名"

**Comment by lingerwaaaa** [comment]
然后你说的控制台是网页里的?

![image](https://user-images.githubusercontent.com/65887744/115684367-df789200-a389-11eb-84d8-1703706f9251.png)

**Comment by qier222** [comment]
> 🌎️ 海外用户可直接播放（需要登录网易云账号）
@junwei-wang @lingerwaaaa 可以试试登录网易云账号再播放

**Comment by lingerwaaaa** [comment]
已经登录了

**Comment by qier222** [comment]
> 已经登录了

我这边测试使用全局代理模拟海外使用，可以正常播放。

**Comment by lingerwaaaa** [comment]
外网..不用翻墙的那种，就是播不了，登陆了，用网页或是exe的都不行..
![image](https://user-images.githubusercontent.com/65887744/115706705-8405ce80-a3a0-11eb-9d9e-6124706aeaf2.png)

**Comment by lingerwaaaa** [comment]
...官方程序是可以播的,这个专辑
![image](https://user-images.githubusercontent.com/65887744/115707085-f1196400-a3a0-11eb-8f0b-07610f4cbddb.png)
