### ISSUE TITLE
歌曲无法收藏或者取消收藏

### ISSUE THREAD

**Issue by neochen6** [qier222/YesPlayMusic#318]
windows10客户端v0.3.3出现该问题：
退出账号后再重新登录，该问题依旧存在。
![image](https://user-images.githubusercontent.com/38391124/108687179-5c75bf80-7531-11eb-95eb-2c08d748f614.png)

**Comment by itanag** [comment]
macos 系统下的客户端无法点红心收藏。控制台报 400 错误 
![image](https://user-images.githubusercontent.com/51741600/108851769-c1a7de80-761f-11eb-8ca6-177e1df3cbbd.png)

**Comment by xuejingtai** [comment]
我的也是这样,希望下个版本可以修复!

**Comment by yangyang0719** [comment]
俺也一样.jpg

**Comment by fansanqiu** [comment]
me too

**Comment by yanglichangyong** [comment]
me too

**Comment by fansanqiu** [comment]
找到一个临时解决方案
1、使用官方客户端新建一个歌单
2、点击歌曲头像进入歌曲页面
3、添加到歌单

**Comment by Wilenoch** [comment]
俺也一样

**Comment by qier222** [comment]
0.3.4版本已修复这个问题

**Comment by latin-1** [comment]
@qier222 The fix commit (82c179c) is not included in the 0.4.3 release. Could you please cut a new release with this fix? Thanks a lot.

**Comment by qier222** [comment]
> @qier222 The fix commit ([82c179c](https://github.com/qier222/YesPlayMusic/commit/82c179c9aeb2df0cd7045caaf26d8a226ba476b3)) is not included in the 0.4.3 release. Could you please cut a new release with this fix? Thanks a lot.

打算放到0.3.5
