### ISSUE TITLE
服务器无响应

### ISSUE THREAD

**Issue by 151819880412** [qier222/YesPlayMusic#320]
# 服务器无响应
windows客户端0.3.2服务器一直未响应

**Comment by qier222** [comment]
0.3.4版本看一下有没有这个问题，还有问题的话请重新打开这个issue

**Comment by 151819880412** [comment]
![image](https://user-images.githubusercontent.com/51997413/110260556-bb364100-7fe7-11eb-83c6-29a01e7a6462.png)
![image](https://user-images.githubusercontent.com/51997413/110260581-cd17e400-7fe7-11eb-99c3-2915cd416bad.png)
登录超时后导致手机号密码输入不了
