### ISSUE TITLE
部署到自己的服务器上没法登陆账户

### ISSUE THREAD

**Issue by husangou** [qier222/YesPlayMusic#321]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版
- 谷歌浏览器
- 控制台 Console 页面的截图（按 F12 可打开控制台）
- 
![image](https://user-images.githubusercontent.com/79092733/108754011-5259be00-753d-11eb-8ff9-f585e7e8ad0f.png)
![image](https://user-images.githubusercontent.com/79092733/108754128-774e3100-753d-11eb-8444-f20f1ad33c60.png)
密码是可以识别错误和正确的就是输入正确密码后跳转到/#/login的界面 不会去登陆 正常按照教程部署的

**Comment by husangou** [comment]
地址http://wyy.xn--ehq201g9tj.xyz/

**Comment by husangou** [comment]
![image](https://user-images.githubusercontent.com/79092733/108759246-03fbed80-7544-11eb-84a4-f6283325af9d.png)

**Comment by jhf1999** [comment]
同样的问题 绑定域名登录没反应 ip+端口登录就可以了

**Comment by husangou** [comment]
> 同樣的問題綁定域名登錄沒反應ip +端口登錄就可以了

难不成要做反代

**Comment by husangou** [comment]
> 同样的问题 绑定域名登录没反应 ip+端口登录就可以了

8080的端口嘛？

**Comment by jhf1999** [comment]
> > 同样的问题 绑定域名登录没反应 ip+端口登录就可以了
> 
> 8080的端口嘛？
我是nginx反代，随便一个端口就可以

**Comment by jhf1999** [comment]
> > 同样的问题绑定域名登录没反应ip +端口登录就可以了
> 
> 8080的端口嘛？

我是nginx反代，随便一个端口就可以

**Comment by husangou** [comment]
好胸弟 反代规则可否白嫖一下

**Comment by W4J1e** [comment]
这个域名很不错哦。

**Comment by husangou** [comment]
> 这个域名很不错哦。

我也觉着但是问题依然没解决 头大死了

**Comment by husangou** [comment]
> > > 同样的问题绑定域名登录没反应ip +端口登录就可以了
> > 
> > 
> > 8080的端口嘛？
> 
> 我是nginx反代，随便一个端口就可以

好胸弟 反代规则可否白嫖一下

**Comment by qier222** [comment]
搞了一下，现在0.3.4版本不存在跨域问题了
