### ISSUE TITLE
希望可以加入心动播放模式

### ISSUE THREAD

**Issue by xqXQzzz1** [qier222/YesPlayMusic#323]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

如题，个人感觉心动模式比私人FM还要好一点，新旧掺杂，很舒服，希望可以加入心动播放模式。

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by qier222** [comment]
已加入todo

**Comment by homeboygm** [comment]
同求心动模式
