### ISSUE TITLE
win10 播放控制器模糊效果

### ISSUE THREAD

**Issue by Lucas-Tianyu** [qier222/YesPlayMusic#327]
希望win 10 客户端在适配dark mode的时候能增加一个关闭播放兰模糊效果的设置

以下是有模糊效果和没有模糊效果的对比，关闭后感觉效果更好，不会和底栏有割裂感
[![fbc0fc58df4894f19bf47d7c23afb08.png](https://pic-lucas.tech/images/fbc0fc58df4894f19bf47d7c23afb08.png)](https://pic-lucas.tech/image/lyn)
[![f4f46fab66578add9c8f108ee488e34.png](https://pic-lucas.tech/images/f4f46fab66578add9c8f108ee488e34.png)](https://pic-lucas.tech/image/iEY)

**Comment by qier222** [comment]
暂时不打算搞这个功能
