### ISSUE TITLE
竖屏会无法显示歌词

### ISSUE THREAD

**Issue by z1sxdc** [qier222/YesPlayMusic#329]
使用“YesPlayMusic.Setup.0.3.3.exe”安装的，系统是win10。窗口横纵比过大时(w*h:720*1280)，歌词会被挤出去。
![image](https://user-images.githubusercontent.com/23397758/109201822-9cfd6380-77e5-11eb-9277-c4fd2e6f160f.png)

**Comment by qier222** [comment]
v0.4.0 版本已修复
