### ISSUE TITLE
来自小白的提问（网站端）

### ISSUE THREAD

**Issue by bat-coco** [qier222/YesPlayMusic#330]
大佬能不能出一个详细一点的网站搭建教程啥的，我照着你说的搞了十几次都不行。。。。。。。。。。。。

**Comment by W4J1e** [comment]
git clone仓库，安装yarn，使用yarn安装依赖，使用yarn命令生成dist，上传dist目录下的文件到服务器。感觉文档写得挺细致的。

**Comment by qier222** [comment]
readme更新了部署的教程，现在部署更简单了。
