### ISSUE TITLE
项目能否使用源码自行编译？

### ISSUE THREAD

**Issue by martin0607** [qier222/YesPlayMusic#332]
看到源码一直在更新，想自己使用最新的源码编译，看了看Action里面都没有新的Realese文件出来。想自己试着编一个Mac的成品。
Electron还没接触过，还在搜相关资料。

**Comment by hawtim** [comment]
你可以在较早之前的 tag 中找到 napi 目录，然后编译 electron 的版本

**Comment by martin0607** [comment]
> 你可以在较早之前的 tag 中找到 napi 目录，然后编译 electron 的版本

API好像缺少文件哎
![image](https://user-images.githubusercontent.com/32560181/109461209-c98ed500-7a9c-11eb-8d9c-9ee01673dbb5.png)

**Comment by qier222** [comment]
readme增加了自行编译的说明，你也可以在本项目的Actions里面找到每个commit的安装包
