### ISSUE TITLE
【BUG】MacOS歌曲点击爱心无反应

### ISSUE THREAD

**Issue by Kevinjyp** [qier222/YesPlayMusic#333]
MacOS Big Sur 11.2.1
客户端

![image](https://user-images.githubusercontent.com/36948184/109409959-cd095a00-79d1-11eb-802a-afe61d379dd2.png)

如题，点击左下角歌曲旁边的小爱心无反应。

**Comment by VidocqH** [comment]
## 下个版本应该就行了😊


Binaryify/NeteaseCloudMusicApi#1151

<img width="1576" alt="截屏2021-02-28 下午6 28 13" src="https://user-images.githubusercontent.com/16725418/109415285-c7703c00-79f2-11eb-826e-ddfa72a99939.png">

**Comment by Kevinjyp** [comment]
> ### 下个版本更新后应该就行了😊

更新的话还是使用安装的brew命令么？

**Comment by VidocqH** [comment]
> > ### 下个版本更新后应该就行了😊
> 
> 更新的话还是使用安装的brew命令么？

嗯，有新版本后（例如0.3.4）用brew upgrade就好了

**Comment by qier222** [comment]
0.3.4版本已修复这个问题

**Comment by Kevinjyp** [comment]
![image](https://user-images.githubusercontent.com/36948184/111405696-e74e7200-870b-11eb-93ed-0d385e83131b.png)
是我的打开方式有问题么？我这里看，0.3.4版本仍然有这个问题
