### ISSUE TITLE
Debian 11+Gnome3.38安装出错！

### ISSUE THREAD

**Issue by hackson99** [qier222/YesPlayMusic#335]
安装提示：

dpkg: 依赖关系问题使得 yesplaymusic 的配置工作不能继续：
 yesplaymusic 依赖于 libappindicator3-1；然而：
  未安装软件包 libappindicator3-1。
然后，debian11上没有 libappindicator3-1这个包。

安装后，yesplay可以正常使用。但是，dabian升级系统时，提示必须删除yesplay才可以升级系统。

怎么办？

谢谢！！

**Comment by hackson99** [comment]
有没有人遇到相同的问题？

**Comment by TinySuccubus** [comment]
同样遇到了

**Comment by ForyoungYu** [comment]
我也是

**Comment by flametuna** [comment]
@hackson99  @TinySuccubus @ForyoungYu  libappindicator3-1 Debian 11 并未收录。可以删除这个依赖，重新打包。

**Comment by flametuna** [comment]
> > @hackson99 @TinySuccubus @ForyoungYu libappindicator3-1 Debian 11 并未收录。可以删除这个依赖，重新打包。
> 
> 這好像是去年初的已修正問題 joy 我剛才確認了一下，應該是修了（？）但我沒 Debian 可以實機測試

并没有，control 文件内依然有 libappindicator3-1 依赖导致在 Debian 下 dpkg 安装出错 (yesplaymusic_0.4.3_amd64.deb)，并影响其他软件包安装。如果此依赖不是必须建议删除。

**Comment by pan93412** [comment]
> > > @hackson99 @TinySuccubus @ForyoungYu libappindicator3-1 Debian 11 并未收录。可以删除这个依赖，重新打包。
> > 
> > 這好像是去年初的已修正問題 joy 我剛才確認了一下，應該是修了（？）但我沒 Debian 可以實機測試
> 
> @pan93412 并没有，control 文件内依然有 libappindicator3-1 依赖导致在 Debian 11 下 dpkg 安装出错 (yesplaymusic_0.4.3_amd64.deb)，并影响其他软件包安装。如果此依赖不是必须建议删除。（这个包最开始是 ubuntu 的，ubuntu 目前依然有这个包，Debian 11 已无对应版本）

其實這問題應該要回報給 electron-packager…… 這些包應該都是這個工具產的。
