### ISSUE TITLE
大哥，整一个Win-arm64的吧

### ISSUE THREAD

**Issue by KiKGod** [qier222/YesPlayMusic#337]
![QQ截图20210303185844](https://user-images.githubusercontent.com/69355563/109795655-25e72580-7c52-11eb-8f3b-c5770c510de7.png)

**Comment by ancba** [comment]
可以自己编译一份啊

**Comment by qier222** [comment]
打包后会显著增加安装包的大小，基于目前 windows arm的用户数，暂时不打算提供arm64的安装包，可以根据readme自行编译。

**Comment by be5invis** [comment]
@qier222 Related: https://github.com/electron-userland/electron-builder/issues/4467
If this gets fixed we should be able to create single-arch packages for Windows.
