### ISSUE TITLE
打开白屏好久才有显示

### ISSUE THREAD

**Issue by inuxor** [qier222/YesPlayMusic#342]
manjaro 通过aur安装的客户端
![图片](https://user-images.githubusercontent.com/1345457/110096758-3b3a8c00-7dd9-11eb-9a39-629825d6ebf5.png)
![图片](https://user-images.githubusercontent.com/1345457/110097119-a2f0d700-7dd9-11eb-9d7f-3570447cde84.png)

估计是请求字体资源超时。是不是可以加个国内无障碍的镜像？

**Comment by qier222** [comment]
Google Fonts在国内有CDN的吧
