### ISSUE TITLE
MacBook Pro的Touch Bar 功能按钮显示乱码

### ISSUE THREAD

**Issue by Fireflyseven** [qier222/YesPlayMusic#346]
MacBook Pro Touch Bar 功能按钮显示乱码（方框里一个问号），点击有反应，但不知道点的是什么功能的按钮，影响使用。
请修复这个问题，建议Touch Bar增加歌词显示功能。

**Comment by Mayandev** [comment]
duplicate issue #113

**Comment by qier222** [comment]
0.3.4版已修复
