### ISSUE TITLE
下一首播放的曲目会重复

### ISSUE THREAD

**Issue by CNJasonChio** [qier222/YesPlayMusic#349]
![image](https://user-images.githubusercontent.com/36125147/110201611-f711bf00-7e9e-11eb-8690-8da1cf807cfc.png)

**Comment by qier222** [comment]
特意这样写的，如果你对一首歌右键选择了多次“下一首播放”，那么就会播放多几次

**Comment by qier222** [comment]
如果不是我前面提到的功能的话，可以重开issue
