### ISSUE TITLE
网易云的API地址是啥？music.163.com？？？

### ISSUE THREAD

**Issue by GoogleCodes** [qier222/YesPlayMusic#353]
![微信截图_20210307204329](https://user-images.githubusercontent.com/23470846/110240284-2cdda300-7f86-11eb-81ad-55c9b06a0629.png)

**Comment by qier222** [comment]
已更新教程，按照教程操作吧

**Comment by GoogleCodes** [comment]
> 已更新教程，按照教程操作吧

好的
