### ISSUE TITLE
滚动条希望不要超过下方播放栏

### ISSUE THREAD

**Issue by Clansty** [qier222/YesPlayMusic#354]
现在滚动时滚动条会出现在整个界面的右边，我觉得应该避开下方播放状态栏

可能可以通过使用一个 div 包裹 nav 和 main 并将其高度设为 calc(100vh - 64px) 并设置 overflow: scroll 来解决这个问题

![image](https://user-images.githubusercontent.com/18461360/110241653-cc059900-7f8c-11eb-90cb-d3fe3f8d1bef.png)

**Comment by Clansty** [comment]
![image](https://user-images.githubusercontent.com/18461360/110241829-ee4be680-7f8d-11eb-8a73-eae2292f5f26.png)
大概像这样（图中滚动条的层级有些问题）

**Comment by qier222** [comment]
好主意

**Comment by qier222** [comment]
但是如果页面很长的话，滚动条会比较短，滑到底部的话，那有可能会被底栏遮挡，出现用户无法拖动滚动条的情况
