### ISSUE TITLE
0.3.4 Windows 10 启动后一片空白，不能载入任何内容

### ISSUE THREAD

**Issue by rampageX** [qier222/YesPlayMusic#355]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 客户端
- 浏览器名称或电脑操作系统
- Windows 10 20H2 x64
- 控制台 Console 页面的截图（按 F12 可打开控制台）

返回 0.3.3 没问题

**Comment by qier222** [comment]
提供下控制台错误截图

**Comment by rampageX** [comment]
![2021-03-07_232920](https://user-images.githubusercontent.com/994081/110245166-0bd47c80-7f9d-11eb-895c-ba2306912815.jpg)

**Comment by qier222** [comment]
找到原因了，这个版本是由GitHub Action打包的，我忘记给GitHub Action环境写env了

**Comment by wuhuifu** [comment]
+1  期待大佬更新

**Comment by qier222** [comment]
已经重新打包了，重新下载安装就可以了 @rampageX @wuhuifu
