### ISSUE TITLE
新版本灰色音乐无法播放了

### ISSUE THREAD

**Issue by RebirthEgo** [qier222/YesPlayMusic#356]
新版本灰色音乐无法播放了

**Comment by qier222** [comment]
没复现

**Comment by RebirthEgo** [comment]
网页端不可以，客户端是没问题的
https://music.qier222.com/#/search/SYML/tracks

**Comment by qier222** [comment]
网页端本来就不能解锁啊😅

**Comment by RebirthEgo** [comment]
那我多虑了

**Comment by W4J1e** [comment]
> 网页端本来就不能解锁啊😅

说到这，我发现不登陆，只输入名称访问歌单的话，都可以播放，但是通过邮箱登陆后即便是黑胶会员，但是有些歌就变成灰色了。
