### ISSUE TITLE
0.3.4 在 macOS 11.2.2 上白屏，不能播放

### ISSUE THREAD

**Issue by artxia** [qier222/YesPlayMusic#357]
刚升级了最新版，404 错误 。白屏，不能播放。
返回 0.3.3 正常
![image](https://user-images.githubusercontent.com/50513568/110247178-e730d280-7fa5-11eb-914e-5a3cacb76df8.png)

**Comment by qier222** [comment]
已经重新打包了，重新下载安装就可以了

**Comment by artxia** [comment]
感谢，刚自己打包完就收到邮件了。。。
另外有个问题，还请看看是不是个例。如下图，每次打开都会提示这个。
macOS 防火墙设置已经添加并允许，依然会弹。
![image](https://user-images.githubusercontent.com/50513568/110247921-8b684880-7fa9-11eb-8305-6948588c2900.png)

**Comment by qier222** [comment]
我的Mac没有这个弹窗，你去系统设置里看看能不能调一下啥东西？

**Comment by artxia** [comment]
系统设置里貌似只有防火墙是管这个的，但是我已经在防火墙允许了它的连接。
不知你是否开启防火墙？或者是 macOS Big Sur 的原因？

![image](https://user-images.githubusercontent.com/50513568/110248466-4b569500-7fac-11eb-8268-84a7155c2be0.png)

**Comment by qier222** [comment]
我的也是Big Sur，我没开防火墙……

**Comment by qier222** [comment]
测试开了下，只会申请一次权限

**Comment by artxia** [comment]
> 测试开了下，只会申请一次权限

😂 看来是个例，难搞了
