### ISSUE TITLE
Win10 0.3.4版本 无法添加歌曲到喜爱的音乐

### ISSUE THREAD

**Issue by xtynk** [qier222/YesPlayMusic#358]
Win客户端版本0.3.4 无法添加歌曲到喜爱的音乐
点击心型图标没任何反应，右键点击歌曲添加也没反应
已登录网易账号
添加专辑是可用的

**Comment by asca0121** [comment]
0.33就不行了

**Comment by neochen6** [comment]
0.3.3其实发布过同样的问题，然后被关闭了，声明0.3.4已经解决了；但实际上并没有。

**Comment by qier222** [comment]
嗨呀，复制代码复制错了，会尽快修复

**Comment by qier222** [comment]
https://github.com/qier222/YesPlayMusic/actions/runs/631472073
可以在这里下载修复了的版本

**Comment by neochen6** [comment]
确实好了，感谢

**Comment by xtynk** [comment]
还有个问题忘记提了，发现修复版本里也能复现。
就是客户端界面右上角的X关闭按钮不生效，点了没反应

**Comment by olddriverv5** [comment]
请问一下怎么好的https://github.com/qier222/YesPlayMusic/actions/runs/631472073并没有找到下载链接啊

**Comment by qier222** [comment]
v0.3.5 版本确认已经修复了
