### ISSUE TITLE
0.3.4版登陆失败后无法重新输入账号或密码

### ISSUE THREAD

**Issue by mxy493** [qier222/YesPlayMusic#359]
### 反馈 bug 需要的信息

- YesPlayMusic-Setup-0.3.4.exe
- Win10 20H2

![image](https://user-images.githubusercontent.com/46776216/110262519-eff9c680-7fee-11eb-8df0-e17a11cdb0b1.png)

**Comment by qier222** [comment]
尝试重新打开软件？

**Comment by mxy493** [comment]
> 尝试重新打开软件？

当然重新打开可以输入了，但是只要登陆失败弹对话框后就没法输入，按F12之后也可以输入
