### ISSUE TITLE
win10，0.3.4，最小化最大化关闭按钮都点击无反应    

### ISSUE THREAD

**Issue by morelove112** [qier222/YesPlayMusic#360]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by qier222** [comment]
提供下控制台截图

**Comment by morelove112** [comment]
因为按钮无法点击我又用回0.3.3了，刚才又用0.3.4又好了，还有个bug就是喜欢那个心点上去没反应，谢谢
还有就是滚动条我觉得很多余，如果非要加的话上下有点突出了
控制台是这样吗，不太懂




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qier222/YesPlayMusic"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月8日(星期一) 中午11:39
收件人:&nbsp;"qier222/YesPlayMusic"<YesPlayMusic@noreply.github.com&gt;;
抄送:&nbsp;"赵廷玉"<454415671@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [qier222/YesPlayMusic] win10，0.3.4，最小化最大化关闭按钮都点击无反应     (#360)





 
提供下控制台截图

**Comment by qier222** [comment]
0.3.6版本应该已经修复了
