### ISSUE TITLE
自己编译的Win x86功能基本上不能用

### ISSUE THREAD

**Issue by JohnsonRan** [qier222/YesPlayMusic#363]
按照教程编译出来的x86版本，加载不出任何东西，按钮无法使用 （
![JLOM6FTSOV1_491SW8D3MVD.png](https://i.loli.net/2021/03/08/dXM8n6CaQzO5eJ2.png)

**Comment by qier222** [comment]
不好意思，漏写了一个步骤。
打包前请执行这个步骤👇
复制 `/.env.example` 文件为 `/.env`

**Comment by JohnsonRan** [comment]
> 不好意思，漏写了一个步骤。
> 打包前请执行这个步骤👇
> 复制 `/.env.example` 文件为 `/.env`

好了唉，谢谢大佬
