### ISSUE TITLE
Windows x64 最小化 向下还原/最大化 关闭无响应（控制台附）

### ISSUE THREAD

**Issue by PurBlu** [qier222/YesPlayMusic#365]
![屏幕截图 2021-03-08 132935](https://user-images.githubusercontent.com/74239692/110278540-665bf000-8012-11eb-8c04-19279adbb0c0.png)
表现为这三个按钮单击没反应，任务栏右键也关不了，只有Taskmgr强杀。重启软件后正常。

**Comment by imgradeone** [comment]
应该是高分屏笔记本的 bug
看一下这个 https://github.com/qier222/YesPlayMusic/issues/364#issuecomment-792545914

**Comment by PurBlu** [comment]
> 应该是高分屏笔记本的 bug
> 看一下这个 [#364 (comment)](https://github.com/qier222/YesPlayMusic/issues/364#issuecomment-792545914)

我想应该不是这个原因。
我是台式机，1920*1080，100%缩放显示大小。似乎与网络有关，发生这个问题时是我都挂了VPN。

**Comment by poy6** [comment]
![image](https://user-images.githubusercontent.com/67370085/113005201-da6b5d00-91a6-11eb-9f54-79098b2b635f.png)
同样的问题，0.3.5 win10 19042.870

**Comment by qier222** [comment]
0.3.6版本应该已经修复了
