### ISSUE TITLE
听歌时会一卡一卡的

### ISSUE THREAD

**Issue by 462051887** [qier222/YesPlayMusic#366]
华硕天选r9 2060用客户端听歌时会一卡一卡的，有点难受，希望作者解决一下这个问题，谢谢啦🙏🙏🙏
Windows 10 家庭中文版 20H2

**Comment by qier222** [comment]
没办法复现这个问题啊

**Comment by 462051887** [comment]
有时会卡有时又不会- - 可能是我电脑的问题吧 看别人好像没我这情况。。。

**Comment by 462051887** [comment]
那个 怎么才能查看歌手的全部单曲呢

**Comment by qier222** [comment]
> 那个 怎么才能查看歌手的全部单曲呢

应该是查看不了，我记得网易云那边只能获取前50首

**Comment by 462051887** [comment]
好吧 其他的体验还是很好的 谢谢作者啦
