### ISSUE TITLE
bug\曲目作者有多人的情况下，播放界面只显示其中一个作者

### ISSUE THREAD

**Issue by NEPHERAovo** [qier222/YesPlayMusic#367]
0.3.4
问题如下图
![image](https://user-images.githubusercontent.com/78498883/110293876-1721b980-802a-11eb-9810-8de6c904d72a.png)
![image](https://user-images.githubusercontent.com/78498883/110293917-20128b00-802a-11eb-8294-627fbd420a0d.png)
![image](https://user-images.githubusercontent.com/78498883/110293934-26086c00-802a-11eb-97ab-9219755022d1.png)

**Comment by qier222** [comment]
歌词页面这个是因为后面还要显示专辑名字，所以就只显示了第一个艺人，大概是表示 “来自San Holo的专辑find your way” 这个意思。
San Holo好评。

**Comment by NEPHERAovo** [comment]
> 歌词页面这个是因为后面还要显示专辑名字，所以就只显示了第一个艺人，大概是表示 “来自San Holo的专辑find your way” 这个意思。
> San Holo好评。

stay vibrant!
但是我发现似乎歌词界面是根据作者排序先后来决定显示哪个艺人的。例如说Chance the Rapper & SZA的Childs Play，在歌词界面显示的是Chance the Rapper，但是实际上该曲目是收录在SZA的专辑中的。

**Comment by qier222** [comment]
> > 歌词页面这个是因为后面还要显示专辑名字，所以就只显示了第一个艺人，大概是表示 “来自San Holo的专辑find your way” 这个意思。
> > San Holo好评。
> 
> stay vibrant!
> 但是我发现似乎歌词界面是根据作者排序先后来决定显示哪个艺人的。例如说Chance the Rapper & SZA的Childs Play，在歌词界面显示的是Chance the Rapper，但是实际上该曲目是收录在SZA的专辑中的。

确实是，之后修复。
https://stay-vibrant.qier222.com
需要爬墙👆

**Comment by qier222** [comment]
api获取到的信息里，album下面没有artist的数据，除非再发送一个请求。所以暂时不打算修复这个。
