### ISSUE TITLE
没有看到私人fm、不能隐藏到通知栏

### ISSUE THREAD

**Issue by xiaowenlv** [qier222/YesPlayMusic#369]
私人fm在哪里找？设置打开了隐藏到通知栏还是会退出，希望以后能自定义快捷键。

**Comment by likeasb** [comment]
首页推荐歌单下的for you

**Comment by xiaowenlv** [comment]
能不能把私人fm放到前面来呢，比如就放在搜索后面

**Comment by Capricornsong** [comment]
> 私人fm在哪里找？设置打开了隐藏到通知栏还是会退出，希望以后能自定义快捷键。

隐藏操通知栏的逻辑是点击最小化按钮隐藏到通知栏，不是传统的点击关闭按钮隐藏到通知栏喔。
