### ISSUE TITLE
scrobble 传入参数错误

### ISSUE THREAD

**Issue by hawtim** [qier222/YesPlayMusic#37]
复现步骤
1. 搜索周杰伦
2. songs 双击屋顶
3. 查看 scrobble 接口的 time 参数（图一）
4. 在 demo 上没报错，但是参数类型确实错误，在本地开发的时候会有被拦截的报错。

![图一](https://user-images.githubusercontent.com/11072796/96823343-e536fe80-145e-11eb-8908-413657abfb6a.png)
![图二](https://user-images.githubusercontent.com/11072796/96823302-c9cbf380-145e-11eb-932c-6064a34e1b82.png)

**Comment by hawtim** [comment]
经检查是这行代码的问题
![image](https://user-images.githubusercontent.com/11072796/96823455-229b8c00-145f-11eb-8543-a3dae5b626bd.png)

调试 howler 的 seek 方法：
```js
seek: function () {
  var self = this;
  var args = arguments;
  var seek, id;
  // 没有参数，自动获取第一个 sound 的 id
  if (args.length === 0) {
    id = self._sounds[0]._id; // 1001
  } else if (args.length === 1) {
    var ids = self._getSoundIds();
    var index = ids.indexOf(args[0]);
    if (index >= 0) {
      id = parseInt(args[0], 10);
    } else if (self._sounds.length) {
      id = self._sounds[0]._id;
      seek = parseFloat(args[0]);
    }
  } else if (args.length === 2) {
    seek = parseFloat(args[0]);
    id = parseInt(args[1], 10);
  }


  if (typeof id === 'undefined') {
    return self;
  }
  // self._state === loading
  if (self._state !== 'loaded' || self._playLock) {
    self._queue.push({
      event: 'seek',
      action: function () {
        self.seek.apply(self, args);
      }
    });
    // 返回自身实例 
    return self;
  }
  // 后续省略 。。。
}
```

**Comment by hawtim** [comment]
提交了个 PR，由于对具体的 time = 180 的逻辑不清楚，你看看是否合适合并进去

**Comment by qier222** [comment]
scrobble 现在逻辑没处理好。time = 180是因为，当歌曲播放完后，会调用action.js里的nextTrack，nextTrack会调用switchTrack，而这时歌曲的进度是0，会记录失败，所以把time改成了180。
