### ISSUE TITLE
歌词界面能否提供一个音量控制条

### ISSUE THREAD

**Issue by memorydream** [qier222/YesPlayMusic#373]
如题，我习惯一直开着歌词界面使用，但是这个界面没有音量控制条，只能回到主界面调整完音量再切换回歌词界面

虽然可以使用快捷键，但是目前没有全局快捷键，把焦点切换到播放器后再使用Ctrl + '+/-' 调整显得有些繁琐，而且这样也没有视觉上的提示

**Comment by qier222** [comment]
重复的issue #273
