### ISSUE TITLE
终于更新了,反馈几个问题

### ISSUE THREAD

**Issue by huanx9** [qier222/YesPlayMusic#374]
可在设置里选择音源输出设备 > 这个其实可以在windows 1903版本以上（windows已经原生支持了）

![](https://kd0.net/my/2021/03/ahtqrqw6.png) 然后这里有一个乱码

很讨厌托盘，感觉0.3.3版本无托盘的设计就很好。  不过众口难调，简单的发个声表示还有人讨厌托盘。

**Comment by Programer-YYDS** [comment]
对 这个问号确实有点难受哈哈
