### ISSUE TITLE
客户端项目启动后报错接口404，后端项目启动正常

### ISSUE THREAD

**Issue by lifengsbotlp** [qier222/YesPlayMusic#378]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by qier222** [comment]
重新安装试试

**Comment by lifengsbotlp** [comment]
经过尝试，.env.example 文件下的所有配置未生效 在request中获取VUE_APP_NETEASE_API_URL为undefined

**Comment by qier222** [comment]
需要复制这个文件为 .env
readme里忘记写了
