### ISSUE TITLE
建议给客户端加个字幕上去

### ISSUE THREAD

**Issue by 1628553830** [qier222/YesPlayMusic#381]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by qier222** [comment]
没看懂这个标题😅

**Comment by chaimao403** [comment]
估计是想要悬浮字幕

**Comment by 1628553830** [comment]
对的，就是歌词弹窗

**Comment by 1628553830** [comment]
类似这种






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "qier222"<notifications@github.com&gt;; 
发送时间: 2021年3月9日(星期二) 晚上11:43
收件人: "qier222/YesPlayMusic"<YesPlayMusic@noreply.github.com&gt;; 
抄送: "敢问情为何物"<a1628553830@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [qier222/YesPlayMusic] 建议给客户端加个字幕上去 (#381)





 
没看懂这个标题😅

**Comment by qzhang-debug** [comment]
啥

**Comment by 1628553830** [comment]
![image](https://user-images.githubusercontent.com/47211142/110566673-56b3e700-818b-11eb-9059-1ec532c603ae.png)

**Comment by qier222** [comment]
暂无添加桌面歌词的计划
