### ISSUE TITLE
Mac客户端音乐库内艺人列表显示不全，只能显示25人

### ISSUE THREAD

**Issue by Andkacuc** [qier222/YesPlayMusic#382]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by NEPHERAovo** [comment]
之前我有提过这个bug来着，专辑页面也是一样的问题

**Comment by EasyD0** [comment]
win10x64,收藏的音乐家和专辑最多显示25

**Comment by qier222** [comment]
0.3.7版本应该已经修复了，还有问题的话可以重新开启这个isssue
