### ISSUE TITLE
还是不能用我喜欢/取消喜欢按钮

### ISSUE THREAD

**Issue by xyls184** [qier222/YesPlayMusic#389]
重装了以后也这样

**Comment by xyls184** [comment]
是不是没有彻底清除上个版本的缓存

**Comment by Decade-kaer** [comment]
> 是不是没有彻底清除上个版本的缓存

卸载重装还是无法红心，右键也无法添加

**Comment by FGBWZY** [comment]
这个问题前面有人提过了，开发者也放出了修复后版本的下载链接，开发者回复的链接地址👉https://github.com/qier222/YesPlayMusic/issues/364#issuecomment-792545914

**Comment by debugbb** [comment]
我是新安装的Win版，也是存在点击喜欢无效的问题 @qier222

**Comment by qier222** [comment]
v0.3.5 版本确认已经修复了
