### ISSUE TITLE
韩文歌词显示出错，挤压到一起了

### ISSUE THREAD

**Issue by lonznt** [qier222/YesPlayMusic#391]
韩文歌词显示好像不行。

https://i.loli.net/2021/03/10/CdxoL6EGF84fWXp.jpg

**Comment by llovvoll** [comment]
測試了多次，問題無法重現

![image](https://user-images.githubusercontent.com/20951677/110727870-fab69480-8256-11eb-8f7b-ffd004e717fc.png)

**Comment by lonznt** [comment]
> 测试了多次，问题无法重现
> 
> ![图像](https://user-images.githubusercontent.com/20951677/110727870-fab69480-8256-11eb-8f7b-ffd004e717fc.png)

唉？？？我勒个！！

本来还想说可能是系统版本不同，然后我换了个电脑试了一下，石化……

这是咋回事啊？ 都是win10系统，怎么笔记本上就错位挤压，台机就正常，分辨率的关系吗？

<img src="https://ftp.bmp.ovh/imgs/2021/03/2a0fad535e88790d.jpg" alt="image" style="max-width:100%;">

**Comment by llovvoll** [comment]
> 唉？？？我勒个！！
> 
> 本来还想说可能是系统版本不同，然后我换了个电脑试了一下，石化……
> 
> 这是咋回事啊？ 都是win10系统，怎么笔记本上就错位挤压，台机就正常，分辨率的关系吗？
> 
> ![image](https://camo.githubusercontent.com/e187faba0c43834b507fcde457c26e5e96c8af5ba4b4b6dbd82f8e4b730de050/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032312f30332f326130666164353335653838373930642e6a7067)

剛剛在 Dell Latitude E7440 搭配 Windows 10 Pro ( v.10.0.19042 ) 分別在 1366x768, 1280x768, 1280x720, 1024x768, 800x600 的解析度下測試也都是正常的，你可以檢查看看電腦的顯示驅動程式或嘗試重新安裝程式試試看

**Comment by Annabel0530** [comment]
有同样情况 显卡驱动更新后也一样 怀疑是字体问题

**Comment by Annabel0530** [comment]
今天用PS的时候发现解决方法了  应该是安装字体的时候覆盖了默认注册表  把显示有问题的字体删掉就好了
![image](https://user-images.githubusercontent.com/40524485/114886035-348a3600-9dd5-11eb-8319-5f5ae1851596.png)
