### ISSUE TITLE
登陆后, 页面空白, 调试后接口提示 被限制.

### ISSUE THREAD

**Issue by nailaojiang** [qier222/YesPlayMusic#394]
### 反馈 bug 需要的信息

- 客户端
- MAC
- 
![image](https://user-images.githubusercontent.com/20086206/110725481-a4475700-8252-11eb-8a02-7b0e3304e2a9.png)

**Comment by martin0607** [comment]
相同情况，路由器没开Unblock插件

**Comment by lycor1s** [comment]
有相同情况

**Comment by memorydream** [comment]
相同情况，arch linux
