### ISSUE TITLE
Use lower case spelling for the package name.

### ISSUE THREAD

**Issue by latin-1** [qier222/YesPlayMusic#400]
The package name with upper case letters is not recommended in both npm and Arch Linux. Although it's not prohibited explicitly, it may cause some problems in edge cases. (e.g. it crashes the pikaur (an AUR helper))

- https://docs.npmjs.com/cli/v7/configuring-npm/package-json#name
  > New packages must not have uppercase letters in the name.
- https://wiki.archlinux.org/index.php/Arch_package_guidelines#Package_naming
  > All letters should be lowercase.

**Comment by qier222** [comment]
I will fix this in the next version, thanks.

**Comment by qier222** [comment]
v0.3.5 版本确认已经修复了
