### ISSUE TITLE
切换上下首的快捷键有点太鸡肋了

### ISSUE THREAD

**Issue by bitepen** [qier222/YesPlayMusic#405]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

最新版的切换歌曲热键是Ctrl+Left Ctrl+Right，切换到其他窗口就几乎残废了，建议弄成Ctrl+Alt+Left，Ctrl+Alt+Right切歌

**Comment by bigbossxu942** [comment]
是什么样的快捷键，我好想没有找到

**Comment by qier222** [comment]
v0.3.5已支持全局快捷键，跟网易云的是一样的

**Comment by bitepen** [comment]
> v0.3.5已支持全局快捷键，跟网易云的是一样的

谢谢大佬 看到了
