### ISSUE TITLE
希望添加下歌词字体大小的调整

### ISSUE THREAD

**Issue by Lost-f** [qier222/YesPlayMusic#425]
默认的字体太大了，略显粗糙...🤦‍♂️

**Comment by llovvoll** [comment]
在设置里面有选项可以调整的

**Comment by PeakmanCheung** [comment]
![image](https://user-images.githubusercontent.com/70582945/111259651-3f577c80-8617-11eb-95f1-610c60ec44a0.png)
![image](https://user-images.githubusercontent.com/70582945/111259657-42eb0380-8617-11eb-9d11-cb00a30a4fa4.png)
win10，0.3.4 没有发现字体调整的选项

**Comment by PeakmanCheung** [comment]
发现作者已经在其他issue中回复了，说字体大小调整已加入to do list

**Comment by llovvoll** [comment]
抱歉，我忘了还没有正式发布，要等项目主发布或是你自行打包客户端

**Comment by wwwenjie** [comment]
maybe it can be closed

**Comment by qier222** [comment]
v0.3.5 版本支持了
