### ISSUE TITLE
For You 有几率返回空值，导致页面为空

### ISSUE THREAD

**Issue by wwwenjie** [qier222/YesPlayMusic#430]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

环境：Web，无痕游览  
电台请求 params: 
```
timestamp: new Date().getTime()
cookie: MUSIC_U=undefined;
```
该请求大部分情况能获取到内容，存在获取空数组的情况，或许当获取结果为空数组的情况下，需要重复请求。

<img width="1440" alt="Screen Shot 2021-03-17 at 10 41 54 AM" src="https://user-images.githubusercontent.com/29472143/111406669-a9524d80-870d-11eb-9763-67aecae74f34.png">

**Comment by qier222** [comment]
没遇到这个情况，api接口返回了错误信息吗？

**Comment by wwwenjie** [comment]
> 没遇到这个情况，api接口返回了错误信息吗？

我在无痕游览模式中经常遇到，api 返回的 data 是 []，上面有 network 截图。感觉是无痕游览的问题，正常模式刚刚试了很多次都有值返回。

**Comment by qier222** [comment]
最新版应该修复了
