### ISSUE TITLE
能不能增加一个设定缓存目录的功能啊，现在缓存的文件找不到在哪儿了

### ISSUE THREAD

**Issue by sylichao** [qier222/YesPlayMusic#432]
windows版本里F12功能用不了，找不到缓存文件在哪儿去了
能不能增加一个设定缓存目录的功能啊，现在缓存的文件找不到在哪儿了

**Comment by WindUpRadio** [comment]
顶

**Comment by sylichao** [comment]
> windows版本里F12功能用不了，找不到缓存文件在哪儿去了
> 能不能增加一个设定缓存目录的功能啊，现在缓存的文件找不到在哪儿了

实在不行，在设置界面把缓存路径显示出来也好啊，至少能找到文件在哪儿

**Comment by xiaoqiuzzz233** [comment]
找不到缓存的目录放哪了 windows版本。

**Comment by qier222** [comment]
关于这个issue的讨论移动到 #558
