### ISSUE TITLE
希望增加一个歌单内搜索的功能

### ISSUE THREAD

**Issue by YY-GAO** [qier222/YesPlayMusic#434]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by qier222** [comment]
@VidocqH 能把搜索选项放到歌单菜单里吗？
![image](https://user-images.githubusercontent.com/68148142/111607052-da687600-8812-11eb-985c-cc40549c5ad0.png)

**Comment by VidocqH** [comment]
> @VidocqH 能把搜索选项放到歌单菜单里吗？
> ![image](https://user-images.githubusercontent.com/68148142/111607052-da687600-8812-11eb-985c-cc40549c5ad0.png)

意思是按了选项后显示搜索框嘛 还是说怎样呢？

**Comment by VidocqH** [comment]
> 按了之后显示搜索框

![屏幕录制2021-03-19 上午2 49 25](https://user-images.githubusercontent.com/16725418/111681363-1bd24300-885e-11eb-980c-99205d1db243.gif)

你的意思是这样嘛？（这帧率有点低，所以播放有点慢额）

**Comment by qier222** [comment]
> > 按了之后显示搜索框
> 
> 
> 
> ![屏幕录制2021-03-19 上午2 49 25](https://user-images.githubusercontent.com/16725418/111681363-1bd24300-885e-11eb-980c-99205d1db243.gif)
> 
> 
> 
> 你的意思是这样嘛？（这GIF帧率有点低，所以播放有点慢额）

这样可以

**Comment by qier222** [comment]
0.3.6已支持
