### ISSUE TITLE
部署至Vercel页面空白

### ISSUE THREAD

**Issue by 1eif** [qier222/YesPlayMusic#435]
- Api也是部署在Vercel，且测试访问没有问题。
- 在后台已经添加了环境变量，但在Api的日志中显示根本没有收到请求。
- 网址：https://yes-play-music-mocha.vercel.app/
[![6c6ay4.png](https://s3.ax1x.com/2021/03/17/6c6ay4.png)](https://imgtu.com/i/6c6ay4)

**Comment by qier222** [comment]
如果是Deploy之后再添加环境变量的话，需要重新Deploy

**Comment by 1eif** [comment]
> 如果是Deploy之后再添加环境变量的话，需要重新Deploy

谢谢  部署前后都试过了，还是一样
- value填写有什么要求吗，我尝试了不加协议，加https://、http://、后面加/ ，都是一样的效果
- 控制台显示错误一样

**Comment by qier222** [comment]
你可以试试看我部署到Vercel的网易云API
`https://netease-cloud-music-api-two.vercel.app`

**Comment by qier222** [comment]
浏览器可能会有缓存，打开控制台，选择Network的标签，勾上Disable cache，再刷新试试看。

**Comment by 1eif** [comment]
找到问题了，Api不能使用自定义域名，使用Vercel提供的域名就正常显示。谢谢
