### ISSUE TITLE
歌单无法添加收藏或保存到音乐库

### ISSUE THREAD

**Issue by RebirthEgo** [qier222/YesPlayMusic#438]
歌单无法添加收藏或保存到音乐库

**Comment by qier222** [comment]
会在下个版本修复

**Comment by shi991203** [comment]
@qier222 在Mac系统最新版本中，可以对单曲进行收藏，但是无法将歌单收藏和添加到音乐库

**Comment by qier222** [comment]
> @qier222 在Mac系统最新版本中，可以对单曲进行收藏，但是无法将歌单收藏和添加到音乐库

是

**Comment by luckykong** [comment]
歌单不能收藏，是发出去申请链接中多加了cookie，从链接中删掉cookie 就可以了。 临时解决的话，用url redirector 重定向一下就可以

> @qier222 在Mac系统最新版本中，可以对单曲进行收藏，但是无法将歌单收藏和添加到音乐库

**Comment by qier222** [comment]
> 歌单不能收藏，是发出去申请链接中多加了cookie，从链接中删掉cookie 就可以了。 临时解决的话，用url redirector 重定向一下就可以
> 
> > @qier222 在Mac系统最新版本中，可以对单曲进行收藏，但是无法将歌单收藏和添加到音乐库

我研究看看

**Comment by qier222** [comment]
已修复，等待下一版客户端发布就可以用上了

**Comment by CC9310** [comment]
现在好像并不可以 版本:0.4.4-1

**Comment by UrealToby** [comment]
同不行
