### ISSUE TITLE
Win客户端0.3.4无法使用最小化、最大化及关闭按钮。

### ISSUE THREAD

**Issue by McSylvanas** [qier222/YesPlayMusic#439]
### 反馈 bug 需要的信息

- 用的是网页版还是客户端————Win客户端0.3.4，无法使用最小化、最大化及关闭按钮。
- 浏览器名称或电脑操作系统————Win10 20H2
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://user-images.githubusercontent.com/23581660/111494334-557d4e00-8779-11eb-8532-49a3692e8b23.png)

**Comment by MrWillCom** [comment]
我这边测试正常，能提供具体的复现方法吗

**Comment by pencilheart** [comment]
YesPlayMusic 0.3.5，Win客户端，Win10 20H2，
![image](https://user-images.githubusercontent.com/61617063/112105979-08213680-8be8-11eb-9ef8-a55260435c03.png)

**Comment by komichiaya** [comment]
YesPlayMusic 0.3.5，Win客户端，Win10 1809
![bug](https://user-images.githubusercontent.com/51192417/112718569-d92ffb00-8f2e-11eb-8a2e-ceba409d625f.png)
，
