### ISSUE TITLE
希望可以加入咪咕音源，想听周杰伦的歌

### ISSUE THREAD

**Issue by is-idea** [qier222/YesPlayMusic#445]
RT...好人一生平安

**Comment by martin0607** [comment]
周董的一直可以听啊

**Comment by is-idea** [comment]
> 周董的一直可以听啊

歌曲有些听不了，而且有的不是周杰伦的。比如《米兰的小铁匠》在咪咕搜的听一下你就知道啦

**Comment by qier222** [comment]
解锁服务那边本来就有咪咕音源，可以在 `src/electron/ipcMain.js` 的 13 行看到有migu
