### ISSUE TITLE
setting按钮的位置讨论

### ISSUE THREAD

**Issue by BeADre** [qier222/YesPlayMusic#45]
首先setting作为一个全局页面的一个配置我觉得放在nav里会好一些 像下面这样

![image](https://user-images.githubusercontent.com/34639100/96965147-41248480-153e-11eb-98b8-004f04e4e245.png)

作者感觉如何呢？ 如何可以的话我提交pr

**Comment by qier222** [comment]
设置不是一个需要经常访问的页面，放nav的话会让nav在视觉上左右更加不平衡（现在已经不平衡了）

**Comment by BeADre** [comment]
主要后面的话设置页肯定还会继续添加list项 比如说drak mode等， 如果放在footer里用户可能在没滑倒底压根就不知道有这样一个设置的页面。 然后第二点左右对称的话 我感觉放个button上去不会太影响美观

**Comment by qier222** [comment]
Dark Mode会有个Auto模式，可以自动切换Light/Dark Mode，默认为Auto模式。
以后会考虑改变搜索框的位置和样式，可能会在右上角加上头像，点击头像后出现二级菜单。

**Comment by BeADre** [comment]
嗯 ok
