### ISSUE TITLE
请问怎么显示歌词？？

### ISSUE THREAD

**Issue by xwwbest** [qier222/YesPlayMusic#452]
请问怎么显示歌词？？桌面没有，软件里面也没有歌词！![微信截图_20210319211314](https://cdn.jsdelivr.net/gh/xwwbest/img@master/imgs/微信截图_20210319211314.72x96fgc11c0.png)

**Comment by llovvoll** [comment]
右下角向上箭头展开后就可以看到歌词页面了

![image](https://user-images.githubusercontent.com/20951677/111786556-e595d180-88f8-11eb-8c44-46534393a0d3.png)

**Comment by xwwbest** [comment]
好的感谢，找了好久没找到！个人建议点击头像弹出歌词界面，而不是点击头像跳转到专辑页面。

**Comment by qier222** [comment]
> 好的感谢，找了好久没找到！个人建议点击头像弹出歌词界面，而不是点击头像跳转到专辑页面。

不打算这样做
