### ISSUE TITLE
每次重新打开文件都会提示申请接入网络连接，防火墙已允许。

### ISSUE THREAD

**Issue by alazysun** [qier222/YesPlayMusic#455]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 最新版0.35 dmg
- macos10.15.7
- [image](https://s4.ax1x.com/2021/03/19/6fBlZj.png)（国内可访问，好像不欢迎代理）

**Comment by ppjxhyyy** [comment]
同样存在这个问题，再次检查了防火墙，已允许✅

**Comment by zhang-qi-yang** [comment]
> 0.3.4有出现过嘛？

0.3.4同样存在这个问题。我今天受不了来这里就是想来说说这个问题的。已允许但每次都提示。

**Comment by zhang-qi-yang** [comment]
0.3.5 和 0.3.6 此问题依旧……

**Comment by VidocqH** [comment]
> 0.3.5 和 0.3.6 此问题依旧……

我发现我没有是因为我关了防火墙😂

**Comment by qier222** [comment]
没复现这个问题
