### ISSUE TITLE
无法加载顶部菜单

### ISSUE THREAD

**Issue by Megghy** [qier222/YesPlayMusic#459]
- 客户端
- Windows10 20H2
- ![image](https://user-images.githubusercontent.com/44969916/111858285-b15ef700-8972-11eb-9fe4-5816288700c4.png)

**Comment by sylichao** [comment]
我的从今天开始也这样了

**Comment by llovvoll** [comment]
我刚刚也发现了这个问题，主要是 user data 旧版数据的问题，自行解决的话可以将页面缓存 清除后就能正常了

**Comment by Megghy** [comment]
> 我刚刚也发现了这个问题，主要是 user data 旧版数据的问题，自行解决的话可以将页面缓存 清除后就能正常了

已解决, 十分感谢
