### ISSUE TITLE
请求加入快捷键设置/取消入口，默认快捷键与Chrome冲突

### ISSUE THREAD

**Issue by mx1n** [qier222/YesPlayMusic#460]
平台：macOS
版本：0.3.5

Chrome默认切换左右Tab的快捷键是`Command+Option+左右方向键`，和上一首/下一首的快捷键冲突

**Comment by qier222** [comment]
在计划中了

**Comment by qier222** [comment]
0.3.6版本已支持关闭全局快捷键
