### ISSUE TITLE
#希望可以添加网易云灰色歌曲喜欢的功能

### ISSUE THREAD

**Issue by olddriverv5** [qier222/YesPlayMusic#462]
最新版本35 比如周杰伦之类的没有版权的歌无法喜欢，可能是我的版本有问题？                        在用安卓的时候插件可以实现喜欢，不知道这个电脑端可以实现吗

**Comment by olddriverv5** [comment]
![image](https://user-images.githubusercontent.com/48822456/111873192-1a258e00-89ca-11eb-8deb-5bc8c61f6905.png)
![image](https://user-images.githubusercontent.com/48822456/111873211-39242000-89ca-11eb-95cb-1742073198a2.png)
是我的客户端不行还是确实缺少这个功能？

**Comment by olddriverv5** [comment]
![image](https://user-images.githubusercontent.com/48822456/111873268-7688ad80-89ca-11eb-9a62-8afb813bb247.png)

**Comment by olddriverv5** [comment]
如果是缺少，跪求这个功能
如果不是，请问有人可以吗

**Comment by debugbb** [comment]
灰色歌曲不支持加歌单应该是因为接口不支持。有没有思路去实现此功能，同跪求

**Comment by sjwang166** [comment]
同求

**Comment by qier222** [comment]
0.3.6版本应该已经修复了

**Comment by debugbb** [comment]
0.3.6灰色歌曲依然不能加入喜欢啊
