### ISSUE TITLE
bug发现

### ISSUE THREAD

**Issue by sunhongfan** [qier222/YesPlayMusic#463]
Mac客户端， 无法收藏歌单，喜欢功能偶尔失效，上下列表滚动界面过渡会卡顿，支持你们，同时也希望共同维护好这个app。

**Comment by qier222** [comment]
无法收藏歌单的bug已经有相关issue了。
喜欢歌曲偶尔失效的问题没遇到过，下次发生的时候看一下控制台有没有错误日志

**Comment by qier222** [comment]
上下列表滚动卡顿

不知道你说的是哪个列表

**Comment by sunhongfan** [comment]
> 上下列表滚动卡顿
> 
> 不知道你说的是哪个列表


就是歌曲搜索出来后的列表 快速滑动鼠标滚轮屏幕就会出现问题
