### ISSUE TITLE
[UX]  切歌快捷键冲突

### ISSUE THREAD

**Issue by wwwenjie** [qier222/YesPlayMusic#469]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

v0.3.5 mac

新版的上一首和下一首的快捷键与 webstrom 的移动光标上一处位置和下一处位置存在冲突。导致想移动光标的时候切歌，现已无法快乐的边听歌边敲代码了。
建议：hotfix 设置中添加禁用快捷键的选项，feat: 设置中移除禁用快捷键的选项并加入自定义快捷键的选项。

**Comment by guohui-ma** [comment]
这个大概什么时候会发新版呀？ @wwwenjie

**Comment by qier222** [comment]
> 这个大概什么时候会发新版呀？ @wwwenjie

下一个版本会有的

**Comment by 15140318524** [comment]
全局切歌快捷键是什么？ctrl+alt+←/→ 吗？为什么我触发不了？我用热键冲突工具检查了一下，好像没有这个热键组合。

**Comment by wwwenjie** [comment]
> 全局切歌快捷键是什么？ctrl+alt+←/→ 吗？为什么我触发不了？我用热键冲突工具检查了一下，好像没有这个热键组合。

可能是你目前没有用到这个快捷键所以没有冲突，不过在 JetBarins 的默认热键中存在冲突。

**Comment by qier222** [comment]
> 全局切歌快捷键是什么？ctrl+alt+←/→ 吗？为什么我触发不了？我用热键冲突工具检查了一下，好像没有这个热键组合。

Windows上没测试过，但是根据Electron文档，应该是 alt+ctrl+箭头。
Mac上用 Option+Command+箭头可以正常使用。
代码里用的是 `Alt+CommandOrControl+Right`

https://www.electronjs.org/docs/api/accelerator

**Comment by pppeace** [comment]
> > 全局切歌快捷键是什么？ctrl+alt+←/→ 吗？为什么我触发不了？我用热键冲突工具检查了一下，好像没有这个热键组合。
> 
> 可能是你目前没有用到这个快捷键所以没有冲突，不过在 JetBarins 的默认热键中存在冲突。

感谢回复，我刚才查了一下，确实JetBrains 家的导航栏切换快捷键冲突了，但是我设置取消掉后还是触发不了播放器的全局快捷键（也尝试过重启JetBrains 和播放器），还是感谢回复，我再尝试一下。

**Comment by pppeace** [comment]
> > 全局切歌快捷键是什么？ctrl+alt+←/→ 吗？为什么我触发不了？我用热键冲突工具检查了一下，好像没有这个热键组合。
> 
> Windows上没测试过，但是根据Electron文档，应该是 alt+ctrl+箭头。
> Mac上用 Option+Command+箭头可以正常使用。
> 代码里用的是 `Alt+CommandOrControl+Right`
> 
> https://www.electronjs.org/docs/api/accelerator

谢谢回复，@wwwenjie 提到JetBrains 快捷键冲突，已经在尝试解决了。

**Comment by qier222** [comment]
0.3.6版本已支持关闭全局快捷键
