### ISSUE TITLE
unknown action type: playTrackOnListByID

### ISSUE THREAD

**Issue by book987** [qier222/YesPlayMusic#472]
- 用的是网页版还是客户端
  - 客户端
- 浏览器名称或电脑操作系统
  - macOS Catalina Version 10.15.6
- 控制台 Console 页面的截图（按 F12 可打开控制台
<img width="528" alt="Screenshot 2021-03-22 at 6 52 45 PM" src="https://user-images.githubusercontent.com/17219814/111979254-cc329680-8b3f-11eb-93d9-67d670bd33ed.png">

播放列表页双击 item 无反应，看了下代码没实现这个 action，是 feature 吗？@qier222

**Comment by qier222** [comment]
是bug，下个版本修复

**Comment by qier222** [comment]
0.3.6版本应该已经修复了
