### ISSUE TITLE
功能解惑:Discord Rich Presence这个功能是什么用，怎么使用？

### ISSUE THREAD

**Issue by wonktondI** [qier222/YesPlayMusic#473]
Discord Rich Presence这个功能咋使用？

**Comment by debugbb** [comment]
同咨询

**Comment by qier222** [comment]
这里有截图
https://github.com/qier222/YesPlayMusic/pull/408

**Comment by wonktondI** [comment]
> 这里有截图
> #408

作者大大，前三张图的效果怎样可以触发？

**Comment by qier222** [comment]
应该下载discord，然后播放音乐就行了吧🤔，我也没用过

**Comment by VidocqH** [comment]
> > 这里有截图
> > #408
> 
> 作者大大，前三张图的效果怎样可以触发？

打开`Discord` 打开`YesPlayMusic` 然后播放就可以了 为了性能 我模仿了`VSCode`中`Discord Rich Presence`的做法 只会在打开`YesPlayMusic`的时候看一看有没有已经打开的`Discord` 有就连接没有就不会再尝试连接 另外 对于多个DiscordRichPresence会有顶掉的情况存在 这是`Discord`自己的问题
