### ISSUE TITLE
功能建议：在底部播放条上增加一个喜欢的按钮

### ISSUE THREAD

**Issue by hawtim** [qier222/YesPlayMusic#48]
如图，个人的操作习惯是听到好听的歌就会想要点个喜欢。
算是一个体验建议，是否考虑同步网易云这个功能。
![image](https://user-images.githubusercontent.com/11072796/97041432-24ba3380-15a2-11eb-93ee-0b8dcb002bbf.png)

网易云的实现：

![image](https://user-images.githubusercontent.com/11072796/97041711-7bc00880-15a2-11eb-8d2c-0d54bea91bb4.png)

**Comment by qier222** [comment]
这个功能有啊，需要登录账号后才会显示。

**Comment by hawtim** [comment]
奇怪了，我在 demo 页面登录账号了，底部条也没显示出来。
这个判断条件我研究一下

![image](https://user-images.githubusercontent.com/11072796/97067596-8f469000-15f1-11eb-9185-d151b401d555.png)

**Comment by hawtim** [comment]
登录之后要再刷新一下才会出现喜欢按钮

**Comment by hawtim** [comment]
还有一个问题，设置页面点击退出登录的时候会到首页，但是底部条的喜欢按钮仍然出现

**Comment by qier222** [comment]
可能是退出登录后，MUSIC_U这个cookie没删除。

**Comment by hawtim** [comment]
退出登录后 MUSIC_U 是删除的，原因应该是这个登录状态不是响应式的，我捋一捋这个登录的逻辑
