### ISSUE TITLE
希望可以实现播放列表的删除功能

### ISSUE THREAD

**Issue by y1464251173** [qier222/YesPlayMusic#481]

**Comment by qier222** [comment]
有这个功能的，要自己创建的才能删除

**Comment by y1464251173** [comment]
> 有这个功能的，要自己创建的才能删除

希望对原有的歌单也能添加删除功能；因为有的歌单中会存在用户不喜欢听的歌，在不方便切歌情况下，就只能任其播放了，这样会降低歌曲推荐的精准度

**Comment by qier222** [comment]
这个情况下你应该新建一个歌单，将歌曲全部放进新歌单，再删除。
不过现在没有批量操作歌曲的功能…… 以后会有的

**Comment by y1464251173** [comment]
> 这个情况下你应该新建一个歌单，将歌曲全部放进新歌单，再删除。
> 不过现在没有批量操作歌曲的功能…… 以后会有的
