### ISSUE TITLE
【Windiws】【客户端】不能替换无版权歌曲

### ISSUE THREAD

**Issue by NCSrapoo** [qier222/YesPlayMusic#483]

**Comment by qier222** [comment]
不清楚你要反馈什么问题

**Comment by NCSrapoo** [comment]
就是他不是可以用UnblockNeteaseMusic自动替换无版权歌曲嘛，现在不能替换

**Comment by qier222** [comment]
我这边可以替换

**Comment by 72Monkeyking** [comment]
> 我这边可以替换

和网络供应商有关吗？公司电信网络可以正常解锁灰色歌曲，家里的移动不行，很是纳闷。

**Comment by NCSrapoo** [comment]
重新安装一遍就好了，但是有部分歌曲不能播放，可能是哪里都没有这首歌了吧，

**Comment by debugbb** [comment]
请试下阿桑的一直很安静，网易无版权，QQ是有的，之前一直解析没问题呢，有一些玄学，哈哈

**Comment by debugbb** [comment]
> 应该是UnblockNeteaseMusic的服务问题，我这边遇到了这个问题了，当无法解析时，弹出框报错了，所以客户端上看上去是无反应的

特别玄学，重启就好了，重启大法

**Comment by 72Monkeyking** [comment]
> > 应该是UnblockNeteaseMusic的服务问题，我这边遇到了这个问题了，当无法解析时，弹出框报错了，所以客户端上看上去是无反应的
> 
> 特别玄学，重启就好了，重启大法

也许是服务器问题吧，家里的网络偶尔能解锁，但流畅度不保证，因为会卡。重启技能已释放，不灵无奈。
