### ISSUE TITLE
歌词动态背景 GPU 占用过高

### ISSUE THREAD

**Issue by HuaJi2333DaDa** [qier222/YesPlayMusic#484]
如题，希望可以优化一下
![image](https://user-images.githubusercontent.com/30079825/112328707-8d444280-8cf1-11eb-81fc-a702d515e473.png)
用的是客户端，客户端版本是：0.3.5
系统版本是：win10 19042.870
控制台 Console 页面的截图：
![image](https://user-images.githubusercontent.com/30079825/112329256-02177c80-8cf2-11eb-839f-693a53364cc3.png)

**Comment by wwwenjie** [comment]
目前的实现确实比较吃性能，所以默认是关闭的。有时间会去看看有没有什么方法能优化下。

**Comment by martin0607** [comment]
也不知道是不是歌词的原因，Mac上也是GPU占用很高，开着音乐浏览网页就很卡

**Comment by wwwenjie** [comment]
> 也不知道是不是歌词的原因，Mac上也是GPU占用很高，开着音乐浏览网页就很卡

是动态背景导致的，可以退出歌词页面或者关闭动态背景来降低GPU占用。最近忙着毕业等忙完了就来优化一下动态背景。

**Comment by Map1en** [comment]
我觉得加个静态的背景的选项也不错的。现在这个动态不仔细看都看不出来是动态的😹

**Comment by Nevodev** [comment]
> 目前的实现确实比较吃性能，所以默认是关闭的。有时间会去看看有没有什么方法能优化下。

如果直接给他blur，他就会一直模糊一直模糊，就比较占GPU。其实就是两张图片在旋转，不需要一直模糊。
这就提供了个思路，可以直接把图片模糊了，变成一张新的图片，再把他放进去旋转。这样就不会一直GPU。

![图片说明](https://user-images.githubusercontent.com/51047891/116804784-2fa6df80-ab54-11eb-8279-afdaa5c8beae.png)

如图所示
