### ISSUE TITLE
assets里面后缀为tar.gz的文件用途

### ISSUE THREAD

**Issue by lovecll991224** [qier222/YesPlayMusic#487]
您好，请问assets里面后缀为tar.gz的文件可以用在刷了梅林的路由器里吗？
因为之前在路由器里面装插件的文件后缀也是这个，所以想问一下这个文件是不是也支持这种功能？
谢谢！

**Comment by qier222** [comment]
不支持安装在路由器上

**Comment by lovecll991224** [comment]
好的 谢谢您回复
