### ISSUE TITLE
Touch Bar无法拖动播放进度

### ISSUE THREAD

**Issue by terencehyz** [qier222/YesPlayMusic#496]
- 客户端
- macOS 11.2.3
<img width="1085" alt="触控栏快照2021-03-27 下午3 10 23" src="https://user-images.githubusercontent.com/16203746/112713218-197f8100-8f0f-11eb-9883-188300e89f7b.png">

**Comment by Edmon-Leo** [comment]
同问

**Comment by qier222** [comment]
Electron 那边暂时没有这样的API可以做这样的事
