### ISSUE TITLE
网页版异常

### ISSUE THREAD

**Issue by GreenTeodoro839** [qier222/YesPlayMusic#497]
就是PWA的最下面一直是这样，
<img width="1080" alt="-540631ee77930950" src="https://user-images.githubusercontent.com/77104800/112725064-350b7b80-8f51-11eb-8094-404394f06607.png">
怎么点都没有反应

**Comment by cxw620** [comment]
是不是国外的服务器？我的也遇到这个问题

**Comment by DsTansice** [comment]
我的也是这样/哭

**Comment by immortal-wh** [comment]
网页版登录后无法正常播放歌曲，点击无反应

**Comment by qier222** [comment]
尽快修复

**Comment by ennnnny** [comment]
可以尝试临时修复（非完美方案）：
打开 `src/utils/Player.js` 文件，250行左右，`_replaceCurrentTrack`方法，找到
```js
if (autoplay) this._scrobble(this.currentTrack, this._howler.seek(), true);
```
替换成
```js
if (autoplay) {
  if (this._howler) {
    this._scrobble(this.currentTrack, this._howler.seek(), true);
  } else {
    this._scrobble(this.currentTrack, null, true);
  }
}
```
