### ISSUE TITLE
能否集成 API，不用单独部署，打包成安装包，降低使用门槛

### ISSUE THREAD

**Issue by Zhiwei1996** [qier222/YesPlayMusic#5]
好看
然后能不能搞简单一点安装

**Comment by pan93412** [comment]
或許可以包成一個 docker image。我晚點做做看。

**Comment by CXY23** [comment]
教程很详细  就是懒得折腾哈  不过自己动手丰衣足食哈

**Comment by pan93412** [comment]
可以直接用 [GitHub 說明提到的 Demo 連結喔](https://music.bluepill.one/)。

**Comment by Easy1999** [comment]
可以使用docker部署

**Comment by i0Ek3** [comment]
可否直接编译成对应平台的安装包呢？自己在本地试了一下，没办法直接打包过去，似乎要修改一些东西才行，原谅我不懂前端......

**Comment by yang-zhifei** [comment]
ui很舒适，如果改成简单的安装，会有很多人愿意用的

**Comment by hawtim** [comment]
> ui很舒适，如果改成简单的安装，会有很多人愿意用的

在处理了，可以关注下 [electron 分支](https://github.com/qier222/YesPlayMusic/tree/electron)
目前由于个人开发没有 windows 机器，所以对 Mac 会比较友好，当然也欢迎你的 PR。

**Comment by NavlysChen** [comment]
linux可以使用吗？

**Comment by openwrt36** [comment]
> > ui很舒适，如果改成简单的安装，会有很多人愿意用的
> 
> 在处理了，可以关注下 [electron 分支](https://github.com/qier222/YesPlayMusic/tree/electron)
> 目前由于个人开发没有 windows 机器，所以对 Mac 会比较友好，当然也欢迎你的 PR。

问下只上传dist文件夹的内容就行了，不用api，还是api已经打包了？

**Comment by hawtim** [comment]
> > > ui很舒适，如果改成简单的安装，会有很多人愿意用的
> > 
> > 
> > 在处理了，可以关注下 [electron 分支](https://github.com/qier222/YesPlayMusic/tree/electron)
> > 目前由于个人开发没有 windows 机器，所以对 Mac 会比较友好，当然也欢迎你的 PR。
> 
> 问下只上传dist文件夹的内容就行了，不用api，还是api已经打包了？

electron 版本才有集成 api，web 版还没有。

**Comment by hawtim** [comment]
> linux可以使用吗？

linux 目前打包出来安装后打不开 ，还在排期解决。

**Comment by openwrt36** [comment]
> > > > ui很舒适，如果改成简单的安装，会有很多人愿意用的
> > > 
> > > 
> > > 在处理了，可以关注下 [electron 分支](https://github.com/qier222/YesPlayMusic/tree/electron)
> > > 目前由于个人开发没有 windows 机器，所以对 Mac 会比较友好，当然也欢迎你的 PR。
> > 
> > 
> > 问下只上传dist文件夹的内容就行了，不用api，还是api已经打包了？
> 
> electron 版本才有集成 api，web 版还没有。
感谢回答，我以为是上传就能像demo一样，求搭建教程

**Comment by qier222** [comment]
@i0Ek3 i @NavlysChen @yang-zhifei 目前打包了 macOS、Windows、Linux 三平台的安装包，欢迎下载测试。

[https://github.com/qier222/YesPlayMusic/releases/tag/v0.2.1-beta1](https://github.com/qier222/YesPlayMusic/releases/tag/v0.2.1-beta1)
