### ISSUE TITLE
[bug] 私人FM中无法切换播放模式

### ISSUE THREAD

**Issue by FrzMtrsprt** [qier222/YesPlayMusic#501]
## 环境
Windows 客户端 0.3.5
## 问题
正常播放模式中选中单曲循环，再进入私人FM，仍然是单曲循环，并且无法切换回顺序播放。
此时必须切换回正常播放模式，才能换回顺序播放。
## 复现步骤
1. 在任意歌单点开任意歌曲
2. 将播放模式切换为单曲循环
3. 点击播放私人FM
4. 发现重复播放当前歌曲，且无法切换播放模式
## 建议
单独存储私人FM的播放模式，开放私人FM中切换顺序播放或单曲循环，且私人FM与正常播放下的播放模式互不干扰。

**Comment by Map1en** [comment]
好像原本网易云也没有提供私人fm模式的播放模式？

**Comment by FrzMtrsprt** [comment]
0.3.6里这个问题似乎还在啊，https://github.com/Map1en/YesPlayMusic/commit/e79d3ce0d1d8292878b6a2bb362a851f109c705c 修好这个问题后，https://github.com/qier222/YesPlayMusic/commit/4f4f2b09e3f29718eaade4a932803f752b223476 又给改回去了

**Comment by qier222** [comment]
> Map1en@e79d3ce

谢谢提醒，改回来了
