### ISSUE TITLE
BUG：登陆账号后资源加载失败，在登陆状态下重启app顶栏消失

### ISSUE THREAD

**Issue by memorydream** [qier222/YesPlayMusic#502]
版本：0.3.5
操作系统：Windows10 21H1预览版

登陆后控制台消息：
![image](https://user-images.githubusercontent.com/34763046/112767127-7f6f2400-9047-11eb-9f7d-984d2a9b0966.png)

登陆后重启APP的界面：
![image](https://user-images.githubusercontent.com/34763046/112767156-a3326a00-9047-11eb-82aa-ab1712115d49.png)

登陆后重启APP的控制台消息：
![image](https://user-images.githubusercontent.com/34763046/112767014-01128200-9047-11eb-9e61-1fd868a14195.png)

使用账号登陆后，用户图标处无变化，单击后菜单无变化，可重复进行登陆操作，使用搜索账号后可顶掉之前的登陆状态，再次重启APP可正常使用

账号登陆并重启APP后，可以通过删除%AppData%下的yesplaymusic文件夹重置所有数据以回到最初状态并正常使用

**Comment by memorydream** [comment]
相关的issue有点多，在新版本发布前考虑将这个issue pin住
问题的临时解决方案在 #517 
@qier222

**Comment by qier222** [comment]
0.3.6应该已经修复了
