### ISSUE TITLE
[Issue] [Windows] Close button cover by scroll bar

### ISSUE THREAD

**Issue by ShiinaManatsu** [qier222/YesPlayMusic#505]
0.3.5 @ Windows 10

Home page
![image](https://user-images.githubusercontent.com/20186095/112791262-bcf99e80-9093-11eb-860e-8f4b6184a3bd.png)

Playing, Title bar totally covered.

![image](https://user-images.githubusercontent.com/20186095/112792224-a48a8380-9095-11eb-91ae-ed83fb254c39.png)

**Comment by qier222** [comment]
v0.4.0 版本已修复
