### ISSUE TITLE
添加喜欢 - 快捷键冲突

### ISSUE THREAD

**Issue by sevth-developer** [qier222/YesPlayMusic#506]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 平台 big sur
- 软件版本 0.3.5

添加喜爱的快捷键和jetbrains全家桶的格式化代码快捷键冲突 `command` + `option` + `L`
(好像有人提到快捷键冲突的问题，如果下个版本有修复的话，忽略我的问题吧 :)

**Comment by wwwenjie** [comment]
已经添加了关闭快捷键的设置，下个版本会发布。

**Comment by qier222** [comment]
0.3.6版本已支持关闭全局快捷键
