### ISSUE TITLE
0.3.5版本占用了idea快捷键 option+command+L

### ISSUE THREAD

**Issue by BarryYBL** [qier222/YesPlayMusic#510]
0.3.5版本占用了idea快捷键 option+command+L，希望有自定义快捷键的功能；或者关闭快捷键等等

**Comment by ShiinaManatsu** [comment]
卸载idea可以解决（

**Comment by BarryYBL** [comment]
> 卸载idea可以解决（

你好像有点不太聪明的样子

**Comment by wwwenjie** [comment]
已经添加了关闭快捷键的设置，下个版本会发布。

**Comment by BarryYBL** [comment]
> 已经添加了关闭快捷键的设置，下一个版本会发布。

好的

**Comment by LiZhenNet** [comment]
> 已经添加了关闭快捷键的设置，下个版本会发布。

大概什么时候发布？

**Comment by wwwenjie** [comment]
可能需要 @qier222  看一下，应该快了。

**Comment by qier222** [comment]
> > 已经添加了关闭快捷键的设置，下个版本会发布。
> 
> 大概什么时候发布？

我看下这几天有没有空发个版

**Comment by LiZhenNet** [comment]
> > > 已经添加了关闭快捷键的设置，下个版本会发布。
> > 
> > 
> > 大概什么时候发布？
> 
> 我看下这几天有没有空发个版

来催更了

**Comment by qier222** [comment]
> > > > 已经添加了关闭快捷键的设置，下个版本会发布。
> > > 
> > > 
> > > 大概什么时候发布？
> > 
> > 
> > 我看下这几天有没有空发个版
> 
> 来催更了

（在搞了在搞了

**Comment by qier222** [comment]
已经发版本了
