### ISSUE TITLE
（该状态是Touch Bar默认状态）M1 MacBook Pro 客户端 ，Touch Bar控制歌曲的上一首下一首无法使用，另外点击Touch Bar点击暂停，虽然可以，但是客户端仍然显示为播放状态（注：此时歌曲已经为暂停状态）

### ISSUE THREAD

**Issue by slince-zero** [qier222/YesPlayMusic#514]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by Edmon-Leo** [comment]
啊确实 我这里也是这个问题，但好像上一首下一首可以切换，只是那个暂停键有一样的问题
