### ISSUE TITLE
可否加入“代理”功能

### ISSUE THREAD

**Issue by linux0ne-su** [qier222/YesPlayMusic#515]
一个需求：
我是局域网用户，通过局域网内一个IP作为代理，去访问外网，那么，本软件可否考虑加入代理功能

几个使用问题：
1、第一次安装后，点“关闭”按钮，没有反应，只能点右下角退出键才能关闭软件。第二次打开后，关闭按钮可以正常响应动作。
2、设置了“点关闭后最小化到系统托盘”，但点了关闭后软件就彻底退出了，屡试屡败。
3、部分歌曲无法播放，这可能是音源的问题，在其它可选的链接上，同一首歌还是有能播放的。例：
![1](https://user-images.githubusercontent.com/60182556/113281596-589b4100-9318-11eb-8a5a-74bb65912370.png)

**Comment by qier222** [comment]
重复的issue #326
