### ISSUE TITLE
BUG: 登入账号后无法加载任何资源

### ISSUE THREAD

**Issue by 2776901795** [qier222/YesPlayMusic#517]
登入账号后无法加载任何资源

打开歌单:
![image](https://user-images.githubusercontent.com/63629186/113304274-75457200-9334-11eb-8c66-b0bbb6512c70.png)
音乐库:
![image](https://user-images.githubusercontent.com/63629186/113304389-90b07d00-9334-11eb-861c-9d9eceba5ccd.png)

版本0.3.5-0.3.3

**Comment by memorydream** [comment]
存在登陆后关闭app再重启，出现 #524 或者 #502 相同的问题么？我发现使用邮箱登陆就会出现这个bug，改用手机号登陆就没问题

**Comment by memorydream** [comment]
@qier222
