### ISSUE TITLE
没有音乐缓存功能吗？或是不能使用

### ISSUE THREAD

**Issue by sunhongfan** [qier222/YesPlayMusic#521]
我听音乐好多了，一看设置里面缓存的大小为0 是根本不缓存， 还是显示有问题呢？

**Comment by kikiyoi** [comment]
显示问题吧，点进去过一会就有了
![image](https://user-images.githubusercontent.com/78886819/113468362-459f8280-9478-11eb-9b1c-f23ef85258fd.png)

**Comment by yt-single** [comment]
那缓存音乐怎么播放呢，没网的时候都进不到歌单里

**Comment by yt-single** [comment]
那缓存音乐怎么播放呢，没网的时候都进不到歌单里

**Comment by Insane170123** [comment]
> 
> 
> 显示问题吧，点进去过一会就有了
> ![image](https://user-images.githubusercontent.com/78886819/113468362-459f8280-9478-11eb-9b1c-f23ef85258fd.png)

缓存的文件在哪呢？
