### ISSUE TITLE
Windows导航栏缺失问题

### ISSUE THREAD

**Issue by Gackson** [qier222/YesPlayMusic#524]
![image](https://user-images.githubusercontent.com/26532664/113498686-bf4f7300-9541-11eb-8398-e982f2a075ab.png)
如图，主界面上方ui缺失，点击查看全部推荐歌单后也因此无法返回。

**Comment by 5Gc** [comment]
我的下方的播放条也缺失

**Comment by qier222** [comment]
需要控制台截图

**Comment by 5Gc** [comment]
> 需要控制台截图

![image](https://user-images.githubusercontent.com/37238483/113512018-598cd680-9595-11eb-9d7e-ec35b771489e.png)

**Comment by Gackson** [comment]
![image](https://user-images.githubusercontent.com/26532664/113517658-f52d3f80-95b3-11eb-8882-af5f43256cd7.png)
![image](https://user-images.githubusercontent.com/26532664/113517684-1a21b280-95b4-11eb-8aca-aec1bdac20d1.png)

**Comment by qier222** [comment]
0.3.6版本应该已经修复了，如果还存在问题的话，请reopen issue 并附上控制台截图
