### ISSUE TITLE
添加切歌时渐近渐出功能

### ISSUE THREAD

**Issue by PIndividual** [qier222/YesPlayMusic#526]
建议添加一个音乐渐近渐出的功能，类似Spotify或者像一些iPod那样，最好给一个可选的时常，比如0秒到12秒
真的，那玩意特别有代入感，试试就知道

**Comment by kid-ness** [comment]
确实可以加渐近渐出，不过可选就算了，按那些大厂的来就好

**Comment by qier222** [comment]
项目使用的音频播放库 howler.js 暂时不支持渐近渐出功能，需要自行实现，可能会比较麻烦。以后可能会搞。

**Comment by Nevodev** [comment]
> 项目使用的音频播放库 howler.js 暂时不支持渐近渐出功能，需要自行实现，可能会比较麻烦。以后可能会搞。

有了之后给个开关吧，有时候不需要这个

**Comment by pan93412** [comment]
Duplicate of #264
