### ISSUE TITLE
图标和按钮位置问题

### ISSUE THREAD

**Issue by PIndividual** [qier222/YesPlayMusic#527]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- macOS客户端
- 使用macOS 10.15.7
- 全屏独占模式下的上面的那一排按钮以及歌词界面收起的那个按钮太靠上了，鼠标不慢慢移过去的话很容易触发顶层的macOS导航栏和窗口边界，很难用

**Comment by wwwenjie** [comment]
参考了一下 Chrome 的 UX，当鼠标移至顶部时，macOS导航栏依旧触发，但是整个 Chrome 的窗口是在导航栏之下的。或许可以看看 Electron 是否有这样的实现方式，目前窗口是不会在导航栏之下，而是被导航栏覆盖。
