### ISSUE TITLE
歌词界面高斯模糊效果（亚克力）

### ISSUE THREAD

**Issue by MacKenia** [qier222/YesPlayMusic#529]
歌词界面高斯模糊效果（亚克力）
非当前歌词均高斯模糊
高斯模糊真的很好看

**Comment by wwwenjie** [comment]
示例：
![IMG_3094](https://user-images.githubusercontent.com/29472143/113656536-aa541a80-96ce-11eb-8818-c4eca32b021e.PNG)

**Comment by guohui-ma** [comment]
It is meaningful, but not urgent.

**Comment by imgradeone** [comment]
似乎以前一阵子有这个功能，但现在又没了。

**Comment by qier222** [comment]
重复的issue #110
