### ISSUE TITLE
不想禁用代理路由器上的UnblockNeteaseMusic服务，请问YesPlayMusic如何才能正常并存使用？

### ISSUE THREAD

**Issue by bobz1** [qier222/YesPlayMusic#534]
win10，yes0.35最新版本，旁路由器OP上开启了UnblockNeteaseMusic服务，然后Yes就不可用了，打开后一片空白，经查询在此  https://github.com/qier222/YesPlayMusic/issues/115   中有提到，有朋友是设置系统用户环境变量，作者也回复了0.33已修复，但是0.35还是不可并存，请教解决办法？谢谢

**Comment by bobz1** [comment]
https://github.com/qier222/YesPlayMusic/issues/115#issuecomment-770158353

用了这个办法，页面内容都能正常显示了，但是点播放无效，所有的歌能看不能放，求解答？

**Comment by heewq** [comment]
不懂技术，我是在UnblockNeteaseMusic设置了排除客户端。
