### ISSUE TITLE
全屏游戏内显示歌词

### ISSUE THREAD

**Issue by jiongjiongzj** [qier222/YesPlayMusic#535]
[做出桌面歌词后可否考虑让歌词在全屏游戏中也能显示？网上似乎没有音乐软件实现这个功能，但是能否通过类似Discord、开黑啦这类语音软件的游戏内叠加层来实现？Discord的效果见下图左上角。

https://www.clan-hispania.com/wp-content/uploads/2020/06/steam-1024x432.png

**Comment by qier222** [comment]
暂无计划支持桌面歌词
