### ISSUE TITLE
切换账号后，依旧是老帐号的（我喜欢的音乐），卸载重装也一样

### ISSUE THREAD

**Issue by Git000305** [qier222/YesPlayMusic#538]
切换账号后，依旧是老帐号的（我喜欢的音乐），卸载重装也一样

**Comment by water-boiled-fish** [comment]
你可以试试把C:\Users\用户\AppData\Roaming\yesplaymusic的文件删掉然后重试

**Comment by Git000305** [comment]
> 你可以试试把C:\Users\用户\AppData\Roaming\yesplaymusic的文件删掉然后重试

没有这个文件

**Comment by Tebiexihuan** [comment]
打开此电脑 最上一排选项卡-查看-隐藏的项目  打勾  就可以找到了

**Comment by VidocqH** [comment]
清一下Cookie

**Comment by qier222** [comment]
应该已经修复了
