### ISSUE TITLE
M1版本无法登陆账号，首页歌单异常，无法加载

### ISSUE THREAD

**Issue by wandiu** [qier222/YesPlayMusic#539]
### M1版本 页面的导航栏和登陆消失了，歌单无法加载

<img width="1079" alt="截屏2021-04-10 09 51 36" src="https://user-images.githubusercontent.com/82247133/114254538-9405d180-99e2-11eb-8536-517458f2766c.png">
<img width="1074" alt="截屏2021-04-10 09 51 28" src="https://user-images.githubusercontent.com/82247133/114254542-9b2cdf80-99e2-11eb-8778-b58bb0e67b9b.png">
<img width="1079" alt="截屏2021-04-10 09 53 03" src="https://user-images.githubusercontent.com/82247133/114254550-a08a2a00-99e2-11eb-97c8-b4cc11b022d8.png">

**Comment by MAX-DERT** [comment]
我也遇到了Windows也是这样

**Comment by MAX-DERT** [comment]
Windows 也有一样的问题

**Comment by wuanshi** [comment]
> Windows 也有一样的问题

chrome不行，但是edge好像可以用

**Comment by MAX-DERT** [comment]
现在已经无法正常使用了还请快修复啊

**Comment by memorydream** [comment]
可以尝试一下 #502 #524 中我所反馈的问题和临时的解决方案，报错信息一致，或许可用

**Comment by qier222** [comment]
应该已经修复了
