### ISSUE TITLE
M1 mac mini下载arm版本显示移动到废纸篓，通用设置已经打开

### ISSUE THREAD

**Issue by xiaoxiaohuangya** [qier222/YesPlayMusic#540]
版本不适配

**Comment by buildyuan** [comment]
用brew安装吧，装intel64的，能用

**Comment by qier222** [comment]
可能是因为没有签名的问题。
临时解决方案：https://github.com/qier222/YesPlayMusic/issues/297#issuecomment-782555219

**Comment by buildyuan** [comment]
> 可能是因为没有签名的问题。
> 临时解决方案：[#297 (comment)](https://github.com/qier222/YesPlayMusic/issues/297#issuecomment-782555219)

有计划加上么。计划着去更新一下 brew cask 的。这个问题过不了

**Comment by qier222** [comment]
> > 可能是因为没有签名的问题。
> > 临时解决方案：[#297 (comment)](https://github.com/qier222/YesPlayMusic/issues/297#issuecomment-782555219)
> 
> 有计划加上么。计划着去更新一下 brew cask 的。这个问题过不了

苹果开发者签名每年要交800左右的钱😂，暂时没开

**Comment by buildyuan** [comment]
> > > 可能是因为没有签名的问题。
> > > 临时解决方案：[#297 (comment)](https://github.com/qier222/YesPlayMusic/issues/297#issuecomment-782555219)
> > 
> > 
> > 有计划加上么。计划着去更新一下 brew cask 的。这个问题过不了
> 
> 苹果开发者签名每年要交800左右的钱😂，暂时没开

了解，感谢。
