### ISSUE TITLE
Macbook M1 版，0.36版本开歌词界面，GPU直接跑满

### ISSUE THREAD

**Issue by jack407315483** [qier222/YesPlayMusic#562]
Mac M1 0.36版本开歌词界面，GPU直接跑满90%以上负载

**Comment by qier222** [comment]
是否在设置里开启了歌词动态背景？

**Comment by baoge666666** [comment]
> 是否在设置里开启了歌词动态背景？

是的，开启歌词动态背景后，再打开歌词界面，YesPlayMusic Help（GPU）会跑满，不打开歌词界面则占用正常。关闭歌词动态背景，一切正常。（M1 MacBook air）

**Comment by helundong** [comment]
我用的mca x86版，linux版都有一样的问题。

**Comment by qier222** [comment]
请查看issue #484
