### ISSUE TITLE
歌词页面只能识别歌名，歌手和专辑都是unknown, 进度，爱心，播放相关的按钮全部失效

### ISSUE THREAD

**Issue by zZLinZz** [qier222/YesPlayMusic#563]
歌词页面只能识别歌名，歌手和专辑都是unknown, 进度，爱心，播放相关的按钮全部失效，收起来歌词页面后这些功能才可以用

- Win 0.3.6版客户端
- Win10  2004 正式版系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://user-images.githubusercontent.com/82893666/115425494-3f5c2500-a232-11eb-8e50-747456c20a52.png)

**Comment by zZLinZz** [comment]
> 歌词页面只能识别歌名，歌手和专辑都是unknown, 进度，爱心，播放相关的按钮全部失效，收起来歌词页面后这些功能才可以用
> 
> * Win 0.3.6版客户端
> * Win10  2004 正式版系统
> * 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://user-images.githubusercontent.com/82893666/115425316-1a67b200-a232-11eb-8c7c-5d0656a2c344.png)

**Comment by guohui-ma** [comment]
+1

**Comment by NavlysChen** [comment]
刚刚更新了也发现unknown的问题

**Comment by Map1en** [comment]
进度，爱心，播放相关的按钮是好用的，现在只是歌手和专辑有问题，等修。

**Comment by qier222** [comment]
重复的issue #556
