### ISSUE TITLE
作者界面无法正常显示，一些歌单和歌曲无法喜欢/收藏

### ISSUE THREAD

**Issue by yiyikea** [qier222/YesPlayMusic#564]
win10 64位系统
0.3.6

![QQ截图20210421085940](https://user-images.githubusercontent.com/79887850/115482169-a3a5d580-a280-11eb-9ea5-02b594b1f3f1.png)
![QQ截图20210421090253](https://user-images.githubusercontent.com/79887850/115482172-a4d70280-a280-11eb-8843-1c2a5831bb26.png)

**Comment by qier222** [comment]
ZARD的专辑无法收藏是因为 “专辑下架或版权锁定”（网易云接口这样提示的）
