### ISSUE TITLE
MacBook Pro-M1：希望可以在Touch Bar上显示实时播放的歌曲信息

### ISSUE THREAD

**Issue by Edmon-Leo** [qier222/YesPlayMusic#565]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by qier222** [comment]
有其他播放器的示例图片吗？

**Comment by Edmon-Leo** [comment]
现在播放的时候Touch Bar只能是这样
<img width="1004" alt="Touch Bar Shot 2021-04-22 at 2 35 33 PM" src="https://user-images.githubusercontent.com/73092366/115667221-2c536d00-a378-11eb-90bb-67fa5e83d33c.png">
如果可以像这样就好了（下图来源于LyricsX，但是并没有显示封面或者播放器的图标），
<img width="1004" alt="Touch Bar Shot 2021-04-22 at 2 40 02 PM" src="https://user-images.githubusercontent.com/73092366/115667620-a126a700-a378-11eb-8614-c1575379de70.png">

我是想 可不可以像上面那个图那样，播放控制器左边加入软件图标或者播放的专辑封面，然后可以同时显示软件名称或者专辑信息

**Comment by qier222** [comment]
Electron 那边暂时没有这样的API可以做这样的事
