### ISSUE TITLE
win10播放自动暂停

### ISSUE THREAD

**Issue by jaminteng** [qier222/YesPlayMusic#567]
win10客户端播放经常自动暂停播放，但是客户端显示的是在运行并且播放着的，进度条也没动，然后点击暂停再点击播放就能恢复  
![image](https://user-images.githubusercontent.com/37527031/115551143-3b391180-a2dd-11eb-92f4-ca2413e5f4f9.png)

**Comment by qier222** [comment]
需要控制台截图
