### ISSUE TITLE
Win10客户端last.fm授权链接失败

### ISSUE THREAD

**Issue by TheLastGreenseer** [qier222/YesPlayMusic#569]
![图片](https://user-images.githubusercontent.com/73424266/115574409-2c118e00-a2f4-11eb-9b6c-207ae19547c9.png)

![图片](https://user-images.githubusercontent.com/73424266/115574341-1dc37200-a2f4-11eb-84fa-4ffc86a40467.png)

Last.fm页面显示无效API

**Comment by qier222** [comment]
刚刚push了个commit，应该已经修复了。
你可以在 https://github.com/qier222/YesPlayMusic/actions/runs/772962330 下载修复后的安装包

**Comment by TheLastGreenseer** [comment]
确实可以了，谢谢！
