### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by kissesch** [qier222/YesPlayMusic#570]
![image](https://user-images.githubusercontent.com/56185169/115575212-ebfedb00-a2f4-11eb-9176-70bf5f55fe8e.png)
请问这种问题要怎么解决

**Comment by qier222** [comment]
试试看使用管理员身份运行？

**Comment by kissesch** [comment]
> 试试看使用管理员身份运行？

刚试了一下，也会出现这个窗口，客户端仍然无法使用

**Comment by qier222** [comment]
那你试试卸载，然后使用管理员身份打开安装包安装？

**Comment by kissesch** [comment]
> 那你试试卸载，然后使用管理员身份打开安装包安
没用，谜一般😂
