### ISSUE TITLE
设置缓存上限后，点击显示不可播放的歌曲为灰色按钮后，缓存上限失效

### ISSUE THREAD

**Issue by JerryChenn07** [qier222/YesPlayMusic#572]
### 反馈 bug 需要的信息

- 客户端
- macos 11.2
- 问题描述：设置缓存上限后，点击显示不可播放的歌曲为灰色按钮后，缓存上限失效，如下两图，应该很好复现，辛苦开发兄弟看一下
![image](https://user-images.githubusercontent.com/32920461/115646495-d28d7b80-a354-11eb-99f2-14abc3ae4e4f.png)

![image](https://user-images.githubusercontent.com/32920461/115646521-dde0a700-a354-11eb-89e6-258624c3b51f.png)

**Comment by qier222** [comment]
0.3.8版已修复
