### ISSUE TITLE
新专辑速递——查看全部 页面显示异常

### ISSUE THREAD

**Issue by RebirthEgo** [qier222/YesPlayMusic#573]
新专辑速递——查看全部 页面显示异常，专辑封面无法显示，字体与主题色一样，无法看清楚。
<img width="1446" alt="Snipaste_2021-04-22_11-51-19" src="https://user-images.githubusercontent.com/54738173/115653080-171f1400-a361-11eb-8123-9eb0f575720c.png">

**Comment by qier222** [comment]
0.3.7版本应该已经修复了，还有问题的话可以重新开启这个isssue
