### ISSUE TITLE
WIN10移动宽带下无法登陆

### ISSUE THREAD

**Issue by Andyvon230** [qier222/YesPlayMusic#575]
![image](https://user-images.githubusercontent.com/37838294/115660375-7f282700-a36e-11eb-8ae7-8a8d791efbb4.png)
输入账号密码后无法显示任何信息
知道是移动网的问题是因为之前有在电信宽带下尝试过，相同的账号秒连上了能正常使用

**Comment by qier222** [comment]
需要控制台截图

**Comment by Andyvon230** [comment]
![image](https://user-images.githubusercontent.com/37838294/115663292-e3e58080-a372-11eb-8f27-af709b3aeeed.png)

**Comment by qier222** [comment]
试试看在控制台输入 resetApp() 重置应用，然后再登录。
你截图的错误信息是登录后的错误信息

**Comment by Andyvon230** [comment]
![image](https://user-images.githubusercontent.com/37838294/115663901-bea54200-a373-11eb-8383-7bcef81f73d2.png)

**Comment by qier222** [comment]
报错看不出来是什么问题
