### ISSUE TITLE
无歌曲时间进度/无歌曲播放时间

### ISSUE THREAD

**Issue by smmya** [qier222/YesPlayMusic#576]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）
类型：网页版
浏览器：谷歌
手机打开网页版播放音乐无歌曲进度条，打开作者大大的却正常，api和静态都是部署在vercel上，地址：music.immi.cf

**Comment by qier222** [comment]
试了下有进度条啊，你试试看清空缓存

**Comment by smmya** [comment]
> 试了下有进度条啊，你试试看清空缓存

谢谢作者回复，另外我想请问一下，我在国内的服务器搭建的api，反代没有办法获得https，然后构建网页就会报告脚本不安全，我应该怎么解决这个问题

**Comment by smmya** [comment]
> 试了下有进度条啊，你试试看清空缓存

无音乐进度应该是缓存的问题，现在可以出来了，谢谢大佬

**Comment by qier222** [comment]
> > 试了下有进度条啊，你试试看清空缓存
> 
> 
> 
> 谢谢作者回复，另外我想请问一下，我在国内的服务器搭建的api，反代没有办法获得https，然后构建网页就会报告脚本不安全，我应该怎么解决这个问题

上https

**Comment by smmya** [comment]
> > > 试了下有进度条啊，你试试看清空缓存
> > 
> > 
> > 谢谢作者回复，另外我想请问一下，我在国内的服务器搭建的api，反代没有办法获得https，然后构建网页就会报告脚本不安全，我应该怎么解决这个问题
> 
> 上https

反代之后并不能使用api，域不一样，打开并不是api页，没办法配置https

另外一提，我使用服务器没办法构建网页端，yarn报错
:~/YesPlayMusic# yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

**Comment by qier222** [comment]
> > > > 试了下有进度条啊，你试试看清空缓存
> > > 
> > > 
> > > 谢谢作者回复，另外我想请问一下，我在国内的服务器搭建的api，反代没有办法获得https，然后构建网页就会报告脚本不安全，我应该怎么解决这个问题
> > 
> > 
> > 上https
> 
> 反代之后并不能使用api，域不一样，打开并不是api页，没办法配置https
> 
> 另外一提，我使用服务器没办法构建网页端，yarn报错
> :~/YesPlayMusic# yarn install
> 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

反代的你自己研究看看吧。
yarn报错是因为环境没装好吧
