### ISSUE TITLE
关于被“封杀”歌手的恢复

### ISSUE THREAD

**Issue by artxia** [qier222/YesPlayMusic#577]
国内平台“封杀”了很多优秀的音乐人，例如 李志、陈升、黄耀明等
所以，这里提出一个思考。
是否可以引入一些国外的音源，来实现更丰富完整的音乐库。
例如：
核心网易云 + UnblockNeteaseMusic 补充 + 其他音源补充 + 网易云盘补充

其他音源 Spotify 、audiomack 好像都有开放api

**Comment by qier222** [comment]
暂时只会专注于做网易云客户端。

**Comment by WXRIW** [comment]
Spotify的Web API只能获取到歌曲信息，无法获取到音频。
最长只能获取到30s的音频，并且需要登录后才能获取。
Web Playback SDK可以获取音频，但是前提是你有Spotify账号，并且是Premium，并且不能引起Spotify官方的关注。
