### ISSUE TITLE
关于Win 0.36版客户端 音乐库界面歌单的刷新问题

### ISSUE THREAD

**Issue by longshensanjie** [qier222/YesPlayMusic#578]
问题描述：添加喜爱的歌单之后, 无文字提醒, 且音乐库界面歌单列表未刷新,  必须手动关闭客户端再重新打开才会刷新, 诸如此类的情况还发生在取消喜爱的歌单操作, 创建歌单操作上, 另外对自己创建的歌单添加歌曲歌单内部也出现类似无法实时更新的问题

**Comment by qier222** [comment]
0.3.7版本应该已经修复了，还有问题的话可以重新开启这个isssue
