### ISSUE TITLE
个别歌曲名出现乱码

### ISSUE THREAD

**Issue by RebirthEgo** [qier222/YesPlayMusic#580]
个别歌曲名出现乱码

<img width="1338" alt="Snipaste_2021-04-22_19-38-42" src="https://user-images.githubusercontent.com/54738173/115708436-92ed8080-a3a2-11eb-98ca-9f628bd635cd.png">

**Comment by llovvoll** [comment]
可以参考下 #391 的解决方式

**Comment by RebirthEgo** [comment]
> 可以参考下[＃391](https://github.com/qier222/YesPlayMusic/issues/391)的解决方式
谢谢完美解决

**Comment by liuchanghuaX1** [comment]
文泉驿微米黑Bug ，还参考https://www.zhihu.com/question/59193641。
