### ISSUE TITLE
不能听灰色的歌了 / UnblockNeteasetMusic失效

### ISSUE THREAD

**Issue by DewberryRye** [qier222/YesPlayMusic#587]
之前的版本可以听灰色的歌曲的，现在不行了，显示无法播放（想知道原因）

**Comment by saysea** [comment]
我也想知道

**Comment by Victor9578** [comment]
shide 我也是

**Comment by 2165998** [comment]
mark

**Comment by qier222** [comment]
看了下应该是上游 UnblockNeteaseMusic 的问题，查看 https://github.com/nondanee/UnblockNeteaseMusic/issues/737

**Comment by 2165998** [comment]
> 看了下应该是上游 UnblockNeteaseMusic 的问题，查看 [nondanee/UnblockNeteaseMusic#737](https://github.com/nondanee/UnblockNeteaseMusic/issues/737)

[nondanee/UnblockNeteaseMusic#737]里貌似已经解决，想问下在咱这往哪里改2233

**Comment by lesnolie** [comment]
请问哪里可以解决呢？ [nondanee/UnblockNeteaseMusic#737 ](https://github.com/nondanee/UnblockNeteaseMusic/issues/737)已经解决

**Comment by ralphwong** [comment]
解锁灰色歌曲依旧失效

**Comment by michael-wonga** [comment]
啥子时候能解决啊，等待等待

**Comment by saintnoven** [comment]
怎么解决灰曲目？

**Comment by saintnoven** [comment]
参照737好像依旧解决不了

**Comment by ycr10** [comment]
什么时候解决？

**Comment by qier222** [comment]
0.3.8版本已修复
