### ISSUE TITLE
支持更多Plasma媒体控制功能

### ISSUE THREAD

**Issue by maxelblack** [qier222/YesPlayMusic#588]
Linux上Plasma桌面环境自带的媒体播放器控制有直接控制进度、显示歌词和专辑图片、切换随机/循环播放之类的功能，能否考虑下支持这些功能？

目前看起来只支持了播放暂停/上下曲功能。

![image](https://user-images.githubusercontent.com/61044187/115943306-b703ab80-a4e1-11eb-9e5b-826f82cd0781.png)

**Comment by qier222** [comment]
在网上没有找到关于如何适配的相关文章，没办法搞

**Comment by Star-caorui** [comment]
开发者您好，我找到了一些相关的资料，可以供您参考

https://github.com/dbusjs/mpris-service
https://specifications.freedesktop.org/mpris-spec/latest/

请通过dbus的方式在linux播放媒体，正常情况应该是这样的（如下图）
![image](https://user-images.githubusercontent.com/51264180/146669941-31f7941a-2679-481d-8814-76ffbefbd00b.png)
![image](https://user-images.githubusercontent.com/51264180/146669962-f101f185-12eb-4b65-a162-2f3b42b1c68c.png)

而yesplaymusic目前是这样的（如下图）
![image](https://user-images.githubusercontent.com/51264180/146669981-385d8c23-fb19-4cfd-9d3a-9793849248f2.png)
![image](https://user-images.githubusercontent.com/51264180/146670006-689173df-3025-4c79-946e-87a1f2713f60.png)

修复这个问题的同时也能修复 https://github.com/qier222/YesPlayMusic/issues/1052 这个问题

祝好
