### ISSUE TITLE
所有歌曲播放页面的歌手和专辑名都为unknown，但底部条状小播放器显示正常

### ISSUE THREAD

**Issue by jzcangshu** [qier222/YesPlayMusic#589]
### 所有歌曲播放页面的歌手和专辑名都为unknown，但底部条状小播放器显示正常

win客户端0.3.6
![1.png](https://i.loli.net/2021/04/24/Jz3tYOGmvBsRpIK.png)
![2.png](https://i.loli.net/2021/04/24/r43ZYwcP5fUmEIC.png)

**Comment by ReInvade** [comment]
客户端也有同样的问题
![屏幕截图 2021-04-24 130052](https://user-images.githubusercontent.com/25477800/115947955-b842d180-a4fd-11eb-926d-f80c8a8c3a04.png)
![屏幕截图 2021-04-24 130106](https://user-images.githubusercontent.com/25477800/115947959-bda01c00-a4fd-11eb-99ac-5affbe8c73df.png)

**Comment by LTHPKBTE** [comment]
此问题已经被作者修复，但是没有更新版本。你可以在这里下载到修复后的版本：
https://github.com/qier222/YesPlayMusic/actions/runs/772778555

**Comment by LTHPKBTE** [comment]
> 此问题已经被作者修复，但是没有更新版本。你可以在这里下载到修复后的版本：
> https://github.com/qier222/YesPlayMusic/actions/runs/772778555

见#556
