### ISSUE TITLE
Win10 | 遇到无法播放的专辑时出现的bug

### ISSUE THREAD

**Issue by WindUpRadio** [qier222/YesPlayMusic#590]
控制台截图：![image](https://user-images.githubusercontent.com/77561446/115944695-cedf2d80-a4e9-11eb-86bc-9459769b530e.png)
bug录屏（不好描述）：

https://user-images.githubusercontent.com/77561446/115944739-32695b00-a4ea-11eb-8716-3b326b85c838.mp4

**Comment by qier222** [comment]
应该是因为无法播放灰色歌曲+循环播放的问题， 相关issue #587
