### ISSUE TITLE
0.3.6版本，win10，发现页面，歌单分类，可以反复添加同一个分类，且无法删除

### ISSUE THREAD

**Issue by RossiYu** [qier222/YesPlayMusic#591]
# 0.3.6版本，win10，发现页面，歌单分类，可以反复添加同一个分类，且无法删除

### 反馈 bug 需要的信息
- 客户端
- win10
![微信图片_20210424134005](https://user-images.githubusercontent.com/14243092/115948774-b9c2c880-a502-11eb-9005-1a29831fb21f.png)

**Comment by qier222** [comment]
已推送commit修复了这个问题
https://github.com/qier222/YesPlayMusic/commit/5355caa4e4df08fcbf1fcb7df9a3864da06b3d71

**Comment by qier222** [comment]
0.3.7版本已发布
