### ISSUE TITLE
在歌词界面双击歌词跳转位置后开始播放

### ISSUE THREAD

**Issue by OkinoAze** [qier222/YesPlayMusic#595]
详细描述为:现已有单击歌词跳转进度.在暂停状态下单击歌词跳转还是暂停状态,可能加个双击跳转开始播放会方便一点.
在空白处双击退出歌词界面理由同上,双击比按按钮要方便一点,可能用户会出现误操作,可以的话加个设置开关会好点.

可能双击的功能会和选择歌词的文本相冲突,如果能实现这个功能的话或许加个右键调出快捷菜,来单复制歌词文本会比较好(?)
还有个设计上的问题:框选歌词文本的时候会选中左边的歌曲封面和歌词信息时间一类的文本.

**Comment by qier222** [comment]
双击歌词播放可以搞搞

**Comment by qier222** [comment]
空白处双击退出歌词界面，这个操作太含蓄了，没有提示的话是没人能意识到的，而且哪里是“空白处”也不太好准确定义

**Comment by qier222** [comment]
0.3.7版本已支持
