### ISSUE TITLE
请问一下，下载在哪里？

### ISSUE THREAD

**Issue by 18629643989** [qier222/YesPlayMusic#598]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by LTHPKBTE** [comment]
好家伙，都注册了github还不了解一下个github的各个模块吗 下次看到有releases那就说明作者在这里发布了有，要不就去readme仔细看看作者的说明
https://github.com/qier222/YesPlayMusic/releases

**Comment by 18629643989** [comment]
> ・圆的天花大香的吉吉特布瑞克·特瑞克特
> [·https://github.com/qier222/YesPlayMusic/releases](https://github.com/qier222/YesPlayMusic/releases)吉布特·

我的意思是应用里面歌曲下载在哪里

**Comment by LTHPKBTE** [comment]
目前还没有这个功能。如果你需要的话请按照issue的格式打开一个feature request。
