### ISSUE TITLE
用户登录cookie与VIP歌曲的播放

### ISSUE THREAD

**Issue by gyh1621** [qier222/YesPlayMusic#6]
第一个问题是现在登录后cookie并不会随请求发送，表现为用户私密歌单无法显示。应该是`axios`的问题，我用了[这里的方式](https://github.com/axios/axios/issues/587#issuecomment-596663756)解决。

第二个问题是VIP歌曲无法播放。简单看了下[代码](https://github.com/qier222/YesPlayMusic/blob/master/src/utils/common.js#L6-L8)，现在VIP歌曲是一律标灰的，或许可以根据用户状态来判断？

我比较暴力直接修改了上面那个判断，但是所有VIP歌曲仍无法播放，是与[这里](https://github.com/qier222/YesPlayMusic/blob/master/src/store/actions.js#L30-L33)有关。我看了api文档，获取播放链接有两种方式，我把上面代码比较粗糙地修改成VIP用另一种就可以了：
```
if (track.fee === 1) {
  getMP3(track.id)
  .then((data) => {
    commit(
      "replaceMP3",
      data.data[0].url
    );
  });
} else {
  commit(
    "replaceMP3",
    `https://music.163.com/song/media/outer/url?id=${track.id}`
  ); 
}
```

我自己本身是VIP用户前端也不太熟悉，所以上面两处就直接修改了没做其它处理，期待后面更加完善的播放器。

**Comment by qier222** [comment]
如果是自己部署的话，跨域确实需要加上withCredentials: true，播放VIP歌曲这个功能还没适配，已加入todo list

**Comment by gyh1621** [comment]
在你们提供的demo里面登录也看不到自己的私密歌单。

**Comment by qier222** [comment]
@gyh1621 demo里的library能看到私密歌单，但是目前还没加上私密歌单的标志，无法分辨哪些是私密歌单。

**Comment by qier222** [comment]
已支持播放VIP歌曲
