### ISSUE TITLE
设置面板建议加入网络代理设置及音乐品质选择就更完美了

### ISSUE THREAD

**Issue by RebirthEgo** [qier222/YesPlayMusic#60]

**Comment by qier222** [comment]
选择音质的选项已经有了。

好奇问一下你是在什么场景下需要用到网络代理选项？

**Comment by RebirthEgo** [comment]
> 选择音质的选项已经有了。
> 
> 好奇问一下你是在什么场景下需要用到网络代理选项？

音质选择看到了，解锁灰色音乐

**Comment by RebirthEgo** [comment]
深色主题下能否把标题栏底色也统一成黑色，在加一个“选择输出音频设备”选项

**Comment by qier222** [comment]
> 深色主题下能否把标题栏底色也统一成黑色，在加一个“选择输出音频设备”选项

截图一下看看哪里没有覆盖到深色主题。音频输出要在系统里选择，macOS 和 Windows 都有选择输出音频设备的选项。

**Comment by zgjsntsm** [comment]
> 选择音质的选项已经有了。
> 
> 好奇问一下你是在什么场景下需要用到网络代理选项？

我想是想配合这个项目吧， [https://github.com/nondanee/UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic)

**Comment by RebirthEgo** [comment]
![My](https://user-images.githubusercontent.com/54738173/100458387-a7349680-30fe-11eb-808d-e0ac420bcf3a.png)

**Comment by RebirthEgo** [comment]
> > 选择音质的选项已经有了。
> > 好奇问一下你是在什么场景下需要用到网络代理选项？
> 
> 我想是想配合这个项目吧，https://github.com/nondanee/UnblockNeteaseMusic

聪明呀

**Comment by RebirthEgo** [comment]
> > 深色主题下能否把标题栏底色也统一成黑色，在加一个“选择输出音频设备”选项
> 
> 音频输出要在系统里选择，macOS和Windows都有选择输出音频设备的选项。

<img width="1285" alt="微信截图_20201127222328" src="https://user-images.githubusercontent.com/54738173/100458790-4eb1c900-30ff-11eb-9f5c-d149f3a6f46d.png">

**Comment by RebirthEgo** [comment]
> > 深色主题下能否把标题栏底色也统一成黑色，在加一个“选择输出音频设备”选项
> 
> 音频输出要在系统里选择，macOS和Windows都有选择输出音频设备的选项。



> > 深色主题下能否把标题栏底色也统一成黑色，在加一个“选择输出音频设备”选项
> 
> 音频输出要在系统里选择，macOS和Windows都有选择输出音频设备的选项。

我说的是类似这样，这个音质会好一些，只是建议
<img width="1285" alt="微信截图_20201127222328" src="https://user-images.githubusercontent.com/54738173/100458936-8f114700-30ff-11eb-8838-4771752c51cc.png">

**Comment by RebirthEgo** [comment]
我是太喜欢这个UI设计了，如果在歌曲上加上收藏歌单和喜欢按键、关注歌手就厉害了。灰色歌曲真是刚需呀！！期待你的新版本

**Comment by qier222** [comment]
> 我是太喜欢这个UI设计了，如果在歌曲上加上收藏歌单和喜欢按键、关注歌手就厉害了。灰色歌曲真是刚需呀！！期待你的新版本

感谢支持，Electron版本的代理设置我会加到Todo里。

不是很明白 “如果在歌曲上加上收藏歌单和喜欢按键、关注歌手就厉害了” 这句的具体意思。目前已经有了收藏歌单、喜欢歌曲、关注歌手的功能。

Windows的顶部的标题栏颜色不确定是根据什么变化的，我之后研究看看。

**Comment by RebirthEgo** [comment]
我没有看到，可能是我没有找到吧，我说的是像下面截图的样式
<img width="1484" alt="Snipaste_2020-11-28_14-25-38" src="https://user-images.githubusercontent.com/54738173/100495416-a3e4ed80-3186-11eb-8efc-97cd7a3f5087.png">
<img width="841" alt="Snipaste_2020-11-28_14-27-43" src="https://user-images.githubusercontent.com/54738173/100495415-a2b3c080-3186-11eb-8245-677f081e2e75.png">
<img width="517" alt="Snipaste_2020-11-28_14-28-55" src="https://user-images.githubusercontent.com/54738173/100495421-a8110b00-3186-11eb-8ec5-ce5bf230e2f6.png">

**Comment by njzydark** [comment]
> > > 选择音质的选项已经有了。
> > > 好奇问一下你是在什么场景下需要用到网络代理选项？
> > 
> > 
> > 我想是想配合这个项目吧，https://github.com/nondanee/UnblockNeteaseMusic
> 
> 聪明呀

已支持 https://github.com/qier222/YesPlayMusic/pull/69

**Comment by huanx9** [comment]
@ njzydark   请问怎么实现？？  我又不行了。  代理8080端口吗？

**Comment by zzinggame** [comment]
@huanx9 Have you found a way for network proxy?

**Comment by qier222** [comment]
> @njzydark  请问怎么实现？？  我又不行了。  代理8080端口吗？

客户端版默认启用UnlockMusic了

**Comment by liaozhaishusheng** [comment]
> > @njzydark  请问怎么实现？？  我又不行了。  代理8080端口吗？
> 
> 客户端版默认启用UnlockMusic了

咦，支持了吗？还是不能播放啊！点击播放后没有反应。
