### ISSUE TITLE
bug：播放界面功能失效

### ISSUE THREAD

**Issue by Adsicmes** [qier222/YesPlayMusic#601]
![image](https://user-images.githubusercontent.com/79645438/115995743-0abfe300-a60f-11eb-8bbb-f7b41975256e.png)

如图
左边的功能键以及进度条失效
windows10 20h2专业版
客户端版本0.3.6

**Comment by qier222** [comment]
0.3.7版本应该已经修复了，还有问题的话可以重新开启这个isssue
