### ISSUE TITLE
vercel部署的话，不可以播放

### ISSUE THREAD

**Issue by wmz1024** [qier222/YesPlayMusic#604]
# vercel部署的话，不可以播放音乐（不是灰色音乐）
vercel现在可以搜索，首页也可以显示了
[![gSHOqH.png](https://z3.ax1x.com/2021/04/26/gSHOqH.png)](https://imgtu.com/i/gSHOqH)
但是点进某个歌单 点击播放就不行

**Comment by qier222** [comment]
你部署的是0.3.5版，不是最新版
