### ISSUE TITLE
增加静态歌词背景功能

### ISSUE THREAD

**Issue by Map1en** [qier222/YesPlayMusic#607]
现在动态歌词背景经过调整还是很吃GPU。

个人感觉这个动态不是很显眼，但背景有这种颜色比黑白纯色要好看不少，所以要不要增加一个无旋转动画的静态歌词背景？
这样很好看，几乎没有额外消耗。

**Comment by qier222** [comment]
我觉得可以，设置里的歌词背景选项可以变成下拉选择框
