### ISSUE TITLE
如何像demo那样，部署web版？

### ISSUE THREAD

**Issue by Aienao** [qier222/YesPlayMusic#608]
并不想要客户端，想通过web访问

**Comment by qier222** [comment]
可以部署到Vercel，但是会因为跨域会存在一些问题。
也可以部署到自己的服务器，需要的话我再更新下教程。

**Comment by Aienao** [comment]
> 可以部署到Vercel，但是会因为跨域会存在一些问题。
> 也可以部署到自己的服务器，需要的话我再更新下教程。

我其实是在windows上先试着部署的，没摸清楚怎么玩。。。

**Comment by qier222** [comment]
> > 可以部署到Vercel，但是会因为跨域会存在一些问题。
> > 也可以部署到自己的服务器，需要的话我再更新下教程。
> 
> 我其实是在windows上先试着部署的，没摸清楚怎么玩。。。
> 能给个详细点的教程么，大佬（来自前端小白的请求。。。）

这几天会更新一下部署的方法到readme

**Comment by Aienao** [comment]
> > > 可以部署到Vercel，但是会因为跨域会存在一些问题。
> > > 也可以部署到自己的服务器，需要的话我再更新下教程。
> > 
> > 
> > 我其实是在windows上先试着部署的，没摸清楚怎么玩。。。
> > 能给个详细点的教程么，大佬（来自前端小白的请求。。。）
> 
> 这几天会更新一下部署的方法到readme

OK，感谢

**Comment by qier222** [comment]
已更新文档
