### ISSUE TITLE
Node 16 无法进行打包客户端

### ISSUE THREAD

**Issue by llovvoll** [qier222/YesPlayMusic#609]
自己遇到的问题，网上也有类似的 issue
https://github.com/electron-userland/electron-builder/issues/5668

# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）
- 
![image](https://user-images.githubusercontent.com/20951677/116111482-45964980-a6e9-11eb-8057-09ed5fe5f2a4.png)

**Comment by F-fengzi** [comment]
hhhhh从那个issue过来
目前是electron-builder的问题，跟这个项目没有关系

**Comment by llovvoll** [comment]
> hhhhh从那个issue过来
> 目前是electron-builder的问题，跟这个项目没有关系

留个底，怕有遇到同样折腾的朋友

**Comment by qier222** [comment]
GitHub Actions好像没啥问题 。
最近的打包 https://github.com/qier222/YesPlayMusic/actions/runs/786201518

**Comment by xiaogaozi** [comment]
GitHub Actions 里用的 Node.js 是 14 版本，实际测试用 Node.js 16 在 macOS 上打包会失败，升级 electron-builder 到最新版也不行。

**Comment by pan93412** [comment]
Node.js 16 無法打包是舊版 electron-builder 的已知問題。近期會考慮更新相關依賴。
