### ISSUE TITLE
持续使用1个月,IndexedDB 文件 超大!

### ISSUE THREAD

**Issue by absir1949** [qier222/YesPlayMusic#610]
### 反馈 bug 需要的信息

-版本: 客户端v0.3.5
-系统: mac os 11.2.3(x86)

- 复现方法: 持续使用,持续听歌
- 结果: indexedDB 文件太大,占用了6.8G!
![image](https://user-images.githubusercontent.com/14873265/116177745-f3841100-a746-11eb-8720-eb2fa36130d2.png)

**Comment by Map1en** [comment]
请使用新版的缓存限制或手动清理缓存
