### ISSUE TITLE
希望能为Lyricify的桌面歌词适配提供支持

### ISSUE THREAD

**Issue by WXRIW** [qier222/YesPlayMusic#612]
Lyricify是我自己写的，是为Spotify、iTunes、QQ音乐、网易云音乐、Music Center for PC提供歌词的一个工具，由于YesPlayMusic暂不打算支持做桌面歌词，所以就稍稍修改了下，目前可以支持YesPlayMusic的歌词适配了，但是由于不知道具体的歌曲id，可能会出现错误识别；由于不知道具体的播放进度，所以在用户手动调节播放进度时，歌词会发生严重的时间偏差。
**如果YesPlayMusic能通过某些方式告诉Lyricify正在播放歌曲的id和播放进度就可以进一步适配了。**
**目前Lyricify是通过YesPlayMusic的窗口标题来获取歌曲信息的，所以只能获取到Song和Artist两个信息**
马上要高三了，准备暑假前花个几天弄一下，如果没搞好就要等高考后了。

**项目地址：**[https://github.com/WXRIW/Lyricify-App](https://github.com/WXRIW/Lyricify-App)
仅[3.5.1.1](https://github.com/WXRIW/Lyricify-App/releases/tag/v3.5.1.1)支持，蓝奏云上3.5.1的不支持。
打开后点不登录，左上角三个点（菜单）-->获取-->网易云音乐。
**[《Lyricify使用说明》](https://wxriw.cn:4443)**

**目前的效果图：**
![image](https://user-images.githubusercontent.com/62491584/116183333-3f878380-a750-11eb-9a62-aab3ddf8959f.png)
![image](https://user-images.githubusercontent.com/62491584/116183235-1b2ba700-a750-11eb-8c91-5eaa002729d2.png)
![image](https://user-images.githubusercontent.com/62491584/116183213-10711200-a750-11eb-9268-59d418bd08e2.png)

**Comment by qier222** [comment]
能否能读取到浏览器的widnow对象？如果可以的话我可以把信息绑定到windows对象上

**Comment by WXRIW** [comment]
没找到相关文章，我对electron也不怎么了解，目前想到的解决方案是通过YesPlayMusic创建一个invisible的窗口，在这个窗口的标题上提供id和播放进度

**Comment by qier222** [comment]
> 没找到相关文章，我对electron也不怎么了解，目前想到的解决方案是通过YesPlayMusic创建一个invisible的窗口，在这个窗口的标题上提供id和播放进度

这个实现方式有点hack，不是很想搞

**Comment by WXRIW** [comment]
只要能够实现C#和Electron的通讯就行了，等等有无大佬能解决吧，目前只能实现基本功能

**Comment by meetcw** [comment]
仅考虑 Linux 的话，可以通过 MPRIS 接口获取标题信息，但是现在还获取不了进度 #616。

如果考虑跨平台的话，能不能在本地开启一个web服务，暴露一些接口给外部歌词软件使用呢？

**Comment by WXRIW** [comment]
https://github.com/WXRIW/Lyricify-App/releases/tag/v3.5.2
支持播放进度同步，期待v0.3.8的到来
