### ISSUE TITLE
歌曲详情页面艺术家信息和专辑信息失效

### ISSUE THREAD

**Issue by cqhhy2001** [qier222/YesPlayMusic#613]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

~bug
在使用“下一首播放”后 歌曲详情页面艺术家信息和专辑信息显示为“未知”
Windows 10 21H1 客户端
![image](https://user-images.githubusercontent.com/21079967/116185720-c2aad880-a754-11eb-957d-74fafc6895cb.png)
![image](https://user-images.githubusercontent.com/21079967/116185793-e5d58800-a754-11eb-90e7-6c60ecd7a217.png)

**Comment by qier222** [comment]
重复的issue #556
