### ISSUE TITLE
尝试在 Linux 实现外部歌词时遇到的问题

### ISSUE THREAD

**Issue by meetcw** [qier222/YesPlayMusic#616]
# 问题
Linux 上 YesPlayMusic 好像实现了Dbus 的MPRIS接口，但是实现的不完整。目前可以通过这个接口控制YesPlayMusic的播放暂和获取歌曲信息等功能，但是通过这个接口获取到的YesPlayMuisc的播放进度一直是0。如果这个接口能够正常工作的话，Linux上实现外部歌词应该比较简单。

下面是我用dbus-send命令测试的结果

获取当前歌曲信息：
```  shell
dbus-send --print-reply=literal --dest=org.mpris.MediaPlayer2.chromium.instance51005 /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'
```
返回结果：
```
   variant       array [
         dict entry(
            xesam:album            variant                         )
         dict entry(
            xesam:artist            variant                array [
                  李国祥               ]
         )
         dict entry(
            xesam:title            variant                摘星的晚上         )
      ]
```
获取播放进度：
```  shell
dbus-send --print-reply=literal --dest=org.mpris.MediaPlayer2.chromium.instance51005 /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Position'
```
返回结果：
```
   variant       int64 0
```

另外请问歌词文件在本地有缓存吗？

--------

看了下依赖，播放音频的功能是由 plyr 和 howler 提供的吗？这样的话也许要向上游反应才行。。。(╥_╥)

**Comment by WXRIW** [comment]
在Windows上同样是这样，无法获取播放进度，只能获取到歌手歌曲，和上一首下一首暂停播放的控制
如果YesPlayMusic能同时提供播放进度就好了（Spotify就会同时提供进度信息）

**Spotify中能获取到的信息：**
![image](https://user-images.githubusercontent.com/62491584/116239194-f3aafd80-a794-11eb-8503-493c1693e82d.png)
**YesPlayMusic中能获取到的信息：**
![image](https://user-images.githubusercontent.com/62491584/116239267-06253700-a795-11eb-8043-6dd15e36fbe6.png)

**Comment by meetcw** [comment]
> 在Windows上同样是这样，无法获取播放进度，只能获取到歌手歌曲，和上一首下一首暂停播放的控制
> 如果YesPlayMusic能同时提供播放进度就好了（Spotify就会同时提供进度信息）
> 
> **Spotify中能获取到的信息：**
> ![image](https://user-images.githubusercontent.com/62491584/116239194-f3aafd80-a794-11eb-8503-493c1693e82d.png)
> **YesPlayMusic中能获取到的信息：**
> ![image](https://user-images.githubusercontent.com/62491584/116239267-06253700-a795-11eb-8043-6dd15e36fbe6.png)

这个是Windows提供的媒体API吗？还是像 #612 里说的通过窗口标题获取的？

**Comment by WXRIW** [comment]
Windows提供的，通过[ModernFlyouts](https://github.com/ModernFlyouts-Community/ModernFlyouts)获取的，我自己还没找到相关获取方法，但是这个播放进度信息不是即时的，Spotify上是每2-3s更新一次。
通过窗口标题只能获取到歌曲和歌手。无法获取进度和专辑图片

**Comment by meetcw** [comment]
> Windows提供的，通过[ModernFlyouts](https://github.com/ModernFlyouts-Community/ModernFlyouts)获取的，我自己还没找到相关获取方法，但是这个播放进度信息不是即时的，Spotify上是每2-3s更新一次。
> 通过窗口标题只能获取到歌曲和歌手。无法获取进度和专辑图片

大概瞄了一眼，这个东西好像是通过一个叫 SMTC API 的东西实现的，但是这个API好像也没有直接提供进度信息。当播放器状态改变时会触发一些事件，ModernFlyouts 上面的进度可能是通过一些事件结合获取到的歌曲信息计算出来的。

https://docs.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrols?view=winrt-19041

**Comment by WXRIW** [comment]
明天期中考试，五一的时候我再看看。上次弄了半天没弄出来。
但这个方法不能获取到id，这也是一个缺点

**Comment by qier222** [comment]
我试试看搞个本地API，然后在浏览器将播放信息传递到electron端

**Comment by qier222** [comment]
已经推送新commit了 https://github.com/qier222/YesPlayMusic/commit/07455c8ecd5f04adca3543e8a661a7bdacf484d6

访问 `http://127.0.0.1:27232/player` 可获取到正在播放歌曲的信息和进度，每秒更新一次
访问 `http://127.0.0.1:10754/lyric?id=歌曲ID` 可获取歌词信息

**Comment by qier222** [comment]
可以在这里下载包含这个API的客户端
https://github.com/qier222/YesPlayMusic/actions/runs/789889994

**Comment by WXRIW** [comment]
辛苦了！我放假的时候去写。

**Comment by WXRIW** [comment]
请问下这个每秒更新是每隔一秒更新一次还是在歌曲播放的每秒的开头更新

**Comment by qier222** [comment]
> 请问下这个每秒更新是每隔一秒更新一次还是在歌曲播放的每秒的开头更新

有没有播放都是每秒更新，我看下能不能搞成获取即时的

**Comment by WXRIW** [comment]
我现在还没用电脑去看具体的返回信息是啥，但想到了一个比较准确的方法：
对于播放进度有两个数据，分别是播放进度（精确到毫秒）和这个播放进度所对应的系统时间（如系统启动毫秒数，或者精确到毫秒的具体时间），这样无论何时都可以获取到十分准确的播放进度信息。

**Comment by qier222** [comment]
现在获取到的数据是实时的了
https://github.com/qier222/YesPlayMusic/actions/runs/791552739

**Comment by WXRIW** [comment]
> 现在获取到的数据是实时的了
> https://github.com/qier222/YesPlayMusic/actions/runs/791552739

似乎还是每秒更新，一秒钟内获取到的数据都是一样的

**Comment by WXRIW** [comment]
如果打算保持现在状态不动了的话，我就开始写优化了。如果还要更改我就再等等

**Comment by meetcw** [comment]
> 现在获取到的数据是实时的了
> [qier222/YesPlayMusic/actions/runs/791552739](https://github.com/qier222/YesPlayMusic/actions/runs/791552739)

现在好像还是不是实时的，1s的间隔有点长了，这个频率可以由调用方来控制吗？

**Comment by WXRIW** [comment]
iTunes的数据也是1s更新一次，所以我已经有针对1s更新的同步方案了
每隔50ms刷新一次，出现返回值不一样时是相对最准确的。

**Comment by gxt-kt** [comment]
> 已经推送新commit了 [07455c8](https://github.com/qier222/YesPlayMusic/commit/07455c8ecd5f04adca3543e8a661a7bdacf484d6)
> 
> 访问 `http://127.0.0.1:27232/player` 可获取到正在播放歌曲的信息和进度，每秒更新一次 访问 `http://127.0.0.1:10754/lyric?id=歌曲ID` 可获取歌词信息

请问怎么获取当前歌曲的like状态
