### ISSUE TITLE
0.37音乐库无法加载出来

### ISSUE THREAD

**Issue by RebirthEgo** [qier222/YesPlayMusic#619]

**Comment by qier222** [comment]
需要控制台截图

**Comment by RebirthEgo** [comment]
<img width="1296" alt="Snipaste_2021-04-28_11-40-38" src="https://user-images.githubusercontent.com/54738173/116343256-aec7ab00-a816-11eb-9811-5ec907bfbc4b.png">

**Comment by qier222** [comment]
你这个是在GitHub下载的安装包吗？

**Comment by RebirthEgo** [comment]
> 你这个是在GitHub下载的安装包吗？

是呀

**Comment by llovvoll** [comment]
是邮箱登录的吗？我发现邮箱登录时不会更新likeSongPlaylistID所以造成页面加载失败

> > 你这个是在GitHub下载的安装包吗？
> 
> 是呀

**Comment by KMMoonlightQ** [comment]
手机号登录 依旧加载不出来音乐库

**Comment by llovvoll** [comment]
> 手机号登录 依旧加载不出来音乐库

控制台 resetApp() 重置再登入试试

**Comment by KMMoonlightQ** [comment]
> > 手机号登录 依旧加载不出来音乐库
> 
> 控制台（按 F12 可打开控制台） resetApp() 重置再登入试试

重置了依旧不行

**Comment by llovvoll** [comment]
> > > 手机号登录 依旧加载不出来音乐库
> > 
> > 
> > 控制台（按 F12 可打开控制台） resetApp() 重置再登入试试
> 
> 重置了依旧不行

是用 https://github.com/qier222/YesPlayMusic/actions/runs/791788708 这个版本的吗？我两台电脑测试都正常呢

**Comment by RebirthEgo** [comment]
> > > > 手机号登录依旧加载不出来音乐库
> > > 
> > > 
> > > 控制台（按F12可打开控制台）resetApp（）重置再登录试试
> > 
> > 
> > 重置了依旧不行
> 
> 是用https://github.com/qier222/YesPlayMusic/actions/runs/791788708这个版本的吗？

都试过，都无效

**Comment by wowmacro** [comment]
相同问题~
升级完0.37删过一次缓存以后音乐库加载不出来了。
刚升级到0.37的时候正常。win7
![微信截图_20210504133108](https://user-images.githubusercontent.com/7532385/116964051-18472e00-acdd-11eb-83f6-a7977d5c7ba5.jpg)

**Comment by qier222** [comment]
已经修复了，可以在这里下载到修复后的版本
https://github.com/qier222/YesPlayMusic/actions/runs/814329058

**Comment by essayZW** [comment]
@qier222 
![image](https://user-images.githubusercontent.com/48241531/117233954-ab57a380-ae56-11eb-9453-fe90bf1b22b3.png)

LInux版本，依旧打不开音乐库，下载的是修复后版本的AppImage
![image](https://user-images.githubusercontent.com/48241531/117234073-e0fc8c80-ae56-11eb-92b8-83a8b3ed79d3.png)

**Comment by qier222** [comment]
@essayZW 重启应用试试？不行就resetApp()

**Comment by essayZW** [comment]
@qier222 
重启过，resetApp()也试过，都是同样问题

**Comment by weitianpaxi** [comment]
网页端，在登陆后无法显示音乐库，但是在登出后，采用发现网易云账号的方法就可以显示音乐库包括私人歌单。

**Comment by Jinjie-Jack-Wang** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/70709944/117253720-1d8daf80-ae7a-11eb-9307-0c5a89b14790.png">
重置后依旧不行
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/70709944/117253900-5af23d00-ae7a-11eb-9c93-51c8a3efb32d.png">

**Comment by jackymlr** [comment]
![image](https://user-images.githubusercontent.com/17738958/117264916-4b78f100-ae86-11eb-9e6e-4ba4ab5c8055.png)
Mac端也有
![image](https://user-images.githubusercontent.com/17738958/117265032-677c9280-ae86-11eb-9567-3fd5f2f54040.png)

**Comment by funnybones2015** [comment]
同样问题，0.3.7 Mac版无法加载音乐库，账户登录上以后，页面一直加载，一直是空白的

**Comment by Jinjie-Jack-Wang** [comment]
我试了，安装0.3.5然后登录打开音乐库刷新一下，应该会出来，然后在关闭安装0.3.7即可使用。我使用的是MAC。

**Comment by KMMoonlightQ** [comment]
> 我试了，安装0.3.5然后登录打开音乐库刷新一下，应该会出来，然后在关闭安装0.3.7即可使用。我使用的是MAC。

同样的方法试了，没有用

**Comment by lyjdwh** [comment]
> 我试了，安装0.3.5然后登录打开音乐库刷新一下，应该会出来，然后在关闭安装0.3.7即可使用。我使用的是MAC。

manjaro 可以成功

**Comment by onecombo** [comment]
坏了，我什么方法都不行，只有0.37有这个问题![1620555400(1)](https://user-images.githubusercontent.com/33618120/117568477-6607d000-b0fb-11eb-9de7-d996cd835e15.jpg)

**Comment by MistQ** [comment]
下载的0.3.7 还是无法加载音乐库
![image](https://user-images.githubusercontent.com/42373544/117603472-c2173680-b185-11eb-91cb-61607400a9ef.png)

**Comment by kksxsyj** [comment]
> 我试了，安装0.3.5然后登录打开音乐库刷新一下，应该会出来，然后在关闭安装0.3.7即可使用。我使用的是MAC。
感谢分享，终于能显示音乐库了

**Comment by soratanmer** [comment]
我喜欢的音乐里是空列表会导致音乐库不显示。
往我喜欢的音乐里加几首歌就解决了。
![image](https://user-images.githubusercontent.com/23238799/118388551-d82a6880-b657-11eb-9ec7-8427ea8a949d.png)
