### ISSUE TITLE
无法加载音乐库

### ISSUE THREAD

**Issue by alan-rx** [qier222/YesPlayMusic#620]
版本号：0.37安装包
win10 20H2
可以正常登录，加红心，无法加载音乐库界面，可复现，多次初始化软件、重新安装无效
网页端可正常使用
![image](https://user-images.githubusercontent.com/83324817/116340092-11488900-a7ce-11eb-947a-b1178956af67.png)
补充：使用过unblock，未关闭时f12显示端口27232问题，关闭后不再出现，只出现上图问题，供参考

**Comment by qier222** [comment]
滑动到底部下载这个版本试试看能不能打开音乐库

https://github.com/qier222/YesPlayMusic/actions/runs/791552739

**Comment by alan-rx** [comment]
新版本：卸载重启重新安装后同时出现27232和旧问题
![image](https://user-images.githubusercontent.com/83324817/116362268-68138a00-a7f1-11eb-8f5a-7b5a15f09fc4.png)

**Comment by yiyikea** [comment]
> 滑动到底部下载这个版本试试看能不能打开音乐库
> 
> https://github.com/qier222/YesPlayMusic/actions/runs/791552739

貌似还是打不开

**Comment by yiyikea** [comment]
> 滑动到底部下载这个版本试试看能不能打开音乐库
> 
> https://github.com/qier222/YesPlayMusic/actions/runs/791552739

先下载旧版本，先登陆，之后后安装新版本就不会出现这个问题

**Comment by alan-rx** [comment]
> > 滑动到底部下载这个版本试试看能不能打开音乐库
> > https://github.com/qier222/YesPlayMusic/actions/runs/791552739
> 
> 先下载旧版本，先登陆，之后后安装新版本就不会出现这个问题

真的吗？我没文化你不要骗我，你说的旧版本是0.36还是没修改过的0.37？

**Comment by kingwoodsa** [comment]
临时解救，从网络请求里面，找到  detail 接口的请求， 从预览中找到 playlist 的 id， 记住这个id，修改  本地存储 中的 data，添加一个 在顶层json中添加一个 likedSongPlaylistID 值为刚刚记住的，重新打开就行了， 如果清除了缓存，再写入即可

**Comment by alan-rx** [comment]
> 临时解救，从网络请求里面，找到 detail 接口的请求，
> ![image](https://user-images.githubusercontent.com/3349679/116543944-14a05980-a921-11eb-8799-8f33bb201c41.png)
> 从预览中找到 playlist 的 id， 记住这个id，修改 本地存储 中的 data，添加一个 在顶层json中添加一个 likedSongPlaylistID 值为刚刚记住的，
> ![image](https://user-images.githubusercontent.com/3349679/116544042-38fc3600-a921-11eb-831e-5fdf585f9948.png)
> 重新打开就行了， 如果清除了缓存，再写入即可

![image](https://user-images.githubusercontent.com/83324817/116547038-f0467c00-a924-11eb-8c45-ae4583e350de.png)
不太成功，原因我也不懂，是我操作不对吗？

**Comment by alboert** [comment]
先装0.35版本登录打开音乐库，然后更新到0.37，还有个好处是0.35版安装时可以选择路径，更新后还在原路径

**Comment by alan-rx** [comment]
> 先装0.35版本登录打开音乐库，然后更新到0.37，还有个好处是0.35版安装时可以选择路径，更新后还在原路径

真的可以了，非常感谢

**Comment by qier222** [comment]
已经修复了，可以在这里下载到修复后的版本，因为存在相同的issue #619，这个issue先关闭了
https://github.com/qier222/YesPlayMusic/actions/runs/814329058
