### ISSUE TITLE
Unblocknetease Music无法关闭

### ISSUE THREAD

**Issue by RebirthEgo** [qier222/YesPlayMusic#621]
Unblocknetease Music关闭后重启软件又自动打开，同样的代理端口设置在网易云客户端是启作用的，但在YesPlayMusic无效，不知道是不是Unblocknetease Music无法关闭导致代理更改失效。

**Comment by kacherli** [comment]
测试代理问题可能有点问题，期待解决下。

**Comment by zry98** [comment]
不需要重启软件,重新打开设置就可以看到又被启用了,且代理设置不生效
