### ISSUE TITLE
歌曲播放进度条不显示实时进度

### ISSUE THREAD

**Issue by wyh2019666** [qier222/YesPlayMusic#625]
如图，Touch Bar和app页面下播放歌曲均不显示
我的系统是macOS 11.3 Big Sur，YesPlayMusic版本0.3.7

<img width="1004" alt="触控栏快照2021-04-28 下午7 53 44" src="https://user-images.githubusercontent.com/57748550/116399504-94fc8700-a85b-11eb-8c23-0341dfca320b.png">
<img width="1552" alt="截屏2021-04-28 下午7 53 18" src="https://user-images.githubusercontent.com/57748550/116399515-962db400-a85b-11eb-8afe-47ad63dca517.png">

**Comment by sukanka** [comment]
我也遇到了同样的问题，进度条不会走，但是可以通过它调节进度就是了

**Comment by funnybones2015** [comment]
我也是，在歌词界面下，不管进度到哪，播放进度条始终显示0:00

![image](https://user-images.githubusercontent.com/15063728/117531423-f7e8dd80-b014-11eb-8c5c-5b0ab620206b.png)

**Comment by keallovelive** [comment]
我也一样，archlinux,0.3.9

**Comment by qier222** [comment]
v0.4.0 版本已修复
