### ISSUE TITLE
UnblockNeteaseMusic开关无效

### ISSUE THREAD

**Issue by so1ar** [qier222/YesPlayMusic#630]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息
关闭UnblockNetEaseMusic后不生效，且再次打开设置页面，开关变回打开的状态。
![1619669070_grim](https://user-images.githubusercontent.com/54471528/116501759-36c7b680-a8e4-11eb-818d-dc7e23f551a7.png)

- 用的是网页版还是客户端
客户端

- 浏览器名称或电脑操作系统
Archlinux

- 控制台 Console 页面的截图（按 F12 可打开控制台）
![1619669338_grim](https://user-images.githubusercontent.com/54471528/116501585-ba34d800-a8e3-11eb-99d8-efd4736d446f.png)

**Comment by qier222** [comment]
重复的issue #621
