### ISSUE TITLE
建议：可以增加一个在显示歌词界面的全屏功能

### ISSUE THREAD

**Issue by EarendelArc** [qier222/YesPlayMusic#631]
建议：可以增加一个在显示歌词界面的全屏功能

**Comment by LTHPKBTE** [comment]
作为暂时的替代方案，别忘了大部分浏览器都是可以使用F11/F10全屏的。包括YesPlayMusic本体在内。

**Comment by imyangjiong** [comment]
好的，谢谢



发自我的小米手机
在 LTHPKBTE ***@***.***>，2021年5月4日 22:50写道：

作为暂时的替代方案，别忘了大部分浏览器都是可以使用F11/F10全屏的。包括YesPlayMusic本体在内。
