### ISSUE TITLE
网页端音乐库不能显示

### ISSUE THREAD

**Issue by Mtoly** [qier222/YesPlayMusic#632]
网页端部署vercel按教程来音乐库还是不能显示
![image](https://user-images.githubusercontent.com/52591084/116772515-2c432380-aa82-11eb-88d8-456dd8cfa081.png)
包括音乐无法加载
看了别的反馈问题还是没有解决

**Comment by tim-wang-tmp** [comment]
看前边的方法解决了，你先下载0.3.5版本，安装后登录账号，然后在安装0.3.7版本，目前我这样操作可以显示音乐库。

**Comment by Mtoly** [comment]
> 看前边的方法解决了，你先下载0.3.5版本，安装后登录账号，然后在安装0.3.7版本，目前我这样操作可以显示音乐库。

能发一下0.35版本的源码么，我找不到呢

**Comment by tim-wang-tmp** [comment]
> > 看前边的方法解决了，你先下载0.3.5版本，安装后登录账号，然后在安装0.3.7版本，目前我这样操作可以显示音乐库。
> 
> 能发一下0.35版本的源码么，我找不到呢

https://github.com/qier222/YesPlayMusic/releases/tag/v0.3.5

**Comment by Mtoly** [comment]
> > > 看前边的方法解决了，你先下载0.3.5版本，安装后登录账号，然后在安装0.3.7版本，目前我这样操作可以显示音乐库。
> > 
> > 
> > 能发一下0.35版本的原始么，我找到呢
> 
> https://github.com/qier222/YesPlayMusic/releases/tag/v0.3.5

感谢

**Comment by sukanka** [comment]
> 看前边的方法解决了，你先下载0.3.5版本，安装后登录账号，然后在安装0.3.7版本，目前我这样操作可以显示音乐库。

其实这样并不能解决，我试了下，回到 0.3.5 确实能加载了，然后登录帐号，升级到 0.3.7, 还是能加载，但是不知道你注意到没有，实际上设置界面显示的版本还是 0.3.5。当我清除缓存重新登录的时候，设置界面显示 0.3.7，音乐库还是打不开。

**Comment by tim-wang-tmp** [comment]
> > 看前边的方法解决了，你先下载0.3.5版本，安装后登录账号，然后在安装0.3.7版本，目前我这样操作可以显示音乐库。
> 
> 其实这样并不能解决，我试了下，回到 0.3.5 确实能加载了，然后登录帐号，升级到 0.3.7, 还是能加载，但是不知道你注意到没有，实际上设置界面显示的版本还是 0.3.5。当我清除缓存重新登录的时候，设置界面显示 0.3.7，音乐库还是打不开。

你卸载了先安装0.3.5，然后手机号登录账号，退出在用0.3.7安装包升级看看，我就是这样操作的，音乐库可以打开。
![微信截图_20210504230949](https://user-images.githubusercontent.com/1762601/117026095-0cd02300-ad2e-11eb-9e26-927db9374bc0.png)

**Comment by sukanka** [comment]
> 你卸载了先安装0.3.5，然后手机号登录账号，退出在用0.3.7安装包升级看看，我就是这样操作的，音乐库可以打开。
居然真的可以，我是网页版居然也可以，感谢！

**Comment by qier222** [comment]
重复的issue #619 
现在网页版已经修复啦
