### ISSUE TITLE
移动端适配

### ISSUE THREAD

**Issue by ZhaoTonggang** [qier222/YesPlayMusic#634]
网页版移动端未适配，手机打开网页版显示有点奇怪

**Comment by LTHPKBTE** [comment]
请看作者todo列表(https://github.com/qier222/YesPlayMusic/projects/1）。有考虑但是暂时不做

**Comment by ZhaoTonggang** [comment]
要不，我先尝试着弄

**Comment by ZhaoTonggang** [comment]
> 请看作者todo列表（https://github.com/qier222/YesPlayMusic/projects/1）。有考虑但是暂时不做

要不，我先尝试着弄

**Comment by qier222** [comment]
可以尝试搞，开个专门的分支搞移动版，不需要兼容桌面端

**Comment by ZhaoTonggang** [comment]
虽然我很想尝试，但是很抱歉，我无法完成这项工作，我没有足够的空余时间。
