### ISSUE TITLE
无法加载音乐库

### ISSUE THREAD

**Issue by mai1202** [qier222/YesPlayMusic#636]
如图
![image](https://user-images.githubusercontent.com/63698132/116838686-e44b0a80-ac01-11eb-882e-c1c23ec0d0e1.png)

**Comment by mai1202** [comment]
我遇到的错误仅出现在 0.3.7 的版本下，0.3.6 版本没有问题。

**Comment by NavlysChen** [comment]
https://github.com/qier222/YesPlayMusic/issues/632#issuecomment-830833961
刚刚我退出了账号以后也打不开了，重装0.3.6后再装0.3.7就可以了，你可以试试

**Comment by qier222** [comment]
重复的issue #619
