### ISSUE TITLE
我很想知道设置里那个unblockNeteasemusic的开关是打开了就能听灰色歌曲吗？

### ISSUE THREAD

**Issue by liukenny961** [qier222/YesPlayMusic#638]
如题。
是不是还要配合unblockNetsasemusic源码什么的。

**Comment by LTHPKBTE** [comment]
*理论上*来说是没有问题的。但是前几天unblockNetsasemusic本身出了点问题(nondanee/UnblockNeteaseMusic#737)现在那边修复了，不知道这边怎么样。

**Comment by liukenny961** [comment]
哦，知道了。
谢谢！
