### ISSUE TITLE
【Bug】Mac客户端歌词显示界面适配问题

### ISSUE THREAD

**Issue by ImplementX** [qier222/YesPlayMusic#639]
Mac客户端歌词显示界面在竖屏全屏情况下专辑封面会拉伸放大导致挤压遮挡歌词，如图
#  分辨率1440 × 2560
![image](https://user-images.githubusercontent.com/23149776/116975866-e17c1280-acf2-11eb-8cb4-f9e6dc273abe.png)

**Comment by ImplementX** [comment]
![image](https://user-images.githubusercontent.com/23149776/116976013-1ee0a000-acf3-11eb-849b-3e806dc46ad0.png)
![image](https://user-images.githubusercontent.com/23149776/116976066-36b82400-acf3-11eb-893c-85c522915fbd.png)

**Comment by qier222** [comment]
v0.4.0 版本已修复
