### ISSUE TITLE
mac版软件登录问题

### ISSUE THREAD

**Issue by yujiadong24** [qier222/YesPlayMusic#64]
在设置界面已登录，但是音乐库显示还是需要登录
<img width="1090" alt="QQ20201201-094135@2x" src="https://user-images.githubusercontent.com/51140864/100686525-792eab00-33b9-11eb-8fd4-dd1725c0c56c.png">
<img width="1090" alt="QQ20201201-094121@2x" src="https://user-images.githubusercontent.com/51140864/100686531-7af86e80-33b9-11eb-85b7-e700b49fe01e.png">

**Comment by qier222** [comment]
已修复，需要下载最新的客户端

https://github.com/qier222/YesPlayMusic/releases/tag/v0.2.2
