### ISSUE TITLE
这是怎么回事，每次打开都会弹出这个东西，我也看不懂

### ISSUE THREAD

**Issue by NCSrapoo** [qier222/YesPlayMusic#640]
![YesPlayMusic](https://user-images.githubusercontent.com/81073939/116979955-38d0b180-acf8-11eb-80d0-bca82817d453.png)

**Comment by LTHPKBTE** [comment]
作者提供的API:访问 http://127.0.0.1:27232/player 可获取到正在播放歌曲的信息和进度，每秒更新一次
访问 http://127.0.0.1:10754/lyric?id=歌曲ID 可获取歌词信息
可能是某些原因导致端口不可用（权限不足？）
