### ISSUE TITLE
macOS 每次打开应用后都会看到系统的询问是否允许这个应用接受网络连接

### ISSUE THREAD

**Issue by PIndividual** [qier222/YesPlayMusic#641]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- macOS客户端
- 系统版本10.15.7
- 每次打开应用后都会看到系统的询问是否允许这个应用接受网络连接，很烦
- 
<img width="532" alt="Screen Shot 2021-05-04 at 8 00 40 PM" src="https://user-images.githubusercontent.com/62368342/117000269-6840e780-ad13-11eb-87dd-fa91701770f7.png">

**Comment by qier222** [comment]
不知道是因为什么引起的，看看有没有其他人知道这个

**Comment by WenJunDuan** [comment]
我也 出现这个问题

**Comment by sylvesterww** [comment]
+1,也出现了这个问题。系统big sur。去防火墙里看了一下也没什么问题。
<img width="261" alt="截屏2021-05-06 下午8 09 19" src="https://user-images.githubusercontent.com/78637425/117296027-28126e00-aea7-11eb-8964-962a2e3b188b.png">

**Comment by shi991203** [comment]
一直都有这个问题

**Comment by artxia** [comment]
这个弹窗 疑似是 macOS 防火墙签名故障。
而且不止 YesPlayMusic.app 会出反复出现这个弹窗，我遇到过另外的 app 也会有这个情况。

解决办法，先关闭 app 打开 Terminal.app 输入代码，重新签名这个 app即可。
完成后会再弹一次，以后就不会再弹。重装和升级疑似都可能需要重签一次。

```
sudo codesign --force --deep --sign - /Applications/YesPlayMusic.app/
```

**Comment by PIndividual** [comment]
求问大佬，输入完显示这个怎么办
/Applications/YesPlayMusic.app/: resource fork, Finder information, or similar detritus not allowed

**Comment by artxia** [comment]
> 求问大佬，输入完显示这个怎么办
> /Applications/YesPlayMusic.app/: resource fork, Finder information, or similar detritus not allowed

试试看先执行`xattr -cr /文件位置`，再执行前面的命令
