### ISSUE TITLE
喜欢的音乐不更新

### ISSUE THREAD

**Issue by PIndividual** [qier222/YesPlayMusic#642]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- macOS客户端
- macOS Catalina，10.15.7
- 更新客户端到0.3.7后，我喜欢的音乐仍然不更新，退出并重新登录无效

**Comment by PIndividual** [comment]
补充一下，点按播放按钮的时候是没问题的，但是显示的仍然是第一个登录用户的
<img width="1192" alt="Screen Shot 2021-05-05 at 11 02 33 AM" src="https://user-images.githubusercontent.com/62368342/117092783-d2986d00-ad91-11eb-8c63-7cdb525217d9.png">
资料

**Comment by qier222** [comment]
已经修复了，可以在这里下载到修复后的版本
https://github.com/qier222/YesPlayMusic/actions/runs/814329058

**Comment by RoyRao2333** [comment]
> 已经修复了，可以在这里下载到修复后的版本
> https://github.com/qier222/YesPlayMusic/actions/runs/814329058

想请问一下，怎么从您提供的URL下载修复后的版本？系统是macOS，谢谢！

**Comment by RoyRao2333** [comment]
> 已经修复了，可以在这里下载到修复后的版本
> https://github.com/qier222/YesPlayMusic/actions/runs/814329058

开发者您好！我刚发现在最新release 0.3.7中，登录账号后Library和我喜欢歌单都打不开（加载不出），而您这个修复后的版本解决了这个问题。但universal版本的app实在是太大了，请问可以单独发布一个Intel芯片的x86版本吗？感谢！

**Comment by qier222** [comment]
> > 已经修复了，可以在这里下载到修复后的版本
> 
> > https://github.com/qier222/YesPlayMusic/actions/runs/814329058
> 
> 
> 
> 开发者您好！您这个修复后的版本的确解决了这个问题。但universal版本的app实在是太大了，请问可以单独发布一个Intel芯片的x86版本吗？感谢！

等正式版发布吧，链接里那个是自动构建的

**Comment by RoyRao2333** [comment]
> > > 已经修复了，可以在这里下载到修复后的版本
> > 
> > 
> > > https://github.com/qier222/YesPlayMusic/actions/runs/814329058
> > 
> > 
> > 开发者您好！您这个修复后的版本的确解决了这个问题。但universal版本的app实在是太大了，请问可以单独发布一个Intel芯片的x86版本吗？感谢！
> 
> 等正式版发布吧，链接里那个是自动构建的



> > > 已经修复了，可以在这里下载到修复后的版本
> > 
> > 
> > > https://github.com/qier222/YesPlayMusic/actions/runs/814329058
> > 
> > 
> > 开发者您好！您这个修复后的版本的确解决了这个问题。但universal版本的app实在是太大了，请问可以单独发布一个Intel芯片的x86版本吗？感谢！
> 
> 等正式版发布吧，链接里那个是自动构建的

感谢！问一个题外话，请问设置里面的🏳️‍🌈🐈是什么功能啊😂

**Comment by NavlysChen** [comment]
> > > > 已经修复了，可以在这里下载到修复后的版本
> > > 
> > > 
> > > > https://github.com/qier222/YesPlayMusic/actions/runs/814329058
> > > 
> > > 
> > > 开发者您好！您这个修复后的版本的确解决了这个问题。但universal版本的app实在是太大了，请问可以单独发布一个Intel芯片的x86版本吗？感谢！
> > 
> > 
> > 等正式版发布吧，链接里那个是自动构建的
> 
> > > > 已经修复了，可以在这里下载到修复后的版本
> > > 
> > > 
> > > > https://github.com/qier222/YesPlayMusic/actions/runs/814329058
> > > 
> > > 
> > > 开发者您好！您这个修复后的版本的确解决了这个问题。但universal版本的app实在是太大了，请问可以单独发布一个Intel芯片的x86版本吗？感谢！
> > 
> > 
> > 等正式版发布吧，链接里那个是自动构建的
> 
> 感谢！问一个题外话，请问设置里面的🏳️‍🌈🐈是什么功能啊😂

打开以后你看看播放的进度条就知道了😂
