### ISSUE TITLE
希望网页端也添加UnblockNeteaseMusic

### ISSUE THREAD

**Issue by acodegod** [qier222/YesPlayMusic#644]

**Comment by qier222** [comment]
不一定能实现，之后搞一下看看

**Comment by weitianpaxi** [comment]
您好，之前有人出过教程，网页端解锁需要国内IP的服务器。下面是教程链接。
https://www.orzlee.com/toss/2020/12/26/neteasecloudmusicapi-yesplaymusic-unblockneteasemusic-build-your-own-music-station-unblock-copyrightfree-music.html

**Comment by acodegod** [comment]
> 您好，之前有人出过教程，网页端解锁需要国内IP的服务器。下面是教程链接。
> [https://www.orzlee.com/toss/2020/12/26/neteasecloudmusicapi-yesplaymusic-unblockneteasemusic-build-your -own-music-station-unblock-copyrightfree-music.html](https://www.orzlee.com/toss/2020/12/26/neteasecloudmusicapi-yesplaymusic-unblockneteasemusic-build-your-own-music-station-unblock-copyrightfree-music.html)

好像版本不一样，好多修改都不相同

**Comment by tywtyw2002** [comment]
直接修改`netease_api/util/request.js`

```
    // if (options.realIP) headers['X-Real-IP'] = options.realIP  // comment this line
    headers['X-Real-IP'] = '118.88.88.88'   //  <---- 这里填入任意一个中国IP。
```

**Comment by pan93412** [comment]
見 #1156 解釋。除非 UNM 改寫否則不太可能。
