### ISSUE TITLE
[Windows][客户端]音乐库打不开

### ISSUE THREAD

**Issue by NCSrapoo** [qier222/YesPlayMusic#645]
网页版都能打开但是客户端就是打不开![YsePlayMusic](https://user-images.githubusercontent.com/81073939/117147243-a4457c80-ade7-11eb-877c-a404771e7ac7.png)

**Comment by Jinjie-Jack-Wang** [comment]
我也有同样问题，在MAC OS里

**Comment by qier222** [comment]
重复的issue #619
