### ISSUE TITLE
音乐库接口id错误导致白屏

### ISSUE THREAD

**Issue by github-superadmin** [qier222/YesPlayMusic#647]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://user-images.githubusercontent.com/50284425/117265407-c80bcf80-ae86-11eb-86c7-b2a9a2e06c02.png)
![image](https://user-images.githubusercontent.com/50284425/117265506-e376da80-ae86-11eb-9316-72c535a1c008.png)
音乐库接口id错误导致白屏，抓包得到的id=0，实际上得改成1才能显示

**Comment by github-superadmin** [comment]
![image](https://user-images.githubusercontent.com/50284425/117265871-42d4ea80-ae87-11eb-854d-b2fc57d0356d.png)
![image](https://user-images.githubusercontent.com/50284425/117265886-48323500-ae87-11eb-8403-2b2736dac047.png)

**Comment by qier222** [comment]
请查看issue #619

**Comment by github-superadmin** [comment]
> 请查看issue #619
