### ISSUE TITLE
动态背景

### ISSUE THREAD

**Issue by Jinjie-Jack-Wang** [qier222/YesPlayMusic#648]
<img width="1680" alt="Screen Shot 2021-05-06 at 7 41 43 PM" src="https://user-images.githubusercontent.com/70709944/117292803-3199d700-aea3-11eb-95e6-dbc7fe8fe958.png">
这个是apple Music，希望有像这个一样的动态背景，跟着歌曲封面的颜色变化

<img width="1080" alt="iShot2021-05-06 19 42 08" src="https://user-images.githubusercontent.com/70709944/117292934-58f0a400-aea3-11eb-9dce-025234944c3b.png">
这个是YesPlayMusic的，已经很好看了，但是感觉有点变化回更好

**Comment by memorydream** [comment]
设置 > 显示歌词背景

**Comment by qier222** [comment]
设置里有相关选项，但是目前效果还不够好
