### ISSUE TITLE
竖屏显示模式和迷你显示

### ISSUE THREAD

**Issue by Jinjie-Jack-Wang** [qier222/YesPlayMusic#649]
<img width="475" alt="iShot2021-05-06 20 06 43" src="https://user-images.githubusercontent.com/70709944/117295615-a589ae80-aea6-11eb-8e50-025e4b06b797.png">

因为横屏显示有的时候有点太占地方，希望可以竖屏显示歌曲信息和歌词。甚至可以是非常小的显示模式，在办公的时候也可以看见歌词和歌曲信息

<img width="315" alt="image" src="https://user-images.githubusercontent.com/70709944/117295922-06b18200-aea7-11eb-93cd-525ac3cabec4.png">

**Comment by qier222** [comment]
重复的issue #639 #629
