### ISSUE TITLE
无法通过手机号和密码登陆

### ISSUE THREAD

**Issue by TristanBlus** [qier222/YesPlayMusic#65]
登陆页面选取手机号和密码进行登陆之后，还是闪回到选择登陆方式的页面。网页版的DEMO经测试没有这个问题，不知道什么原因。

**Comment by njzydark** [comment]
已修复 https://github.com/qier222/YesPlayMusic/pull/62

**Comment by TristanBlus** [comment]
> 已修复 #6

不好意思，可能我描述的不够清楚。DEMO网站是可以登陆的，但是PC版客户端(win)还是存在这个问题，刚才又测试了一遍还是这个问题。登录页面输入账号密码后的页面又返回到选择登录方式了。

**Comment by qier222** [comment]
> > 已修复 #6
> 
> 不好意思，可能我描述的不够清楚。DEMO网站是可以登陆的，但是PC版客户端(win)还是存在这个问题，刚才又测试了一遍还是这个问题。登录页面输入账号密码后的页面又返回到选择登录方式了。

已经修复了，但是还没打包发布新安装包，需要等发布新版。
或者你可以克隆最新的仓库然后自己打包。

**Comment by qier222** [comment]
已修复，需要下载最新的客户端

https://github.com/qier222/YesPlayMusic/releases/tag/v0.2.2
