### ISSUE TITLE
启动后显示音乐库  选项失效

### ISSUE THREAD

**Issue by QLFY233** [qier222/YesPlayMusic#658]
启动后显示音乐库  选项失效，无论是否打开此选项软件开启时都会进入首页
而且这个功能在之前的版本中有效
![image](https://user-images.githubusercontent.com/73421931/117563108-490cd600-b0d6-11eb-9edf-79728a87b03f.png)

反馈 bug 需要的信息
-win10客户端，版本v0.3.7

**Comment by guowei-gong** [comment]
我的音乐库无法打开，它是空白的

**Comment by L3sliez** [comment]
借楼，看到有一样问题的，音乐库登陆后加载不出来
![image](https://user-images.githubusercontent.com/47407901/118135617-d3866a00-b435-11eb-8296-deabb82bd5b2.png)
报错是这是这样的

**Comment by foreverwws** [comment]
![image](https://user-images.githubusercontent.com/35222820/118577640-5a806d00-b7bd-11eb-9e07-c2c3a39fec3e.png)
0.3.8版，win10，音乐库还是打不开，使用的手机号登录

**Comment by qier222** [comment]
> 借楼，看到有一样问题的，`音乐库`登陆后加载不出来
> 
> - 客户端 ubuntu20.04
> 
> - 报错是这是这样的
> 
> ![image](https://user-images.githubusercontent.com/47407901/118135860-134d5180-b436-11eb-8121-502931a64de9.png)
> 
> 
> 
> 貌似是api资源找不到？（并不太清楚
> 
> - 下载的是**yesplaymusic_0.3.7_amd64.deb**包
> 
> 
> 
> 

重新登录试试
