### ISSUE TITLE
解锁灰色歌曲已失效了吗？

### ISSUE THREAD

**Issue by oishi81** [qier222/YesPlayMusic#660]
用的最新版本，unblockneteasemusic已经打开

**Comment by milkum** [comment]
如果你会改代码参考这个链接里的方法，像我这种代码盲只能等更新了
https://github.com/nondanee/UnblockNeteaseMusic/issues/737

**Comment by oishi81** [comment]
原来如此，谢指点，只能等更新了，我是windows环境，不知道怎么重新编译代码

**Comment by qier222** [comment]
重复的issue #587
