### ISSUE TITLE
退出时残留 /tmp/.org.chromium.Chromium.* 文件

### ISSUE THREAD

**Issue by vancez** [qier222/YesPlayMusic#662]
ArchLinux，用的是客户端
运行时会创建两个 .org.chromium.Chromium.xxx 文件和文件夹，退出后只删了文件夹，文件还在，重复开关几次就会留下很多/tmp/.org.chromium.Chromium.* 文件

**Comment by qier222** [comment]
这个是Electron自动生成的，tmp文件夹的内容在重启系统后应该会自动被删除，如果文件不大的话不需要理会。
