### ISSUE TITLE
“添加到歌单”按钮无效

### ISSUE THREAD

**Issue by KiWinger** [qier222/YesPlayMusic#667]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 网页版、客户端均无效
- Win10 20H2/QQ Brower Chromium70.0.3538.25
- 控制台 Console 页面的截图（按 F12 可打开控制台）
- 
![image](https://user-images.githubusercontent.com/49084827/118347011-7a702080-b572-11eb-8deb-dc77ecb03670.png)

**Comment by qier222** [comment]
无法复现

**Comment by KiWinger** [comment]
> 无法复现

问题出现版本0.3.7
更新0.3.8后恢复正常

**Comment by StandGreat** [comment]
现在使用的0.4.5还是无法把歌曲添加到歌单中，“添加到歌单”这个按钮是有用的，但是弹出来的二级菜单选择歌单无效
