### ISSUE TITLE
音乐库依旧加载不出来

### ISSUE THREAD

**Issue by zhao141** [qier222/YesPlayMusic#669]
Windows最新版依旧加载不出来音乐库，试过了多种方法登录均不可以
![image](https://user-images.githubusercontent.com/48958017/118354107-0cd8ea00-b59c-11eb-8e90-7642e3cbaf74.png)

**Comment by zhao141** [comment]
v0.3.7

**Comment by zhao141** [comment]
在用了修复包后OK了

**Comment by zhao141** [comment]
Thanks

**Comment by wujinyi521** [comment]
> 在用了修复包后OK了

请问修复包在那里可以找到？

**Comment by zhao141** [comment]
现在更新到最新就可



---原始邮件---
发件人: "jinyi ***@***.***&gt;
发送时间: 2021年5月17日(周一) 凌晨3:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [qier222/YesPlayMusic] 音乐库依旧加载不出来 (#669)




  
在用了修复包后OK了
  
请问修复包在那里可以找到？
