### ISSUE TITLE
【macOS】0.3.8版本音乐库打不开

### ISSUE THREAD

**Issue by masterwangf** [qier222/YesPlayMusic#673]
![image](https://user-images.githubusercontent.com/29242166/118582869-b00d4780-b7c6-11eb-9b63-1f37ffafe0de.png)
![image](https://user-images.githubusercontent.com/29242166/118583045-f6fb3d00-b7c6-11eb-9091-1070d71b6b4f.png)

**Comment by masterwangf** [comment]
resetApp()已经试过 也没用

**Comment by qier222** [comment]
如果你有时间的话，可以按照以下操作，然后将控制台的所有报错信息截图发上来：
1. 执行resetApp()
2. 在登录页面登录账号
3. 在跳转到音乐库页面后截图控制台所有报错信息

**Comment by soratanmer** [comment]
往我喜欢的音乐里加几首歌看看，library.vue里面有个判断是如果我喜欢的音乐为空就无法显示音乐库。。。

**Comment by masterwangf** [comment]
![image](https://user-images.githubusercontent.com/29242166/118617873-a0592780-b7f5-11eb-9b5e-658243ea27c2.png)
@qier222

**Comment by masterwangf** [comment]
往喜欢的音乐里面加了一首歌 可以展示了！

**Comment by masterwangf** [comment]
> 往我喜欢的音乐里加几首歌看看，library.vue里面有个判断是如果我喜欢的音乐为空就无法显示音乐库。。。

往喜欢的音乐里面加了一首歌 可以展示了！

**Comment by qier222** [comment]
这个问题已经修复了，可以在这里下载到修复后的版本
https://github.com/qier222/YesPlayMusic/actions/runs/852730953

**Comment by masterwangf** [comment]
``

> 这个问题已经修复了，可以在这里下载到修复后的版本
> https://github.com/qier222/YesPlayMusic/actions/runs/852730953

感谢！ 可以正常显示了！
