### ISSUE TITLE
［BUG］客户端0.3.8歌词界面收藏按钮不管用

### ISSUE THREAD

**Issue by stevaon** [qier222/YesPlayMusic#675]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息
[BUG] 歌词界面收藏按钮不管用
- 客户端0.3.8
- win10 2004版
![image](https://user-images.githubusercontent.com/46243429/118585357-50fe0180-b7cb-11eb-8dd5-f3f4e01cbb96.png)

**Comment by ycr10** [comment]
同上，艺人也似乎也无法加载

**Comment by Revincx** [comment]
已经确认是buttons这个div被挡住了，加上`z-index: 0`的属性就能解决。
挡住它的貌似是lyrics-background，删掉之后就能点了，不过我CSS学的一般，没搞清楚为啥会挡住。。
这个我就不发pr了 @qier222

**Comment by qier222** [comment]
已修复，可以在这里下载修复后的版本
https://github.com/qier222/YesPlayMusic/actions/runs/852730953

**Comment by stevaon** [comment]
已用，谢谢
