### ISSUE TITLE
0.3.8播放条不动，歌曲正常播放

### ISSUE THREAD

**Issue by FCSDFSDVXDFG** [qier222/YesPlayMusic#678]

**Comment by qier222** [comment]
提供下界面截图和控制台错误信息

**Comment by RoyRao2333** [comment]
> 提供下界面截图和控制台错误信息

我也发现了这个问题，界面截图这样的
![image](https://user-images.githubusercontent.com/31413093/118915076-e251ad00-b95e-11eb-829f-984628dd38d4.png)
请问控制台错误信息怎么获取呢？

**Comment by qier222** [comment]
按F12，然后选择Console

**Comment by RoyRao2333** [comment]
> 按F12，然后选择Console

刚发现，有时候正常，有时候进度条就不动
目前Console是这样的
![image](https://user-images.githubusercontent.com/31413093/118926278-a58fb100-b972-11eb-9413-e2ab363f2e2d.png)

**Comment by RichardBaker3020** [comment]
ubuntu 上这个问题可以复现

**Comment by CredBenz** [comment]
> 按F12，然后选择Console
Win10 上面也有这个bug。进度条和歌词都不会动
![avatar](https://img13.360buyimg.com/ddimg/jfs/t1/195227/18/5174/264827/60af9b1dE5df85c55/a06273e5862f5faa.png)

**Comment by Mark-Imaginist** [comment]
我这里网页版和 Windows 客户端 0.3.9 也都有此问题，歌词正常滚动但进度条不走，无规律复现

**Comment by qier222** [comment]
v0.4.0 版本已修复
