### ISSUE TITLE
BUG: 歌词界面没有歌词时右半部分的按钮被遮挡，无法点击

### ISSUE THREAD

**Issue by memorydream** [qier222/YesPlayMusic#680]
版本：0.3.8 (Action Build/Release#305  commit 41a30a2)
平台：windows10

在没有歌词时，有元素遮挡了右半部分的控制按钮，导致该部分按钮无法被点击
![image](https://user-images.githubusercontent.com/34763046/118671944-75d59180-b82a-11eb-8a2a-c867e390179f.png)

在F12中将其隐藏后可以点击到按钮
![image](https://user-images.githubusercontent.com/34763046/118672253-af0e0180-b82a-11eb-9ba5-774f16c26227.png)

**Comment by qier222** [comment]
重复的issue #675

**Comment by memorydream** [comment]
> 重复的issue #675

应该不是，这个issue使用的版本是  https://github.com/qier222/YesPlayMusic/actions/runs/852730953

**Comment by qier222** [comment]
你下载试试看能不能解决这个问题吧

**Comment by memorydream** [comment]
> 你下载试试看能不能解决这个问题吧

那我重新下载安装一份试试

**Comment by memorydream** [comment]
> 你下载试试看能不能解决这个问题吧

重新安装了一遍，同样的问题，是Action构建的包

**Comment by memorydream** [comment]
应该很容易复现，放一首没有歌词的纯音乐就行

**Comment by qier222** [comment]
刚刚push了新代码，应该修复了
