### ISSUE TITLE
用键盘上的音乐控制切歌多次后，音乐控制器失效

### ISSUE THREAD

**Issue by cqhhy2001** [qier222/YesPlayMusic#686]
https://user-images.githubusercontent.com/21079967/118910827-bd0d7080-b957-11eb-9daf-8fdbfc346f36.mp4
![image](https://user-images.githubusercontent.com/21079967/118910916-e0d0b680-b957-11eb-868d-068163edb178.png)
Windows客户端 0.3.8

**Comment by qier222** [comment]
需要提供控制台截图，按F12然后选择Console

**Comment by cqhhy2001** [comment]
> 需要提供控制台截图，按F12然后选择Console

![image](https://user-images.githubusercontent.com/21079967/118923192-c1448880-b96d-11eb-8457-cc02b0736c32.png)
![image](https://user-images.githubusercontent.com/21079967/118923207-c86b9680-b96d-11eb-8989-452c996a6d82.png)
![image](https://user-images.githubusercontent.com/21079967/118923236-ce617780-b96d-11eb-847e-ddc1a87d7700.png)

![image](https://user-images.githubusercontent.com/21079967/118923327-f4871780-b96d-11eb-9105-9081415006c7.png)

现在“喜欢的音乐”也无法载入，无法播放任何音乐

**Comment by qier222** [comment]
试一下在控制台输入 resetApp() 重置应用

**Comment by cqhhy2001** [comment]
谢谢
好的目前来说是正常了，但是希望解决一下这个奇怪的问题
