### ISSUE TITLE
windows登录都登录不进去了密码对的一直显示错误望尽快修复 首页和发现也不显示全是白板

### ISSUE THREAD

**Issue by wyh0326** [qier222/YesPlayMusic#688]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息
![image](https://user-images.githubusercontent.com/65211335/119135602-3947a700-ba71-11eb-832e-5af27dd4a9db.png)
![image](https://user-images.githubusercontent.com/65211335/119135640-45336900-ba71-11eb-9811-869eb2b2f0bf.png)
![image](https://user-images.githubusercontent.com/65211335/119135662-4b294a00-ba71-11eb-93b2-63ee5046d1f5.png)

- 用的是网页版还是客户端 客户端  
- 浏览器名称或电脑操作系统windows10 
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by milk36** [comment]
遇到同样的登录问题
