### ISSUE TITLE
有两个问题 一是点击喜欢没反应 哪种情况下都不行 二是导入的歌单里的歌曲版本不对

### ISSUE THREAD

**Issue by Binary2101** [qier222/YesPlayMusic#690]
版本0.3.8 mac

有两个问题 一是点击喜欢没反应 哪种情况下都不行 
console截图如下（红色部分）
![](https://cdn.jsdelivr.net/gh/Binary2101/Picbed/img/20210521233638.png)

二是导入的歌单里的歌曲版本不对
比如官方专辑里的歌曲导入后播放的是live版等等

**Comment by qier222** [comment]
第一个问题无法复现，并且有些歌曲是无法添加到喜欢的。
第二个问题请看常见问题解答 https://github.com/qier222/YesPlayMusic/issues/552
