### ISSUE TITLE
windows上按F11全屏后缩小到托盘，任务栏仍有窗口

### ISSUE THREAD

**Issue by QLFY233** [qier222/YesPlayMusic#694]
windows 10上按F11全屏后缩小到托盘，任务栏仍有窗口
![image](https://user-images.githubusercontent.com/73421931/119246260-ac0c6b80-bbb2-11eb-9239-32a3ab04fae4.png)
歌曲正常播放，这个窗口可以打开，但是界面对操作没有反应，进度条不动，快捷键无效
按托盘图标可以重新打开正常的窗口
![image](https://user-images.githubusercontent.com/73421931/119246344-63a17d80-bbb3-11eb-930f-0458ed73061b.png)

**Comment by memorydream** [comment]
目前的最新版本没有发现这个问题，我认为这已经被修复了
