### ISSUE TITLE
网页版播放完一首歌就停止播放了

### ISSUE THREAD

**Issue by princeliuyuyu** [qier222/YesPlayMusic#696]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by qier222** [comment]
第二首歌是不是灰色歌曲？

**Comment by princeliuyuyu** [comment]
> 第二首歌是不是灰色歌曲？

不是，我用手机浏览器播放，播放完一首歌就停止

**Comment by uxyyy** [comment]
> 第二首歌是不是灰色歌曲？

我也是这样，播完一首就停了

**Comment by uxyyy** [comment]
> > 第二首歌是不是灰色歌曲？
> 
> 不是，我用手机浏览器播放，播放完一首歌就停止

xd找到解决方法了吗

**Comment by princeliuyuyu** [comment]
> > > 第二首歌是不是灰色歌曲？
> > 
> > 
> > 不是，我用手机浏览器播放，播放完一首歌就停止
> 
> xd找到解决方法了吗

没有，我没有任何办法

**Comment by qier222** [comment]
这个没办法复现。目前只专注做桌面端，不考虑移动端兼容问题。
