### ISSUE TITLE
macos 0.3.8版本状态栏显示bug

### ISSUE THREAD

**Issue by m174460635** [qier222/YesPlayMusic#697]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 0.3.8 feat: add song title translate (#691) Build / Release #322
- macos
![image](https://user-images.githubusercontent.com/20900457/119429119-cb390380-bd40-11eb-9555-15cf3b4e66b2.png)

**Comment by qier222** [comment]
已修复
