### ISSUE TITLE
[Feature Request] 关于歌曲播放界面歌词栏滚动的建议

### ISSUE THREAD

**Issue by MrAru** [qier222/YesPlayMusic#698]
目前在歌曲播放界面, 通过鼠标滚轮对歌词进行上下滑动时的体验较差. 目前的情况似乎是只有当鼠标落于歌词上方时 (此时该行歌词被高亮显示) 才会监听滚轮事件

![image](https://user-images.githubusercontent.com/26517155/119492272-72458b80-bd91-11eb-9537-e4f3322ec5fc.png)

因此很多时候为了滚动歌词, 需要先刻意调整鼠标, 将鼠标放置于能使某行歌词高亮的位置, 再滑动鼠标滚轮. 而一旦该操作完成, 由于歌词栏已滚动, 鼠标大概率又会落在非高亮区域, 因此又需要重新进行上述过程. 这导致在该界面滚动歌词时的使用体验较差. 是否可以考虑将鼠标滚轮事件的监听范围扩大至整个右侧的歌词栏 ?

![image](https://user-images.githubusercontent.com/26517155/119493139-77570a80-bd92-11eb-95e5-8cc1cfe4ff1d.png)

Environments info:
OS: Arch Linux
Yesplaymusic version: 0.3.8
Electron version: 12.0.7

**Comment by MrAru** [comment]
UPDATE:
![image](https://user-images.githubusercontent.com/26517155/119763066-6cf75680-bee1-11eb-833a-261ccf488e99.png)
在更新至 Ver. 0.3.9 版本后, 每行歌词上有了 18 px 的 padding, 该问题已基本解决. 此 Issue 将关闭.

**Comment by qier222** [comment]
> UPDATE:
> 
> ![image](https://user-images.githubusercontent.com/26517155/119763066-6cf75680-bee1-11eb-833a-261ccf488e99.png)
> 
> 在更新至 Ver. 0.3.9 版本后, 每行歌词上有了 18 px 的 padding, 该问题已基本解决. 此 Issue 将关闭.

这个padding一直都有吧🤔

**Comment by MrAru** [comment]
> 这个padding一直都有吧

似乎是的, 但是在之前的版本里这个 padding 的宽度和长度完全和歌词本身一致 (从使用体验上而言, 我没有仔细确认), 因此哪怕鼠标偏移一点也需要重新移动鼠标来定位. 现在的 padding 样式则正好可以填充掉上下两行歌词之间的空隙.
