### ISSUE TITLE
-Feature Request- 希望在歌曲播放界面、首页播放栏上添加收藏按钮

### ISSUE THREAD

**Issue by LTHPKBTE** [qier222/YesPlayMusic#699]
如题。希望就在喜欢旁边就可以了，平常不怎么用喜欢，一直是分类收藏歌曲的，加上之后收藏就不用去歌单里右键收藏了。

**Comment by qier222** [comment]
不考虑在界面上增加收藏按钮，不过之后会支持右键弹出菜单，弹出菜单会有收藏按钮。
