### ISSUE TITLE
Mac 0.3.9 版本 桌面歌词不会浮动在最前

### ISSUE THREAD

**Issue by mgxnore** [qier222/YesPlayMusic#701]
Mac 版桌面歌词不会浮动在最前，切换到别的应用就会被挡住。Windows 版的倒是可以浮动在最前。希望可以修复 Mac 版的问题。

**Comment by qier222** [comment]
将在在下一版本移除桌面歌词，所以并不会修复此类bug，相关讨论可以在 issue #782 查看
