### ISSUE TITLE
Windows桌面歌词最大化后若还原会出现黑边

### ISSUE THREAD

**Issue by Scorpio-hk** [qier222/YesPlayMusic#703]
![Snipaste_2021-05-25_21-23-02](https://user-images.githubusercontent.com/59406087/119505559-a9bb3480-bd9f-11eb-996e-b4b0ad564576.png)
😹 感觉有点吹毛求疵了

**Comment by FGBWZY** [comment]
- 同出现黑边
- 但是我的桌面还会跑😂️ 往左边/左上/上面跑，跑一段时间就不跑了，不知道是啥原因
![2021 5 25](https://user-images.githubusercontent.com/67892283/119523413-518c2e80-bdaf-11eb-8838-4aa36a3b29f4.GIF)

**Comment by qier222** [comment]
将在在下一版本移除桌面歌词，所以并不会修复此类bug，相关讨论可以在 issue #782 查看
