### ISSUE TITLE
桌面歌词出现不同步

### ISSUE THREAD

**Issue by HopeLight** [qier222/YesPlayMusic#706]
### 反馈 bug 需要的信息

PC客户端
YesPlayMusic-0.3.9.exe
在桌面歌词上，有的歌曲会出现严重的不同步

**Comment by iujmnb98** [comment]
好像桌面歌词有0.5秒左右的延迟

**Comment by HopeLight** [comment]
> 好像桌面歌词有0.5秒左右的延迟

确实，是有这个问题，我测试了三遍，用了不同的歌曲，那个歌词还是会慢。

**Comment by qier222** [comment]
将在在下一版本移除桌面歌词，所以并不会修复此类bug，相关讨论可以在 issue #782 查看
