### ISSUE TITLE
播放无声音

### ISSUE THREAD

**Issue by coldrook** [qier222/YesPlayMusic#711]
0.3.8-0.3.9播放无声音

**Comment by coldrook** [comment]
msi-z490i主板自带声卡
youtube等流媒体及listen1软件播放正常
yesplaymusic0.3.8开始播放无声音，切换音频输出无效

**Comment by qier222** [comment]
这个我没办法复现

**Comment by coldrook** [comment]
> 这个我没办法复现

已经搞定，路由或yesplaymusic关闭unlockneteasemusic
