### ISSUE TITLE
桌面歌词非常好，略有小瑕疵

### ISSUE THREAD

**Issue by inoton** [qier222/YesPlayMusic#713]
正在使用 YesPlayMusic appimage格式的客户端 ，
操作系统：Fedora Linux 34 (x86_64) 
窗口环境是 GNOME,
显示协议为 wayland .
桌面歌词功能目前已可用，但有闪烁杂色边框，略影响观感，如下图

<img src="https://github.com/inoton/Bright/blob/main/yes.png?raw=true" alt="image1" width="1000" height="253">
<img src="https://github.com/inoton/Bright/blob/main/yes1.png?raw=true" alt="image2" width="1000" height="296">

感谢！

**Comment by qier222** [comment]
将在在下一版本移除桌面歌词，所以并不会修复此类bug，相关讨论可以在 issue #782 查看
