### ISSUE TITLE
能显示歌词是不错 就是歌词有点问题

### ISSUE THREAD

**Issue by kailous** [qier222/YesPlayMusic#715]
# 总算有歌词了，但是感觉仅仅是有了，并不好用。
1. 歌词不能置顶，一点别的窗口，歌词就找不到了，开启歌词就没有太多意义。
2. 歌词的背景不太美丽，建议增加一个模糊背景 透明度+模糊程度+底色的调整，或者给几个预设切换，或者有一个方便修改的配置文件，方便动手能力强的直接修改参数配置。
3. 制作一个图钉功能，把歌词钉在固定的位置，钉住的时候，鼠标可以穿透点击。不影响工作。

**Comment by qier222** [comment]
是桌面歌词还是应用内的歌词界面？

**Comment by WXRIW** [comment]
如果是Windows可以试试 [Lyricify](https://github.com/WXRIW/Lyricify-App) ，它可以提供额外的歌词支持。包括固定桌面歌词功能（鼠标可穿透）。

**Comment by kailous** [comment]
> 是桌面歌词还是应用内的歌词界面？

是桌面歌词

**Comment by qier222** [comment]
将在在下一版本移除桌面歌词，所以并不会修复此类bug，相关讨论可以在 issue #782 查看
