### ISSUE TITLE
UnblockNeteaseMusic解析无效

### ISSUE THREAD

**Issue by Yuuki-Rito** [qier222/YesPlayMusic#716]
正在使用 YesPlayMusic appimage格式的客户端 ，
操作系统：Ubuntu20.04
0.3.9，尝试了删除config下面的文件以及resetApp，UnblockNeteaseMusic还是无效，是只有我出现这情况吗
![2021-05-28 13-38-05 的屏幕截图](https://user-images.githubusercontent.com/24408875/119935651-72749f80-bfba-11eb-8c73-0d94c934d541.png)

**Comment by cqhhy2001** [comment]
0.3.8可以，升级0.3.9后我在Windows上的客户端似乎也存在这个问题

**Comment by memorydream** [comment]
没能在0.3.9 windows中复现这个问题

**Comment by cqhhy2001** [comment]
Windows上无法播放的内容直接被软件跳过了，不清楚如何提交Log？

**Comment by Yuuki-Rito** [comment]
> Windows上无法播放的内容直接被软件跳过了，不清楚如何提交Log？

看了一下请求，这应该是正常拿到数据了吧，但实际还是无法播放。至于你说的Log，是不太清楚
![2021-05-28 13-38-05 的屏幕截图](https://user-images.githubusercontent.com/24408875/120060205-fd23d000-c088-11eb-8a3b-f0b1ac007c9a.png)

![QQ截图20210529141432](https://user-images.githubusercontent.com/24408875/120060198-f1380e00-c088-11eb-8ba5-79b8c05ba837.png)

**Comment by Yuuki-Rito** [comment]
> 没能在0.3.9 windows中复现这个问题
在Windows下尝试了一下，部分是可以的，但Ubuntu下面所有灰色都不可以。看了一下请求，这应该是表示数据正常拿到了吧。
![2021-05-28 13-38-05 的屏幕截图](https://user-images.githubusercontent.com/24408875/120060255-525fe180-c089-11eb-90a7-e901c6c559c7.png)
![QQ截图20210529141432](https://user-images.githubusercontent.com/24408875/120060257-54c23b80-c089-11eb-9f92-1558c3d37c39.png)

**Comment by Yuuki-Rito** [comment]
> 没能在0.3.9 windows中复现这个问题
在Windows下尝试了一下，部分是可以的，但Ubuntu下面所有灰色都不可以。看了一下请求，这应该是表示数据正常拿到了吧。
![2021-05-28 13-38-05 的屏幕截图](https://user-images.githubusercontent.com/24408875/120060255-525fe180-c089-11eb-90a7-e901c6c559c7.png)
![QQ截图20210529141432](https://user-images.githubusercontent.com/24408875/120060257-54c23b80-c089-11eb-9f92-1558c3d37c39.png)

**Comment by Yuuki-Rito** [comment]
> 没能在0.3.9 windows中复现这个问题

在Windows下尝试了一下，部分是可以的，但Ubuntu下面所有灰色都不可以。看了一下请求，这应该是表示数据正常拿到了吧。
![QQ截图20210529141432](https://user-images.githubusercontent.com/24408875/120060419-5f310500-c08a-11eb-9c19-090ea3d62d09.png)
![2021-05-28 13-38-05 ](https://user-images.githubusercontent.com/24408875/120060422-62c48c00-c08a-11eb-8517-e884e89c7353.png)

**Comment by memorydream** [comment]
> > 没能在0.3.9 windows中复现这个问题
> 
> 在Windows下尝试了一下，部分是可以的，但Ubuntu下面所有灰色都不可以。看了一下请求，这应该是表示数据正常拿到了吧。
> ![QQ截图20210529141432](https://user-images.githubusercontent.com/24408875/120060419-5f310500-c08a-11eb-9c19-090ea3d62d09.png)
> ![2021-05-28 13-38-05 ](https://user-images.githubusercontent.com/24408875/120060422-62c48c00-c08a-11eb-8517-e884e89c7353.png)

我拿几首灰了的歌（包括你截图中的那首），感觉这个问题有些玄学，有时候能放有时候不能放，可能是没有匹配到合适的源？测试设备为windows10 和 arch linux，在此issue下所出现的歌全部可以播放

**Comment by memorydream** [comment]
> ![QQ截图20210529141432](https://user-images.githubusercontent.com/24408875/120060419-5f310500-c08a-11eb-9c19-090ea3d62d09.png)

这个数据在我的测试中为网易云的试听链接
