### ISSUE TITLE
桌面歌词自动位移

### ISSUE THREAD

**Issue by eatkid** [qier222/YesPlayMusic#721]
**环境**：
windows10 客户端
4K显示器 150%系统缩放

**问题描述**：
打开桌面歌词后歌词以约0.5s一次的速度朝屏幕左上角缓慢位移。

![u6dse-tjv26](https://user-images.githubusercontent.com/24886050/120067154-ad570000-c0ac-11eb-8b8c-de15f7de6eb5.gif)

**Comment by youlan2333** [comment]
同样问题

**Comment by qier222** [comment]
将在在下一版本移除桌面歌词，所以并不会修复此类bug，相关讨论可以在 issue #782 查看
