### ISSUE TITLE
希望客户端版可在浏览器中使用

### ISSUE THREAD

**Issue by Mark-Imaginist** [qier222/YesPlayMusic#723]
客户端默认使用的粗体微软雅黑字体和 DirectWrite 渲染在 Windows 10 下的显示效果不太好，但用浏览器直接访问 localhost:27232 白屏无法使用，希望能支持在浏览器中使用
![music qier222 com](https://user-images.githubusercontent.com/38615702/120079328-e495d300-c0e5-11eb-8a23-327e5c18ff3c.png)
![localhost_27232](https://user-images.githubusercontent.com/38615702/120079341-f24b5880-c0e5-11eb-8027-bce0a96772a8.png)
如图，分别为网页版（更纱黑体UI SC、关闭 DirectWrite）和客户端（微软雅黑）的显示效果，差别很明显
虽然是个不太影响使用的小问题，但如果能实现就更好了，非常感谢

**Comment by qier222** [comment]
可以自行更改global.scss里面的font-family属性，不过需要你自己自行编译了哦
