### ISSUE TITLE
打开 UnblockNeteaseMusic 后白屏无法使用

### ISSUE THREAD

**Issue by Mark-Imaginist** [qier222/YesPlayMusic#730]
![屏幕截图 2021-05-31 213715](https://user-images.githubusercontent.com/38615702/120202256-fc419880-c258-11eb-9a04-b69bfa5a5015.png)
![屏幕截图 2021-05-31 213615](https://user-images.githubusercontent.com/38615702/120202278-02377980-c259-11eb-8096-34a14fb6c6b5.png)
网易云音乐 UWP 可正常播放灰色歌曲，但在 YesPlayMusic 打开代理选项后一直白屏
客户端 0.3.9 
Windows 10 21H1

**Comment by pan93412** [comment]
Duplicate of #788
