### ISSUE TITLE
桌面歌词相关

### ISSUE THREAD

**Issue by Flora-air** [qier222/YesPlayMusic#735]
使用的最新版本的客户端 win10 20H2
双击桌面歌词之后还原 桌面歌词会多出一个圆角之外的切边 如图：
![image](https://user-images.githubusercontent.com/62434508/120613384-c7b42380-c488-11eb-9bf2-daa5614e33b9.png)

需要重新启动桌面歌词才可以正常圆角显示 如图
![image](https://user-images.githubusercontent.com/62434508/120613576-f3370e00-c488-11eb-86b9-05e635805603.png)

**Comment by youlan2333** [comment]
一样的问题

**Comment by qier222** [comment]
将在在下一版本移除桌面歌词，所以并不会修复此类bug，相关讨论可以在 issue #782 查看
