### ISSUE TITLE
Native wayland support for yesplaymusic with newest electron

### ISSUE THREAD

**Issue by RichardBaker3020** [qier222/YesPlayMusic#736]
Electron 12 has native wayland support, wayland support for yesplaymusic would be great because it allows for better dpi scaling.

I could actually lauch the app with some extra options:
`yesplaymusic --enable-features=UseOzonePlatform --ozone-platform=wayland`, but it didn't funcition properly like a default launch, the title bar didn't appear either.

Thanks for keeping updating this wonderful project :)

**Comment by pan93412** [comment]
We've upgraded Electron to v13.

**Comment by arcatva** [comment]
The ` --enable-features=UseOzonePlatform --ozone-platform=wayland` flags are not working with electron v13 built from aur electron-13-bin. I tried electron-29-bin and those flags worked properly.
