### ISSUE TITLE
深色主题下 Windows 通知区域（任务栏/托盘）图标右键菜单各项图标仍为黑色

### ISSUE THREAD

**Issue by Geeyun-JY3** [qier222/YesPlayMusic#740]
- 客户端版本：0.3.9
- 电脑操作系统：Windows 10 21H1 19043.1023

深色主题下 Windows 通知区域（任务栏/托盘）图标右键菜单各项图标仍为黑色，可视性较差
![image](https://user-images.githubusercontent.com/49396421/120848825-dba27700-c5a7-11eb-97c0-5ba37e43f631.png)

**Comment by memorydream** [comment]
重构托盘实现的时候顺便尝试了一下这个需求，发现electron不支持使用svg作为托盘菜单内图标，electron也没有在windows下判断背景为light还是dark的api，所以暂时应该是没有办法优化这部分的体验了

综上，我会关闭这个issue，如果你有什么相关的建议，可以继续在这个issue提问并说明
