### ISSUE TITLE
音乐无法播放

### ISSUE THREAD

**Issue by GEATB894** [qier222/YesPlayMusic#741]
打开歌单没有歌曲显示，直接点播放键也没用。升级新版本后就这样。退回去也一样了

**Comment by qier222** [comment]
麻烦提供下控制台截图

**Comment by GEATB894** [comment]
> 麻烦提供下截图

![QQ截图20210606090725](https://user-images.githubusercontent.com/78966778/120909350-c3fde800-c6a6-11eb-99eb-f2046be420b5.png)
是这个吗

**Comment by qier222** [comment]
可以根据这个方法重置客户端试试
https://github.com/qier222/YesPlayMusic/issues/552
