### ISSUE TITLE
右上角 已经显示登录头像 但是无法收藏歌单 加入我喜欢列表 提示未登录

### ISSUE THREAD

**Issue by 2465622629** [qier222/YesPlayMusic#742]
系统环境 win10 20H2
当时网络应该是正常的

**Comment by qier222** [comment]
麻烦提供下控制台截图

**Comment by 2465622629** [comment]
直接上传图片失败 就上传图床了 

https://ftp.bmp.ovh/imgs/2021/06/2141ea708ca4a7a0.png

**Comment by qier222** [comment]
按照这里方法重置客户端试试吧
https://github.com/qier222/YesPlayMusic/issues/552
