### ISSUE TITLE
悬浮歌词鼠标穿透

### ISSUE THREAD

**Issue by ding667** [qier222/YesPlayMusic#743]
希望能给悬浮歌词自定义鼠标穿透，如果能调整透明度就更好了。

**Comment by WXRIW** [comment]
可以试试 [YesPlayMusic 与 Lyricify 搭配使用方法](https://github.com/WXRIW/Lyricify-App/wiki/Lyricify-for-YesPlayMusic) 提供的外部歌词支持。

**Comment by qier222** [comment]
将在在下一版本移除桌面歌词，所以并不会修复此类bug，相关讨论可以在 issue #782 查看
