### ISSUE TITLE
Bug arm64客户端，歌曲播放进度条不会随着时间滚动

### ISSUE THREAD

**Issue by SKEETCHAN** [qier222/YesPlayMusic#745]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

歌曲播放时，进度条不会跟随时间滚动前爬；虽然可以手动拖动进度条来调整时间线，但是进度条仍然会停留原地。
动态歌词可以跟随时间对应滚动。

### 反馈 bug 需要的信息

- 客户端版本arm64
- 脑操作系统: m1 big sur 11.4
![截屏2021-06-05 下午9 13 00](https://user-images.githubusercontent.com/40740405/120893025-992e7800-c643-11eb-93b7-8b623ac3f10b.png)

**Comment by qier222** [comment]
重复的issue #729
