### ISSUE TITLE
歌词页不同屏幕自动适配已修改，但无法保存求助

### ISSUE THREAD

**Issue by RebirthEgo** [qier222/YesPlayMusic#746]
歌词页在竖屏上显示不全不能适配不同尺寸，研究了一久用CSS在控制台里修改可以实现适配，但无法保存，由于对代码不太懂求教！ 下面是修改过的参数截图。

<img width="250" alt="001" src="https://user-images.githubusercontent.com/54738173/120899371-fe916180-c661-11eb-8ea8-f692a44036c6.png">
<img width="228" alt="002" src="https://user-images.githubusercontent.com/54738173/120899373-005b2500-c662-11eb-80be-b11ebd638c64.png">
<img width="253" alt="003" src="https://user-images.githubusercontent.com/54738173/120899374-00f3bb80-c662-11eb-9797-6e29b52d7803.png">
<img width="313" alt="004" src="https://user-images.githubusercontent.com/54738173/120899375-018c5200-c662-11eb-89d4-b18b47506867.png">
<img width="542" alt="005" src="https://user-images.githubusercontent.com/54738173/120899376-018c5200-c662-11eb-8c31-dd6e406530c0.png">
<img width="1164" alt="006" src="https://user-images.githubusercontent.com/54738173/120899377-02bd7f00-c662-11eb-8f44-a33a92ca2e63.png">

**Comment by qier222** [comment]
在最新代码中已经修复了，这几天会发新版本
