### ISSUE TITLE
Windows客户端 javascript脚本报错

### ISSUE THREAD

**Issue by psychopath666** [qier222/YesPlayMusic#750]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

![屏幕截图 2021-06-07 182325](https://user-images.githubusercontent.com/60169540/121001602-09f99f80-c7be-11eb-977e-2db595a1871b.png)

![image](https://user-images.githubusercontent.com/60169540/121001564-ff3f0a80-c7bd-11eb-84c0-250a7819f2e0.png)

最新win10系统。之前一直正常使用，偶尔出现这个重启一下就行了。现在每次启动都报错，重启和重新安装都无法解决。

**Comment by Tramis** [comment]
俺也一样

**Comment by psychopath666** [comment]
更新4.0之后问题应该是解决了，现在不报错了
