### ISSUE TITLE
BUG: 私人FM播放一段时间后找不到下一首歌

### ISSUE THREAD

**Issue by memorydream** [qier222/YesPlayMusic#752]
0.3.9 客户端
win10
![image](https://user-images.githubusercontent.com/34763046/121358741-6ba83e00-c965-11eb-8eb2-51ce0999588a.png)

有些消息没有合在一起，那是我切到歌单里去放了一首歌，切歌没问题再切回FM，按下一曲后出现的

**Comment by qier222** [comment]
可以用 resetApp() 临时解决下，这个问题大概是因为加载下一首的api请求失败了
