### ISSUE TITLE
BUG：莫名其妙卡住且cpu占比超高

### ISSUE THREAD

**Issue by kevintao0417** [qier222/YesPlayMusic#754]
一开始好好的
改了个快捷键突然卡住
cpu占比到24%
重开
运行以后去浏览歌单时又卡住
音乐还在播放但无法暂停了

**Comment by kevintao0417** [comment]
win客户端
全局卡住自然调不出console

**Comment by qier222** [comment]
复现不出来，等等看其他用户有没有类似的问题吧

**Comment by kevintao0417** [comment]
> 复现不出来，等等看其他用户有没有类似的问题吧
我这里已经反复出现好几次了
和这个有关系吗
![image](https://user-images.githubusercontent.com/46237180/121381087-fc881500-c977-11eb-992f-2206575c42bc.png)

**Comment by qier222** [comment]
没有关系。
你去设置页面看一下歌曲缓存有多大

**Comment by kevintao0417** [comment]
无限制

**Comment by Lucas-TY** [comment]
![fa684ac9ee4c733d07548733bc9e36e](https://user-images.githubusercontent.com/48132189/121392648-2a725700-c982-11eb-89df-bd0d5bc59599.png)

**Comment by Lucas-TY** [comment]
安装0.4好像要卸载之前的版本，重新安装后就好了

**Comment by Lucas-TY** [comment]
当时卡顿解决后console里还是javascript报错

**Comment by Lewislou** [comment]
我也遇到类似问题，内存占用瞬间到达9000多M，然后直接死机。我是3.9用setup.exe安装的，没问题。4.0再用.exe或者setup.exe安装都有这个问题。
