### ISSUE TITLE
云盘音乐还是不能播放

### ISSUE THREAD

**Issue by SouLXH** [qier222/YesPlayMusic#759]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by SouLXH** [comment]
客户端
win10 21H1


二维码登陆无反应
![image](https://user-images.githubusercontent.com/44329481/121473633-8f1ac980-c9f5-11eb-9124-3d17f58463f2.png)
`xhr.js:177 POST http://localhost:27232/api/daily_signin?type=0&timestamp=1623305417076 400 (Bad Request)
(anonymous) @ xhr.js:177
t.exports @ xhr.js:13
t.exports @ dispatchRequest.js:52
Promise.then (async)
u.request @ Axios.js:61
(anonymous) @ bind.js:9
s @ user.js:77
m @ common.js:110
activated @ library.vue:241
re @ vue.runtime.esm.js:1854
Bn @ vue.runtime.esm.js:4219
Fn @ vue.runtime.esm.js:4192
tr @ vue.runtime.esm.js:4370
Qn @ vue.runtime.esm.js:4335
(anonymous) @ vue.runtime.esm.js:1980
le @ vue.runtime.esm.js:1906
Promise.then (async)
ae @ vue.runtime.esm.js:1933
ve @ vue.runtime.esm.js:1990
er @ vue.runtime.esm.js:4402
rr.update @ vue.runtime.esm.js:4544
yt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
(anonymous) @ vue-router.esm.js:2989
(anonymous) @ vue-router.esm.js:2988
ee.updateRoute @ vue-router.esm.js:2409
(anonymous) @ vue-router.esm.js:2263
(anonymous) @ vue-router.esm.js:2397
r @ vue-router.esm.js:2001
r @ vue-router.esm.js:2008
Ft @ vue-router.esm.js:2012
(anonymous) @ vue-router.esm.js:2392
r @ vue-router.esm.js:2001
(anonymous) @ vue-router.esm.js:2005
(anonymous) @ vue-router.esm.js:2379
(anonymous) @ vue-router.esm.js:2127
(anonymous) @ vue-router.esm.js:2203
Promise.then (async)
(anonymous) @ vue-router.esm.js:2150
(anonymous) @ vue-router.esm.js:2171
(anonymous) @ vue-router.esm.js:2171
Xt @ vue-router.esm.js:2170
(anonymous) @ vue-router.esm.js:2106
h @ vue-router.esm.js:2357
r @ vue-router.esm.js:2004
r @ vue-router.esm.js:2008
(anonymous) @ vue-router.esm.js:2005
(anonymous) @ vue-router.esm.js:2379
(anonymous) @ Scrollbar.vue:58
h @ vue-router.esm.js:2357
r @ vue-router.esm.js:2004
(anonymous) @ vue-router.esm.js:2005
(anonymous) @ vue-router.esm.js:2379
(anonymous) @ index.js:155
h @ vue-router.esm.js:2357
r @ vue-router.esm.js:2004
r @ vue-router.esm.js:2008
Ft @ vue-router.esm.js:2012
ee.confirmTransition @ vue-router.esm.js:2387
ee.transitionTo @ vue-router.esm.js:2260
e.push @ vue-router.esm.js:2704
(anonymous) @ vue-router.esm.js:3020
we.push @ vue-router.esm.js:3019
Te.a.push @ index.js:141
(anonymous) @ loginAccount.vue:221
Promise.then (async)
(anonymous) @ loginAccount.vue:220
Promise.then (async)
handleLoginResponse @ loginAccount.vue:219
Promise.then (async)
login @ loginAccount.vue:191
keyup @ loginAccount.vue?c81a:1
re @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
i._wrapper @ vue.runtime.esm.js:6917
xhr.js:177 POST http://localhost:27232/api/daily_signin?type=1&timestamp=1623305417076 400 (Bad Request)`

**Comment by SouLXH** [comment]
云盘音乐无法播放

`undefined:1 GET http://localhost:27232/undefined?param=1024y1024 404 (Not Found)
Image (async)
e.load @ browser.js:76
t.getPalette @ vibrant.js:58
t.getPalette @ builder.js:57
getCoverColor @ lyrics.vue:378
created @ lyrics.vue:306
re @ vue.runtime.esm.js:1854
Bn @ vue.runtime.esm.js:4219
t._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
an @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
h @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6477
In.t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
rr.get @ vue.runtime.esm.js:4479
rr @ vue.runtime.esm.js:4468
Rn @ vue.runtime.esm.js:4073
Or.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
h @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
j @ vue.runtime.esm.js:6216
T @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
rr.get @ vue.runtime.esm.js:4479
rr.run @ vue.runtime.esm.js:4554
Qn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
le @ vue.runtime.esm.js:1906
Promise.then (async)
ae @ vue.runtime.esm.js:1933
ve @ vue.runtime.esm.js:1990
er @ vue.runtime.esm.js:4402
rr.update @ vue.runtime.esm.js:4544
yt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
set @ index.js:53
value @ Player.js:537
(anonymous) @ Player.js:564
Promise.then (async)
value @ Player.js:562
playThisListDefault @ TrackList.vue:214
playThisList @ TrackList.vue:194
dblclick @ TrackList.vue?d484:1
re @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
i._wrapper @ vue.runtime.esm.js:6917
Show 3 more frames
browser.js:97 Uncaught (in promise) Error: Fail to load image: undefined?param=1024y1024
    at HTMLImageElement.n.complete.n.onerror (browser.js:97)
n.complete.n.onerror @ browser.js:97
Promise.then (async)
getCoverColor @ lyrics.vue:379
created @ lyrics.vue:306
re @ vue.runtime.esm.js:1854
Bn @ vue.runtime.esm.js:4219
t._init @ vue.runtime.esm.js:5008
a @ vue.runtime.esm.js:5154
an @ vue.runtime.esm.js:3283
init @ vue.runtime.esm.js:3114
h @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6477
In.t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
rr.get @ vue.runtime.esm.js:4479
rr @ vue.runtime.esm.js:4468
Rn @ vue.runtime.esm.js:4073
Or.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
h @ vue.runtime.esm.js:5978
d @ vue.runtime.esm.js:5925
j @ vue.runtime.esm.js:6216
T @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
In.t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
rr.get @ vue.runtime.esm.js:4479
rr.run @ vue.runtime.esm.js:4554
Qn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
le @ vue.runtime.esm.js:1906
Promise.then (async)
ae @ vue.runtime.esm.js:1933
ve @ vue.runtime.esm.js:1990
er @ vue.runtime.esm.js:4402
rr.update @ vue.runtime.esm.js:4544
yt.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
set @ index.js:53
value @ Player.js:537
(anonymous) @ Player.js:564
Promise.then (async)
value @ Player.js:562
playThisListDefault @ TrackList.vue:214
playThisList @ TrackList.vue:194
dblclick @ TrackList.vue?d484:1
re @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
i._wrapper @ vue.runtime.esm.js:6917
dexie.mjs:1270 Unhandled rejection: TypeError: Cannot read property '0' of undefined
    at h (app://./js/index.1fd6dcf5.js:1:119332)
    at app://./js/index.1fd6dcf5.js:1:29078
From previous: 
    at qt.n (app://./js/chunk-vendors.7efa24f0.js:45:61311)
    at Proxy.value (app://./js/index.1fd6dcf5.js:1:29683)
    at app://./js/index.1fd6dcf5.js:1:30283
    at app://./js/chunk-vendors.7efa24f0.js:45:68522
    at Qt (app://./js/chunk-vendors.7efa24f0.js:45:62723)
    at ne (app://./js/chunk-vendors.7efa24f0.js:45:63390)
    at IDBTransaction.<anonymous> (app://./js/chunk-vendors.7efa24f0.js:45:64044)
From previous: 
    at qt.n (app://./js/chunk-vendors.7efa24f0.js:45:61311)
    at Proxy.value (app://./js/index.1fd6dcf5.js:1:28653)
    at Proxy.value (app://./js/index.1fd6dcf5.js:1:29644)
    at app://./js/index.1fd6dcf5.js:1:30283
    at app://./js/chunk-vendors.7efa24f0.js:45:68522
    at Qt (app://./js/chunk-vendors.7efa24f0.js:45:62723)
    at ne (app://./js/chunk-vendors.7efa24f0.js:45:63390)
    at IDBTransaction.<anonymous> (app://./js/chunk-vendors.7efa24f0.js:45:64044)
From previous: 
    at qt.n (app://./js/chunk-vendors.7efa24f0.js:45:61311)
    at m (app://./js/index.1fd6dcf5.js:1:119918)
    at Proxy.value (app://./js/index.1fd6dcf5.js:1:28649)
    at Proxy.value (app://./js/index.1fd6dcf5.js:1:29644)
    at app://./js/index.1fd6dcf5.js:1:30283
    at app://./js/chunk-vendors.7efa24f0.js:45:68522
    at Qt (app://./js/chunk-vendors.7efa24f0.js:45:62723)
    at ne (app://./js/chunk-vendors.7efa24f0.js:45:63390)
From previous: 
    at qt.n (app://./js/chunk-vendors.7efa24f0.js:45:61311)
    at Object.t.get (app://./js/chunk-vendors.7efa24f0.js:45:70965)
    at m (app://./js/index.1fd6dcf5.js:1:119903)
    at Proxy.value (app://./js/index.1fd6dcf5.js:1:28649)
    at Proxy.value (app://./js/index.1fd6dcf5.js:1:29644)
    at app://./js/index.1fd6dcf5.js:1:30283
    at app://./js/chunk-vendors.7efa24f0.js:45:68522
    at Qt (app://./js/chunk-vendors.7efa24f0.js:45:62723)
From previous: 
    at qt.n (app://./js/chunk-vendors.7efa24f0.js:45:61311)
    at Ce (app://./js/chunk-vendors.7efa24f0.js:45:69448)
    at Object.t._trans (app://./js/chunk-vendors.7efa24f0.js:45:70697)
    at Object.t.get (app://./js/chunk-vendors.7efa24f0.js:45:70845)
    at m (app://./js/index.1fd6dcf5.js:1:119903)
    at Proxy.value (app://./js/index.1fd6dcf5.js:1:28649)
    at Proxy.value (app://./js/index.1fd6dcf5.js:1:29644)
    at app://./js/index.1fd6dcf5.js:1:30283
From previous: 
    at Object.t._promise (app://./js/chunk-vendors.7efa24f0.js:45:94682)
    at Ce (app://./js/chunk-vendors.7efa24f0.js:45:69367)
    at Object.t._trans (app://./js/chunk-vendors.7efa24f0.js:45:70697)
    at Object.t.get (app://./js/chunk-vendors.7efa24f0.js:45:70845)
    at m (app://./js/index.1fd6dcf5.js:1:119903)
    at Proxy.value (app://./js/index.1fd6dcf5.js:1:28649)
    at Proxy.value (app://./js/index.1fd6dcf5.js:1:29644)
    at app://./js/index.1fd6dcf5.js:1:30283
Ee @ dexie.mjs:1270
(anonymous) @ dexie.mjs:1033
re @ dexie.mjs:1032
(anonymous) @ dexie.mjs:928
ne @ dexie.mjs:1022
te @ dexie.mjs:1005
Promise.then (async)
(anonymous) @ dexie.mjs:606
Mt @ dexie.mjs:623
Yt @ dexie.mjs:926
Gt @ dexie.mjs:912
Xt @ dexie.mjs:939
Yt @ dexie.mjs:920
Gt @ dexie.mjs:912
Xt @ dexie.mjs:939
Yt @ dexie.mjs:920
Gt @ dexie.mjs:912
Xt @ dexie.mjs:939
Yt @ dexie.mjs:920
Gt @ dexie.mjs:912
Promise.then (async)
(anonymous) @ dexie.mjs:874
Wt @ dexie.mjs:864
(anonymous) @ dexie.mjs:871
Qt @ dexie.mjs:959
ne @ dexie.mjs:1022
(anonymous) @ dexie.mjs:1081`
![image](https://user-images.githubusercontent.com/44329481/121473947-f59fe780-c9f5-11eb-9eec-ff33bbaac672.png)
 前两个post是登陆 后面是播放

**Comment by lethefrost** [comment]
我更新4.0之前是云盘全都无法播放，现在是部分云盘歌曲无法播放，大致看了一圈，好像原本没有封面没有专辑和歌手等信息的就无法播放，但可以加载出时长，仅有歌手没有其他信息的连时长都加载不出来（不太确定这个观察是否正确，仅供参考）不太清楚为什么。这些曲子源文件应该没问题？我在网易官方客户端试了下都可以播放。谢谢～q大辛苦啦

**Comment by SouLXH** [comment]
> 我更新4.0之前是云盘全都无法播放，现在是部分云盘歌曲无法播放，大致看了一圈，好像原本没有封面没有专辑和歌手等信息的就无法播放，但可以加载出时长，仅有歌手没有其他信息的连时长都加载不出来（不太确定这个观察是否正确，仅供参考）不太清楚为什么。这些曲子源文件应该没问题？我在网易官方客户端试了下都可以播放。谢谢～q大辛苦啦

原本没有封面没有专辑和歌手等信息的歌就是网易服务器里面没有的歌，能识别出来的就是之前上架过网易的歌，上架过的歌有一个唯一的识别码，服务器会根据识别码自动匹配各种信息，然后类似百度云盘MD5识别直接秒传也就是播放链接实际是网易自己的不是你上传上的。。。。。。。

**Comment by lethefrost** [comment]
> > 我更新4.0之前是云盘全都无法播放，现在是部分云盘歌曲无法播放，大致看了一圈，好像原本没有封面没有专辑和歌手等信息的就无法播放，但可以加载出时长，仅有歌手没有其他信息的连时长都加载不出来（不太确定这个观察是否正确，仅供参考）不太清楚为什么。这些曲子源文件应该没问题？我在网易官方客户端试了下都可以播放。谢谢～q大辛苦啦
> 
> 原本没有封面没有专辑和歌手等信息的歌就是网易服务器里面没有的歌，能识别出来的就是之前上架过网易的歌，上架过的歌有一个唯一的识别码，服务器会根据识别码自动匹配各种信息，然后类似百度云盘MD5识别直接秒传也就是播放链接实际是网易自己的不是你上传上的。。。。。。。

原来是这样，谢谢科普😳

**Comment by qier222** [comment]
0.4.1版已修复
