### ISSUE TITLE
新版本音乐放一段时间就会卡死，要重启才可以继续播放，感谢加入灰色音乐使用非常不错！！！

### ISSUE THREAD

**Issue by RebirthEgo** [qier222/YesPlayMusic#76]

**Comment by njzydark** [comment]
这个问题已修复 急用的话可以试一下我自己打包的 https://github.com/njzydark/YesPlayMusic/actions/runs/403704545

**Comment by RebirthEgo** [comment]
> 这个问题已修复急用的话可以试一下我自己打包的https://github.com/njzydark/YesPlayMusic/actions/runs/403704545

好的谢谢
