### ISSUE TITLE
0.4.0 扫码登录，一直卡在正在登录中，用邮箱登录成功后，右上角还是显示登录

### ISSUE THREAD

**Issue by StevenZhang1125** [qier222/YesPlayMusic#760]
win10 pc端软件 
![image](https://user-images.githubusercontent.com/11782151/121477732-cc358a80-c9fa-11eb-8d9e-1498455e4c38.png)
![image](https://user-images.githubusercontent.com/11782151/121477953-099a1800-c9fb-11eb-8ccc-02958540d761.png)

**Comment by qier222** [comment]
重复的issue #757 
重启下客户端就正常了，下个版本会修复这个问题

**Comment by YuanfengZhang** [comment]
> 重复的issue #757
> 重启下客户端就正常了，下个版本会修复这个问题

很抱歉再次在这里评论，但是下载4.0版本后也遇到了同样的问题，重启客户端、重启Win10系统、更新代理设置均无效。扫码后永远停留在“登录成功，请稍等...”

**Comment by oubeichen** [comment]
一样的卡在这个界面，MacOS Universal 版

**Comment by mochounan** [comment]
linux 也是这种情况
