### ISSUE TITLE
[BUG]登陆状态错误

### ISSUE THREAD

**Issue by SouLXH** [qier222/YesPlayMusic#762]
客户端
WIn1021H1

经测试网页版登陆后 右上角图片可文字可以正常加载出来，客户端不可以。
![image](https://user-images.githubusercontent.com/44329481/121487129-5df5c580-ca04-11eb-9e8b-80886f064912.png)
![image](https://user-images.githubusercontent.com/44329481/121487190-6e0da500-ca04-11eb-957e-a478c5007c7e.png)
一图是客户端 二图是网页端
登陆方式均是手机号登陆，报错在上一个lssue上有贴出来。

**Comment by pan93412** [comment]
應已在新版解決。
