### ISSUE TITLE
win10安装版，有时候听着听着就不知道怎么就停了（可能是听不了或者怎么了），就卡在那一首了，不能自动切换

### ISSUE THREAD

**Issue by Anoxia77** [qier222/YesPlayMusic#763]
# 有些歌曲放不了后直接就停止播放了，但是播放按钮是
![image](https://user-images.githubusercontent.com/49194603/121493094-0f4b2a00-ca0a-11eb-8a40-82cfedae77e1.png)
开着的，进度条没有走

**Comment by SouLXH** [comment]
你现在的问是我上个版本（0.3.9）的问题，更新到0.4.0我没有这些问题了，上个版本都没法使用，自动停了啥的经常出现，这个版本完美已经使用两个小时没出播放问题了，，，，就是云盘音乐似乎解析有问题？有的无法播放 有的等五六七八秒就可以播放了

**Comment by Anoxia77** [comment]
可能是的，但是好像无法播放后也没办法自动切换，我今天早上下载的0.4.0,然后使用的时候还有会有那个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月10日(星期四) 下午5:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qier222/YesPlayMusic] win10安装版，有时候听着听着就不知道怎么就停了（可能是听不了或者怎么了），就卡在那一首了，不能自动切换 (#763)





 
你现在的问是我上个版本（0.3.9）的问题，更新到0.4.0我没有这些问题了，上个版本都没法使用，自动停了啥的经常出现，这个版本完美已经使用两个小时没出播放问题了，，，，就是云盘音乐似乎解析有问题？有的无法播放 有的等五六七八秒就可以播放了

**Comment by 462051887** [comment]
+1

**Comment by FGBWZY** [comment]
+1

**Comment by ajian2002** [comment]
+1 v4.0 突然停下
