### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by SouLXH** [qier222/YesPlayMusic#768]
客户端
WIN1021H1
![image](https://user-images.githubusercontent.com/44329481/121622610-e75ad580-caa0-11eb-9893-994cd4f9bd37.png)
 暂停一段时间后  桌面歌词直接挂了，无法继续同步歌词，切歌也无效，应该是Lyricify的bug
![image](https://user-images.githubusercontent.com/44329481/121622665-fa6da580-caa0-11eb-8588-1c26e8858ee0.png)
然后客服端F12报错，

**Comment by SouLXH** [comment]
我提出了这么多BUG，是想让yesplaymusic越来越好，希望开发者坚持住，多好的播放软件。

**Comment by qier222** [comment]
桌面歌词在最新代码中已经被移除了，所以不会修复相关的bug

**Comment by SouLXH** [comment]
> 桌面歌词在最新代码中已经被移除了，所以不会修复相关的bug

别移除啊，挺好的，虽然不完美。
