### ISSUE TITLE
支持音乐云盘 是网易云的那个云盘嘛？

### ISSUE THREAD

**Issue by wowmacro** [qier222/YesPlayMusic#773]
支持音乐云盘 是网易云的那个云盘嘛？

**Comment by wowmacro** [comment]
我云盘里上传存的歌 好像还不能播呀。是因为文件名太长了嘛？
![Uploading 微信截图_20210612064001.jpg…]()

**Comment by wowmacro** [comment]
![微信截图_20210612064001](https://user-images.githubusercontent.com/7532385/121755303-69063e00-cb49-11eb-8b2d-ea6f6e1b8e8f.jpg)

**Comment by SouLXH** [comment]
就是支持的是网易云盘，但是现在播放有问题，需要加载一段时间才能播放

**Comment by wowmacro** [comment]
> 就是支持的是网易云盘，但是现在播放有问题，需要加载一段时间才能播放

我试着丢在那里不管它。2个小时了。也没加载出来。。可不可以遇到这种1分钟加载不出来就自动跳过呀。不然这就一直卡在那。。

**Comment by wowmacro** [comment]
能支持云盘真的挺好的。
我喜欢的翻唱版都在我的网易云盘上。
