### ISSUE TITLE
桌面歌词渐变和切换歌曲时卡顿

### ISSUE THREAD

**Issue by maxelblack** [qier222/YesPlayMusic#778]
桌面歌词在渐变到下一句和切换歌曲时渐变动画十分卡顿，如下面截图这样的效果有时会一直不变持续半秒以上（也有同另一issue的杂边问题）

![image](https://user-images.githubusercontent.com/61044187/121777023-95aa6c00-cbc2-11eb-89b3-7d26db354c5f.png)

- 桌面环境是 Arch Linux 上的 Plasma 5.22 ，运行在 X11 Display Server 。
- 用的是客户端最新版本（0.4.0）

**Comment by qier222** [comment]
将在在下一版本移除桌面歌词，所以并不会修复此类bug，相关讨论可以在 issue #782 查看
