### ISSUE TITLE
OSD 桌面歌詞功能是否計畫移除?

### ISSUE THREAD

**Issue by lekoOwO** [qier222/YesPlayMusic#782]
在 https://github.com/qier222/YesPlayMusic/commit/caaf62ea20fc556d3a10bf2abba59c8ea15f6b42 中看到了移除 OSD 桌面歌詞的 commit，請問是否計畫移除桌面歌詞功能?

桌面歌詞一直是我很依賴的核心功能之一，希望能保留，謝謝。

**Comment by qier222** [comment]
是的，已经移除了。经过思考还是决定不加桌面歌词，个人觉得桌面歌词并不是个很好的展现歌词的方式，会挡住用户屏幕上的内容且容易吸引注意力。

**Comment by youlan2333** [comment]
> 是的，已经移除了。经过思考还是决定不加桌面歌词，个人觉得桌面歌词并不是个很好的展现歌词的方式，会挡住用户屏幕上的内容且容易吸引注意力。

我觉得还是保留桌面歌词的功能好一点，部分用户包括我依賴使用它，我们可以在设置中增加开启/关闭选项，并告知这是实验性的，您看如何？

**Comment by shih-liang** [comment]
我是桌面歌词功能的作者，我在 [link](https://github.com/shih-liang/YesPlayMusicOSD ) 维护了一个带有桌面歌词的版本，欢迎来试试~
