### ISSUE TITLE
音乐库中没有云盘

### ISSUE THREAD

**Issue by chen310** [qier222/YesPlayMusic#787]
1. 使用edge浏览器没有扫码登录这一选项，chrome浏览器就有
2. 使用chrome浏览器扫码登录后实际上并没有登录成功
3. edge浏览器登陆后音乐库中没有云盘这一项，而chrome浏览器登陆后则有
![msedge_Vn6QUdnAbm](https://user-images.githubusercontent.com/33364396/121976376-43ca3780-cdb6-11eb-8cd3-60c2ce8f27e4.png)

**Comment by qier222** [comment]
浏览器缓存，建议下载客户端用
