### ISSUE TITLE
m1 Mac安装之后提示软件损坏

### ISSUE THREAD

**Issue by Fred-supre** [qier222/YesPlayMusic#794]
### 我使用的是M1芯片的Mac
- 下载release中的`YesPlayMusic-mac-0.4.0-arm64.dmg`包并安装之后点开软件会提示：
> “YesPlayMusic”已损坏，无法打开。 您应该将它移到废纸篓。

- 如果下载安装`YesPlayMusic-mac-0.4.0-universal.dmg`可以正常运行

**Comment by FXNanN** [comment]
M1芯片的Mac运行时提示已损坏怎么办？
安装YesPlayMusic后，在终端里执行 xattr -r -d com.apple.quarantine /Applications/YesPlayMusic.app 就可以了。 #297 (comment)
