### ISSUE TITLE
登录Bug

### ISSUE THREAD

**Issue by RoyRao2333** [qier222/YesPlayMusic#795]
# Bug

0.4.0版本支持扫码登录后，在进行扫码后，会一直显示”登陆成功，请稍等“，等了很久都没有进去。
![image](https://user-images.githubusercontent.com/31413093/122142372-ea2f3f00-ce81-11eb-828c-c75f090bfda3.png)

此时如果改用邮箱登录，那么的确可以进入Library，但是右上角的头像会显示未登录。
<img width="1066" alt="Screen Shot" src="https://user-images.githubusercontent.com/31413093/122142281-b6ecb000-ce81-11eb-9b99-de5a476eb77c.png">

- 客户端 (0.4.0)
- macOS 11.4
- 控制台 Console 页面的截图（报错）：

![image](https://user-images.githubusercontent.com/31413093/122142246-9e7c9580-ce81-11eb-9c47-69a22bc43bf8.png)
![image](https://user-images.githubusercontent.com/31413093/122142315-ca981680-ce81-11eb-9e88-420a2ed8e259.png)

**Comment by BaconKwan** [comment]
登陆出问题了

**Comment by ceabqw** [comment]
我这也一样,邮箱扫码都不行
![image](https://user-images.githubusercontent.com/83302491/123169588-5552b580-d42e-11eb-9363-8af8dc38f617.png)
怀疑是这个

**Comment by RoyRao2333** [comment]
> 我这也一样,邮箱扫码都不行
> ![image](https://user-images.githubusercontent.com/83302491/123169588-5552b580-d42e-11eb-9363-8af8dc38f617.png)
> 怀疑是这个

大概率了，UserID获取不到吧可能，等待修复咯

**Comment by sherlocksho** [comment]
我也是，无法通过扫玛登陆，但手机号登陆正常
![Uploading 2021-07-03 23-03-41 的屏幕截图.png…]()

**Comment by Brannua** [comment]
1. 关闭 yesplaymusic 设置中的 UnblockNeteaseMusic 功能

**Comment by Brannua** [comment]
我下面这样做登陆成功了，供朋友们参考。
1. 关闭 yesplaymusic 设置中的 UnblockNeteaseMusic 功能
2. 注册网易邮箱（如果没有），并在手机端网易云音乐app中，让自己的帐号绑定网易邮箱
3. 重启 yesplaymusic，使用网易邮箱登陆

**Comment by qier222** [comment]
0.4.1版已修复
