### ISSUE TITLE
F12无法打开DevTools

### ISSUE THREAD

**Issue by TheresaQWQ** [qier222/YesPlayMusic#798]
- 客户端
- Win 10 20H2
- 就是打不开DevTools
按F12会出现如下图所示的报错
![image](https://user-images.githubusercontent.com/22370654/122340616-12e43100-cf75-11eb-9296-9f1d26863871.png)

**Comment by wk989898** [comment]
同报错，但是可以打开。
https://github.com/qier222/YesPlayMusic/blob/89d346b2ffa09bc1b60fff605a6b03924adb1eda/src/electron/menu.js#L186-L191
