### ISSUE TITLE
0.4.0版本 自定义快捷键 报错

### ISSUE THREAD

**Issue by xieincz** [qier222/YesPlayMusic#799]
- 用的是网页版还是客户端
- 客户端0.4.0
- 浏览器名称或电脑操作系统
- win10 19043.1055
- 控制台 Console 页面的截图（按 F12 可打开控制台）
![image](https://user-images.githubusercontent.com/39424496/122538078-ca05a880-d058-11eb-87e7-d7f4f700534d.png)
![image](https://user-images.githubusercontent.com/39424496/122538260-f3becf80-d058-11eb-948f-a8e4c461a1eb.png)

**Comment by qier222** [comment]
0.4.1已修复
