### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by updater1234** [qier222/YesPlayMusic#800]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

可否在安装程序中添加一个安装位置的选项，让用户自行决定软件安装的位置。我感觉这个功能应该不难实现。

**Comment by inoton** [comment]
1. Windows 右键解压到你要的目录，解决。
2. Linux用 appimage ,放到家目录，解决。

**Comment by updater1234** [comment]
OK
