### ISSUE TITLE
右下角没有歌曲显示

### ISSUE THREAD

**Issue by sorrowfeng** [qier222/YesPlayMusic#802]
- 建议在右下角图标处加上歌曲名称显示功能, 当鼠标悬停在图标上时, 只会显示YesPlayMusic,  要是能显示歌曲名称就好了.
![image](https://user-images.githubusercontent.com/61925560/122698594-31e70980-d27a-11eb-87f2-1a514e03ea77.png)

- 最小化功能, 能不能将软件从任务栏隐藏, 再从右下角打开

**Comment by memorydream** [comment]
> * 最小化功能, 能不能将软件从任务栏隐藏, 再从右下角打开

设置-最小化到托盘

**Comment by qier222** [comment]
暂时没有计划做这个功能
