### ISSUE TITLE
[Feature] 支持无缝播放

### ISSUE THREAD

**Issue by FrzMtrsprt** [qier222/YesPlayMusic#806]
希望能添加对无缝播放的支持，有些专辑里的歌曲是连续的，歌曲之间的停顿有些影响体验

**Comment by pan93412** [comment]
Duplicate of #264

**Comment by ChromaPIE** [comment]
#264 的描述失准。淡出淡入和无缝播放是两种概念。现在移动端官方的网易云音乐已经实现了无缝播放，但pc端没有这个特性。随便找了一个视频：https://www.bilibili.com/video/BV1XY41137GR
