### ISSUE TITLE
👍 好应用，已收录，感谢开发者！

### ISSUE THREAD

**Issue by macwkcom** [qier222/YesPlayMusic#807]
![image](https://user-images.githubusercontent.com/53843550/122954534-1a12a100-d3b2-11eb-8d06-b477b679e595.png)

[收录地址](https://www.macwk.com/soft/yesplaymusic)

因为并不是所有开发者都需要被宣传，如果开发者觉得不合适，回复我一下，我把它下掉，抱歉，有些先斩后奏了。🥰

**Comment by long2ice** [comment]
@macwkcom 老哥，你这网站PV应该挺高吧，也没有广告，仅靠捐赠盈利吗

**Comment by macwkcom** [comment]
> @macwkcom 老哥，你这网站PV应该挺高吧，也没有广告，仅靠捐赠盈利吗

是啊，非盈利性网站。
