### ISSUE TITLE
无法自动播放下一首

### ISSUE THREAD

**Issue by TheLastGreenseer** [qier222/YesPlayMusic#813]
Windows 10 客户端
![Screenshot 2021-06-24 213424](https://user-images.githubusercontent.com/73424266/123272573-73a2d900-d534-11eb-8888-4bda6ded2b5b.png)
![Screenshot 2021-06-24 213331](https://user-images.githubusercontent.com/73424266/123272579-743b6f80-d534-11eb-9e1f-0199dbbd64d3.png)
无论后台还是前台播放都会出现同样的问题
卡住时进度条时长显示为歌曲时长+1秒
切换上下首尚正常，但点击进度条便会把卡住的歌从头播放，而且进度条不再移动
倾向于在相同的歌上反复出现同样的问题

**Comment by pan93412** [comment]
Duplicate of #418 (?)
