### ISSUE TITLE
manjaro 下使用appImage或是pacman包

### ISSUE THREAD

**Issue by Jichzhang** [qier222/YesPlayMusic#818]
使用如标题的两种方式在manjaro上打开的窗口无法更改窗口大小，显示器分辨率4k，缩放200%

**Comment by 1900011604** [comment]
显示分辨率2736x1824，缩放200%，上个月下载装的都还可以，这个月重装就成这样了

Manjaro 20.1

![Screenshot_20210708_214126](https://user-images.githubusercontent.com/65082432/124938184-ab347980-e03a-11eb-85dd-17da2c711d24.png)

**Comment by Jichzhang** [comment]
有试过用用老版的么，我之前试了不行，然后放弃...

**Comment by dalaoshi777** [comment]
我也是manjaro 新版本是这样 yesplaymusic0.38就没问题
