### ISSUE TITLE
vercel网页版部署教程就是垃圾，跟着教程走根本无法正常试用，首页显示不正常，无法登陆，歌单也进不去

### ISSUE THREAD

**Issue by gimgoo** [qier222/YesPlayMusic#823]
api和这个都是部署到vercel的，api测试已经正常跑起来了，但是这个项目只能看到界面，而且有些显示不出来。

![image](https://user-images.githubusercontent.com/31849284/124050927-159f5580-da4e-11eb-9b9e-0e412d50cc72.png)

![image](https://user-images.githubusercontent.com/31849284/124050905-0b7d5700-da4e-11eb-9ae2-750228a65e34.png)

环境变量那里填了vercel api域名，没有https的。

请问问题出在哪？

**Comment by gimgoo** [comment]
跟着教程走，操作没问题，最后无法正常运行的教程，可以删掉了。本该的写的不写。这样的教程就是垃圾

**Comment by llovvoll** [comment]
都已经会用 GitHub 了，那你可以发个 PR 协助改进教程

**Comment by isyume** [comment]
确实，我也是部署了，这里的vercel部署教程压根就不行，要么该写的没写，要么方法失效了。vercel那段辣鸡教程确实该删

**Comment by yumetec** [comment]
楼主说的一点毛病都没有，vercel部署教程确实垃圾，之前也有其他人反馈过了，然并卵，有些人还阴阳怪气不承认，笑死

**Comment by llovvoll** [comment]
啥叫开源懂不懂？不过看来也不懂其精神，你们就乖乖做个伸手牌吧

**Comment by VidocqH** [comment]
差不多得了，开源的东西，大伙儿都是自己找时间做的。有毛病就看看Issue有没有，没有就发一个，社区哪天有人修了就OK了，也可以尝试自己解决再提个PR。别上来就一句垃圾，这里没有全职团队。

**Comment by qvshuo** [comment]
伸手党阴阳怪气还上来就骂人的风气都跑到这儿来了？有能力自己改代码，没能力就闭嘴，你以为人家开源项目的作者是你爹？还要给你擦屁股？

**Comment by yumetec** [comment]
> 伸手党阴阳怪气还上来就骂人的风气都跑到这儿来了？有能力自己改代码，没能力就闭嘴，你以为人家开源项目的作者是你爹？还要给你擦屁股？

首先，别人说的是对的，只是说了vercel部署部分是垃圾，应该删掉。伸手摸你妈了？让你来着当婊子还立牌坊？合着你意思，跑到一个三岔路口放个牌子，有条路不对，别人说出来那条路不通，还他妈不能说？伸手党？求你看了？有人求你立牌子吗？婊子。GitHub是开源的不代表什么都是对的，错了还不让人说？别人说了这个项目是垃圾吗？没有，别人只说了有问题的那一部分教程，要你改了？你有能力？你很牛逼？开源项目作者是你爸，你这个婊子得出来立个牌坊，让大家认识一下，明白吗？让大家都伸伸手，帮你扣一下屁股。跑着阴阳怪气，还伸手党，别人只是评论，描述了个事实，vercel部分教程有问题，很早之前有其他人反馈过也不见解决，没解决教程还没删，还继续在那误导他人，骂人了？说垃圾的都是说vercel部分教程，说过作者垃圾？反倒你觉得自己很牛逼，出来展示一下你的婊子能力？

**Comment by qvshuo** [comment]
> > 伸手党阴阳怪气还上来就骂人的风气都跑到这儿来了？有能力自己改代码，没能力就闭嘴，你以为人家开源项目的作者是你爹？还要给你擦屁股？
> 
> 首先，别人说的是对的，只是说了vercel部署部分是垃圾，应该删掉。伸手摸你妈了？让你来着当婊子还立牌坊？合着你意思，跑到一个三岔路口放个牌子，有条路不对，别人说出来那条路不通，还他妈不能说？伸手党？求你看了？有人求你立牌子吗？婊子。GitHub是开源的不代表什么都是对的，错了还不让人说？别人说了这个项目是垃圾吗？没有，别人只说了有问题的那一部分教程，要你改了？你有能力？你很牛逼？开源项目作者是你爸，你这个婊子得出来立个牌坊，让大家认识一下，明白吗？让大家都伸伸手，帮你扣一下屁股。跑着阴阳怪气，还伸手党，别人只是评论，描述了个事实，vercel部分教程有问题，很早之前有其他人反馈过也不见解决，没解决教程还没删，还继续在那误导他人，骂人了？说垃圾的都是说vercel部分教程，说过作者垃圾？反倒你觉得自己很牛逼，出来展示一下你的婊子能力？

素质真高

**Comment by long2ice** [comment]
开源毒瘤伸手党
