### ISSUE TITLE
功能心愿单，不知道好不好实现。

### ISSUE THREAD

**Issue by RebirthEgo** [qier222/YesPlayMusic#83]
<img width="288" alt="Snipaste_2020-12-10_21-00-26" src="https://user-images.githubusercontent.com/54738173/101776351-c2a29700-3b2b-11eb-9bd7-884831922baf.png">

**相似歌手及相似音乐，这两项还是比较实用的。**

<img width="125" alt="Snipaste_2020-12-10_21-01-50" src="https://user-images.githubusercontent.com/54738173/101776499-fe3d6100-3b2b-11eb-92bd-2f4b6c8a4184.png">

**歌词及评论是锦上添花，如果有就更好了。**

<img width="903" alt="Snipaste_2020-12-10_21-05-19" src="https://user-images.githubusercontent.com/54738173/101776725-5a07ea00-3b2c-11eb-8f17-fa78a7db31fe.png">

可以像这样点击正在播放歌手的封面，跳转至歌词页面，此页面可以查看歌词及评论。

“部署网易云 API”不会编程还是挺难弄的，自己研究了好久也没弄成，还是得来麻烦大神。

**Comment by qier222** [comment]
0.3版本歌手页已经有相似歌手和歌词了。
不打算加评论功能，相似的音乐暂时没打算添加（不知道加在哪里）。
