### ISSUE TITLE
WIN11环境下报毒

### ISSUE THREAD

**Issue by eatkid** [qier222/YesPlayMusic#831]
系统环境：WIN11 （22000.51）
描述：安全中心自动扫描会报毒，而且处理不掉。通过edge下载文件后也会触发扫描报毒导致下载失败
![image](https://user-images.githubusercontent.com/24886050/124273463-9fe0da00-db72-11eb-88a6-6bea7fc4a76b.png)

处理不掉导致循环报毒：
![image](https://user-images.githubusercontent.com/24886050/124273529-b4bd6d80-db72-11eb-81f7-59db03808031.png)

**Comment by isNijikawa** [comment]
没有给微软交保护费, 下setup.exe

**Comment by SouLXH** [comment]
关了MD就行了，
