### ISSUE TITLE
我也是，无法通过扫玛登陆，但手机号登陆正常

### ISSUE THREAD

**Issue by sherlocksho** [qier222/YesPlayMusic#834]
我也是，无法通过扫玛登陆，但手机号登陆正常
系统：ubuntu LTS18.0.4
浏览器：firefox

_Originally posted by @sherlocksho in https://github.com/qier222/YesPlayMusic/issues/795#issuecomment-873420407_

**Comment by qier222** [comment]
0.4.1版已修复
