### ISSUE TITLE
歌曲时长是通过哪个接口获得的？

### ISSUE THREAD

**Issue by ZhaoSheng2000** [qier222/YesPlayMusic#838]
最近也在学着做一个类似的app，但是不知道作者的歌曲时长是从哪个接口拿到的数据？

**Comment by VidocqH** [comment]
[接口](https://neteasecloudmusicapi.vercel.app/#/?id=获取歌曲详情)
如`/song/detail?ids=347230`，时长则是`songs[0].dt`，单位是毫秒
