### ISSUE TITLE
[Feature]建议优化播放列表显示&排序

### ISSUE THREAD

**Issue by ZombieFly** [qier222/YesPlayMusic#840]
### 列表中不移除已播放完成的歌曲

当开启循环列表后，播放列表的歌在播放完成后会逐个消失，当又从头开始时歌曲又会全部出现，在此之前无法浏览将会在下一次循环中将要播放的歌曲。建议采用经典的高亮正在播放歌曲，播放列表总体显示保持不变的列表方案。

### 列表歌曲顺序可自由调度

被添加入列表的歌单或插队入的歌应支持自由调度播放顺序，而不是仅能添加一个插队副本或是删除。

### 右键歌曲增加播放列表追加

目前仅有插队播放（即“添加至队列”），或许这是沿袭自网易云客户端？然而网易云网页版的“添加至播放列表”为追加，建议增加“追加至播放列表”，可能更贴合部分用户（比如我个人）的使用习惯。

**Comment by pan93412** [comment]
已分拆。
