### ISSUE TITLE
Mac客户端音乐云盘无法上传音乐 没有任何反应

### ISSUE THREAD

**Issue by Small-SaltedFish** [qier222/YesPlayMusic#848]
Mac客户端
网盘无法上传音乐 上传音乐无反应 没有任何反应 长时间等待后刷新 还是没有反应

**Comment by iErics** [comment]
同样的问题

**Comment by bugs1998** [comment]
![image](https://user-images.githubusercontent.com/34487136/125570100-36775c1e-93ef-4e29-94e2-74836b612dd3.png)
![image](https://user-images.githubusercontent.com/34487136/125570160-c4df05b4-65f7-4af9-8496-5538f698456e.png)
- 上传的时候报错了

**Comment by mgxynsmn** [comment]
好像是修改前端的默认请求参数大小,然后重新编译打包成dmg包
目前可以使用网页端的进行上传

**Comment by qier222** [comment]
0.4.1版已修复
