### ISSUE TITLE
 云盘部分音乐无法播放

### ISSUE THREAD

**Issue by bugs1998** [qier222/YesPlayMusic#850]
- 客户端
- 10.14.6 (18G95)
- 播放云盘音乐时，部分音乐不能播放，没有反应

**Comment by bugs1998** [comment]
![image](https://user-images.githubusercontent.com/34487136/125570400-b0af3fdb-f3d4-4685-a639-c5d400cb2b4e.png)

**Comment by hxhc** [comment]
有人提交[[pr](https://github.com/qier222/YesPlayMusic/pull/812)了，你可以把最新的仓库clone下来，自己build一下。我已经试过播放问题是解决成功了，但是云盘上传问题没有解决。

**Comment by bugs1998** [comment]
1
