### ISSUE TITLE
macOS控制栏暂停音乐app的播放状态不同步

### ISSUE THREAD

**Issue by anthooooooooony** [qier222/YesPlayMusic#851]
<img width="1177" alt="截屏2021-07-14 16 35 54" src="https://user-images.githubusercontent.com/15117048/125591203-0c912a4e-7e93-421f-8754-4cd11c921853.png">
如图所示，非常感谢尽心维护

mac客户端，Big Sur

**Comment by qier222** [comment]
没复现这个bug

**Comment by rinmyo** [comment]
M2 + Sonoma 14.4.1
同样 bug
