### ISSUE TITLE
超棒的软件！！播放时找不到音源会一直寻找，能否添加超时跳转播放下一首功能？

### ISSUE THREAD

**Issue by Youtong-Rong** [qier222/YesPlayMusic#852]
#客户端播放音乐找不到音源会一直寻找，能否添加超时跳转功能？

循环歌单听歌过程中，经常需要自己手动切换下一首，要不然会一直等待寻找音源。
如果能够超时1分钟或可以用户自定义，将会更加方便灵活。

辛苦啦辛苦啦！！强烈推荐优秀软件！

**Comment by jizongFox** [comment]
This feature can be important!

**Comment by pan93412** [comment]
應已在新版解決。
