### ISSUE TITLE
快捷键有时候会出现失灵的情况哦

### ISSUE THREAD

**Issue by wg96644364** [qier222/YesPlayMusic#853]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by Truthss** [comment]
在我每次重新开机之后打开yesplay都会出现快捷键不能使用的问题
经测试发现需要进入设置（仅进入）就可以解决问题
客户端
重装系统：win10专业版 1909

**Comment by baipolpol** [comment]
软件启动后快捷键经常不起作用 需要在设置里重新关闭再打开开关才能生效

**Comment by KeyueMiao** [comment]
> 软件启动后快捷键经常不起作用 需要在设置里重新关闭再打开开关才能生效

我也是同样的情况

**Comment by qier222** [comment]
0.4.1已修复
