### ISSUE TITLE
现在只能开代理才登陆了吗？

### ISSUE THREAD

**Issue by lwokf** [qier222/YesPlayMusic#855]
软件端现在开了代理网易云才能登陆，原来不用的呀

**Comment by RainFlying** [comment]
开不开代理，都是 “登录成功，请稍等”，等半个小时还是请稍等。
开了 VPN 之后，显示 “登录成功，请稍等”， 然后过一会就说 “二维码失效，请重试”。

**Comment by RainFlying** [comment]
使用邮箱帐号密码登录，直接显示登录失败。

**Comment by stlion** [comment]
我用0.40版本单文件EXE版，无需代理即可邮箱登陆，并且正常播放账号里的歌单。
如果登陆有问题，根据我的经验，可能是代理或挟持，检查一下路由器或电脑，有无启用“网易云去灰”之类的功能，建议关掉“去灰”后再尝试登陆。

**Comment by RainFlying** [comment]
> 我用0.40版本单文件EXE版，无需代理即可邮箱登陆，并且正常播放账号里的歌单。
> 如果登陆有问题，根据我的经验，可能是代理或挟持，检查一下路由器或电脑，有无启用“网易云去灰”之类的功能，建议关掉“去灰”后再尝试登陆。

刚在公司尝试了一下，邮箱登录倒是正常的，不过扫码登录还是一样的请稍候。

**Comment by helundong** [comment]
感谢，用了代理终于登录上了。

**Comment by qier222** [comment]
0.4.1版已修复
