### ISSUE TITLE
使用域名部署时无法登录

### ISSUE THREAD

**Issue by if1y** [qier222/YesPlayMusic#86]
比较诡异。

前期用 IP 测试正常，于是使用 Caddy 反代至域名访问。
API 保持 IP 访问，抓包显示 API 是正常请求了的。

但是每次只要点击`登陆`，等待几秒时间API返回信息后，就会跳回原有的登录方式选择页……

**Comment by qier222** [comment]
建议将 YesPlayMusic 部署到 https://example.com，将网易云API部署到 https://example.com/api，API和前端页面再同一个域名下就不会有跨域的问题了。

**Comment by if1y** [comment]
其实我一开始是把api部署在同域名的8080端口，播放器用80端口，但是访问api就一直报错 404，才改回了ip……

**Comment by qier222** [comment]
> 其实我一开始是把api部署在同域名的8080端口，播放器用80端口，但是访问api就一直报错 404，才改回了ip……

同个域名/IP，但是不同端口，也是跨域。

附上我的Nginx反代配置
```nginx
location /api {
    rewrite  ^.+api/?(.*)$ /$1 break;
    add_header Cache-Control no-cache;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_pass         http://127.0.0.1:42436;
    proxy_connect_timeout 30s;
}
```

**Comment by if1y** [comment]
解决了，感谢！
