### ISSUE TITLE
操作响应极其缓慢

### ISSUE THREAD

**Issue by ZhanYiHui119** [qier222/YesPlayMusic#863]
使用方式：客户端
操作系统：Windows10专业版
截图：![Snipaste_2021-07-24_21-29-57](https://user-images.githubusercontent.com/83508276/126870170-8e1e1fa6-4c57-4a88-bdd7-2f685d8d684d.png)
问题反馈：在进行点击”上一首“”下一首“双击歌曲”等操作的时候，软件不会立刻响应，一般都会等待几十秒甚至一分多钟才能够响应，而且在切换三个功能区的时候加载速度比较缓慢。（另外，就目前来看，歌词页面对于竖屏适配的不是很好，只有歌词，没有封面和操作按钮）

**Comment by pan93412** [comment]
應已在新版本修正。
