### ISSUE TITLE
功能请求：自定义主题颜色

### ISSUE THREAD

**Issue by luoling8192** [qier222/YesPlayMusic#868]
希望可以自定义主题颜色，个人不是很喜欢蓝色哈哈哈，如果能改掉就好了

**Comment by chwt163** [comment]
现在的黑色太黑了，白色字体显得有点刺眼，要是能自定义就好了，我个人比较喜欢像这样的深灰色：
![屏幕截图_20240617_213835](https://github.com/qier222/YesPlayMusic/assets/70951194/91d03146-aaee-4938-92a3-76c76acbff67)

**Comment by luoling8192** [comment]
挖坟了，作者都不维护了，过段时间我 Fork 一份继续维护好了

**Comment by chwt163** [comment]
> 挖坟了，作者都不维护了，过段时间我 Fork 一份继续维护好了

作者不是不维护，是在开发新版吧？希望新版能支持自定义颜色就好了
