### ISSUE TITLE
不算bug的bug？

### ISSUE THREAD

**Issue by NavlysChen** [qier222/YesPlayMusic#87]
今天想起来看了下这个项目，发现已经做好Electron 版本了。于是下载了win版来试试看。

不小心点了右上角关闭界面，以为关闭界面就是直接退出软件，就在开始菜单又点击了一下，出现了以下的报错，还以为怎么刚装上就用不了了，后面发现原来是最小化到系统托盘了。但是不像其他软件一样，当前存在一个实例正在运行，再点击桌面图标或开始菜单图标时直接打开已运行实例，而是重新打开一个实例，然后就提示端口已被监听的错误。

虽说好像不是啥大bug，不过有时感觉有点膈应
![f69b5ee93e3e65a1d26687d44a9e0f3](https://user-images.githubusercontent.com/42211168/102985841-caf6cb00-454a-11eb-99cd-106525d476c8.png)
![3505fae082119a99f12043e1cdc9671](https://user-images.githubusercontent.com/42211168/102985872-d77b2380-454a-11eb-9163-dfa67a723e34.png)

**Comment by qier222** [comment]
争取下个版本修复

**Comment by qier222** [comment]
在新版本里修复了，我这边测试过没问题。
