### ISSUE TITLE
请求支持网易云私人FM

### ISSUE THREAD

**Issue by isPoto** [qier222/YesPlayMusic#871]
像倒带 app 支持网易云私人 FM 接口。可以使用私人FM 的音乐推荐。

目前桌面端尚无相关实现，申请支持。

私人FM 用得比较多，因为我主要靠它发现好听的音乐。

**Comment by memorydream** [comment]
![image](https://user-images.githubusercontent.com/34763046/128300042-344685f5-4722-413f-a401-d46331582c85.png)
左边日推，右边FM
