### ISSUE TITLE
希望能够增加插件的功能

### ISSUE THREAD

**Issue by TotoWang-hhh** [qier222/YesPlayMusic#874]
我很乐意用户能够用我的软件下载音乐。

我知道这个功能可能需要很长的时间来实现，但是我短期内并不需要这个功能。
你们可以先在软件副本上单独开发这个功能，最后再完整地加入正式版。

我想要开发基于该软件的插件并非推广我的软件，只是希望用户有更好的体验，能够在听歌的同时下载音乐而不用重新搜索。

### 插件可以调用的接口：
- 在某个区域（如功能区等位置）添加按钮，并绑定某个程序
- 监听用户的操作，适时作出响应（输入账号密码时返回类似“输入隐私内容”的字符串）
- 播放来自插件的音频和音效
- 在设置中添加条目
- 创建新的自定义界面或者弹窗
- 自动打开一个界面或弹窗
### 后期：
- 可以制作插件商店
### 其他：
- 在一处统一管理插件，插件可以禁用、启用或卸载
- 插件可以从插件商店或文件中导入
- 网易云灰色音乐解锁等功能可以变成系统插件，无法卸载，只能禁用。
- 插件安装文件可以是7z压缩包改后缀，压缩包内存放插件的所有内容和插件信息（插件信息存在一个json文件里）。

还有就是希望能够照顾下我这种Python开发者，在pypi上写个库。

有任何关于python的问题可以问我，我很高兴为你（们）解答！因为这是我最喜欢的音乐软件（今天用这个听歌又是一下午）。

## 我非常希望自己能够为该软件做一点点贡献。

**Comment by TotoWang-hhh** [comment]
另外补充一下：
插件在某个区域添加的按钮可以获取这个区域的属性，比如这是哪一首歌的选项区，歌曲Id 是啥，等等
插件可以获取软件当前的信息，比如当前登陆的是谁的账号，当前正在播放什么歌曲等等。

**Comment by qier222** [comment]
暂时没有计划做这个功能
