### ISSUE TITLE
希望能够开发移动端（其实很简单，详见正文）

### ISSUE THREAD

**Issue by TotoWang-hhh** [qier222/YesPlayMusic#875]
这里重点讲我对开发移动端的一些建议，所以请不要在意与其他问题的重复。

移动端其实很简单，初期可以直接用简易的软件内浏览器解决

具体的开发可以找人帮忙（这忙我可帮不了，主要是我不会），可以有iOS、安卓和UWP版。

至于iOS应用商店上架的问题，其实真的没有必要不然还得每个月花99块钱。要让iOS用户下载软件只需要一个IPA（这个就得找iOS端的开发者了:)）、一个plist文件（网上有示例）、一个特殊的按钮（放在下载页）和一个存放这些东西的网站（要有SSL协议，你的网站应该行）就行，具体百度。
这样用户点击下载按钮就能安装软件，不过有个缺点就是用户不能在苹果商店里面看到这个软件。
TestFlight的办法不推荐，因为用户名额和使用时间有限。

至于何时显示下载页的入口（如果你们打算开发一个下载页面），我觉得有两个办法
方法一：通过UA来判断，给YesPlayMusic的客户端定一个自己的UA，比如“YesPlayMusic iOS App”其他版本大同小异。服务端先判断是不是客户端的UA再来决定显不显示下载页面的入口
方法二：通过参数来判断，客户端在请求网页是发送一个isapp的参数，设置为true，服务端读取这个参数来判断是不是客户端

**Comment by wangyingbo** [comment]
什么玩意？？？没有签名没有证书怎么让用户下载？

**Comment by TotoWang-hhh** [comment]
我是外行，抱歉说错了

> 什么玩意？？？没有签名没有证书怎么让用户下载？

**Comment by RingingVolcano** [comment]
弄移动端是想等着吃网易律师函吗（

**Comment by TotoWang-hhh** [comment]
> 弄移动端是想等着吃网易律师函吗（

？？？
第三方播放器违法了？？？
话说API是干嘛的？？？

**Comment by RingingVolcano** [comment]
> > 弄移动端是想等着吃网易律师函吗（
> 
> ？？？
> 第三方播放器违法了？？？
> 话说API是干嘛的？？？

举个例子，Share是怎么停止维护的？

**Comment by TotoWang-hhh** [comment]
> > > 弄移动端是想等着吃网易律师函吗（
> > 
> > ？？？
> > 第三方播放器违法了？？？
> > 话说API是干嘛的？？？
> 
> 举个例子，Share是怎么停止维护的？

那我觉得风险不大，只要不做大流行，然后上面我说的这些话都是没办法把软件做大的。

我自己也是做音乐软件这块的，目前啥问题都没有，可能已经有大概上十个用户了（根据博客的阅读量猜测的）

**Comment by TotoWang-hhh** [comment]
> > > 弄移动端是想等着吃网易律师函吗（
> > 
> > ？？？
> > 第三方播放器违法了？？？
> > 话说API是干嘛的？？？
> 
> 举个例子，Share是怎么停止维护的？

当然也谢谢你的提醒
