### ISSUE TITLE
希望能加入前往网页端查看评论的按钮

### ISSUE THREAD

**Issue by Loss-of-time** [qier222/YesPlayMusic#877]
毕竟偶尔评论区会有一些有用的信息 比如背景 作者动态 赏析什么的

**Comment by ybm911** [comment]
希望不忘初心，不要忘了当初为什么重新制作一个网易云软件。
为的是简洁，还原一个单纯的听歌软件。
最好还是不要加入不必要的功能

**Comment by halibw** [comment]
> 毕竟偶尔评论区会有一些有用的信息 比如背景 作者动态 赏析什么的

你为什么不去用官方版

**Comment by hawtim** [comment]
agree
