### ISSUE TITLE
YesPlayMusic 改进建议：首页布局采取区块设计和增加小窗模式

### ISSUE THREAD

**Issue by isPoto** [qier222/YesPlayMusic#878]
我有两点提议：
1. 首页的排列布局由目前的行布局，改为区块布局。

![yesmusicRedesign](https://user-images.githubusercontent.com/59009389/128636213-6cc1e903-fb0f-4e41-afb5-98ffedc8bb5f.png)

感谢 YesPlayMusic 惊艳的 UI 设计和开发，让我听音乐有更好的体验。感谢开发者的付出和心血。

我设计了该样式，这样设计会不会更好？如果需要详细了解某模块，直接点击标题展开。而且区块设计也让同一屏呈现的内容更加详实、紧凑和方便。不用像我现在主听私人 FM 要翻几页才行。

主要是我认为现在的布局信息呈现效率有些低，而且我只用私人FM和推荐歌单。如果上述建议不采纳，也请考虑首页的显示模块可以编辑，让我可以把 by Apple Music 替换为 For You。

2. 希望能增加小窗功能。用于听私人FM 时切曲
听私人FM，频繁切曲是必须的，因为你要发现音乐，你有时候很快就知道推荐的音乐不适合你，你需要切曲下一首。如果没有小窗模式，我每次都得切换软件，必须鼠标要在硕大的界面中找到切曲、喜欢和不喜欢。这很麻烦。建议增加小窗。

![image](https://user-images.githubusercontent.com/59009389/128636273-9aae1cb7-bbfc-4747-9356-c60ac8b49a47.png)

以上，感谢。

**Comment by liukenny961** [comment]
我觉得这样的话主页信息有点密集了……

**Comment by isPoto** [comment]
> 我觉得这样的话主页信息有点密集了……

它让需要特定模块的用户都能在首页找到。你能想象我只听私人FM的，每次都得打开软件、翻好几页才找到私人FM位置的烦恼吗？再比如，你想听排行榜，你得翻到末尾，这可不叫用户体验。

如果希望用现在的行式布局，至少也请提供自定义显示模块的选择，让用户可以决定首页的第一行和第二行是他们需要的模块。

**Comment by qier222** [comment]
会考虑出个首页排序功能
