### ISSUE TITLE
Mac菜单样式乱了,全屏没有问题

### ISSUE THREAD

**Issue by 52Lau** [qier222/YesPlayMusic#88]
![image](https://user-images.githubusercontent.com/37538641/103009660-0c4ea100-4572-11eb-9115-df4fb3c59f22.png)

**Comment by BlahDuckling747** [comment]
Windows 10 2004 20246.1也有这个问题（但我觉得应该和系统的小版本没什么关系）

**Comment by RebirthEgo** [comment]
这个之前我也遇到过，窗口水平拉大一些就解决了

**Comment by qier222** [comment]
应该是初始化的时候，窗口大小的默认值没生效，应该可以在下个版本修复。

**Comment by qier222** [comment]
应该是修复了，有问题的话可以再打开这个issue
