### ISSUE TITLE
chrome应用程序打开，登录的时候保存的账号密码，账号会填到搜索框当中，算bug吗？

### ISSUE THREAD

**Issue by China-Huanghe** [qier222/YesPlayMusic#883]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 [可打开控制台）](url)
![image](https://user-images.githubusercontent.com/77739994/129210625-4a0cd217-4591-4c8f-b65b-4387afc1899b.png)

**Comment by TotoWang-hhh** [comment]
不知道是Chrome还是YesPlayMusic的BUG，总之YasPlayMusic这边修复一下还是可以解决的
