### ISSUE TITLE
全局快捷键要恢复默认才可以使用

### ISSUE THREAD

**Issue by Ges0ng** [qier222/YesPlayMusic#884]
不知道是我的问题还是，每次重新开机后，全局快捷键必须恢复默认一下才可以使用，不然就是没反应，只有弹出窗口后快捷键才能用。

客户端，win10

**Comment by kevintao0417** [comment]
同

**Comment by xchangfu** [comment]
每次打开后，全局快捷键失效，要在设置界面重新启用才能生效，原来不止我一个发现有这个问题😂

**Comment by 00LT00** [comment]
不是重启，是在界面里面使用一次快捷键，就会让全局快捷键启用，是个能稳定复现的bug

**Comment by qier222** [comment]
0.4.1版已修复
