### ISSUE TITLE
请问如果我只听网易云的歌曲，那么YesPlay的优势在哪里呀？小白求解。因为我down了网易云官方app感觉体积更小，而且听歌没差别呢

### ISSUE THREAD

**Issue by soberest288** [qier222/YesPlayMusic#885]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

**Comment by dalaoshi777** [comment]
网易云丑 字体难看  界面丑 有bug而且不修复

**Comment by FCSDFSDVXDFG** [comment]
（看介绍就知道了吧）去掉了许多无用功能，歌曲不用VIP，UI也好看

**Comment by Geeyun-JY3** [comment]
明确自己的需求，选就是了。README 将功能写得清清楚楚。

**Comment by HangQ730** [comment]
我反正在PC端再也没用过网易云，就因为能听周董

**Comment by TotoWang-hhh** [comment]
这个比较好看
