### ISSUE TITLE
希望能用心做做Win版安装包

### ISSUE THREAD

**Issue by TotoWang-hhh** [qier222/YesPlayMusic#887]
希望Win版安装包有欢迎界面和安装路径调整等功能，可以考虑把安装程序放在免安装版里面，可以参考AnyDesk的安装。

建议：可以把安装栏放在顶部三个按钮后面（音乐库按钮后面），点击后跳转进一个页面（不弹出新窗口）这个界面就是安装程序。
建议：在用户使用免安装版一段时间后询问用户是否喜欢软件，回答喜欢则提示用户安装（可以在安装按钮下面弄个气泡框），回答不喜欢就提示用户反馈

**Comment by TotoWang-hhh** [comment]
当然普通的免安装还是做，给魔改PE用

**Comment by Wildccy** [comment]
这是开源项目 你可以自己fock一份进行打包  🙅‍♀️做伸手党

**Comment by TotoWang-hhh** [comment]
> 这是开源项目 你可以自己fock一份进行打包  🙅‍♀️做伸手党

主要是我不会这个软件的语言，一看就懵……
之前也尝试过魔改这个软件，结果完全没头绪
