### ISSUE TITLE
音量条的改进建议

### ISSUE THREAD

**Issue by TotoWang-hhh** [qier222/YesPlayMusic#889]
## 建议：
- 软件内的音量条可以联动系统的音量合成器
- 音量条旁边可以增加音量百分比的数字显示

另外就是问下作者还健在吗？

**Comment by 11006281** [comment]
我还是认为应该要回到社群维护了.....不然现在分叉开发对这个专案也不好

**Comment by pan93412** [comment]
作者健在。其餘問題已另外開 Issue 追蹤。
