### ISSUE TITLE
Windows单文件程序版，点击右上角的X，每次都会弹出这个窗口，是不是可以增加个默认设置呢？默认关闭程序或者默认最小化？

### ISSUE THREAD

**Issue by China-Huanghe** [qier222/YesPlayMusic#892]
![image](https://user-images.githubusercontent.com/77739994/130000389-1e273316-244e-4111-85da-5e7282d88f98.png)

**Comment by TotoWang-hhh** [comment]
这个我反馈过了

**Comment by TotoWang-hhh** [comment]
的确很烦
