### ISSUE TITLE
网易云云盘音乐无法听

### ISSUE THREAD

**Issue by zjm54321** [qier222/YesPlayMusic#894]
### 反馈 bug 需要的信息

- 用的是mac版
- macOS 11.5
- 网易云音乐云盘中的歌曲无法读取。播放显示歌曲名但实际仍在播放上一首歌曲

**Comment by TTTPOB** [comment]
https://github.com/qier222/YesPlayMusic/pull/812 修复过啦可是release还没更新

**Comment by qier222** [comment]
0.4.1版已修复
