### ISSUE TITLE
歌词在切换歌曲后的显示问题

### ISSUE THREAD

**Issue by BurnoutAg7** [qier222/YesPlayMusic#90]
问题描述：在播放歌单中的一首带歌词的歌曲（称作A）后播放不带歌词的歌曲（称作B），将会在B的歌词界面显示A的歌词

**Comment by qier222** [comment]
https://github.com/qier222/YesPlayMusic/commit/01e5dbe6522b500ab71fbb1a90ef9378020b280e

这个commit修复了这个bug

**Comment by BurnoutAg7** [comment]
好的，谢谢答疑

**Comment by BurnoutAg7** [comment]
全新问题：现在有带歌词的两首歌曲A和B，在播放完A自动切换到B时，歌词不会自动滚回顶部，而会显示B的末尾几行歌词

**Comment by BurnoutAg7** [comment]
新问题：带歌词的歌曲中假若有一行外文歌词没有翻译，原本是翻译的位置会显示`undefined`

**Comment by qier222** [comment]
> 新问题：带歌词的歌曲中假若有一行外文歌词没有翻译，原本是翻译的位置会显示`undefined`

这个在之前的commit里已经修复了

**Comment by qier222** [comment]
> 新问题：现在有带歌词的两首歌曲A和B，在播放完A自动切换到B时，歌词不会自动滚回顶部，而会显示B的末尾几行歌词。（需要在B开始播放歌词对应的音频后，才会把B的歌词滚回上方）

我有时间就测试看看

**Comment by BurnoutAg7** [comment]
一个新的bug：假设有一行歌词A，它的下一行就是歌词B，它们都有翻译。若B是纯数字歌词，B的翻译会因为本人无法推测的原因显示A的翻译。（说是无法推测而不是随机，是因为清理了几次缓存后一直是特定的一部分纯数字歌词显示上一行的翻译）
复现方式：播放https://music.163.com/#/song?id=1376659382，重点关注歌词“223”和“123”的翻译显示。

**Comment by qier222** [comment]
> 一个新的bug：假设有一行歌词A，它的下一行就是歌词B，它们都有翻译。若B是纯数字歌词，B的翻译可能会因为本人无法推测的原因显示A的翻译。（并不一定是随机，因为清理了几次缓存后一直是特定的一部分纯数字歌词显示上一行的翻译）
> 复现方式：播放[アンヘル](https://music.163.com/#/song?id=1376659382)，重点关注歌词“223”和“123”的翻译显示。

这个应该已经修复了。每次Push代码的时候GitHub Action都会自动打包一份客户端，你可以在这里下载到最新未发布的版本 https://github.com/qier222/YesPlayMusic/actions/runs/468239211

**Comment by qier222** [comment]
> 一个新的bug：假设有一行歌词A，它的下一行就是歌词B，它们都有翻译。若B是纯数字歌词，B的翻译可能会因为本人无法推测的原因显示A的翻译。（并不一定是随机，因为清理了几次缓存后一直是特定的一部分纯数字歌词显示上一行的翻译）
> 复现方式：播放[アンヘル](https://music.163.com/#/song?id=1376659382)，重点关注歌词“223”和“123”的翻译显示。

看了下确实有问题，尝试修复中

**Comment by qier222** [comment]
以上的问题在0.3.1版修复了。还发现有问题的话可以重新打开issue。
