### ISSUE TITLE
登录加载

### ISSUE THREAD

**Issue by dzoo15** [qier222/YesPlayMusic#900]
[网页版、客户端](url)
- 浏览器edge或电脑win
登陆成功，扫码长时间加载不进去。密码登录显示错误
![屏幕截图 2021-08-28 123703](https://user-images.githubusercontent.com/59956201/131206282-d2afbc5b-6706-44a4-b312-00f6d15357b8.png)

**Comment by 00LT00** [comment]
+1 手机密码就直接秒登录，扫码就一直在等

**Comment by 11006281** [comment]
https://github.com/qier222/YesPlayMusic/pull/835
