### ISSUE TITLE
不是网易云的歌不能加到我喜欢或者歌单吗？

### ISSUE THREAD

**Issue by nichanglan** [qier222/YesPlayMusic#902]
# 不是网易云的歌不能加到我喜欢或者歌单吗？

- 用的 YesPlayMusic 客户端
- 电脑系统：Windows 10
- 以新裤子的《你要跳舞吗》为例，点击“添加到我喜欢的音乐”
![image](https://user-images.githubusercontent.com/35494180/131474020-2add9ed4-79f7-451f-83d1-8a1d1f4deee4.png)
此时 F12 终端显示：
![image](https://user-images.githubusercontent.com/35494180/131474231-33d23b12-f24a-416f-9ce4-1e51df0a76d3.png)

我喜欢里没有新裤子的《你要跳舞吗》
ps：这首歌 QQ 音乐可以听网易云听不了，不知道是不是因为版权的问题无法添加。如果无法添加到我喜欢，是否可以添加到其他地方（比如某个歌单）？这样点击歌单就能找到了，否则还得去输入框重新输入再搜索。

**Comment by bugs1998** [comment]
没版权的现在不能添加到我喜欢，之前添加的不受影响

**Comment by qier222** [comment]
楼上说的对
