### ISSUE TITLE
灰色歌曲替换不完美，希望提供直接搜索QQ音乐的功能

### ISSUE THREAD

**Issue by luo-chuan** [qier222/YesPlayMusic#904]
灰色歌曲替换不正确，如果能直接搜QQ音乐就可以没有这个烦恼了。

比如：
灰色歌曲是： https://music.163.com/#/song?id=28643165  
正确歌曲是 :   https://i.y.qq.com/v8/playsong.html?songid=108493940 

然后实际上替换后不是正确歌曲，您可以自己听一下。
或者给个手动替换功能也行，不要自动替换。

**Comment by qier222** [comment]
暂时无计划提供这个功能
