### ISSUE TITLE
看评论功能

### ISSUE THREAD

**Issue by yjc007** [qier222/YesPlayMusic#905]
希望能看歌曲的评论，毕竟网易云的灵魂也就在评论上

**Comment by memorydream** [comment]
这个软件的卖点之一就是无任何社交功能，如果想要社交相关的功能还是使用其他软件比较合适

**Comment by updater1234** [comment]
> 这个软件的卖点之一就是无任何社交功能，如果想要社交相关的功能还是使用其他软件比较合适

赞同
