### ISSUE TITLE
Win11 下频发的报错

### ISSUE THREAD

**Issue by heyuhengmatt** [qier222/YesPlayMusic#909]
运行过程中频发的闪退报错信息：

![image](https://user-images.githubusercontent.com/36391318/132243989-b1a2f0c9-23b3-4b23-bda0-552cdd5a6fbc.png)

多次测试发现，打开**桌面歌词**、打开**彩虹猫**似乎会提高这个错误的发生率

有任何帮助信息吗？

**Comment by pan93412** [comment]
看起來是 Windows 11 舊版的問題。
