### ISSUE TITLE
新需求，灰色歌曲解锁

### ISSUE THREAD

**Issue by fansanqiu** [qier222/YesPlayMusic#91]
大佬有考虑灰色歌曲解锁么？

https://github.com/nondanee/UnblockNeteaseMusic

**Comment by alphagocc** [comment]
这个你看看commits，有过了吧

**Comment by fansanqiu** [comment]
因为打开新歌单的时候老是会跳过很多歌才播放某一条，还以为没加进去来着。


奶思，Thanks大大～

**Comment by qier222** [comment]
下个版本会让灰色歌曲可以双击播放，并加个提示让用户知道可以点击。

**Comment by RebirthEgo** [comment]
> 下一个版本将会变成灰色的歌曲可以双击播放，并加个提示让用户知道可以点击。

0.3版本灰色歌单确实不能像前面版本那样顺畅播放了，点很次没有反应

**Comment by qier222** [comment]
没有加入可双击播放的提示。现在客户端设置里，网易云无版权的歌曲显示灰色开关已默认为关闭。
