### ISSUE TITLE
Windows客户端报错

### ISSUE THREAD

**Issue by PIndividual** [qier222/YesPlayMusic#914]
开启的时候会报错，启动后无法获取任何信息
![image](https://user-images.githubusercontent.com/62368342/133059893-6eee498a-4c59-4576-928b-eef6f22e3c94.png)

**Comment by Codeniu** [comment]
ctrl+r 刷新一下，或者 f12 控制台查看梗详细的错误信息

**Comment by youlan2333** [comment]
（win11 21H2 客户端最新）
![Uploading QQ截图20210919204438.png…]()
![QQ截图20210919204758](https://user-images.githubusercontent.com/64688148/133928082-b5a306d9-7767-4475-baf8-341cb9570570.png)

**Comment by memorydream** [comment]
> 开启的时候会报错，启动后无法获取任何信息
> ![image](https://user-images.githubusercontent.com/62368342/133059893-6eee498a-4c59-4576-928b-eef6f22e3c94.png)

端口10754被其他程序占用了

**Comment by memorydream** [comment]
> （win11 21H2 客户端最新）

这个不影响使用，暂时不清楚是哪里引起的

**Comment by pan93412** [comment]
Duplicate of #914
