### ISSUE TITLE
优化Mac v4.0客户端的airpods体验

### ISSUE THREAD

**Issue by Flora-air** [qier222/YesPlayMusic#915]
MacOS 11.5.2 v4.0客户端 已经查阅没有相关的issue 和plan
第一次连接AirPods播放需要手动切换到airpods
希望能增加连接了AirPods就默认使用AirPods输出 而不需要去手动切换输出设备的功能

而且在音频输出设备里会出现两个AirPods的选项（也许是左耳右耳？也希望优化一下 
<img width="780" alt="Screen Shot 2021-09-13 at 22 37 53" src="https://user-images.githubusercontent.com/62434508/133103727-c29b4667-044c-48db-919e-88b01de09c47.png">
）

**Comment by qier222** [comment]
建议用第三方应用如AirBuddy和ToothFairy
