### ISSUE TITLE
Feat: 希望可以自定义背景图片

### ISSUE THREAD

**Issue by Jason23347** [qier222/YesPlayMusic#919]
粗略地查过资料，electron 需要自定义一个 `file://` scheme，其他方面的可行性应该都可以保证。

但是我虽稍微熟悉 js 但不是很熟悉本项目的技术栈，所以希望有好心人实现我的愿望2333

当然，如果直到十一假期都还没人接手的话，我将考虑提交PR

**Comment by qier222** [comment]
没有计划添加这个功能，增加背景图片会破坏原本的设计。
