### ISSUE TITLE
界面中的按钮位置问题

### ISSUE THREAD

**Issue by vsxd** [qier222/YesPlayMusic#922]
平台：macOS客户端

反馈一个UI中的小问题，不影响正常使用。如下图，返回按钮在某些窗口大小下会被系统的窗口控制按钮遮盖一部分。

![Screenshot 2021-09-24 at 18.12.36.png](https://i.loli.net/2021/09/24/mBDdW1KGn9yFgcC.png)

**Comment by qier222** [comment]
已知晓，但是暂时没计划修复
