### ISSUE TITLE
bug: 0.4.1 mac 版无法正常关闭应用

### ISSUE THREAD

**Issue by beyai** [qier222/YesPlayMusic#929]
按 command+q， 菜单点击 Quit,  docker右键点击退出 都无法正常关闭，只能强制退出
系统版本：mac os 10.15.7
应用版本：0.4.1

**Comment by qier222** [comment]
可通过重置客户端解决

> 如何卸载重装客户端？
> 按F12打开控制台，输入 `resetApp()` ，再重启客户端即可重置客户端。

或者按F12打开控制台，选择Application -> Local Storage，编辑settings下面的closeAppOption的值为'exit'

**Comment by memorydream** [comment]
手上没有mac设备不知道具体是什么情况，托盘右键菜单的退出和之前的行为应该是完全一致的，app.exit()会走到某个被监听的事件吗？

**Comment by williamjin1992** [comment]
> 可通过重置客户端解决
> 
> > 如何卸载重装客户端？
> > 按F12打开控制台，输入 `resetApp()` ，再重启客户端即可重置客户端。
> 
> 或者按F12打开控制台，选择Application -> Local Storage，编辑settings下面的closeAppOption的值为'exit'

使用如上两种办法仍无法解决问题。

**Comment by MuBeiSAMA** [comment]
同样的问题，编辑localStorage无效

**Comment by lqq444** [comment]
同样的问题，不要升级

**Comment by kksxsyj** [comment]
按照上面的说法重置应用果然就好了

**Comment by Andylee24** [comment]
同样的问题，编辑localStorage无效

**Comment by Przeblysk** [comment]
重置 localStorage 都无效

**Comment by CarrotChou** [comment]
> 重置 localStorage 都无效

重置不行，卸载重新安装就好了

**Comment by Przeblysk** [comment]
> > 重置 localStorage 都无效
> 
> 重置不行，卸载重新安装就好了

一样不行

**Comment by Przeblysk** [comment]
暂时可以在设置中关闭全局快捷键来解决这个问题

**Comment by Przeblysk** [comment]
> 暂时可以在设置中关闭全局快捷键来解决这个问题

然后在 resetApp() 就生效了 = =这个bug有点奇怪

**Comment by williamjin1992** [comment]
先关闭全局快捷键，然后F12内resetApp() 可彻底解决问题。

**Comment by Dr-T** [comment]
开启“设置 - 其他 - 🐈️ 🏳️‍🌈”后可以正常退出

**Comment by ding667** [comment]
linux deb版 关闭全局快捷键后恢复正常

**Comment by Xfcmy** [comment]
MacOS 11.6
0.4.1
关闭全局快捷键
即可正常关闭App
