### ISSUE TITLE
歌词滚动问题

### ISSUE THREAD

**Issue by SakuraPure** [qier222/YesPlayMusic#937]
客户端
win10操作系统

在听歌时发现歌词不跟随滚动
![截图](https://static01.imgkr.com/temp/e1349d7f7e444accac81a4df5e798f44.png)
![p2](https://static01.imgkr.com/temp/cde5789c301942128c1e0ef0aac03809.png)

**Comment by qier222** [comment]
不知道是不是我网络问题，截图只能加载上半部分

**Comment by pan93412** [comment]
應已在後續版本修正。
