### ISSUE TITLE
建议新功能：增加收藏被下架或版本锁定的音乐

### ISSUE THREAD

**Issue by yidasanqian** [qier222/YesPlayMusic#939]
版本0.4.1
点击喜欢/收藏网易云接口提示：“操作失败，专辑下架或版权锁定”

希望增加个收藏功能，可以收藏被下架或版本锁定的音乐

**Comment by qier222** [comment]
这个是网易云接口的限制，实现不了

**Comment by yidasanqian** [comment]
> 这个是网易云接口的限制，实现不了

我的意思是增加本地收藏功能，不调网易云接口
