### ISSUE TITLE
bug：Win10 v0.4.1版本特定歌手的歌曲全部无法播放

### ISSUE THREAD

**Issue by aDobeZ** [qier222/YesPlayMusic#942]
目前测试到的歌手是L'Orchestra Cinematique，该歌手的所有歌曲都无法播放，并且播放状态呈现被卡住的状态。

系统信息：
版本	Windows 10 家庭中文版
版本号	20H2
操作系统内部版本	19042.1237
体验	Windows Feature Experience Pack 120.2212.3530.0

软件版本：v0.4.1

**Comment by memorydream** [comment]
![image](https://user-images.githubusercontent.com/34763046/135229298-74e92938-d15a-41fa-99db-e354e9c627f9.png)
我这里正常播放，你要不提供一下F12控制台的截图？

**Comment by twoheartliu** [comment]
YesPlayMusic-mac-0.4.1-universal.dmg 周杰伦的歌无法播放，设置里 启用 UnblockNeteaseMusic 是启用状态

**Comment by Singhoy** [comment]
我是所有歌都不能放。。。进去列表一首歌都没有

**Comment by aDobeZ** [comment]
> ![image](https://user-images.githubusercontent.com/34763046/135229298-74e92938-d15a-41fa-99db-e354e9c627f9.png) 我这里正常播放，你要不提供一下F12控制台的截图？
目前看起来你截图的那首歌我这边也能正常的播放，应该是我之前测试的时候遗漏了这首歌。但是同一个专辑里的Sweden歌曲无法播放，你可以在你的平台上测试一下。BTW，对于控制台里哪些信息比较重要呢？我可以帮你截图。感谢！

**Comment by memorydream** [comment]
> > ![image](https://user-images.githubusercontent.com/34763046/135229298-74e92938-d15a-41fa-99db-e354e9c627f9.png) 我这里正常播放，你要不提供一下F12控制台的截图？
> 
> @memorydream 目前看起来你截图的那首歌我这边也能正常的播放，应该是我之前测试的时候遗漏了这首歌。但是同一个专辑里的Sweden歌曲无法播放，你可以在你的平台上测试一下。BTW，对于控制台里哪些信息比较重要呢？我可以帮你截图。感谢！

Sweden我这里也可以播放
只要开着控制台，如果不能播放应该会在控制台新增一条Error，把那个截图就好了

**Comment by pan93412** [comment]
有再出現問題請重開 issue。

**Comment by Singhoy** [comment]
这是自动回复邮件。
 

Your message has been received. Thank you for your mail.You receive this email because the recipient sets up an auto-response.
