### ISSUE TITLE
Firefox浏览器无法播放下一首

### ISSUE THREAD

**Issue by RuofengX** [qier222/YesPlayMusic#943]
如题，nginx如何配置？
#### **这个问题似乎不再出现，本人无法复现**
首页正常运行，登陆页面无二维码显示。
此时打开控制台，可以看到资源`/login/api/login/qr/key`404错误。而去掉路径`/login`，直接访问/api/login/qr/key会返回一个类似`{"data":{"code":200,"unikey":"9cc18053-3452-49f0-bb3f-55554d6cfe1b"},"code":200}`的json对象。怀疑nginx反代配置问题。  
  
### 相关配置 
.env文件：
```
VUE_APP_NETEASE_API_URL=/api
VUE_APP_ELECTRON_API_URL=/api
VUE_APP_ELECTRON_API_URL_DEV=/api
VUE_APP_LASTFM_API_KEY=09c55292403d961aa517ff7f5e8a3d9c
VUE_APP_LASTFM_API_SHARED_SECRET=307c9fda32b3904e53654baff215cb67
DEV_SERVER_PORT=20201
```  

---

nginx配置：
```
server {
    listen 80;
    listen [::]:80;
    server_name music.ruofengx.cn;

    return 301 https://$server_name$request_uri;
}

server {
        listen 443      ssl http2;
        listen [::]:443 ssl http2;
        server_name music.ruofengx.cn;

        ssl_certificate     /etc/ssl/nginx/1_music.ruofengx.cn_bundle.crt;
        ssl_certificate_key /etc/ssl/nginx/2_music.ruofengx.cn.key;
        root /var/www/html;

        index index.html;
        location /api/ {
                proxy_pass http://localhost:3000/;
        }

}
```

**Comment by RuofengX** [comment]
有时又能够正常工作，正常显示二维码的时候资源链接为`https://music.ruofengx.cn/api/login/qr/key?timestamp=1632979510537`，和之前不显示的时候不一样。

**Comment by RuofengX** [comment]
测试得到：Firefox浏览器无法播放下一首，对作者的网站也是。使用Edge浏览器就正常加载下一首。Firefox版本92.0.1

**Comment by RuofengX** [comment]
同时，Last.fm授权后，callback链接返回404，查看dist文件夹发现没有callback路径。可能在某个版本网页部署就已经出现问题

**Comment by Smart-Chou** [comment]
vercel部署后last.fm授权链接无法回调

**Comment by RuofengX** [comment]
> 
> 
> vercel部署后last.fm授权链接无法回调

https://github.com/qier222/YesPlayMusic/issues/712#issuecomment-932336083
我使用的是自己服务器，根据router文件内容，疑似确失部分资源没有生成。
