### ISSUE TITLE
重新启动应用之后全局快捷键就会失效

### ISSUE THREAD

**Issue by Truthss** [qier222/YesPlayMusic#945]
客户端
Windows 11 Insider Preview 22468.1000
![图片](https://user-images.githubusercontent.com/32219813/135496060-6784d6f4-4037-427b-8b74-07ce4b56f8a2.png)

每次重新启动应用之后全局快捷键就会失效
还是需要在每次开启应用之前重新关闭打开一次“启用全局快捷键”按钮才能正常使用全局快捷键功能

**Comment by xchangfu** [comment]
全局快捷键确实还是有问题

**Comment by daojiAnime** [comment]
同样问题

**Comment by pan93412** [comment]
#1083 應以修正。
