### ISSUE TITLE
Windows扩展窗口中关闭软件, 再无扩展窗口状态下再次运行软件, 窗口无法跟随还原到电脑屏幕

### ISSUE THREAD

**Issue by ClassLate** [qier222/YesPlayMusic#946]
> Windows扩展窗口中关闭软件, 再无扩展窗口状态下再次运行软件, 窗口无法跟随还原到电脑屏幕

## 使用版本

- win10, 21H1, 19043.1237
- yesplay, 客户端v0.4.1

## 复现步骤

- 打开投影(win + p), 选择扩展
  > 打开投影前, 软件运行与否不影响结果
- 将软件窗口拖到扩展屏幕
- 关闭软件
  > 退出, 并非最小化
- 关闭投影
- 运行软件
  > 此时软件窗口已经不会在电脑桌面显现了

**Comment by pan93412** [comment]
Duplicate of #635
