### ISSUE TITLE
最小化到托盘后，任务栏中的图标是否可以不显示

### ISSUE THREAD

**Issue by mrdrivingduck** [qier222/YesPlayMusic#949]
RT。很喜欢这款软件的颜值！但是其它一些软件在最小化到托盘后，在任务栏中就不会显示了 (微信/有道/Thunderbird/...)。感觉这样子更合理？

Windows 10 客户端。

![image](https://user-images.githubusercontent.com/32560442/135703371-b76a683f-09d6-4cb0-ac0c-b56404985fc0.png)

**Comment by memorydream** [comment]
设置里选择最小化到托盘后关闭软件，是不会在任务栏中显示的，可能是你哪里的操作有误

**Comment by mrdrivingduck** [comment]
感谢，我找到设置的地方了。
