### ISSUE TITLE
歌词页UI及新IOCN设计

### ISSUE THREAD

**Issue by RebirthEgo** [qier222/YesPlayMusic#95]
歌词页UI我做了一版，希望能有一点帮助，我把源文件也一起上传看能否用得到。
现在歌词页最大化后不能自动缩放，在竖屏上只能显示一半。平时喜欢把歌词最大化在副屏使用。

——————————————————————————————————————————————————————
**夜间模式**

![001](https://user-images.githubusercontent.com/54738173/104479944-f24b3000-55fe-11eb-805f-684438589e97.jpg)

![002](https://user-images.githubusercontent.com/54738173/104479973-f8d9a780-55fe-11eb-8782-dc5f9a1569a4.jpg)

**白色**

![003](https://user-images.githubusercontent.com/54738173/104479983-fecf8880-55fe-11eb-9c29-dc8627bee63b.jpg)

![004](https://user-images.githubusercontent.com/54738173/104480000-042cd300-55ff-11eb-9f70-1beda6b8f1e7.jpg)

**使用场景**

![效果图](https://user-images.githubusercontent.com/54738173/104477459-18230580-55fc-11eb-8ce6-69b2884812c8.jpg)

**ICON**

![新ICON](https://user-images.githubusercontent.com/54738173/104477518-28d37b80-55fc-11eb-9be4-1e5f3e2e7587.png)

[歌词页UI及新IOCN设计.zip](https://github.com/qier222/YesPlayMusic/files/5809708/UI.IOCN.zip)

**Comment by qier222** [comment]
争取下个或下下个版本优化歌词的竖屏显示

**Comment by Ahian** [comment]
老哥牛逼啊
