### ISSUE TITLE
网页端无法登陆

### ISSUE THREAD

**Issue by maoshuochen** [qier222/YesPlayMusic#951]
# 尽量每个 issue 只提一个 bug 或新功能

### 提新 issue 前请确认 👉

- 没人提过这个 issue（[这里看所有 issue](https://github.com/qier222/YesPlayMusic/issues)）
- 项目的 Todo 里没有与你 issue 相关的内容（[这里看 Todo](https://github.com/qier222/YesPlayMusic/projects/1)）

### 反馈 bug 需要的信息

- 用的是网页版还是客户端
- 浏览器名称或电脑操作系统
- 控制台 Console 页面的截图（按 F12 可打开控制台）

网页端无法登陆
Chrome - Win10
![image](https://user-images.githubusercontent.com/36188136/135714614-af417e72-fd57-4df2-9194-ec8da2ebc67c.png)

**Comment by pan93412** [comment]
新版無類似問題。復現請 reopen。
