### ISSUE TITLE
音乐播放问题，音乐信息与声音不匹配

### ISSUE THREAD

**Issue by RebirthEgo** [qier222/YesPlayMusic#96]
在正常播放音乐时，此时搜索一位新歌手进行播放（**如果歌手的音乐处于灰色时）**，播放的音乐还是在正常前的声音，但信息栏、歌词等已经是新歌手的播放状态，或是可以播放但没声音。

例如：新裤子乐队《生命因你而火热》

**Comment by qier222** [comment]
没复现这个问题，现在发了新版本，你试试看？

**Comment by RebirthEgo** [comment]
> 没复现这个问题，现在发了新版本，你试试看？

新版本没有问题了，谢谢。请教一个问题，播放灰色音乐时不能添加喜欢，这是BUG还是实现不了
