### ISSUE TITLE
新功能：QQ 登录

### ISSUE THREAD

**Issue by PCD1CFbjDC** [qier222/YesPlayMusic#960]
能否在登录方式中增加 QQ 登录呢🤔

**Comment by WuJunkai2004** [comment]
这个不用妄想了，网易自己调用QQ的api很正常，但是不可能开放给用户。

**Comment by ceabq** [comment]
api没有这个功能
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e7%99%bb%e5%bd%95
