### ISSUE TITLE
[Bug]archlinux kde无法关闭软件

### ISSUE THREAD

**Issue by vonl1** [qier222/YesPlayMusic#961]
```
OS: Arch Linux x86_64 
Kernel: 5.14.8-arch1-1 
DE: Plasma 5.22.5 
aur/yesplaymusic 0.4.1-1 (+5 0.89)
```
### 情况描述:
点击关闭窗口,软件会最小化,无法退出
### 软件的启动进程截图
![2021-10-05_20-42-08](https://user-images.githubusercontent.com/40910092/136024509-8896a1c7-e5ed-473c-933b-c53d2d5d9109.png)
![2021-10-05_20-43-18](https://user-images.githubusercontent.com/40910092/136024668-cf291dce-7c05-438b-801f-db819652c587.png)
![2021-10-05_20-44-01](https://user-images.githubusercontent.com/40910092/136024790-3bc29018-a2ba-4ec1-8e7c-e5247cb3ce34.png)
![2021-10-05_20-44-55](https://user-images.githubusercontent.com/40910092/136024958-4a0a5513-ed0e-4f53-afbe-38866f69f45d.png)
![2021-10-05_20-45-32](https://user-images.githubusercontent.com/40910092/136025029-5bf35fac-cc0c-47e7-bf2b-c5063f4d0c3a.png)
![2021-10-05_20-45-58](https://user-images.githubusercontent.com/40910092/136025100-032e9d88-cb67-4d8d-9cdc-a199637b6a74.png)
![2021-10-05_20-46-29](https://user-images.githubusercontent.com/40910092/136025171-cf71f276-c830-4ced-9a81-7ee75c5aff7f.png)
![2021-10-05_20-46-48](https://user-images.githubusercontent.com/40910092/136025225-b5b3377e-9397-4b59-a5c1-2405aaa0a5b0.png)
![2021-10-05_20-47-09](https://user-images.githubusercontent.com/40910092/136025286-207a106f-73fb-4128-a4f2-cb83c5845a2f.png)

**Comment by memorydream** [comment]
复现不了，托盘图标还在吗？在的话到设置里看看     关闭主窗口时...  这个选项的值是否为询问或退出

**Comment by vonl1** [comment]
退出时没有询问或退出,托盘图标还在,kwin快捷键关闭窗户和鼠标关闭都是软件最小化

**Comment by memorydream** [comment]
![image](https://user-images.githubusercontent.com/34763046/136031103-9fc75fb5-4c33-437d-ab68-954ffa2d9960.png)
![image](https://user-images.githubusercontent.com/34763046/136031282-1ff7482b-6e35-4feb-8225-81ef533c6954.png)
我这里很正常

**Comment by vonl1** [comment]
好了默认是询问,但是我也没见软件的询问,设置为退出之后就好了

**Comment by memorydream** [comment]
> 好了,默认是询问,但是我也没见软件的询问,设置为退出之后就好了

询问选项在linux中会直接退出，不会有弹窗，我不清楚为什么是这样的行为

**Comment by vonl1** [comment]
你试一下默认询问点退出是什么样

**Comment by memorydream** [comment]
> 你试一下默认询问点退出是什么样

和退出是同样的行为

**Comment by Brannua** [comment]
> > 好了,默认是询问,但是我也没见软件的询问,设置为退出之后就好了
> 
> 询问选项在linux中会直接退出，不会有弹窗，我不清楚为什么是这样的行为

+1

**Comment by memorydream** [comment]
> 最新版 manjaro linux kde桌面，设置关闭时询问会直接退出，问一下有解决办法吗

#969 已修复

**Comment by memorydream** [comment]
> 好了,默认是询问,但是我也没见软件的询问,设置为退出之后就好了

#969 已修复
