### ISSUE TITLE
如何更换账号？？？？？？？？？？？？？

### ISSUE THREAD

**Issue by LittleRey** [qier222/YesPlayMusic#97]
如何更换账号？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by qier222** [comment]
打开首页，滑动到底部进入设置页面就可以看到登出按钮了
