### ISSUE TITLE
cookie过期后导致无法获取数据的bug

### ISSUE THREAD

**Issue by wandiu** [qier222/YesPlayMusic#975]
Mac m1 客户端没法打开音乐库
<img width="1073" alt="截屏2021-10-12 11 17 10" src="https://user-images.githubusercontent.com/82247133/136885530-6f2e549d-9a02-468e-a17f-4506c0423e01.png">

**Comment by billowssun** [comment]
能修复吗，重新登陆好麻烦，windows也是一样的情况。

**Comment by WuJunkai2004** [comment]
可否考虑在部分fetch后面接catch，遇到400或者301就主动要求重新登录？
