### ISSUE TITLE
音乐库无法加载

### ISSUE THREAD

**Issue by keepcreative** [qier222/YesPlayMusic#976]
![image](https://user-images.githubusercontent.com/35420606/137169714-93470a69-6157-46d1-9085-f62140f75826.png)

**Comment by Direct-A** [comment]
同样出现这个问题，关了代理也还是存在

**Comment by Hill-Jiang** [comment]
我也遇到了同样的问题，账号在登录状态
F12 打开控制台，找到失败的请求，点开发现报错是“请登录后再查看”
然后退出账号，重新登录就好了
