### ISSUE TITLE
软件功能性

### ISSUE THREAD

**Issue by Agatha-Chen** [qier222/YesPlayMusic#983]
软件可以最小化到通知区域吗？要不然关上就没了，最小化只能在任务栏太不方便和美观了。望解决，谢谢。

**Comment by memorydream** [comment]
![image](https://user-images.githubusercontent.com/34763046/137557384-974ef509-24b3-401e-ba8b-44f0c0060aec.png)

**Comment by memorydream** [comment]
https://github.com/qier222/YesPlayMusic/actions/runs/1327231044
也可以在这里下载还未发布的最新修改版，这个版本已经合并了 #936 中提到的所有修改
