### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by liuxiaoming989** [qier222/YesPlayMusic#985]
# Mac下无法退出的问题

### 在我的MacBook Pro上

- 退出键与最小化合为一体并且最小化窗口似乎在退出上方
- command Q不起任何作用
- 如果你需要视频，我可以用邮箱发给你
### 反馈 bug 需要的信息

- Mac客户端，V0.4.1
- macOS Big Sur 11.6

**Comment by memorydream** [comment]
#929 重复
