### ISSUE TITLE
设置页面繁体中文选项台湾旗帜 emoji 字符错误

### ISSUE THREAD

**Issue by Hibanaw** [qier222/YesPlayMusic#988]
希望可以正常使用🇹🇼，避免争议也可以用🇨🇳/🇭🇰，或者所有语言都不要添加旗帜

**Comment by memorydream** [comment]
![image](https://user-images.githubusercontent.com/34763046/137626848-485bdb77-f115-4455-a3f3-d07784189c30.png)
哪里有旗帜？

**Comment by Hibanaw** [comment]
> ![image](https://user-images.githubusercontent.com/34763046/137626848-485bdb77-f115-4455-a3f3-d07784189c30.png) 哪里有旗帜？

Windows 的话为避嫌系统字体没有旗帜 emoji
![image](https://user-images.githubusercontent.com/61813396/137626911-e937fe31-9d58-4591-b8c9-8cfc82d9a0e3.png)

**Comment by memorydream** [comment]
![image](https://user-images.githubusercontent.com/34763046/137626958-4dca6eb1-49f7-4b2c-bac7-65209a182ffb.png)
那可能是字体问题？arch linux，也没有
