### ISSUE TITLE
Linux KDE 环境最小化到托盘后无法从 dock 启动

### ISSUE THREAD

**Issue by Hibanaw** [qier222/YesPlayMusic#989]
Linux 最新的 action release 客户端
桌面环境 KDE Plasma 5.22.5
最小化到托盘后无法从驻留 dock 的图标启动

**Comment by memorydream** [comment]
系统信息：
![image](https://user-images.githubusercontent.com/34763046/137626668-da5ad6f1-6f4e-422b-8521-1fdfb9604378.png)

托盘菜单:
![image](https://user-images.githubusercontent.com/34763046/137626710-3f111baa-a50a-4033-9911-19e47f5afe78.png)

**Comment by Hibanaw** [comment]
> 刚刚从最新的action下载了一份测试，没能复现这个问题，托盘菜单内的`显示主面板`可以在最小化到托盘后呼出应用

托盘可以，但是点 pin 到 dock 上的图标不行
就是说这个位置
![image](https://user-images.githubusercontent.com/61813396/137626853-46f862de-c304-471a-bcc9-9f4c08e776be.png)

**Comment by memorydream** [comment]
> > 刚刚从最新的action下载了一份测试，没能复现这个问题，托盘菜单内的`显示主面板`可以在最小化到托盘后呼出应用
> 
> 托盘可以，但是点 pin 到 dock 上的图标不行 就是说这个位置 ![image](https://user-images.githubusercontent.com/61813396/137626853-46f862de-c304-471a-bcc9-9f4c08e776be.png)

那还请不要最小化到托盘，仅最小化即可

**Comment by Hibanaw** [comment]
好的，其实这个版本已经可以解决无法退出的问题了，谢谢

**Comment by memorydream** [comment]
#992 ，你可以拉取这个pr的修改自行编译
