### ISSUE TITLE
希望支持便携模式

### ISSUE THREAD

**Issue by YuI2333** [qier222/YesPlayMusic#993]
1. 希望配置文件支持跟随主程序目录，重装系统省事儿了😊

2. 希望音乐库增加“本地”选项，支持导入和关联本地文件，取代Foobar2000可待吗🥰

3. 希望主窗口支持透明度调整😀

4. 托盘图标在浅色模式下和主题同化了，希望新增深色图标跟随主题切换(●'◡'●)

**Comment by pan93412** [comment]
2. #126
