### ISSUE TITLE
Mac版无法正常退出

### ISSUE THREAD

**Issue by 1qaz2wsxhashfyi** [qier222/YesPlayMusic#996]
使用最新的0.4.1版本，操作系统为macOS 10.15。打开界面后按cmd+Q无法退出，仅仅是关闭窗口，在菜单栏点击退出YesPlayMusic也不能退出，只有通过强制退出（Force Quit）才能彻底关闭应用。之前的版本从未出现过该问题。

**Comment by memorydream** [comment]
#929
